### ISSUE TITLE
[Bug] Hash Links do not work properly

### ISSUE THREAD

**Issue by Zach-Allen** [nozzle/react-static#1004]
### Reporting a bug?

 When using hashlinks they work on the first click usually, but will not work the second time you click the link unless the page gets refreshed. 

### Steps to Reproduce the problem

1.  Create a Hashlink
2.  click on hashlink
3.  scroll away from section and click on the link again. It will not auto scroll the second time. 

### Expected Behavior

Should auto scroll to linked section every time the button is clicked.

**Comment by tannerlinsley** [comment]
Not sure how we are going to track this down tbh. We will need to hook into the `window.history`'s push/pop state and make sure that we are firing the scroller on every single call to those methods, regardless if the hash actually changed or not.

Also, the scroller tech is getting reworked in v7. So we may punt on this until v7 is out... but that could be a while.

**Comment by tannerlinsley** [comment]
v7 no longer ships with a built-in hash link animator. I would suggest:
- Using the `* { scroll-behavior: smooth; }` css property (limited browser support)
- Using an appropriate hash scrolling utility that is compatible with your router of choice.
