### ISSUE TITLE
[Bug] Changelog.md is out of date

### ISSUE THREAD

**Issue by SteveALee** [nozzle/react-static#1006]
Changelog is some 6 releases behind

**Comment by tannerlinsley** [comment]
Yeah, we need to get that automated. Major and minor releases should be fully documented though.

**Comment by SteveALee** [comment]
i once used semantic-release and also tried commitizen to help it select vtsion numbers from commit meesages. cant recall if changelog was handled by that setup though.

**Comment by SteveALee** [comment]
6.3.0 is not documented

**Comment by tannerlinsley** [comment]
Gonna have to punt on the 6.3.0 changelog for now. We'll do our best going forward.
