### ISSUE TITLE
[Bug] Build files making their way to dist folder

### ISSUE THREAD

**Issue by adrianObel** [nozzle/react-static#1009]
### Reporting a bug?

Hi there!

This could be a bug or a feature request depending on how you look at things. 

Running `react-static build` will not only add the assets from `public/` and the generated html, css, and js files, but it will also add several other files which should *not* be made public. 

To name a few: 
`client-stats.json`
`react-static-browser-plugins.js`
`react-static-build-config.json`
`react-static-templates.js`

It might be that these are build requirements but I don't see why they need to be dumped out on the dist folder and not on `tmp/`

This issue was briefly mentioned in an old issue I found https://github.com/nozzle/react-static/issues/664 but there was a regression at some point and the fix is long gone.

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  npm run build

### Expected Behavior

No sensitive information in dist folder

**Comment by tannerlinsley** [comment]
Yeah you're right. This should go in a nondeployed directory, preferably a
build artifacts folder that isn't the tmp though. This way it can easily be
committed if using incremental builds.

**Comment by sw-yx** [comment]
making as good first issue

**Comment by adrianObel** [comment]
@tannerlinsley were you thinking of changing the output to an `artifacts/` dir? 

After briefly looking through the code it seems like [this is the place](https://github.com/nozzle/react-static/blob/c27241b01153a221ebb969fd9353968827ff3f52/packages/react-static/src/static/clientStats.js). Is it just changing that to a different location or did you have something else in mind?

**Comment by tannerlinsley** [comment]
Yes that would work great. Just need to add that directory to the base
config and reference it there.

**Comment by adrianObel** [comment]
Great, I'll take a crack at it.
