### ISSUE TITLE
React storybook

### ISSUE THREAD

**Issue by crubier** [nozzle/react-static#101]
Hi, I successfully integrated react storybook with this project. However there are small discrepancies (mostly in the CSS) because storybook uses its own webpack config, and react storybook generates its own webpack config.

Any Idea on how to make those two work together ?

**Comment by tannerlinsley** [comment]
Maybe use react-story instead? Haha. Sorry. In all seriousness this why
react storybook is kindof a pain. There's effectively no way to use it in
another build system because of its strict requirements of its own crazy
build system.

**Comment by calvinrbnspiess** [comment]
@crubier maybe [`react-styleguidist`](https://github.com/styleguidist/react-styleguidist) is a good alternative because it feels more flexible at the first sight.

**Comment by crubier** [comment]
I used `react-styleguidist` for a while but `react-storybook` has ten times more github stars and overall support.

I agree with the problems with `react-storybook`, but it is the leading solution for this matter, and we have to live with it. I have around 100 stories, using storybook addons such as apollo connector and others...

The only thing that would be needed for `react-storybook` to be compatible with `react-static`, would be for `react-static` to export a function that outputs its webpack config. This would allow this kind of config in `.storybook/weback.config.js`

```js
import exportWebpackConfig from "react-static/lib/webpackXXX"
import reactStaticConfig from "../static.config"
return exportWebpackConfig(reactStaticConfig)
```

**Comment by tannerlinsley** [comment]
@zsherman

**Comment by crubier** [comment]
This function that I call `getWebPackStaticWebpackConfig` already exists internally, I would just need a way to access it as a user of `react-static`
