### ISSUE TITLE
[Bug] @reach/router's location state isn't passed to new route

### ISSUE THREAD

**Issue by ostrebler** [nozzle/react-static#1018]
Hey !

### Bug

First I've got this navigation function : 
```
import { navigate } from '@reach/router'
// ............
export const toServices = state => {
    navigate('/services', { state: { state }})
}
```
Then I use it from my home page, and land on the services page with the following relevant parts : 
```
import { Location, globalHistory } from '@reach/router'

const Services = props => (
   console.log(props.location.state)         // not ok
   console.log(globalHistory.location.state) // ok
   return (
      // whatever...
   )
)

export default props => (
  <Location>
    {({ location }) => (
      <Services location={location} {...props}/>
    )}
  </Location>
)
```

Whatever I pass as state to the navigate function, it's nowhere to be found in `props.location.state`.
However it's always in `globalHistory.location.state`.

I don't know if that's a bug from @reach/router, I hope not (because they don't seem that active on the project). Has anyone using react-static had the same issue ?

### Expected Behavior

The state being passed even to props.location.state.

Thank you.

**Comment by Herohtar** [comment]
Can you provide a more complete example of where and how you are using it? Maybe a demo repository? I tried to reproduce it from what you show here and `props.location.state` always contains the data passed from `navigate` as expected, so I'm not seeing the problem you describe.

**Comment by ostrebler** [comment]
I completely switched back to 5.9.12 because of another issue : https://github.com/nozzle/react-static/issues/1022
I don't have that code anymore.

I'll try and update again as soon as I get help for that other issue, and if I still have a location state problem, I'll post a more complete example here.

Thank you for your answer.

**Comment by tannerlinsley** [comment]
Yeah, we'll need a way to reproduce this. In my initial experiments, all is well.
