### ISSUE TITLE
[Bug] After upgrade, node_modules' css files are loaded AFTER mine

### ISSUE THREAD

**Issue by ostrebler** [nozzle/react-static#1022]
### Steps to Reproduce the problem

Use : 
- An External UI library like AntDesign in my case,
- Your own less file in `src/`,
- React-static 6,
- the `react-static-plugin-less` plugin

When using the `start` command, everything works fine. But when building, the CSS from AntDesign is loaded after my own which cancels all my overwritings out.

My code is a bit long, but here is the repo : https://github.com/ostrebler/strebler

I don't know if that's linked in any way, but since I switched to react-static 6, I get this after build : 

![linktags](https://user-images.githubusercontent.com/30187797/52895310-d2175a00-31b8-11e9-8dbe-e49f3d525f07.png)

and file size warning while building : 

![exportsize](https://user-images.githubusercontent.com/30187797/52895348-2de1e300-31b9-11e9-88f4-cae9e90db70b.png)

I guess it might be linked.

### Expected Behavior

That the CSS from AntDesign is being loaded before my own CSS. Before react-static 6 this was the case.

**Comment by ostrebler** [comment]
Maybe linked to https://github.com/nozzle/react-static/issues/984

**Comment by tannerlinsley** [comment]
I believe this is directly related to that issue. Let's track it there.

**Comment by lilbumblebear** [comment]
@ostrebler were you ever able to figure this out?  I am having the same problem with react-static v7 and REALLY struggling to find a good solution.  Any tips would be appreciated!
