### ISSUE TITLE
[Bug] `eslint-config-react-tools` dependency messes up local eslint config.

### ISSUE THREAD

**Issue by mikestopcontinues** [nozzle/react-static#1033]
### Reporting a bug?

I use a third-party eslint-config. The trouble is, `react-static` installs `eslint-config-react-tools` as a standard dependency. Node seems to give priority to this package's eslint-plugins, which causes some errors, as the version of `eslint-plugin-babel` it requires is pretty old.

```
  1:1  warning  Definition for rule 'babel/quotes' was not found                 babel/quotes
  1:1  warning  Definition for rule 'babel/no-unused-expressions' was not found  babel/no-unused-expressions
  1:1  warning  Definition for rule 'babel/valid-typeof' was not found           babel/valid-typeof
```

It doesn't look like the dep is being used for anything at all, but I'm attaching a PR where `eslint-config-react-tools` is simply moved to `devDependencies`. If nothing else, it cuts the `react-static` down by a big chunk.

**Comment by sw-yx** [comment]
ive also pr’ed to bump the deps of eslint config react tools
