### ISSUE TITLE
react-native-web support

### ISSUE THREAD

**Issue by kations** [nozzle/react-static#1035]
Hi,
with this in my node.api.js dev works like expected, but after yarn build, the page with the react native component is empty without any error.

export default () => ({
  webpack: config => {
    config.resolve.alias = {
      ...(config.resolve.alias || {}),
      "react-native$": "react-native-web"
    };

    return config;
  }
});

Maybe we need a plugin like https://github.com/slorber/gatsby-plugin-react-native-web but my Webpack skills are limited

Thanks

**Comment by tannerlinsley** [comment]
A plugin would be cool! I've never used RNW though, and I'm not sure how it fits into the React-Static ecosystem just yet. We'll keep an eye on it though and hopefully it becomes a larger use-case. For now, we don't have any direct support for it though.

Feel free to open a PR if you succeed!
