### ISSUE TITLE
[Docs] How to configure webpack?

### ISSUE THREAD

**Issue by daniellizik** [nozzle/react-static#1038]
reac-static ver: `6.0.18`

I'm finding the docs sort of vague. I did this to my `static.config.js`
```js
import webpackConfig from 'config/conf'

export default {
  plugins: ['react-static-plugin-emotion'],
  webpack: () => webpackConfig,
  Document; ({ Html, Head, Body, children }) => (<SomeHtml />);
}
```
However, this webpack method never seems to get called after I run `$ react-static start`.

According to [the docs](https://github.com/nozzle/react-static/blob/master/docs/plugins/node-api.md#webpack-functionfunction) `webpack` has to be a function that returns config. Am I doing it right?

**Comment by sw-yx** [comment]
i believe (but am not sure) that that part of the docs is now out of date. been meaning to ask @tannerlinsley about that to confirm

to actually modify webpack, use node.api.js: https://github.com/nozzle/react-static/blob/master/docs/plugins/node-api.md#webpack-functionfunction

**Comment by daniellizik** [comment]
@sw-yx thanks, that helped a lot. From [this line](https://github.com/nozzle/react-static/blob/fa89ffdead2d2da871ce98e6715518e628faea52/packages/react-static/src/static/getConfig.js#L243) it appears that `node.api.js` needs to export a default function that returns your config object. I tried this and that appeared to fix my original question but I'm getting some new errors now

**./node.api.js**
```js
export default () => ({
  webpack: (config) => ({
    ...config
    ...otherStuff
  })
})
```
