### ISSUE TITLE
devAssetsPath config option

### ISSUE THREAD

**Issue by kalinchuk** [nozzle/react-static#1039]
**Is your feature request related to a problem? Please describe.**
The react-static site is linked via a URL path (/path-to-site) on a load balancer which points the path to another server. Because of that the asset path is incorrect (it's requesting `/main.js` vs `/path-to-site/main.js`) Adding `assetPath: 'path-to-site'` works but that also breaks the dev environment. That is why I think having a `devAssetsPath` is a good idea.

**Describe the solution you'd like**
Allow `devAssetsPath` config option. Use the correct assets path based on the environment.

**Describe alternatives you've considered**
I've tried variations of different config options and also web server rewrites but haven't found a clean, workable solution. The only solution that works now is to comment out `assetsPath` config when working in the dev environment.

**Comment by tannerlinsley** [comment]
Would it be sufficient to just ignore `assetPath` in development?

**Comment by kalinchuk** [comment]
Yes, that would work. I was going to set `devAssetsPath: ''` if that option was available.

**Comment by tannerlinsley** [comment]
Try out v7. If this is still an issue, we can easily reopen this issue and PR a new option to either disable this during dev or even add a devAssetsPath if you'd like. Regardless, it will much easier to fix in v7.

Thanks!
