### ISSUE TITLE
[Bug] Failed exporting HTML for URL. Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by evular** [nozzle/react-static#1043]
### Reporting a bug?

Once I migrated to react-static 6 from 5.9.7, I cannot build my application. I get an error "Failed exporting HTML for URL. Cannot read property 'map' of undefined". I am quite sure, that markdown files are not being parsed during build stage. Are the any ways to fix it or should I stay with 5.9.7 ?

### Environment

  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 72.0.3626.109
    Firefox: 65.0
    Firefox Developer Edition: 65.0
    Safari: 12.0.3
  npmPackages:
    react: ^16.8.3 => 16.8.3 
    react-dom: ^16.8.3 => 16.8.3 
    react-helmet: ^5.2.0 => 5.2.0 
    react-hot-loader: ^4.7.1 => 4.7.1 
    react-lazy-load-image-component: ^1.3.2 => 1.3.2 
    react-router-ga: ^1.2.0 => 1.2.0 
    react-share: ^2.4.0 => 2.4.0 
    react-slick: ^0.23.2 => 0.23.2 
    react-static: ^6.3.6 => 6.3.6 

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  Copy rep https://github.com/evular/evular.lt-test and build it.
2.  Yarn build
3.  Failed exporting HTML for URL. Cannot read property 'map' of undefined

### Expected Behavior

Everything should build.

### Reproducible Demo

https://github.com/evular/evular.lt-test

**Comment by ostrebler** [comment]
You're using `gray-matter` in combination with `marked`, why ?
Both are designed to parse YAML.

Try using only one, and I recommend none of them but `front-matter` instead. That's what I'm using, no problem so far.

**Comment by evular** [comment]
> You're using `gray-matter` in combination with `marked`, why ?
> Both are designed to parse YAML.
> 
> Try using only one, and I recommend none of them but `front-matter` instead. That's what I'm using, no problem so far.

Thanks, but it is not working this way. I believe there are changes in how the application is built. Otherwise, it should not work in 5.9.7.

**Comment by tannerlinsley** [comment]
In your repo, you have files like `Home.jsx` in your `pages` directory. Any valid importable file in this directory is automatically transformed into a route for you. So in this case, your site is trying to export a route at `/Home` using the `src/pages/Home.jsx` file as the template. In that file, you rely on the `posts` routeData, but in your config, you are not creating a `/Home` route, nor are you passing it the `posts` data that it needs. This looks like the problem for most of the pages actually. To fix this you can either:
- Move any template files you don't want to have automatically routed for you from the special `pages` directory to a different directory.
- Create routes and pass the necessary data for each of the pages defined in the `pages` directory.
