### ISSUE TITLE
[Bug] The imperative version of prefetch does not work on v6.3.6

### ISSUE THREAD

**Issue by hellojere** [nozzle/react-static#1045]
### Reporting a bug?

Upgrading React Static to `6.3.6` from `6.3.3` causes the `prefetch` function to return `undefined`. 

The following works on `6.3.3` but not on `6.3.6`: 

```
import { prefetch } from 'react-static'

const myFunc = async () => {
  const data = await prefetch('/')
  console.log('The preloaded data:', data)
}
```

### Steps to Reproduce the problem

1.  Try using the `prefetch` with the latest React Static `6.3.6`

### Expected Behavior

The React Static version `6.3.6` to return the expected props. 

### Reproducible Demo

I created a demo with two branches, one for each version: 
<https://github.com/hellojere/reactstatic-prefetch-bug-demo/branches>

**Comment by tannerlinsley** [comment]
Unfortunately, we cut this version with a regression. The next version (releasing today) will fix that regression.  Sorry Jere!

**Comment by hellojere** [comment]
Any updates on this? I desperately need the Terser features for hooks, but also heavily using the `prefetch`.

**Comment by tannerlinsley** [comment]
v7 fixes this and I'll also be releasing a patch today for v6. Stay tuned.

**Comment by tannerlinsley** [comment]
Patch is released. Thanks!
