### ISSUE TITLE
No Doctype ?

### ISSUE THREAD

**Issue by tomagladiator** [nozzle/react-static#105]
Hello, react-static forget to include a `<!doctype html>`in the first line of all HTML pages.
It's not useless, If you dont put a doctype declaration, browsers ( at least desktop ) 'quirks mode' will interpret your page as the oldiest version of Html or undeterminated...

How can I add it ? Thanks !

**Comment by SShrike** [comment]
Hmm, perhaps if and after #104 is merged this would be quite easy to fix. Since you're feeding the output HTML as a template for Webpack, could just as well slap the doctype at the top of the template.

**Comment by D1no** [comment]
Like UTF-8 Charset, you are right, that should be part of all templates.

**Comment by tannerlinsley** [comment]
DocType is addressed at the export stage and is applied to every single file exported. So be not afraid ;). DocType is there.... watching over you. Creepily.... but consistently haha
