### ISSUE TITLE
[Bug] Babel error on basic template build v6.3.6

### ISSUE THREAD

**Issue by chrisjpatty** [nozzle/react-static#1052]
First off, thanks for all the hard work on `react-static`. I've run into a bit of a snag with my first v6.x site. I have a near-fresh basic template that fails on the build. with a mysterious error that I don't even know where to start debugging. It prints this error so many times it exceeds the limits of my console:
```bash
  Error: /Users/chrisjpatty/projects/hidden-willows/node_modules/@babel/runtime/helpers/esm/objectWithoutPropertiesLoo  se.js:1 (function (exports, require, module, __filename, __dirname  ) { export default function _objectWithoutPropertiesLoose(  source, excluded) {
      ^^^^^^
  SyntaxError: Unexpected token export
```

### Environment

```
System:
    OS: macOS Sierra 10.12.6
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Memory: 621.81 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.2 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 72.0.3626.119
    Firefox: 60.0.1
    Safari: 11.0.3
  npmPackages:
    react: ^16.8.1 => 16.8.3
    react-dom: ^16.8.1 => 16.8.3
    react-hot-loader: ^4.3.12 => 4.7.1
    react-spring: ^8.0.10 => 8.0.10
    react-static: ^6.3.6 => 6.3.6
  npmGlobalPackages:
    react-dragtastic: 2.3.1
    react-native-cli: 2.0.1
    react-static: 6.3.6
    react-vr-cli: 0.3.5
```

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  Installed a new react-static basic template.
2.  Added 3 routes to the config file with corresponding basic components.
3. `yarn start` works perfectly and produces no errors.
4. `yarn build` produces the error posted above.

### Expected Behavior

A fresh and shiny react-static website.

### Reproducible Demo

The code for this can be found [here](https://github.com/chrisjpatty/hidden-willows)

**Comment by chrisjpatty** [comment]
I discovered the problem. For some reason `react-static` doesn't seem to be able to handle importing from a subdirectory of an npm module. In this case I tried to import `react-spring` as per the animated route guide. Version 8.x of `react-spring` requires that to use the render props components you have to import them from a subdirectory which breaks the build. Downgrading to version 7.x of `react-spring` fixes the issue, but I'm not sure if it's a problem with `react-spring` or `react-static`. I'll leave this open in case you want to look into it.

**Comment by tannerlinsley** [comment]
This is very strange. I've definitely used modules like this and not had a problem. I'll DL your repo and take a look at it as soon as I have some free time.

**Comment by byte-artisan** [comment]
I got a very similar error when creating a fresh site from basic template.
It says: 
ERROR in C:/Users/.../test/artifacts/react-static-templates.js 1:1016
Module parse failed: Unexpected token (1:1016)
You may need an appropriate loader to handle this file type.
Added a detail post at [stackoverflow](https://stackoverflow.com/questions/55179980/error-you-may-need-an-appropriate-loader-to-handle-this-file-type-when-buildi)

**Comment by tannerlinsley** [comment]
This seems to be an edge case in v6 that we have been unsuccessful in pinning down, but we are confident that new architecture changes in v7 probably have solved this problem. Try it out and reopen if needed!
