### ISSUE TITLE
[DISCUSS] How to add webpack-bundle-analyzer to react-static v6.

### ISSUE THREAD

**Issue by firstziiz** [nozzle/react-static#1059]
I want to add `webpack-bundle-analyzer`. I don't know how because I don't know where I can edit/customize webpack config.

Thank you for explaining.

**Comment by tannerlinsley** [comment]
The bundle analyzer is already integrated into react-static. https://github.com/nozzle/react-static/blob/master/docs/config.md#bundleanalyzer

**Comment by patelrikin** [comment]
@tannerlinsley this information seems removed from newer docs for some reason:

```
bundleAnalyzer
An optional Boolean. Set to true to serve the bundle analyzer on a production build.

// static.config.js
export default {
  bundleAnalyzer: true,
}
```

**Comment by SleeplessByte** [comment]
That's because it moved to the templates: https://github.com/react-static/react-static/blob/master/packages/react-static/templates/blank/package.json#L8
