### ISSUE TITLE
Easier access to node devtools inspector

### ISSUE THREAD

**Issue by mikestopcontinues** [nozzle/react-static#1061]
**Is your feature request related to a problem? Please describe.**

I've gotten into the habit of using `node --inspect` to access chrome devtools in place of the terminal, and I'd like to be able to do that while working on react-static projects. Devtools offers a lot more flexibility for debugging, so it's a big win to be able to access it.

**Describe the solution you'd like**

Ideally, one could just do `react-static --inspect` or even just add the functionality to `react-static --debug`.

**Describe alternatives you've considered**

Right now, I can get fairly concise access to the inspector with `node --inspect -e "require('react-static/node').start()"`. It's easy enough, but detaching it from the CLI tool reduces it's flexibility, and it also keeps other users from adopting a pretty awesome little helper.

**Additional context**

Links:
* [Node inspector API](https://nodejs.org/api/inspector.html)
* [Tutorial](https://flaviocopes.com/node-debug-devtools/)

**Comment by theWebalyst** [comment]
Hi, I currently use `node --inspect` on a different project, and the Chrome browser debugger with react-static. I'm not a very advanced user, but have not noticed any difference.

Can you explain if there are advantages, extra features etc to `node --inspect`. Thanks.

**Comment by mikestopcontinues** [comment]
@happybeing, I suspect there's no difference. With `--inspect`, you still
open chrome and connect to your node instance. Likely, whatever package you
use with react-static is built on the same api.

>

**Comment by theWebalyst** [comment]
Ah, I see now. I think I misunderstood your suggestion - you are talking about debugging `React-static ` itself. At first I thought you were talking about debugging a website built with it - my bad 😊

**Comment by tannerlinsley** [comment]
Yeah, there needs to be better story around this for sure. It would also help people contribute more easily to React Static core if they can use the debugger to step through it. Is there anyone that would like to dig deeper on this?

**Comment by mikestopcontinues** [comment]
I'd be happy to offer up a PR sometime in the next week or so.

**Comment by tannerlinsley** [comment]
Looking forward to it!
