### ISSUE TITLE
[Bug] withSiteData(withRouteData(Comp)) vs withRouteData(withSiteData(Comp))

### ISSUE THREAD

**Issue by AubreyHewes** [nozzle/react-static#1063]
When using `withSiteData(withRouteData(Comp))` the route data is overwritten by the site data.. This seems to break bc. As before v6 it worked..

### Expected

`withSiteData(withRouteData(Comp))` overrides site data with route data

### Actual

`withSiteData(withRouteData(Comp))` overrides route data with site data

Switching it around `withRouteData(withSiteData(Comp))` works...

### Environment

```
  System:
    OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
    CPU: (8) x64 Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
    Memory: 636.58 MB / 15.56 GB
    Container: Yes
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/bin/n/bin/node
    Yarn: 1.13.0 - /usr/bin/yarn
    npm: 6.4.1 - ~/bin/n/bin/npm
  Browsers:
    Chrome: 72.0.3626.119
    Firefox: 65.0.1

```

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  react-static create
1.  cd test
1.  yarn
1. add "value" to `siteData`
1. add "value" to route
1.  create the route component that exports `withSiteData(withRouteData(Comp))` 

`withSiteData(withRouteData(Comp))` overrides route data with site data (wha wha?)

### Expected Behavior

`withSiteData(withRouteData(Comp))` overrides site date with route data

### Reproducible Demo

I tried to get it working in codesandbox but failed (anyone have a codesandbox template for react-static?)

Used template: basic (changed for the example..)

https://github.com/AubreyHewes/react-static-withsitedata-vs-withroutedata

**Comment by hellojere** [comment]
This is not a bug, and it's working as expected. 

If you look at the React Static source code, these functions are extremely similar: 

```javascript
export function withSiteData(Comp, opts = {}) {
  return props => (
    <SiteData {...opts}>
      {siteData => <Comp {...siteData} {...props} />}
    </SiteData>
  )
}
```

```javascript
export function withRouteData(Comp, opts = {}) {
  return props => (
    <RouteData {...opts}>
      {routeData => <Comp {...routeData} {...props} />}
    </RouteData>
  )
}
```

And your reproducible demo shows the following: 
![Screenshot 2019-03-13 at 17 00 26](https://user-images.githubusercontent.com/773501/54289275-86867f00-45b1-11e9-9d96-7a2d60f7fdc8.png)

So it is expected that the props passed to these functions override the arguments with identical names.

**Comment by CalMlynarczyk** [comment]
I would think this is expected behavior. The inner HOC will get called first, and then the outer HOC next, in which case the second one will overwrite any intersected properties.

It's the same as the following:
```javascript
Object.assign({
    a: 5,
    b: 6,
}, {
    a: 3,
    c: 8,
})
/*
{
    a: 3,
    b: 6,
    c: 8,
}
*/
```

**Comment by tannerlinsley** [comment]
This is correct. The HOC's apply their results directly to the props of the component, so if both withSiteData and withRouteData provide any overlapping props, the outer-most HOC will override the inner ones.

**Comment by AubreyHewes** [comment]
I understand where you are all coming from, though is not how it worked (before v6).. I had to change a load of code ;-)

**Comment by tannerlinsley** [comment]
You're right. In previous versions, the HOC's would assign to a named prop like `routeData` and `siteData`. I can see how this change would require a lot of code changes. In v7, we'll be have even more changes that supports hooks like `useRouteData`.

**Comment by AubreyHewes** [comment]
no probs :-) the problem was more the bc side of things. Looking out for v7 ! appreciate all your work! x
