### ISSUE TITLE
Q: Is there a way to control the strengths of webpack's uglifier/obfuscator (if there is one)?

### ISSUE THREAD

**Issue by neilyoung** [nozzle/react-static#1069]
I noticed, that the default settings for productive build are more or less producing clear source code, even though there is a little minification, but nearly no obfuscation in it. Is there a way to make the obfuscation stronger via configuration through <del>react-native</del> react-static?

**Comment by Herohtar** [comment]
I think you are misunderstanding the main purpose of UglifyJS; it minifies your JavaScript so that it is smaller in size and thus requires less bandwidth and reduces loading time. It is *not* an obfuscator.

What are you trying to achieve by obfuscating your code?

**Comment by neilyoung** [comment]
@Herohtar Thanks for clarification. The idea was to make it a bit harder for sniffers to read. Right now it is not hard at all :)

**Comment by sw-yx** [comment]
fwiw we use terser not uglifier. i'm not sure what react-native has to do with any of this?

**Comment by neilyoung** [comment]
@sw-yx Sure, not an issue fo react-native, but since I'm using `npm run build` as means to create my SPA distributions, I thought, there would be a way to plugin such an obfuscator during the build. Was just looking for suggestions. Would you mind to share, how you combine terser and react-native?
TIA

**Comment by neilyoung** [comment]
Oops, sorry. Meant react-static

**Comment by neilyoung** [comment]
OK, I see: I would need to update to a react-static 6.3.x version. But with this and a similar package.json (as a sample project produces) I'm running into issues (yarn build)

```

ERROR in a_long_path_down_the_roadspa/artifacts/react-static-templates.js 1:669
Module parse failed: Unexpected token (1:669)
You may need an appropriate loader to handle this file type.
> import _path from"path";import _universalImport from"babel-plugin-universal-import/universalImport";import universal,{setHasBabelPlugin}from'a_long_path_down_the_roadspa/node_modules/react-universal-component/dist/index.js';setHasBabelPlugin();var universalOptions={loading:function loading(){return null;},error:function error(props){console.error(props.error);return React.createElement("div",null,"An error occurred loading this page's template. More information is available in the console.");}};var t_0=universal(_universalImport({id:"../node_modules/react-static/lib/browser/components/Default404",load:function load(){return Promise.all([import(/* webpackChunkName: 'node_modules-react-static-lib-browser-components-Default404' */'../node_modules/react-static/lib/browser/components/Default404')]).then(function(proms){return proms[0];});},path:function path(){return _path.join(__dirname,'../node_modules/react-static/lib/browser/components/Default404');},resolve:function resolve(){return require.resolveWeak('../node_modules/react-static/lib/browser/components/Default404');},chunkName:function chunkName(){return"node_modules-react-static-lib-browser-components-Default404";}}),universalOptions);// Template Map
| export default{'../node_modules/react-static/lib/browser/components/Default404':t_0};export var notFoundTemplate="../node_modules/react-static/lib/browser/components/Default404";
 @ ../lib/bootstrapTemplates.js 4:15-63 15:20-68
 @ multi ../lib/bootstrapPlugins.js ../lib/bootstrapTemplates.js ../lib/bootstrapApp.js
Child extract-css-chunks-webpack-plugin ../../css-loader/dist/cjs.js??ref--4-oneOf-2-1!../../postcss-loader/src/index.js??postcss!../../../src/app.css
```
