### ISSUE TITLE
CSS Modules

### ISSUE THREAD

**Issue by tujoworker** [nozzle/react-static#107]
Thanks for making this nice framework! Looks very promising!

How about CSS Modules support, like styleName=“selector” instead of className? CSS Modules are getting popular now :)

**Comment by tannerlinsley** [comment]
https://twitter.com/tannerlinsley/status/925049430377619456 :)

**Comment by tujoworker** [comment]
Yea! Good answer 👍

**Comment by tujoworker** [comment]
Here is a working example: [react-static-css-modules](https://github.com/tujoworker/react-static-css-modules)
But I got it not work with the babel version: [babel-plugin-react-css-modules](https://github.com/gajus/babel-plugin-react-css-modules) (there is the classic version witch one would be just fine, as long we not get the babel version working [react-css-modules](https://github.com/gajus/react-css-modules)) - but the autor is recommending the babel ting, as it is so much faster.

The *styleName* would only work with the babel version, but it does not. Anyway, we have the reference version we can use: `className={css.about}`
```jsx
<div className={css.about} styleName="css.about">
...
```

**Comment by 2metres** [comment]
I've managed to get CSS Modules working in dev mode, but when I run `react-static build` the module styles are added to the CSS but not the HTML.

[My static.config.js](https://github.com/2metres/firebase-example/blob/React-Static-basic/static.config.js)

Any ideas?

**Comment by tujoworker** [comment]
Could You share the content of the webpack config as well?

--
This email was sent on the road.
