### ISSUE TITLE
Disabling/configuring loading spinner

### ISSUE THREAD

**Issue by klis87** [nozzle/react-static#1074]
**Is your feature request related to a problem? Please describe.**
I want to disable loading spinner, especially in production. This is especially important to me because this spinners usually is shown on language change. In my case language is part of url, so language change actually changes route. I don't want to show loading spinner, especially on language change.

**Describe the solution you'd like**
We could add a way to disable spinner, maybe a flag to `static.config.js`? I would be also nice to allow to configure spinner. Right now it is an blue spinner on a blank page. Not only it should be possible to provide own spinner implementation, but also I guess it should be possible to inject in anywhere, so it doesn't override the whole page

**Describe alternatives you've considered**
I tried to use  `minLoadTime: 0` in `static.config.js`, but it would be kind of cheating which doesn't work anyway.

**Additional context**
n/a

**Comment by tannerlinsley** [comment]
In v6 you can configure the spinner on Routes, SiteData and RouteData with the Loader prop. Unfortunately this is undocumented and will be removed next version on favor of suspense. So proceed with caution.

Tanner Linsley

**Comment by klis87** [comment]
@tannerlinsley thx, I did the following: `const Loader = () => null;` It works, but ideally what I would like to have is not to show loader at all in some cases. So lets say I am on route `/en/about-us` and I switch language so I push new route `/pl/about-us` . Is it or will it be possible to just keep `/en/about-us` visible and switch `/pl/about-us` when it is available? Or to rephrase, to disable loader, not to make it blank.

**Comment by tannerlinsley** [comment]
What you’re describing is suspense 😉. Back in v4, we did routing in a similar way. We monkey patched and delayed actual page navigation until the data and template were resolved. While this *looked* like suspense, it was far from it and produced a TON of bugs. This is why we moved to the new fallback/loader strategy.

So, even if you were to disable or render a blank loader, react will still attempt to load the new page and you’ll see a splash of white until the data/template resolve. There isn’t much we can do here until async react and true suspense ship.

HOWEVER, there is another remedy to your problem. React Static will not show a loader if the data has already been preloaded. If you can detect early which language they are switching to, you might be able to call `await prefetch('/lang/page’)`. When that promise resolves, it means any navigation to it will be immediate and not show a loader.

I hope this is making more sense.

Tanner Linsley

**Comment by klis87** [comment]
@tannerlinsley thx for detailed answer. I cannot wait for true async React, especially on server side.

In the meantime I will do the following. The problem is that I pass `language` to data to every component, like in #475 . Maybe I could use `createSharedData` because actually each component  will have exactly the same data apart from language, because I use i18next for translations. So this would solve all data props apart from `language`. And I was just enlightened that I don't really need to have language passed as data, because I can read it from path with React router. So then I won't have spinner because no new data will need to be fetched on lang switch :)

**Comment by tannerlinsley** [comment]
Perfect :) That’s a much better solution for now.

Hopefully in v7 we can figure out the right plugin points for this and just make it plug and play.

Tanner Linsley

**Comment by klis87** [comment]
:+1:  thx again and I am sure this library is gonna be even more awesome than it is now. I also considered Gatsby but I don't really wanna use graphql for not remote stuff. I am sure that with future react with the possibility to pause and stop rendering will allow us to make such a flexible and simple plugin API which could be used for anything, including plug and play i18next.

**Comment by pauloamgomes** [comment]
@tannerlinsley apologies for asking here as it seems already closed, but I have a weird issue where the loader div just wraps around the first div element on the page (that happens after building and on page refresh). Its a bit annoying because it breaks mostly the page layout, so my question would be how I can disable the Loader and if it's possible to configure it (you mentioned above that is configurable but not documented).

Thanks in advance.
