### ISSUE TITLE
[Bug] Cannot write file errors on fresh typescript template

### ISSUE THREAD

**Issue by jedmao** [nozzle/react-static#1081]
### Reporting a bug?

Getting a bunch of errors on a fresh typescript template when I run `yarn start`.

```
ERROR in undefined(undefined,undefined):
TS5055: Cannot write file '/Users/jemao/Documents/GitHub/bar/artifacts/react-static-browser-plugins.js' because it would overwrite input file.
```

### Environment

```
  System:
    OS: macOS 10.14.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 875.17 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.15.2 - ~/.nvm/versions/node/v10.15.0/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Browsers:
    Chrome: 73.0.3683.86
    Safari: 12.1
  npmPackages:
    react: ^16.8.1 => 16.8.6 
    react-dom: ^16.8.1 => 16.8.6 
    react-hot-loader: ^4.3.12 => 4.8.1 
    react-static: ^6.0.18 => 6.3.6 
    react-static-plugin-typescript: ^3.1.0 => 3.2.0
```

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  Install fresh typescript template.
2.  `yarn start`

### Expected Behavior

No errors.

**Comment by Vinnl** [comment]
I think this can be solved by setting `allowJs` to `false` in your tsconfig - which isn't entirely satisfying if you want JS files to be checked by TypeScript as well, but will probably do for now.

@tannerlinsley Might want to add this to the suggested `tsconfig` in the plugin's README as well.

**Comment by tannerlinsley** [comment]
I'll accept a PR to add that to the plugin's README. Thanks guys!
