### ISSUE TITLE
[Bug] 7.0.4 Could not find a route for the "index" page of your site! This is required. Please create a page or specify a route and template for this page.

### ISSUE THREAD

**Issue by meesvandongen** [nozzle/react-static#1094]
error message: `Could not find a route for the "index" page of your site! This is required. Please create a page or specify a route and template for this page.`. While there is a index page in ./src/pages and the plugin for this is installed.

This happens to the default typescript template (which is missing `"react-static-plugin-typescript": "^7.0.0"` & typescript, on another note).

steps to reproduce:
1. react-static create 
2. select typescript
3. install dependencies

### Environment
```

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-2700K CPU @ 3.50GHz
    Memory: 5.50 GB / 15.69 GB
  Binaries:
    Node: 11.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
    Internet Explorer: 11.0.17763.1
  npmPackages:
    react: ^16.8.2 => 16.8.6
    react-dom: ^16.8.2 => 16.8.6
    react-static: ^7.0.0 => 7.0.5
    react-static-plugin-reach-router: ^7.0.0 => 7.0.0
    react-static-plugin-sitemap: ^7.0.0 => 7.0.0
    react-static-plugin-source-filesystem: ^7.0.0 => 7.0.0
    react-static-plugin-typescript: ^7.0.0 => 7.0.0

```

### Expected Behavior
No error

**Comment by tannerlinsley** [comment]
Definitely a bug. Would you like to try and look into this one @meesvandongen?

**Comment by meesvandongen** [comment]
I will try, but cannot promise anything. I will report back soon.

**Comment by Herohtar** [comment]
`7.0.5` is giving me this error message in my repo after trying to upgrade, and I'm not using Typescript.

**Comment by tannerlinsley** [comment]
@meesvandongen, @sw-yx just PR'd some changes that should help fix this issue. I'm working on the last little bit to complete it.

@Herohtar, are you using `react-static-plugin-source-filesystem`?

**Comment by Herohtar** [comment]
@tannerlinsley Just figured it out... I was using `location: path.resolve('./src/pages')` as shown in the plugin example. Changing to just `location: './src/pages'` gets past that. My guess is it has something to do with Windows paths, since `path.resolve()` will give an absolute path of the form `C:\Users\...`

Now to figure out the next error I'm getting...

**Comment by tannerlinsley** [comment]
Yeah, that's a funky one. Open a new issue for any news stuff. This should be fine in the latest version (or the one I'm releasing tonight)

**Comment by 17cupsofcoffee** [comment]
For what it's worth, I'm still getting this issue on 7.0.7 with the basic template - seems to be the same thing that Herohtar mentioned, as I'm also on Windows, and removing the `path.resolve` fixed it for me.

**Comment by FayeB** [comment]
This problem is still occurring.  TannerLindsey's fix works but this still means difficulties for Windows based developers having to search Github for answers to this problem.
