### ISSUE TITLE
[Bug] Build error when using react-static-plugin-react-router.

### ISSUE THREAD

**Issue by dgavara** [nozzle/react-static#1095]
react-static version 7.0.5
![image](https://user-images.githubusercontent.com/40208273/55588427-bc73da80-56fb-11e9-82a8-19d6bfa46c97.png)

**Comment by tannerlinsley** [comment]
Please paste a link to your repo if you can. If it's not public, would you be able to work up a small example repo that has this issue so we can reproduce it and debug it?

**Comment by dgavara** [comment]
Here is the link to my repository.
https://github.com/dgavara/react-static-v7-bugs

**Comment by dgavara** [comment]
@tannerlinsley Did you get a chance to look into it?

**Comment by tannerlinsley** [comment]
I found the issue. The `components/Router` file is an artifact from an older testing version of the template, and in your case it is incorrectly proxying Reach Router, instead of React Router. I would just remove the proxy component file and import react-router directly.

**Comment by dgavara** [comment]
Great. So I need to use all the individual routes from react-router manually. Right?

**Comment by tannerlinsley** [comment]
Only for dynamic routes. Static routes are rendered using the Routes component from react static

Tanner Linsley

**Comment by dgavara** [comment]
But the error which I am getting is for static routes.

**Comment by tannerlinsley** [comment]
Make sure you don't have any references in your project to reach router.

Tanner Linsley

**Comment by dgavara** [comment]
Nope. I don't have any.

**Comment by dgavara** [comment]
Also I am not getting that error if I use react-router directly. And I am getting different error now. 

![image](https://user-images.githubusercontent.com/40208273/55835759-aba3da00-5aea-11e9-8d6f-40bbde2a767a.png)

**Comment by dgavara** [comment]
Think that's an issue with style-loader executing in non-browser environments. https://github.com/webpack-contrib/style-loader/pull/273/files
