### ISSUE TITLE
[Bug] Installation - Cannot install basic starter

### ISSUE THREAD

**Issue by aprather51** [nozzle/react-static#1096]
First time trying and installing react-static
![image](https://user-images.githubusercontent.com/10257247/55594490-6f950180-5705-11e9-89d7-852a0360b69c.png)

Trying to run, but end up getting bug...
![image](https://user-images.githubusercontent.com/10257247/55594712-45900f00-5706-11e9-90a9-c8faa63b6d61.png)

How do I resolve it?

**Comment by martiuh** [comment]
I assume you are using an older version of `react-static` (I had this issue with 5.9.12), in order to solve this issue just check your `static.config.js` file and at the very bottom remove the last object

```js
      {
        is404: true,
        component: 'src/containers/404',
      },
```

After that you should be good to go, although I think your app wouldn't have a custom 404 page.

**Comment by meesvandongen** [comment]
Your route should have `path: '404'`

**Comment by aprather51** [comment]
@martiuh  - I wouldn't know which version of `react-static` I as using, all I did was follow the instruction  [here](https://github.com/nozzle/react-static/tree/master/#quick-start). I checked with `static.config.js` and removed following syntax...
```js
    {
        is404: true,
        component: 'src/containers/404',
      },
```
I end up got another error when trying to run
![image](https://user-images.githubusercontent.com/10257247/55657038-98c59880-57be-11e9-9864-bbee86a9ef11.png)

@meesvandongen  -  rename `components` into `template` did not solve issue. 

I only wonder if there is a stable version of `react-static`? How do I install it and run without problem?

**Comment by martiuh** [comment]
What I would recommend is

```bash
# uninstall the global local version of react-static in your machine
npm uninstall -g react-static

# use npx to create a new react-static project
npx react-static create
```
The 7.0.5 works fine, I have used it on both Windows and Ubuntu. Yesterday I did 3 or 4 installs from `npx` and they worked well.

**Comment by tannerlinsley** [comment]
Newer major versions of react static include breaking changes. You can either follow the breaking changes outlined in the changelog to upgrade an existing project, or start a new one and migrate your existing code to it.

Tanner Linsley

**Comment by aprather51** [comment]
Did try everything, follow breaking change from changelog [here](https://github.com/nozzle/react-static/blob/master/CHANGELOG.md#700) and migrate. Still encounter same error...
```
Module not found: Error: Can't resolve 'react-static-routes' in '/.../.../.../../my-static-site/src'
```
After major break changes, It's becoming time consuming trying to find for solution so I will not continue. Hope there are improvement on template starter and guides in the future.  Thank for your time.

**Comment by tannerlinsley** [comment]
React-static-routes has been deprecated. If you are still inporting it in your projects, please `import { Routes } from 'react-static'` instead.

Tanner Linsley
