### ISSUE TITLE
using local fonts

### ISSUE THREAD

**Issue by tazaka** [nozzle/react-static#110]
Hello, if i use fonts from https://google-webfonts-helper.herokuapp.com and add to css file , build faild on error: 
Error: Module build failed: ModuleParseError: Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.

Can you help me ? Thank you

**Comment by D1no** [comment]
have you tried with latest?

**Comment by tazaka** [comment]
I have 3.0.6

**Comment by tannerlinsley** [comment]
Should be fixed in latest
