### ISSUE TITLE
[Bug] react-apollo can't resolve 'react-dom/server' in 7.0.x

### ISSUE THREAD

**Issue by Knovour** [nozzle/react-static#1116]
### Reporting a bug?

After updated from 6.3.6 to 7.0.7, react-apollo got problem.

```
[✓] Site Data Downloaded
  Error: ✖ ｢wdm｣:
  ERROR in ~/Projects/PROJECT_NAME/node_modules/react-apollo/react-apollo.esm.js
  Module not found: Error: Can't resolve 'react-dom/server' in '~/Projects/PROJECT_NAME/node_modules/react-apollo'
   @ ~/Projects/PROJECT_NAME/node_modules/react-apollo/react-apollo.esm.js 1354:20-47 1363:39-66 1404:20-47
   @  ~/Projects/PROJECT_NAME/src/App.jsx
   @ ~/Projects/PROJECT_NAME/src/index.js
   @ multi webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server ../lib/bootstrapPlugins.js ../lib/bootstrapTemplates.js index.js

```

### Environment

- react-static: 7.0.7
- react & react-dom: 16.8.6
- react-apollo: 2.5.4
- react-hot-loader: 4.8.3

**Comment by tannerlinsley** [comment]
Does this happen with just react-apollo, or with every/any `esm` module?

**Comment by Knovour** [comment]
I'm not sure, my project only use react-apollo right now

But I created a new project and added `ApolloProvider` again, it still cause the same error.

**Comment by tannerlinsley** [comment]
Go to the file `node_modules/react-static/lib/utils/binHelper.js` and comment out these lines:

```javascript
Module.prototype.require = function (modulePath) {
  // If we are running in the repo, we need to make sure
  // module resolutions coming from other react-static packages
  // are first attempted from the
  var isInWorkspace = needsWorkspaceCheck && inRepo(this); // Only redirect resolutions to non-relative and non-absolute modules

  if (!modulePath.startsWith('.') && !modulePath.startsWith('/')) {
    if ( // If module is in the repo try and redirect
    isInWorkspace || // Always try and redirect react and react-dom resolutions
    ['react', 'react-dom'].some(function (d) {
      return modulePath.includes(d);
    })) {
      try {
        modulePath = resolveFrom(path.resolve(process.cwd(), 'node_modules'), modulePath);
      } catch (err) {//
      }
    }
  }

  return originalRequire.call(this, modulePath);
};
```

Then let me know if it works.

**Comment by Knovour** [comment]
Same

```
  Error: ✖ ｢wdm｣:
  ERROR in /Users/knovour/Projects/my-static-site/node_modules/react-apollo/react-apollo.esm.js
  Module not found: Error: Can't resolve 'react-dom/server' in '/Users/knovour/Projects/my-static-site/node_modules/react-apollo'
   @ /Users/knovour/Projects/my-static-site/node_modules/react-apollo/react-apollo.esm.js 1352:20-47 1361:39-66 1402:20-47
   @ /Users/knovour/Projects/my-static-site/src/App.js
   @ /Users/knovour/Projects/my-static-site/src/index.js
   @ multi webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server ../lib/bootstrapPlugins.js ../lib/bootstrapTemplates.js index.js

  Error: ✖ ｢wdm｣:
  ERROR in /Users/knovour/Projects/my-static-site/node_modules/react-apollo/react-apollo.esm.js
  Module not found: Error: Can't resolve 'react-dom/server' in '/Users/knovour/Projects/my-static-site/node_modules/react-apollo'
   @ /Users/knovour/Projects/my-static-site/node_modules/react-apollo/react-apollo.esm.js 1352:20-47 1361:39-66 1402:20-47
   @ /Users/knovour/Projects/my-static-site/src/App.js
   @ /Users/knovour/Projects/my-static-site/src/index.js
   @ multi webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server ../lib/bootstrapPlugins.js ../lib/bootstrapTemplates.js index.js
```

**Comment by tannerlinsley** [comment]
Is there a `react-dom` module located in:
- `node_modules`?
- `node_modules/react-apollo/node_modules`?

**Comment by Knovour** [comment]
in `node_modules`

<img width="239" alt="螢幕快照 2019-04-17 上午12 58 53" src="https://user-images.githubusercontent.com/893846/56229259-138a8f80-60ac-11e9-896c-1b2d4fa9197c.png">

**Comment by tannerlinsley** [comment]
There's a `react-dom` directory in there? I can't see it.

**Comment by Knovour** [comment]
Sorry, I mean the `react-dom` is in the `node_modules` directory.
react-apollo's `node_modules` only have `ts-invariant` package inside

**Comment by tannerlinsley** [comment]
have you tried deleting your lock file and node_modules and reinstalling?

**Comment by Knovour** [comment]
I have tried to delete and reinstall it many times
And it only happens in version 7

**Comment by Knovour** [comment]
I added a `react-dom/server` alias in `react-static/lib/static/webpack/webpack.config.dev.js`.
And the error messages are gone
```
alias: {
        react: (0, _resolveFrom.default)(config.paths.NODE_MODULES, 'react'),
        'react-dom/server': (0, _resolveFrom.default)(__dirname, '@hot-loader/react-dom/server'),
        'react-dom': (0, _resolveFrom.default)(__dirname, '@hot-loader/react-dom'),
      }
```

But still has #1109 problem

**Comment by Knovour** [comment]
It looks like the same issue in Next.js
https://github.com/zeit/next.js/issues/3711

Delete `react-dom` alias is working, too

**Comment by tannerlinsley** [comment]
One reason this could be happening is because of our development alias to hot-loader/react-dom. In master, I've removed this alias for a different implementation and am hoping that that change alleviates this issue. If you have means to do so, please build master and test. Otherwise, wait for the next release and we'll see if this is improved at all.

**Comment by Knovour** [comment]
You mean change the path to `config.paths.NODE_MODULES`?

I have tried it before, nothing change. And `webpack.config.prod.js` has the same error when build.

I think the reason of this error is the `resolve-from` package will generate react-dom path to `/my-static-site/node_modules/react-dom/index.js`.

Then `react-dom/server` would become `/react-dom/index.js/server.js`.

If I add `replace('index.js', '')` to react-dom alias, it works fine

**Comment by Knovour** [comment]
Example project here.
https://github.com/Knovour/react-static-apollo

**Comment by Knovour** [comment]
So...?

**Comment by LukeStanislaus** [comment]
I am also getting this issue, I can edit the alias but that doesn't fix the problem in my CI 😢

**Comment by mtiger2k** [comment]
I add 
'react-dom/server': (0, _resolveFrom.default)(NODE_MODULES, 'react-dom/server'), 
in react-static/lib/static/webpack/webpack.config.dev.js, and the error is gone.

**Comment by bencpeters** [comment]
Getting this error as well.

**Comment by mattswart** [comment]
**For what it's worth**: I started getting this error after importing a google font in `app.css`

```
@import url('https://fonts.googleapis.com/css?family=Open+Sans|Orbitron&display=swap')
```

**Comment by tannerlinsley** [comment]
The alias has been removed and appears to have fixed things. Reopen if needed. Thanks!
