### ISSUE TITLE
react-static create should include starter .gitignore

### ISSUE THREAD

**Issue by stu-b-doo** [nozzle/react-static#1129]
**Is your feature request related to a problem? Please describe.**
Unnecessary manual step to git init after `react-static create`. The painful bit is looking up a starter .gitignore. I come to the react-static git repo, find a suitable .gitignore [such as this one](https://github.com/nozzle/react-static/blob/master/packages/react-static/templates/basic/.gitignore). 

**Describe the solution you'd like**
Deliver .gitignore as part of `react-static create` which I can modify or delete

**Comment by tannerlinsley** [comment]
This is a bug with npm pack. Currently it ignores .gitignore files in templating systems like React Static. We'll figure out a way to make this work better in the future.

**Comment by dgellow** [comment]
@tannerlinsley What would be a basic gitignore file?

```
node_modules
tmp
artifacts
```

Anything else to add to this list?

**Comment by noahbrenner** [comment]
Probably want to ignore `dist/` too.

**Comment by ngocdaothanh** [comment]
> What would be a basic gitignore file?

See `.gitignore` in the templates:
https://github.com/react-static/react-static/tree/master/packages/react-static/templates

> We'll figure out a way to make this work better in the future.

As of March 2021, this issue hasn't been fixed yet.
Let's reopen this issue?
