### ISSUE TITLE
[Bug] ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by marqpdx** [nozzle/react-static#1133]
### Overview

This is follow up to https://github.com/nozzle/react-static/issues/1122

A new app is created with `react-static create`

### Steps

1. create a new RS site - `react-static create`
1. choose basic template
1. cd into the new project
1. add the react-static-plugin-source-filesystem plugin - `yarn add react-static-plugin-source-filesystem`
1. add to the static.config.js as such:
```
  plugins: [
    [
      'react-static-plugin-source-filesystem',
      {
        location: path.resolve('./src/pages'),
      },
    ],
  ]
```
Now try `yarn start`, get error `ReferenceError: regeneratorRuntime is not defined`

The error references: `Error: The following error occurred in the plugin located at "/usr/local/projects/aa_working/Active/rs-test/my-static-site/node_modules/react-static-plugin-source-filesystem/node.api.js"`

Thanks :)

**Comment by marqpdx** [comment]
I wanted to follow up w/ this. Re-tried all this with 7.0.9, and got a new error (black screen of death, kind of wild actually)

```
An internal error occured!

Error: RoutesInner suspended while rendering, but no fallback UI was specified.

Add a <Suspense fallback=...> component higher in the tree to provide a loading indicator or placeholder to display.
    in RoutesInner
    in Unknown (created by Routes)
    in Routes (at App.js:16)
    in div (at App.js:15)
    in Unknown (created by Root)
    in Catch (created by Root)
    in Root (at App.js:9)
    in App (at src/index.js:17)
    at throwException (http://localhost:3000/main.js:20936:17)
    at renderRoot (http://localhost:3000/main.js:22190:15)
    at performWorkOnRoot (http://localhost:3000/main.js:23093:11)
    at performWork (http://localhost:3000/main.js:23003:11)
    at performSyncWork (http://localhost:3000/main.js:22977:7)
    at requestWork (http://localhost:3000/main.js:22832:9)
    at scheduleWork (http://localhost:3000/main.js:22645:9)
    at scheduleRootUpdate (http://localhost:3000/main.js:23340:7)
    at updateContainerAtExpirationTime (http://localhost:3000/main.js:23366:14)
    at updateContainer (http://localhost:3000/main.js:23434:14)
```
again, the steps:
```
react-static create
vim package.json # to edit webpack-dev-server" to "3.2.1" for other issue
yarn install # to update webpack-dev-server
yarn upgrade-interactive --latest # upgrade to 7.0.9
yarn add react-static-plugin-source-filesystem
# update the static.config.js w/ the plugin
yarn start
# get error
```

![Screen Shot 2019-04-19 at 9 12 40 AM](https://user-images.githubusercontent.com/1056353/56432727-58b4ea00-6283-11e9-8682-2cbfc0c438de.png)

**Comment by NukaPunk** [comment]
I'm getting the same error. Black screen was different, just the generic "An internal error occured!".

Checking the console I get this:

<img width="719" alt="image" src="https://user-images.githubusercontent.com/6144177/56473460-45478180-6431-11e9-9b43-6146883de46e.png">

So when I added an error boundary this is what I'm getting:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/6144177/56473435-09acb780-6431-11e9-8751-5e2d7e9ad1c5.png">

**Comment by sw-yx** [comment]
hey, just chiming in to say i tried to reproduce your bug and couldn't. everything works fine when i follow your steps except for editing webpackdevserver (cos it seems to be unrelated). its also harder to help you when you dont provide a repo for reproduction.

see https://github.com/sw-yx/reactstaticregenruntimebug for my repro of your steps and it works fine on my machine.

**Comment by NukaPunk** [comment]
I found mine was due to a typo where I was calling `ReactDOM.render(App, document.getElementById('app'))` instead of the correct `
ReactDOM.render(<App />, document.getElementById('app'))`. I'm not sure why an error that would normally percolate up was getting eaten by React Static. Might be worth looking into.

**Comment by maxholman** [comment]
I was getting the same Suspense error, and managed to track it down to where the templates are loaded in [src/browser/components/Routes.js](https://github.com/nozzle/react-static/blob/70e1f8c67738c1fa51f6f479f3ae91ae75394bdc/packages/react-static/src/browser/components/Routes.js#L83)

React isn't my expertise, nor react-static, so I just bypassed this by wrapping my `<Routes />` with a `<Suspense fallback=...>` as a temporary measure.

**Comment by tannerlinsley** [comment]
`<Suspense fallback='...'/>` is not a temporary measure. This is required. React Static uses Suspense (and suspense mocking) to generate the pages for your site. Start with the basic template and go from there.
