### ISSUE TITLE
CSS hot-reload and reloadClientData not working

### ISSUE THREAD

**Issue by bard** [nozzle/react-static#1144]
### Environment

```
    react: ^16.8.2 => 16.8.6 
    react-dom: ^16.8.2 => 16.8.6 
    react-static: ^7.0.0 => 7.0.5 
    react-static-plugin-reach-router: ^7.0.0 => 7.0.0 
    react-static-plugin-sitemap: ^7.0.0 => 7.0.0 
    react-static-plugin-source-filesystem: ^7.0.0 => 7.0.0 
```

### Steps to Reproduce the problem

1. `npx react-static create`
2. accept defaults
3. `yarn start`
4. modify `src/app.css`

### Expected Behavior

CSS changes are applied live.

### Actual Behavior

No change is applied. 

Appears to be CSS-specific since changes to `App.jsx` are applied.

**Comment by bard** [comment]
The same appears to affect `reloadClientData`. The event reaches the client (console shows "React Static: Reloading Data...") but content doesn't update.

**Comment by tannerlinsley** [comment]
We have issued a patch update to address a ton of hot-reloading problems. Please upgrade and reopen if the problem persists.

**Comment by bard** [comment]
Unfortunately the problem persists with both stylesheets and `reloadClientData`. (I cannot re-open an issue closed by a repository owner or collaborator.)
