### ISSUE TITLE
HTML <title> is empty on disabled JavaScript

### ISSUE THREAD

**Issue by tujoworker** [nozzle/react-static#115]
If I set a custom rendered `<Html><head><title>...` component in the **static.config.js** like `Document: {...}` - then the title gets not set without enabled JavaScript. There are a couple of reasons that speaks to have this set in the build process.

Title is empty in the index.html file, or all other files for instance.
```html
<title data-react-helmet="true"></title>
```

**Comment by EmilTholin** [comment]
Hi Tobias! Are you trying to use the same title for every page? You could use the `Head` in your topmost component instead, and it will work without JavaScript.

```javascript
import React from 'react'
import { Router, Link, Head } from 'react-static'
import Routes from 'react-static-routes'

const App = () => (
  <Router>
    <div>
      <Head>
        <title>This is my page title!</title>
      </Head>
      <nav>
        <Link to="/">Home</Link>
        <Link to="/about">About</Link>
        <Link to="/blog">Blog</Link>
      </nav>
      <div className="content">
        <Routes />
      </div>
    </div>
  </Router>
)

export default App
```

**Comment by tujoworker** [comment]
@EmilTholin Thanks for the tip! This works, Yes.

Anyway, the meta tags are working once I set them in the *static.config.js*, so why not have *title* working in there anyway? For sure, should then all the pages, witch have not set an additional `<Head><title>...` get this title? I would say, Yes. Thats how meta tags works as well.

**The Question is, is this a bug?**   

I don't know, but here is the config:
```javascript
    ...
    getSiteProps: () => ({
        title: 'React Static',
        metaDescription: 'A progressive static-site framework for React'
    }),
    Document: class CustomHtml extends Component {
        render() {
            const {
                Html,
                Head,
                Body,
                children,
                siteProps,
                renderMeta
            } = this.props

            return (
                <Html>
                    <Head>
                        <title>{siteProps.title}</title>
                        <meta charSet="UTF-8" />
                        <meta
                            name="description"
                            content={siteProps.metaDescription}
                        />
                        <meta
                            name="viewport"
                            content="width=device-width, initial-scale=1"
                        />
                        {renderMeta.styleTags}
                    </Head>
                    <Body>{children}</Body>
                </Html>
            )
        }
    },
    ...
```

**Comment by EmilTholin** [comment]
Interesting. I'm not very good at React Helmet, and I'm sure Tanner will come with some cool insight, but maybe the [HeadWithMeta component](https://github.com/nozzle/react-static/blob/master/src/static.js#L92-L106) should be changed to:

```javascript
const HeadWithMeta = ({ children, ...rest }) => {
  const hasTitle = React.Children.toArray(children)
    .includes(child => child.type === 'title')

  return (
    <head {...rest}>
      {head.base}
      {!hasTitle && head.title}
      {head.meta}
      {head.link}
      {process.env.extractedCSSpath && (
        <link rel="stylesheet" href={`/${process.env.extractedCSSpath}`} />
      )}
      {head.noscript}
      {head.script}
      {head.style}
      {children}
    </head>
  )
}

```

**Comment by tannerlinsley** [comment]
Have you tested that?

**Comment by EmilTholin** [comment]
No, not yet. Probably won't have time to test is properly today, sadly.

**Comment by tannerlinsley** [comment]
Well, if you'd like to test it soon and submit a PR, that looks like a good way to support both the default hard coded title and react-helmets title.
