### ISSUE TITLE
[Bug] Missing route for index page

### ISSUE THREAD

**Issue by dev-rsilver** [nozzle/react-static#1152]
I'm still experiencing the index.js error (#1122) when trying to utilize React Static on Windows 10. This error occurs directly after setting up a "basic" project via "create" and running yarn start with no modifications.

As far as I can tell, this may have something to do with the way the basic project is installed. Even with the latest version of React Static installed globally, once the CLI completes the project setup, the React Static packages (main and plugins) appear to be set to versions (in yarn.lock) that are lower than the latest available versions. 

Running yarn upgrade directly after installation of the template and then yarn start fixed this for me.

**Comment by xianrusso** [comment]
I ran into the same issue on Windows 10.  yarn upgrade did the trick for me.

**Comment by tannerlinsley** [comment]
This should be fixed in the latest version. Thanks guys!
