### ISSUE TITLE
getComponentForPath replacement

### ISSUE THREAD

**Issue by buzinas** [nozzle/react-static#1153]
From the Changelog:

> - The child renderer and corresponding getComponentForPath utility previously provided via the Routes component has been deprecated.

What's the replacement for `getComponentForPath` now that it was removed?

**Comment by rickyrombo** [comment]
+1 - I'm attempting to do animated routes, but this seems to be blocking me.

**Comment by tannerlinsley** [comment]
The replacement is a combination of `<Routes />` and `useRoutePath`. Similar to how React Router and Reach Router do animations by preserving the keys of both routes around, you can use these to do the same. I'll be working on an example as soon as I have some time.

**Comment by tannerlinsley** [comment]
We're going to track this in #1103

**Comment by buzinas** [comment]
`useRoutePath` always returns `/` for me 😕
