### ISSUE TITLE
Path to resolve styled-components FOUC on v6 is unclear

### ISSUE THREAD

**Issue by RickBross** [nozzle/react-static#1154]
Seems like the examples are outdated..

* Should i use `beforeRenderToHtml`?
* Should I use `renderToHtml`?
* Why doesn't `react-static-plugin-styled-components` fix it?
* Do I need to do a combination of all of these things?

Please help

**Comment by RickBross** [comment]
This is blocking my company from releasing our homepage... A lot of pressure on here. Totally down to paypal you guys a bounty for a hand!

**Comment by tannerlinsley** [comment]
I get my computer back from Apple in a day and I'll the this bounty on. Curse the MacBook keyboard!

**Comment by sw-yx** [comment]
i used to have this problem but `react-static-plugin-styled-components` fixed it for me actually. why did it not work for you. also calm down with the emojis.

**Comment by RickBross** [comment]
@sw-yx just using that in `.babelrc.plugins` and `static.config.js.plugins`? That's all I need?

**Comment by sw-yx** [comment]
yep

**Comment by RickBross** [comment]
If I do `npm run build`, cd to build, and then start a python server... the styles should even load if I disable javascript right?

Because it's not working... should I just commit it to my branch and let the CI pipeline push it up and hope it works?

**Comment by RickBross** [comment]
I `npm --save-dev react-static-plugin-styled-components`, is it okay if its in devdeps or no?

**Comment by RickBross** [comment]
@sw-yx?

**Comment by Herohtar** [comment]
I could be wrong, but I'm pretty sure they can't be in dev

**Comment by RickBross** [comment]
@Herohtar they? what's they?

**Comment by Herohtar** [comment]
Sorry, I meant the react-static plugins, like you asked about.

**Comment by RickBross** [comment]
@Herohtar 
<img width="571" alt="Screen Shot 2019-04-26 at 2 21 19 PM" src="https://user-images.githubusercontent.com/4257160/56828110-97701480-682e-11e9-9363-3bd2e787cf3c.png">

All I have to do is this + the package-lock.json and I should be good? Do I have to use yarn for some reason?

It's still not working.. do I even need to add anything in .babelrc?

**Comment by RickBross** [comment]
@tannerlinsley any idea? I'm trying to get this solved before EOD

**Comment by RickBross** [comment]
Are the versions correct? I'm using `react-static@6.0.18` but it's also in devDependancies because there are vulnerabilities in it and we can't have it in our production deps for compliance reasons.

Could that throw it off?

**Comment by Herohtar** [comment]
You probably can't use v7 plugins with react-static v6, and I think react-static has to be in the regular dependencies, but I'm not an expert on react-static so one of the others will have to confirm that.

**Comment by tannerlinsley** [comment]
React Static is a runtime and client dependency. Install it as such.

Tanner Linsley

**Comment by RickBross** [comment]
turns out it works with `react-static` as a devdep... I was using plugin@v7 and static@v6

**Comment by tannerlinsley** [comment]
Yeah, plugins are respectively versioned alongside react-static core for compatibility. You can only use v7 plugins with v7 core.

**Comment by RickBross** [comment]
Let's update the v6 README to yarn add @6^ or something then so it's more clear

**Comment by tannerlinsley** [comment]
Where in the readme?

**Comment by tannerlinsley** [comment]
I guess I assumed that was pretty generally understood. When v7 launches and we're not mixing version information in the README, it will also be more clear.

**Comment by Pixelatex** [comment]
` so it's more clear that you're following semvar and a major change isn't backwards compatible!`
Following semver is not an exception but is what should be expected, gonna close this as keeping it open will not help anyone further.
