### ISSUE TITLE
[Docs] the purpose of react-static-plugin-source-filesystem

### ISSUE THREAD

**Issue by adamchenwei** [nozzle/react-static#1156]
Whats up with the docs?
I do not really understand the purpose of `react-static-plugin-source-filesystem`
I used 'basic' template, its inside static.config.js

```
plugins: [
    [
      require.resolve('react-static-plugin-source-filesystem'),
      {
        location: path.resolve('./src/pages'),
      },
    ],
    require.resolve('react-static-plugin-reach-router'),
    require.resolve('react-static-plugin-sitemap'),
  ],
```

Can anyone let me know what is its purpose and why its need to include /pages folder? how it impact anything?

**Comment by tannerlinsley** [comment]
> A React-Static plugin that adds support for recursively importing routes from a directory

This means that any files in your projects `pages/` directory will be turned into static routes.

Example: 
- src/pages/index.js - would produce a route with the path of `/` and the template set to `src/pages/index.js`
- src/pages/about/us.js - would produce a route with the page of `/about/us` and the template set to `src/pages/about/us.js`
