### ISSUE TITLE
[Bug] 404 Not Found on routes with parameters

### ISSUE THREAD

**Issue by dgavara** [nozzle/react-static#1160]
The links with parameters are throwing 404 errors when the page loads. For example, one of my route is 

``` <Route exact path="/article/:id" component={Article} />```

The article ids are coming from the backend. So when I load the page I get 404 on

```http://localhost:3002/__react-static__/routeInfo/article/1```
```http://localhost:3002/__react-static__/routeInfo/article/2```
```http://localhost:3002/__react-static__/routeInfo/article/3```

How can we resolve this issue?

**Comment by benedfit** [comment]
Have you tried coupling one of the dynamic routing guides (https://github.com/nozzle/react-static/tree/master/docs/guides) with https://github.com/nozzle/react-static/blob/master/docs/api.md#addprefetchexcludes in your App.js?

**Comment by dgavara** [comment]
Yes. I did.
