### ISSUE TITLE
[Bug] CSS Hot Reload Not Working

### ISSUE THREAD

**Issue by Robp773** [nozzle/react-static#1169]
### Environment

  **System**:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 2.11 GB / 7.87 GB
  **Binaries**:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
    Internet Explorer: 11.0.17763.1
  **NPM**:
    "react": "^16.8.2",
    "react-dom": "^16.8.2",
    "react-static": "^7.0.0",
    "react-static-plugin-reach-router": "^7.0.0",
    "react-static-plugin-sitemap": "^7.0.0",
    "react-static-plugin-source-filesystem": "^7.0.0"

### Steps to Reproduce the problem

1. npm i -g react-static
2. react-static create
3. choose basic example
4. change app.css CSS to trigger reload

### Expected Behavior
Reloaded CSS displayed on screen. 

JS changes are reflected correctly but CSS does not apply on screen until I manually refresh. After experiencing this issue I created a fresh basic template and this is still not working there. 

After editing app.css the console shows - File changed: \src\app.css
Updating bundle...
[✓] Bundle Updated (0.7s)

so changes are being detected just not displayed.

**Comment by martiuh** [comment]
Upgrade to the latest version of react static. for example `yarn add react-static`

**Comment by Robp773** [comment]
> Upgrade to the latest version of react static. for example `yarn add react-static`

I've tried this and 'react-static -v ' shows 7.0.10 which should be the most recent.

**Comment by martiuh** [comment]
Yes the globally installed version is 7.0.10 but the package for basic starter is 7.0.0 (gotta bump that versions). so in your project directory just update the local version of the `react-static` to 7.0.10 (which is the latest version) and you should be able to HMR the CSS.

**Comment by Robp773** [comment]
Sorry for the confusion - I think the environment details I pasted above were from the basic template that I started up after encountering the problem on a different react-static project. I wanted to see if the HMR problem was present on a fresh react-static project. 

The project that I've been trying to debug this on has 7.0.10 already on it which I confirmed with npx react-static -v.  I also started up the fresh basic template and updated it from 7.0.0 and am still having the same issue.

**Comment by martiuh** [comment]
Yep. I can confirm HMR for CSS is not working out of the box in 7.0.10, I think it's a problem with the webpack config plugins order, I had a problem before with `extract-css-chunks-webpack-plugin` that was solved with the ordering of plugins. Gotta try it later and if works send a PR.
