### ISSUE TITLE
Helmet behaves strangely when rendering is asynchronous

### ISSUE THREAD

**Issue by EmilTholin** [nozzle/react-static#117]
I was seeing some odd behavior with meta tags in the head of the static pages in my project. I created a new `basic` template, added a `<Head><title> This is About </title></Head>` to the About container, and `<Head><title> This is Home </title></Head>` to the Home container, and ran `yarn build`. 

The About-title ended up in the `index.html` file and the Home-title was nowhere to be seen.

I looked into it a bit, and I think the [async renderToString](https://github.com/nozzle/react-static/blob/master/src/static.js#L67) is the culprit. It works as intended if I just remove the `await` keyword.

It looks like [Helmet doesn't work all that well if the rendering is asynchronous](https://github.com/nfl/react-helmet/issues/216). I dare not create a PR making it synchronous, because I'm sure it has some other use case I'm not aware of.

**Comment by tannerlinsley** [comment]
@EmilTholin Still seeing this issue?

**Comment by EmilTholin** [comment]
Yep. The simple test above gives the same result with a new `basic` example on `4.1.0`. It works flawlessly if I remove the [`await`](https://github.com/nozzle/react-static/blob/master/src/static.js#L67).
Maybe the race condition with asynchronous Helmet is just for certain specs. That's frustrating.

**Comment by tannerlinsley** [comment]
Does removing the await affect performance?

**Comment by EmilTholin** [comment]
In the `basic` example, no, but I can't say for certain. I guess it's a breaking change, since some users might rely on async logic in their own `renderToHtml` in `static.config.js` (even though it's not documented). 

Does the static files look right in your projects? [The issue with asynchronous logic between `renderToString` and the call to `rewind()`](https://github.com/nfl/react-helmet/issues/216) might not effect everyone then... Bummer.

**Comment by tannerlinsley** [comment]
Yes, we should most definitely change the `renderToHtml` method to be synchronous. This will be a breaking change mostly because of syntax. So we'll save it for the next breaking change batch.

**Comment by xogeny** [comment]
Why is it necessary to change `renderToHtml` to be synchronous.  If people want it to be synchronous, just don't have it return a `Promise`.  The ability to have it be `async` is quite important.  For example, I'm planning in integration `mathjax-node-page` so that my equations get converted to `<svg>` elements during site compilation.  The conversion is synchronous, so making `renderToHtml` will break everything.  I can imagine plenty of other scenarios as well.  If `getRoutes` can be `async`, why can't `renderToHtml`?

**Comment by EmilTholin** [comment]
Because [Helmet doesn't work properly](https://github.com/nfl/react-helmet/issues/216) if `renderToString` is asynchronous, and will introduce race conditions for your meta data rendering. The `await` keyword will always make it return a promise under the hood. There might be some other way around it and still keep it asynchronous, which would be awesome, but I haven't found any.

**Comment by EmilTholin** [comment]
I played around with this some more, and I think I've found something cool. What do you think?

```javascript
// Allow extractions of meta via config.renderToString
const renderStringAndHead = Comp => {
  const appHtml = renderToString(Comp)
  // Extract head calls using Helmet
  const helmet = Helmet.renderStatic()
  const head = {
    htmlProps: helmet.htmlAttributes.toComponent(),
    bodyProps: helmet.bodyAttributes.toComponent(),
    base: helmet.base.toComponent(),
    link: helmet.link.toComponent(),
    meta: helmet.meta.toComponent(),
    noscript: helmet.noscript.toComponent(),
    script: helmet.script.toComponent(),
    style: helmet.style.toComponent(),
    title: helmet.title.toComponent(),
  }

  return { appHtml, head }
}
const { appHtml, head } = await config.renderToHtml(
  renderStringAndHead,
  ContextualComp,
  renderMeta,
)
```

This way `renderToHtml` in `static.config.js` can be asynchronous, but Helmet will be rendered synchronously directly after the `renderToString`.

**Comment by Pixelatex** [comment]
Does this mean it's import to insert dynamic data in the head? :s
