### ISSUE TITLE
Example for Google Optimize CSS Delivery

### ISSUE THREAD

**Issue by tazaka** [nozzle/react-static#118]
Hello, please add example for google recommend optimize css delivery as here : https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery
I need use two separate css file , one for critical.css and second for non-critical.css.
critical.css render as minifi <style>...</style> to Head and non-critical.css would be loaded asynchronously as 

```
<html>
  <head>
    <style>
      .blue{color:blue;}
    </style>
    </head>
  <body>
    <div class="blue">Hello, world!</div>
    <noscript id="deferred-styles">
      <link rel="stylesheet" type="text/css" href="non-critical.css"/>
    </noscript>
    <script>
      var loadDeferredStyles = function() {
        var addStylesNode = document.getElementById("deferred-styles");
        var replacement = document.createElement("div");
        replacement.innerHTML = addStylesNode.textContent;
        document.body.appendChild(replacement)
        addStylesNode.parentElement.removeChild(addStylesNode);
      };
      var raf = requestAnimationFrame || mozRequestAnimationFrame ||
          webkitRequestAnimationFrame || msRequestAnimationFrame;
      if (raf) raf(function() { window.setTimeout(loadDeferredStyles, 0); });
      else window.addEventListener('load', loadDeferredStyles);
    </script>
  </body>
</html>
```

**Comment by tannerlinsley** [comment]
This is going to be up to you to determine what is "critical" css and what is non critical. I'm not sure this warrants an example though. Importing css files automatically compiles, optimizes and places them where they should be. If you wanted to alter that process, you would need to use some combination of webpack loaders or build hooks.
