### ISSUE TITLE
[Discussion] Stop build if missing data

### ISSUE THREAD

**Issue by simonunlikely** [nozzle/react-static#1185]
Hey !

Is there a way to stop the build if some data is not correctly fetched (for example server returns a 500 on a page). Right now build will still work rendering an empty page, but I'd rather have an older version with the content instead of an up to date code with broken content :)

**Comment by Herohtar** [comment]
Check the data and throw an exception?

**Comment by sw-yx** [comment]
what Hero said :)

**Comment by simonunlikely** [comment]
thanks ! That's what I thought but wasn't sure it actually was the best way to handle these cases :)
