### ISSUE TITLE
[Bug] FOUC when serving dist

### ISSUE THREAD

**Issue by ugogo** [nozzle/react-static#1186]
### Reporting a bug?

👋Hey guys,

I'm experiencing a FOUC issue when serving the dist bundle.
The app is using [evergreen](https://github.com/segmentio/evergreen) and nothing else (besides 3 lines of CSS there and there)

I've checked the related issues, but everyone is actively using `styled-components`, where I don't. Just in case I tried to use the `react-static-plugin-styled-components`, nothing has changed.

Thanks!

### Environment

```
 System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Memory: 1.41 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.6.0 - ~/.nvm/versions/node/v11.6.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.5.0-next.0 - ~/.nvm/versions/node/v11.6.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 74.0.3729.157
    Safari: 12.1
  npmPackages:
    react: ^16.8.6 => 16.8.6
    react-day-picker: ^7.3.0 => 7.3.0
    react-dom: ^16.8.6 => 16.8.6
    react-final-form: ^4.1.0 => 4.1.0
    react-hot-loader: ^4.8.4 => 4.8.4
    react-static: ^7.0.10 => 7.0.10
    react-static-plugin-reach-router: ^7.0.10 => 7.0.10
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

### Steps to Reproduce the problem

**Local bundle** ✅
- `yarn start` 

➡️ http://recordit.co/ckgVs7728B
 

**Dist bundle** ❌ 
- `yarn build`
- `yarn serve`

➡️ http://g.recordit.co/EOBg7dz5zw.gif

### Reproducible Demo

I reproduced the issue into this repo: https://github.com/ugogo/react-static-fouc

**Comment by sw-yx** [comment]
i think this is because you need to extract styles during SSR. thats what `react-static-plugin-styled-components` does if you look into the code (its not that long, go do it). we would just have to replicate what this guy did with gatsby https://github.com/segmentio/evergreen/issues/154 with the extractStyles api, with react-static.

**Comment by ugogo** [comment]
Hey @sw-yx, thanks a lot for the help!
Everything work as expected on my project, so I submitted a PR to externalize this plugin #1188.
🙌🏼

**Comment by sw-yx** [comment]
oh, wonderful!!!!
