### ISSUE TITLE
Need SEO support for new application 

### ISSUE THREAD

**Issue by vivekspraxa** [nozzle/react-static#1190]
Hi I am new with React-Static and I need a sample application example(Which have SEO support) through which I can achieve that. 

FYI: On my old app data coming as JSON from Server side . Can we show the site HTML in View Source.

Also it will be good if you can also explain how it works.

**Comment by sw-yx** [comment]
any app created with react static has seo support. you can ping your server data with `node-fetch`, `axios` or any other node data fetch libraries. please read the docs.

**Comment by skoal2007** [comment]
Hi vivekspraxa , did you have your answer?  which section of DOCs I should read? I cannot find related content.
