### ISSUE TITLE
[Bug] React static doesn't correctly set exit status when build fails

### ISSUE THREAD

**Issue by ibobo** [nozzle/react-static#1198]
React static doesn't set the exit status to non-zero when a build fails for some reason; this breaks usual unix semantics so when executing a build on a CI server it isn't possible to stop actions downstream if the build fails. Ie.
```
react-static build && rm -rf /destination && mv dist/* /destination
```
results in an empty folder if react-static failed.

**Describe the solution you'd like**
The correct behavior should be returning a non-zero exit status when a build is failed.

**Describe alternatives you've considered**
The workaround for now is to check if a specific file is rendered to assess the build completed successfully. Ie. above command should become:
```
react-static build; test -f dist/somefile && rm -rf /destination && mv dist/* /destination
```

**Comment by sw-yx** [comment]
yup, we have a PR for this already: https://github.com/nozzle/react-static/pull/1183. just that @tannerlinsley has been a bit busy with work but he'll get to this

**Comment by ibobo** [comment]
Glad to hear this! Thanks!
