### ISSUE TITLE
Allow `index.js` to be set to any file

### ISSUE THREAD

**Issue by StephanBijzitter** [nozzle/react-static#1202]
**Is your feature request related to a problem? Please describe.**
I'm using TypeScript and wish for my `index.js` file to be `index.ts`, but I cannot currently do that.

**Describe the solution you'd like**
https://github.com/nozzle/react-static/blob/master/docs/config.md#paths allows us to change `src` to anything we want, but it still requires us to have `index.js` in there.

An additional option could be added called `entryFileName` that defaults to `index.js`, allowing it to be overridden

**Describe alternatives you've considered**
An alternative to yet another option would be to look for `src/index.*$`, rather than `src/index.js`, allowing at least the file extension to be flexible.

**Comment by wappsify** [comment]
This is already possible by adding this in your `static.config.js`:
```js
export default {
  entry: 'index.ts',
}
```

I'm not sure why this is not documented, however the TypeScript template also uses this config option as can be seen here:
https://github.com/nozzle/react-static/blob/045a0e119974f46f68c633ff65116f9d74807caf/packages/react-static/templates/typescript/static.config.js#L8

**Comment by StephanBijzitter** [comment]
Oh, well then I'll create a small PR to update the documentation :-)
I didn't use the any template so I didn't see this.

Thanks so much!
