### ISSUE TITLE
How to load a updated data as React Static loading data at build time 

### ISSUE THREAD

**Issue by vivekspraxa** [nozzle/react-static#1206]

**Comment by sw-yx** [comment]
i dont appreciate low quality issues and will close this unless you elaborate.

**Comment by vivekspraxa** [comment]
I actually need to fetch the update data at a certain time period. In generally React Static fetch the data when the site is build which never update again.

**Comment by sw-yx** [comment]
i see. in this case you can trigger builds by using web hooks with cronjob services. there are many free services out there like https://webtask.io/ and you can find more https://www.google.com/search?q=free+cron+job.
