### ISSUE TITLE
[QUESTION]: Making it work with AWS lambda

### ISSUE THREAD

**Issue by itchingpixels** [nozzle/react-static#1224]
Hi!

Our react-static (which we really like to work with) site may soon outgrow our current setup - that we use it as a static site generator, and we were wondering if we can move the rendering to the server.
We're using serverless to deploy to AWS lambda in the company, and we were wondering how we could deploy react-static to work with AWS lambda. There's a guide, but to be honest, I don't entirely understand how that would work / how and what would we deploy exactly.
Are there any working examples, boilerplate or something similar that we could potentially use?

Thanks!:)

**Comment by digitalkaoz** [comment]
hey @itchingpixels the guide is pretty good (from me :D)
i use react-static in aws-lambda all the time!

simply create a lambda package which is simply your app (as you would develop it locally). Then you just need an AWS Lambda handler like in the guide. Afterwards you simply need to upload the static artifact to a s3 bucket.

**Comment by sw-yx** [comment]
no guide that i know of, @digitalkaoz what guide are you talking about?

**Comment by digitalkaoz** [comment]
Like the official Guide in the Docs?
https://github.com/nozzle/react-static/blob/master/docs/guides/aws-lambda.md

swyx <notifications@github.com> schrieb am Mo., 24. Juni 2019, 15:37:

**Comment by itchingpixels** [comment]
okay, thank you!
I actually completely misunderstood the reason to deploy this to lambda.
thanks!
