### ISSUE TITLE
Use Probot?

### ISSUE THREAD

**Issue by tannerlinsley** [nozzle/react-static#131]
https://probot.github.io/

**Comment by cgmx** [comment]
This would be a pretty cool integration 😮

**Comment by D1no** [comment]
Can it also file PRs when dependencies upgrade? That would be pretty cool

**Comment by cgmx** [comment]
Well if the app hasn't already been made, I'm sure it would be easy to make an app for it, @D1no.

**Comment by cgmx** [comment]
Although I'm not exactly sure how you could test dependency versions against each other? 🤔 
Could use NPM to query the version and then compare the version string against the version string of the local package?

**Comment by D1no** [comment]
They already exist:
- https://greenkeeper.io/
- https://www.versioneye.com/
- https://david-dm.org/

I was on the go when I commented and wondered if probot supports it too.

**Comment by tannerlinsley** [comment]
Now using Probot-stale and Probot-support :)
