### ISSUE TITLE
Warning: Expected server HTML to contain a matching <div> in <div>.

### ISSUE THREAD

**Issue by rileylnapier** [nozzle/react-static#144]
Hi, I just did react-static create and did the dynamic import example.

npm start and i'm getting this error.  did i do something wrong?

![image](https://user-images.githubusercontent.com/7017640/32642942-8334574c-c58c-11e7-9cd2-b39d84d0cfc1.png)

**Comment by rileylnapier** [comment]
my terminal output, if that helps

![image](https://user-images.githubusercontent.com/7017640/32642956-9ff5a39a-c58c-11e7-9f49-a35514879c24.png)

**Comment by EmilTholin** [comment]
Hi @rileylnapier!

It looks like you are using an old version of `react-static`. Could you try the newest version and see if you still have the same issue?

**Comment by denis-sokolov** [comment]
Happens for me with react-static 4.0.1. How can I help you investigate?

**Comment by EmilTholin** [comment]
Interesting. I get the same error with a fresh `dynamic-imports` on `4.0.1` as well. I'm not sure what causes it yet, but it might have something to do with [that the initial html can't be rehydrated](https://stackoverflow.com/questions/45350360/react-16-warning-warning-js36-warning-did-not-expect-server-html-to-contain-a).

**Comment by EmilTholin** [comment]
It's not an issue when building the site with build and testing it with serve, so there is no issue with the "real" static rendering and rehydration, only with the dev server.

**Comment by EmilTholin** [comment]
I have looked into this a bit, and it only happens in development, so it's nothing to worry about.

This is how the `document` looks like after using `yarn start` on a fresh `dynamic-imports` example:

<img width="600" alt="dynamic_imports_document" src="https://user-images.githubusercontent.com/11573167/32672775-a86d22bc-c64c-11e7-9dd6-1a577150ec24.png">

And [this is how the development index file placeholder looks like](https://github.com/nozzle/react-static/blob/master/src/utils.js#L153-L157). If you add the markup above to the placeholder component, the warning goes away. 

It looks like React got `suppressHydrationWarning` in `16.1.0`, but I'm not entirely sure how to use it yet. It should be possible to use that to suppress this warning in development.

**Comment by rileylnapier** [comment]
also, i think im seeing an issue with the 4.0.1 release. 

looking at "master", this is the tree:

![image](https://user-images.githubusercontent.com/7017640/32673085-86da45c0-c602-11e7-9007-cde941e3a168.png)

but then comparing to what npm installed.  granted we have a "lib" folder now...

![image](https://user-images.githubusercontent.com/7017640/32673102-97fdd9b6-c602-11e7-82db-0384b545cc89.png)

but the files are different. i noticed this because im trying to use the config.devServer option and its not working in 4.0.1.  The spread operator is missing in webpack config.

so im thinkning there was a problem with publishing to npm?

**Comment by EmilTholin** [comment]
Interesting. That is another issue, though. Could you open up a new one for that?

**Comment by tannerlinsley** [comment]
Master is usually out of date with release until we cut a release.  It's ben 5 days, but I just cut a new minor release. so that shouldn't be a problem now.

**Comment by rileylnapier** [comment]
i deleted my comment about the 4.0.1 release out of sync with master as i created separate ticket... realized it makes the convo little disjointed.  

but def would like to see npm start not throw warning/error in console

**Comment by rileylnapier** [comment]
Since in dev server we aren’t doing any ssr.  Maybe we just reactdom.render instead of hydrate?  And only hydrate on production builds??

**Comment by tannerlinsley** [comment]
I'm not seeing this any longer in the latest build with master. Going to close unless someone has an alternative way to repro. :)

**Comment by tacomanator** [comment]
I still have the issue on latest release 4.3.0. Only happens in development (not production). To reproduce add a custom route which is not declared in config. For example:

```javascript
import React from "react";
import { Router, Route } from "react-static";
import Routes from "react-static-routes";

const log = ({match}) => {
  // ...
  return null;
};

export default () => (
  <Router>
    <div>
      <Route path="/" component={log} />
      <Routes />
    </div>
  </Router>
);
```

**Comment by denis-sokolov** [comment]
Still have the issue in 4.3.0. I do not have any custom routes. I made sure I have no `<Route>` components at all except for App (`() => <Router><Routes /></Router>`).

**Comment by ChristophM2000** [comment]
Hi,
It also occurs here with fresh basic example.
In Chrome Debugger I see getFirstHydratableChild tries to get an element child of the #root element. But at a time #root does not have any childs, so it returns null, which leads to that warning.

Greetings,
Christoph

**Comment by rileylnapier** [comment]
It’s because we don’t server render anything during the dev phase. Really
we shouldn’t call hydrate when we are dev and only call hydrate during prod

**Comment by mattyfresh** [comment]
Checking for hot module replacement is one solve:

```javascript
 const render = (Comp) => {
    const renderMethod = !!module.hot ? ReactDOM.render : ReactDOM.hydrate
    renderMethod(
      <AppContainer>
        <Comp />
      </AppContainer>,
      document.getElementById('root')
    )
  }
```

**Comment by corydeppen** [comment]
I'm seeing this using the TypeScript example running `react-static@4.3.4`. Can this be reopened if it's still a valid issue?

**Comment by bernatfortet** [comment]
I'm getting this on my production site after I build 
`Did not expect server HTML to contain a <div> in <div>.`

    "react-static": "^5.7.6",
    "react-router": "^4.2.0",

**Comment by amrita-griffin** [comment]
I'm getting this issue on both localhost (dev) and production environments. Same error as @bernatfortet 
   ` "react-static": "^5.9.7" `is used.

**Comment by krazyjakee** [comment]
@mattyfresh this was a fix for a separate project but thanks for taking the time. Been working on this bug for a looong time.

**Comment by kimgysen** [comment]
Uhm...!  This solution does not click for me. How are you supposed to fix bugs in dev if you can't reproduce prod in dev? And why would you opt for omitting server rendering during development? Seems everybody agrees with that, not sure if I do. Any convincing possible?

**Comment by Pixelatex** [comment]
Please don’t necro ancient issues.

This was an issue on pre v6 versions and if it still occurs on current versiosn, make a new issue.

Also nextjs isn’t really related to this

**Comment by sayjeyhi** [comment]
In my case it was because of using `PersistGate`  and `react-loadable`.
if you using this libraries, you could use preloadAll instead of preloadReady

**Comment by SleeplessByte** [comment]
Thanks everyone for the input into this issue. The original issue has been resolved. If you run into this yourself, please search and try the solutions mentioned above.

We are understaffed in terms of this project as there is no direct sponsoring/funding yet. We happily receive PRs for documentation if you deem it necessary or helpful.
