### ISSUE TITLE
'react-static-routes' shown as missing

### ISSUE THREAD

**Issue by Nikica-Luger** [nozzle/react-static#145]
The 'react-static-routes' module is shown as missing by many tools (Webstorm, Flow static types etc), although react static renders perfectly. Other issues reported errors during build, this is not the case now, just this warning.

**Comment by EmilTholin** [comment]
Hi @Nikica-Luger!

This is probably because `react-static` has an `index.d.ts` file with all the types declared, but `react-static-routes` doesn't. That could be a nice PR, but I'm not sure where the `react-static-routes` repository is located.

**Comment by D1no** [comment]
@tannerlinsley if you tell me how / where react-static-routes is exported, I can add it to somehow to the typings.

**Comment by Nikica-Luger** [comment]
So `react-static-routes.js` is dynamically created in `dist` directory and `dist` directory is set as path to resolve modules in webpack.config?

**Comment by tannerlinsley** [comment]
Correct

**Comment by tannerlinsley** [comment]
I'm not sure how to alleviate this. Any ideas? Maybe shipping a dummy `react-static-routes` module with `react-static` core, so it doesn't freak out?

**Comment by EmilTholin** [comment]
Yeah, that should probably be good enough. Im horrible at TypeScript, but maybe add something basic like this to `index.d.ts`?

```typescript
declare module "react-static-routes" {
    export const Routes: React.Component;
}
```

**Comment by tannerlinsley** [comment]
Does the latest addition to the typescript ignores, fix this?

**Comment by D1no** [comment]
I checked and I have not encountered the issue. Any other TypeScript User is welcome to check as well. We only strong type our containers, not presentational components

**Comment by tannerlinsley** [comment]
Going to close then, unless it can be repo'd again :) Thanks guys.

**Comment by corydeppen** [comment]
I can reproduce it in a new TypeScript project by renaming `src/App.js` to `src/App.tsx`.

**Comment by D1no** [comment]
Lets continue here: https://github.com/nozzle/react-static/issues/205
