### ISSUE TITLE
4.0.1 release via npm doesn't match documentation

### ISSUE THREAD

**Issue by rileylnapier** [nozzle/react-static#146]
looking through documenation readme, it says I can use 

static.config.js.devServer

this config is used in this file:
![image](https://user-images.githubusercontent.com/7017640/32673602-adb8de98-c604-11e7-8bcb-b0cb9c425c3b.png)

via spread operator:
![image](https://user-images.githubusercontent.com/7017640/32673616-b8cfecf4-c604-11e7-82b0-738ebc85c949.png)

but looking at the code npm installed...

there is no lib/webpack/index.js and the lib/webpack.js file doesn't have devServer config being extended... so my devServer doesn't work as I need it

![image](https://user-images.githubusercontent.com/7017640/32673645-cabf42fc-c604-11e7-8221-c643b60efd1c.png)

**Comment by tannerlinsley** [comment]
Closed with latest release of 4.1.0 :) Sorry!

**Comment by rileylnapier** [comment]
thanks for quick turnaround!  testing out the devServer options now :)

**Comment by rileylnapier** [comment]
yay! my proxy worked!!

![image](https://user-images.githubusercontent.com/7017640/32676299-faea90f8-c60e-11e7-8ab7-c5b5e9c2d0c6.png)

gonna give yall a star :)

**Comment by tannerlinsley** [comment]
Awesome! What's that for exactly?

**Comment by rileylnapier** [comment]
so im building a frontend and the api lives on a different server say

https://api.tacoshop.com/v1/

and my frontend lives here:

https://www.tacoshop.com

but when I dev, i can't hit https://api.tacoshop.com/v1/ from my localhost because of CORS yeah?  our CORS rules won't validate localhost so i can't do some requests.

but what i can do, in my frontend code is prefix all requests that I know need to go to the api with __dev__ and then create a proxy rule on the server to reroute all __dev__ to api and set the correct origin header so my api will accept my requests.

config looks like the following:

![image](https://user-images.githubusercontent.com/7017640/32676898-2f1c47fc-c611-11e7-8dbf-dc7ae27ccec4.png)

i tried to do this with gatsby, but they don't allow me as much control as yall do.

**Comment by tannerlinsley** [comment]
Awesome :)
