### ISSUE TITLE
CSS missing in production build

### ISSUE THREAD

**Issue by frewinchristopher** [nozzle/react-static#148]
Hi all, 

First off, AMAZING project, what you all have built is such a cool and powerful tool!!!

I've got an issue with styles in the production build. I have a single App.css (always already precompiled from SASS), and it has a single entry point in `App.js`

I've tried both `require('App.css')` and `import 'App.css'` as a sanity check in `App.js`, but I get same result - no styles with the production build!

The styles show up exactly as expected on localhost:3000 with the dev build `npm run start`

But I get a style-less page after running a `npm run build` and `npm run serve` (no warnings during `npm run build` either)

I do get one warning in the Chrome developer console when running the production build in the browser however:

`Resource interpreted as Stylesheet but transferred with MIME type text/html`

This has got to be something small, but I'm just not seeing it.... any ideas?

Thanks!

**Comment by EmilTholin** [comment]
Hi @frewinchristopher!

That's odd. Could you use `react-static create` to create a new example, `npm run build` and `npm run serve` and see if you get the same behavior?

**Comment by frewinchristopher** [comment]
OK, I figured it out! (by accident) when I removed the `siteRoot` property from `static.config.js`, the CSS works... perhaps a CORS issue or something? I suppose I can only use the `siteRoot` property when the project is "truly" (actually productive with the corresponding domain)? Anyway, thanks for the super quick response time!

**Comment by tannerlinsley** [comment]
:)

**Comment by slauzinho** [comment]
Is this intended? We can only have `siteRoot` when deploying to production. Otherwise we need to comment out this line to be able to get the css styles or `yarn build` > `yarn serve` will serve the site without css.
