### ISSUE TITLE
Error in paths

### ISSUE THREAD

**Issue by poorpaddy** [nozzle/react-static#154]
When utilizing the new paths functionality, anything other than  `dist: './dist'` seems to fail. For example when I run it correctly builds the following paths out as `dist/somethingElse`.

```
paths: {
    dist: './dist/somethingElse',
  },
```

However it then says it can't resolve the paths of the pages `Module not found: Can't resolve '../src/pages/home/index'`

**Comment by poorpaddy** [comment]
In further investigation the `dist/somethingElse/react-static-routes.js` is outputting as `import src_pages_home_index from `'../src/pages/home/index'` which would expect the src directory to be within the dist folder. It should output as `../../src/pages/home/index`.

**Comment by EmilTholin** [comment]
Hi @poorpaddy!

Great find! I think [this way of importing templates](https://github.com/nozzle/react-static/blob/master/src/static.js#L229-L231) has to be made dynamic, like this:

```javascript
  const templateImports = templates
    .map(template => `import ${template.replace(/[^a-zA-Z]/g, '_')} from '${path.resolve(config.paths.ROOT, template)}'`)
    .join('\n')
```

**Comment by poorpaddy** [comment]
That does the trick
