### ISSUE TITLE
Builds fail for components requiring `window`

### ISSUE THREAD

**Issue by jay-manday** [nozzle/react-static#16]
Hi there!

Really great work on this, very nice alternative to Next + Gatsby and very slick. I've been getting errors on my build, I have 2 components that need the browsers window object and they crash the build process, I've tried a few different thinks like `ErrorBoundary` etc. My project runs just fine in the dev environment (minus my font but ill get to that later). 

Here is the error: `ReferenceError: window is not defined`

[Here is the Repo](
https://github.com/jay-manday/jm-site)

Anyway, thanks for this killer project, deff gonna use this for some more things in the future.

**Comment by tannerlinsley** [comment]
Since react-static builds static versions of your site, most times you'll need to make sure the `window` object is available (which is essentially making sure you are in a browser environment). For most cases, simply wrapping your browser-only code in something like this is sufficient:
```javascript
if (typeof window !== 'undefined') {
  // browser-only code
}
```

**Comment by ineghi** [comment]
Hi guys !

Is React static can be used in other context than browser ?
If no, could we assume document and window are globally available and get rid on conditionnal imports and stuff like that everywhere ? Or better, a option to make some variables globally accessible in the react static config, to let the project versatile. 
```
if (typeof window !== 'undefined') {
    const SmoothScroll = require('smooth-scroll')
}
```

this exemple works, but when you are using multiple front libraries it quickly become a mess ^^

What you think ?

**Comment by tannerlinsley** [comment]
You must write node safe code. Using window without a document check will error in the build stage because there is no DOM.  https://react-static.js.org/docs/concepts#writing-universal-node-safe-code
