### ISSUE TITLE
consider adding a command "react-static deploy" ?

### ISSUE THREAD

**Issue by rileylnapier** [nozzle/react-static#160]
i'd like to write my deploy steps with the same babel setup that react-static gives.

so an idea could be inside static.config.js we add an export for deploy.  and react-static deploy just calls this function?

could lead the way for plugins like "react-static-deploy-s3" or "react-static-deploy-netlify" or 

would we be interested in something like this? if not i'll maybe just use a gulpfile.babel.js file

**Comment by tannerlinsley** [comment]
That is an interesting idea. There’s a lot of assumptions with it that I
would want to flesh out first.  To get started on that:

Would `react-static deploy` simply be a one-to-one function to a `deploy`
method? Would it need access to anything else in the static.config.js? What
would that entire lifecycle look like?

**Comment by rileylnapier** [comment]
hmm, i'll ponder this a bit... it might make sense to keep things simple and just bring my own deployment, but my thought process:

i would think it would just be a one to one mapping with the exported function.  or maybe a string to the location of the file and/or string mapping to a node_module if plugins get introduced?  

we could either import all of static.config.js in the deploy funciton or import { getConfig } from 'react-static/lib/utils';

to keep the lifecycle simple, i would maybe then decouple any other steps so when deploying you might have to

react-static build && react-static deploy

static.config.js
```
export default {
  deploy: {
    name: "react-static-sync-s3",
    options: {
      Bucket: "my-bucket",
      ACL: "public"
    }
  },
}
```

or maybe 
```
import myDeployScript from './my-deploy-script';

export default {
  deploy: myDeployScript
}
```

**Comment by tannerlinsley** [comment]
So, I've been thinking more about this. It technically wouldn't be very difficult at all to do this on your own.  If your main reason is so that you have access to the same babel environment, you could easily just import and use `babel-register` at the top of your own npm script, and go to town.

What benefits would this feature provide over that, other than not needing to create this file?

**Comment by rileylnapier** [comment]
yeah suppose i could just babel-register.  i just think its kind of ugly to sit at the top of the file.  let me just do that for now and if i come up with better reason then ill repopen
