### ISSUE TITLE
Selecting "styled-components" generates an incomplete package.json

### ISSUE THREAD

**Issue by josephdburdick** [nozzle/react-static#162]
Hello, when using the latest version of this (v4.0.1) and selecting "styled-components" out of the options  to generate an incomplete package.json is generated which prevents the project from working properly.

The following is generated:
```
{
  "dependencies": {
    "react-static": "^4.1.0"
  }
}
```

**Comment by EmilTholin** [comment]
Hi @jorgegonzalez!

That's odd. How did you go about it? I just installed a fresh global version of `react-static@4.1.0`, ran `react-static create`, named it `test-styled`, selected the `styled-components` example and got the following `package.json`, which worked great:

```json
{
  "name": "react-static-starter",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "start": "react-static start",
    "build": "react-static build",
    "serve": "serve dist -p 3000"
  },
  "dependencies": {
    "axios": "^0.16.2",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-router": "^4.2.0",
    "react-static": "^4.1.0",
    "styled-components": "2.2.0"
  },
  "devDependencies": {
    "eslint-config-react-tools": "1.x.x",
    "serve": "^6.1.0"
  }
}
```

**Comment by jorgegonzalez** [comment]
Don't @ me 💅

**Comment by tannerlinsley** [comment]
?

**Comment by josephdburdick** [comment]
Hmm, interesting. It appears my global install left me with v4.0.1. I did another global install and was left without 'styled-components' inside package.json. I'll try to reinstall.

**Comment by josephdburdick** [comment]
Can confirm after explicitly requesting `react-static@4.1.0` instead of just `react-static` that it installed correctly with all dependencies.
