### ISSUE TITLE
Does dom change references after hydrating ?

### ISSUE THREAD

**Issue by ineghi** [nozzle/react-static#166]
Hi folks, 

I copied a Three.js scene (working in a classical React project) in a basic react-static scaffold, and I observed a strange behavior;
The code was properly executed, but nothing was rendered... then I make changes in the parent component; hot reload made everything to work properly.

The classical way of working of Three.js is to make an append of a renderer property containing a generated canvas element in the dom. 
My guess is that once the pre render build is done and the application hydrates, the reference of the appended canvas element is lost, thus the renderer does nothing.

Anyway, I made it work by passing the ref of a already-there blank canvas to the renderer, as the reference was then controlled in the react environment, but still, the question bothers me :)

Did I missed something ?

**Comment by D1no** [comment]
We use three.js as well, and yes, you need to manage the dom via react (what you did is correct), or carefully manage the `shouldComponentUpdate` lifecycle of an enclosing component (to have a playing field to work in that is not managed by the react world).

Hot module replacement diffs against the internal representation of the AST, so yes, it would take out any externally added elements (if they are not blocked by `shouldComponentUpdate`).

Using refs is the proper react equivalent to jQueries `$.select("canvas")` as those refs are updated incase the component gets re-mounted etc.

Hope this helps. If you don't have any further questions, feel free to close this issue.
