### ISSUE TITLE
[Feature Request] Critical CSS Generation

### ISSUE THREAD

**Issue by mjsisley** [nozzle/react-static#167]
React-snap (an alternative approach to static site generation) allows for automated critical css generation (https://github.com/stereobooster/react-snap#inline-css). It uses a combination of https://github.com/peterbe/minimalcss and https://github.com/filamentgroup/loadCSS.

Other critical css generation tools include: 
* https://github.com/addyosmani/critical
* https://github.com/pocketjoso/penthouse

This was discussed briefly here: https://github.com/nozzle/react-static/issues/118, but wanted to point to some other examples of critical css generation being done in an automated way.

**Comment by D1no** [comment]
Mh, the idea intrigues me. Though it is important to know, that automatic critical css optimisations require a perfect css AST. Access already exists for such optimisations via the `renderToHTML` hock, as per the documentation:

> ## [Configuration (`static.config.js`)](https://github.com/nozzle/react-static#configuration-staticconfigjs)
> A `static.config.js` file is required at your project root to configure react-static. It must export a **default** object with the following interface:
> ```javascript
> export default {
>   // ...
> 
>   // An optional function to customize the server rendering logic. Receives:
>   // - render: renders the JSX to and html string
>   // - Component: the final react component to be rendered to HTML
>   // - meta, a MUTABLE object that is exposed to the optional Document component as a prop
>   // Expected to return an HTML string
>   // This is the perfect place for css-in-js integration (see styled-components and glamorous examples for more information)
>   renderToHtml: (render, Component, meta) => {
>     meta.hello = 'world'
>     return render(<Component />)
>   },
> 
>   // ...
> }
> ```

One could throw an async function in there that fires up any optimisation by parsing the final component to HTML -> optimiser and adjust the meta information before calling the final render.

Given that, I am not in the position to estimate the impact / value of this (we use styled components and one stylesheet). So I guess when a prototype of this exists, we can all take a look at it. And for that, to me it seems no changes to the code are necessary.

**Comment by tannerlinsley** [comment]
Yeah, I agree with @D1no. The current api technically allows you to implement some level of this on your own, give you have access to the raw HTML and styles that will get written out to disk beforehand in an async function.  

Most implementations of critical css right now also rely on actually rendering the page content in a browser, detecting on screen elements, and then extracting out the css for those elements. Though I'm very intrigued by this possibility, the current implementations available right now would significantly increase build times (need to render the page in something like puppeteer) and I wouldn't feel comfortable including something like this in the core just yet.  

When things settle down in that arena, and a clear leader emerges, then we could look at some official bindings or built-in options.  For now, I suggest playing around with the configs `renderToHtml: async (render, Comp, meta) => {...}` function. You can really get your hands dirty there without much work :)
