### ISSUE TITLE
static image is not showing

### ISSUE THREAD

**Issue by gmchaturvedi1** [nozzle/react-static#17]
My static image is not howing .

regards
gmchaturvedi

**Comment by derekperkins** [comment]
Do you have more details? Are you talking in dev mode or in production? Are you putting the image file in the `public` folder and linking to it from there?

**Comment by gmchaturvedi1** [comment]
yes i am working in decv mode  and putting my image files in the same folder of components.

reagrds
gmchaturvedi

**Comment by tannerlinsley** [comment]
To reference raw assets using only a URL, you must put them in the `public` folder. Otherwise, you have to use a webpack loader.
