### ISSUE TITLE
Add markdown rule

### ISSUE THREAD

**Issue by josephdburdick** [nozzle/react-static#171]
Hello, I've made a few attempts and want to know if I'm on the right track. 

I'm importing project details in markdown files and I've set the webpack option within static.config.js as follows:
```
webpack: (config, { defaultLoaders }) => {
    const renderer = new marked.Renderer()
    config.module.rules.push({
      test: /\.md$/,
      loader: 'html!markdown?gfm=false',
      options: renderer,
    })
    return config
  },
```
When running the project I get a series of errors:
```
Failed to rebuild.
./node_modules/grid-styled/dist/index.js
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <p>&#39;use strict&#39;;</p>
| <p>Object.defineProperty(exports, &quot;__esModule&quot;, {
|   value: true

./node_modules/react-dom/index.js
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <p>&#39;use strict&#39;;</p>
| <p>function checkDCE() {
|   /<em> global <strong>REACT_DEVTOOLS_GLOBAL_HOOK</strong> </em>/

./node_modules/react/index.js
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <p>&#39;use strict&#39;;</p>
| <p>if (process.env.NODE_ENV === &#39;production&#39;) {
|   module.exports = require(&#39;./cjs/react.production.min.js&#39;);
```
And the errors continue quite a bit. Obviously I'm not configuring webpack correctly. I assume that if it had anything to do with the `html` loader definition in my new rules that it would fail at an HTML item and tell me so. Your docs seem high-quality, I just believe I'm missing something. Any direction would be greatly appreciated, thank you.

**Comment by EmilTholin** [comment]
Hi @josephdburdick!

This might not be what is giving rise to your issue, but I think you want to give the `renderer` as an option in `options`, and not as the entire `options` object:

```javascript
webpack: config => {
  const renderer = new marked.Renderer()

  config.module.rules.push({
    test: /\.md$/,
    use: [{
      loader: 'html-loader',
    }, {
      loader: 'markdown-loader',
      options: {
        renderer,
      },
    }],
  })

  return config
},
```

**Comment by josephdburdick** [comment]
@EmilTholin  Thanks for pointing that out. I made the change and I'm still facing a SyntaxError. I believe that Webpack isn't registering the config because it's parsing this as as Javascript.

Resulting terminal ouptu from running the project:
```
{ SyntaxError: /Users/jb/Projects/internal/presentday/src/data/projects/aoa-ny/aoa-ny.md: Invalid left-hand side in prefix operation (1:2)
> 1 | ---
    |   ^
  2 | order: 10
  3 | name: aoa-ny
  4 | title: AOA NY
    at Parser.pp$5.raise (/Users/jb/Projects/internal/presentday/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp$2.checkLVal (/Users/jb/Projects/internal/presentday/node_modules/babylon/lib/index.js:3233:14)
    at Parser.checkLVal (/Users/jb/Projects/internal/presentday/node_modules/babylon/lib/index.js:6145:22)
    at Parser.pp$3.parseMaybeUnary (/Users/jb/Projects/internal/presentday/node_modules/babylon/lib/index.js:3464:12)
    at Parser.pp$3.parseExprOps (/Users/jb/Projects/internal/presentday/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/jb/Projects/internal/presentday/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/jb/Projects/internal/presentday/node_modules/babylon/lib/index.js:3344:19)
    at Parser.parseMaybeAssign (/Users/jb/Projects/internal/presentday/node_modules/babylon/lib/index.js:6474:20)
    at Parser.pp$3.parseExpression (/Users/jb/Projects/internal/presentday/node_modules/babylon/lib/index.js:3306:19)
    at Parser.pp$1.parseStatement (/Users/jb/Projects/internal/presentday/node_modules/babylon/lib/index.js:1906:19)
  pos: 2,
  loc: Position { line: 1, column: 2 },
  _babel: true,
  codeFrame: '\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 1 | \u001b[39m\u001b[33m--\u001b[39m\u001b[33m-\u001b[39m\n \u001b[90m   | \u001b[39m  \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m 2 | \u001b[39morder\u001b[33m:\u001b[39m \u001b[35m10\u001b[39m\n \u001b[90m 3 | \u001b[39mname\u001b[33m:\u001b[39m aoa\u001b[33m-\u001b[39mny\n \u001b[90m 4 | \u001b[39mtitle\u001b[33m:\u001b[39m \u001b[33mAOA\u001b[39m \u001b[33mNY\u001b[39m\u001b[0m' }
error Command failed with exit code 1.
```

**Comment by EmilTholin** [comment]
That's frustrating. I added the `webpack` code I wrote above to the `static.config.js` in a fresh `styled-components` example in `react-static@4.2.3`, and added [this example Markdown](http://www.unexpected-vortices.com/sw/rippledoc/quick-markdown-example.html) to a `.md` file, and it worked.

Could you create a repository isolating your issue?

**Comment by D1no** [comment]
Nope. ‘.md’ needs to be added to the code whitelist. 
https://github.com/nozzle/react-static/blob/master/src/commands/index.js

We tryied to add common extensions. When ever Babel parses non js files you’ll see the token error.

**Comment by EmilTholin** [comment]
I [created a very basic example of how it can be done](https://github.com/EmilTholin/react-static-markdown-example). Maybe it can be of some help.

**Comment by josephdburdick** [comment]
I appreciate the examples you guys have produced, it has helped me get a better idea as to what the problem is and what the solution could be.

First, I understand the approach with static.config.js, is there a way however to import the .md file inside the static.config.js file so produce the data that would be summoned within a route definition? For example, I have a route for "projects" and each :id for the project is the name of the markdown or frontmatter file that would be pulled from `src/projects/projectID.md`

**Comment by EmilTholin** [comment]
@josephdburdick Ah, gotcha. In your `src` files you need to use webpack, but in the `static.config.js` file you can use any Node utility you like, e.g:

```javascript
import { markdown } from 'markdown'

// ... 

export default {
  getRoutes: () => {
    return [
      {
        path: '/about',
        component: 'src/containers/About',
        getProps: () => ({
          markdown: markdown.toHTML(fs.readFileSync('./src/test.md', 'utf-8')),
        })
      },
    ]
  },
}
```

I added [an example to the same repository](https://github.com/EmilTholin/react-static-markdown-example/blob/master/static.config.js).
