### ISSUE TITLE
Feature: Custom Path for server

### ISSUE THREAD

**Issue by poorpaddy** [nozzle/react-static#174]
It would be nice to add a custom path for local server. Right now when you spin up the local server it builds out a dist directory to serve from. This creates a permissions conflict when using https with port 443 and when your builds export to dist as well.

```
paths: {
    src: 'src', // The source directory. Must include an index.js entry file.
    serve: 'local' // The directory local server runs from
    dist: 'dist', // The output directory.
    public: 'public' // The public directory (files copied to dist during build)
  },
```

**Comment by EmilTholin** [comment]
Hi @poorpaddy!

Have you seen the `Using Custom devServer properties` part of the [Webpack Config and Plugins](https://github.com/nozzle/react-static#webpack-config-and-plugins) section? You can customize the `devServer` [however you like](https://github.com/nozzle/react-static/blob/master/src/webpack/index.js#L88).

**Comment by poorpaddy** [comment]
Hi @EmilTholin,

Yes, I'm currently using it but not sure how to stop it from generating dist everytime react-static runs.

```
devServer: {
    host: 'local.xxxx.com',
    historyApiFallback: true,
    https: (USE_HTTPS) ? {
      key: fs.readFileSync('./cert/local-xxxx-com.pem'),
      cert: fs.readFileSync('./cert/local-xxxx-com.pem'),
      ca: fs.readFileSync('./cert/local-xxxx-com.pem')
    } : false,
    disableHostCheck: true,
    port: USE_HTTPS ? 443 : 5000
  },
```

**Comment by tannerlinsley** [comment]
If you're using HTTPS, or any ports lower on the scale, you'll likely need to use `sudo react-static start/build` either way. Does that solve your problem?

**Comment by poorpaddy** [comment]
@tannerlinsley not really. I need to to use https locally which sudo is fine for. But for the actual build for production output I do not want https or sudo because the server the static html gets deployed will handle that and sudo causes some challenges in that case since it is an automatic deployment based on our pom file.

**Comment by tannerlinsley** [comment]
So you want the dev server to be able to use a directory other than dist?

**Comment by poorpaddy** [comment]
That is is correct.

**Comment by tannerlinsley** [comment]
Should be available in the latest release as a new config option: `config.paths.devDist` :)
