### ISSUE TITLE
Support for trailing slash ("/")

### ISSUE THREAD

**Issue by pA1nD** [nozzle/react-static#176]
Only in the local development env (via `npm start`): Have a page like `http://localhost:3000/portfolio` and accessing it as `http://localhost:3000/portfolio/` gives neither the page itself nor the 404 page.
Instead it will show you only the loading animation and shows an error in the console.

Expected behaviour for me would be to show the /portfolio.

**Comment by EmilTholin** [comment]
Hi @pA1nD!

Great find! I think this behavior was introduces in https://github.com/nozzle/react-static/pull/164. I tried with https://github.com/nozzle/react-static/commit/122470d2c54cc1b8973c32ba781c497a8744626b (the commit just before that), and it works as intended.

It is not just trailing `/` that gives rise to the issue. E.g. `/blog/post/1` has the same problem.
