### ISSUE TITLE
Closing script tag in prop string breaking HTML parser in browser

### ISSUE THREAD

**Issue by BeheadedKamikaze** [nozzle/react-static#178]
I have blog post content coming from Wordpress and it contains Javascript tags. This is fine and renders properly using `<article dangerouslySetInnerHTML={{ __html: post.body }} />`.

The issue is that the props get serialised into the bottom of the document, but my `post.body` string contains the fragment `</script>`, which causes the browser to stop parsing the document as a script, and the rest of the string gets parsed as HTML; the result is not pretty.

One solution would be in the `window.__routeData` to encode the slash using a backslash like `<\/script>`, which I have done manually and verified that it works. Another solution would be to break the string, like `"...<" + "/script>..."`.

Is there any way for the encoder to do this automatically?

There is nothing "special" about the `/` character so it doesn't get encoded by default - it's just rather unfortunate that when it appears between `<` and `script>`, that it breaks the context in a browser parser.

**Comment by tannerlinsley** [comment]
Yeah we should probably escape stuff like that.
