### ISSUE TITLE
devDist path doesn't work

### ISSUE THREAD

**Issue by poorpaddy** [nozzle/react-static#181]
The expected result on start would be a directory created called local. It does not and simply generates a dist folder as it did before.

ex
```
paths: {
  dist: './dist/' + env + '/',
  devDist: 'local'
}
```

**Comment by EmilTholin** [comment]
Hi @poorpaddy! Could you try `4.3.1` and see if this works now?

**Comment by poorpaddy** [comment]
Confirmed. devDist is working.
