### ISSUE TITLE
Syntax error:  Octal literal in strict mode (9:50)

### ISSUE THREAD

**Issue by VladimirDev93** [nozzle/react-static#184]
Hello,

I really liked the demonstration of the module so I thought why not try it. After installing the module **globally**, I've created the app, navigated to the folder, ran `npm start` and this is what it printed. 
I haven't touched anything.

```bash
> react-static start


=> Copying public directory...
=> [✓] Public directory copied: 5.597ms
=> Building Routes...
More than one route is defined for path: /
More than one route is defined for path: /
=> [✓] Routes Built: 153.290ms
=> Building App Bundle...
=> [✓] App serving at http://localhost:3000

Failed to rebuild.
./dist/react-static-routes.js
Syntax error:  Octal literal in strict mode (9:50)

   7 | import src_containers_Post from '..\src\containers\Post'
   8 | import src_containers_Blog from '..\src\containers\Blog'
>  9 | import src_containers____ from '..\src\containers\404'
     |                                                   ^
  10 |     const templateMap = {
  11 |     t_0: src_containers_Home,
  12 | t_1: src_containers_About,
```

Also, there are lots of `Babel` module warnings that something is deprecated. Something for ES7.

`react-static v4.3.0`

**Comment by EmilTholin** [comment]
Hi @VladimirDev93! That's interesting. I just installed a fresh `react-static@4.3.0` globally, used `react-static create` to create a `basic` example, and used `npm start` in the folder, and I don't get this error. 

What example did you use? Do you get the same error if you use `npm start` instead of `react-static start` to start the dev server?

The warnings you see in the console [will be removed in a later release when Babel 7 is more mature. It's just one thing remaining before the PR can be merged](https://github.com/nozzle/react-static/pull/161).

**Comment by VladimirDev93** [comment]
@EmilTholin Yes I created the `basic` example and used `npm start`, not the `react-static start` command.

If it's any help
`nodejs : 8.9.1`,
`npm: 4.6.1`,
`os: windows 10`

I've just tried to update `npm` to `5.5.1` and still getting the same error, however, I did not test the module on `Linux Mint` yet.

**Comment by EmilTholin** [comment]
That's interesting. It looks like you are running Node with `--use-strict` in some way. I have never used Node on Windows, so I don't think I can be of much help there.

Could you try changing the name of `src/containers/404.js` to `src/containers/notfound.js`, and change `src/containers/404` to `src/containers/notfound` in `static.config.js` and see if that helps? It might be that Node on Windows has problems with file names starting with a number if that should work.

**Comment by VladimirDev93** [comment]
Nope, that doesn't work as it gave me 5 errors of `Module not found` after changing from `404` to `notfound` (`404.js => notfound.js in containers` and `404 => notfound in static.config.js`).

If nobody else is reporting this issue, then my OS has problems.

**Comment by VladimirDev93** [comment]
Everything works fine on `Linux Mint`

Just strange that I was waiting for it to **launch the default browser**. Can you make it so that when the app is served successfully on a local server, that it also launches the default browser with live reload?

**Comment by EmilTholin** [comment]
Great that it's working on Linux Mint!

You can [change the options to the Webpack Dev Server with `devServer`](https://github.com/nozzle/react-static/blob/master/src/webpack/index.js#L88) in `static.config.js`, but I don't think you can set `open: true`.

**Comment by ImranMH** [comment]
I have face the same problem in my windows machine . is show the message below 

User@DESKTOP-B4M1POT MINGW64 /g/working/react/react-static
$ yarn start
yarn start v0.21.3
$ react-static start

=> Copying public directory...
=> [✓] Public directory copied: 8.141ms
=> Building Routes...
=> [✓] Routes Built: 682.275ms
=> Building App Bundle...
=> [✓] App serving at http://localhost:3000
Failed to rebuild.
./dist/react-static-routes.js
Syntax error: G:/working/react/react-static/dist/react-static-routes.js: Octal l                 iteral in strict mode (9:50)

   7 | import src_containers_Post from '..\src\containers\Post'
   8 | import src_containers_Blog from '..\src\containers\Blog'
>  9 | import src_containers_404 from '..\src\containers\404'
     |                                                   ^
  10 |     const templateMap = {
  11 |     t_0: src_containers_Home,
  12 | t_1: src_containers_About,

**Comment by karland** [comment]
I have the same problem on Windows. Even on Windows the import path should have forward slashes:

RIGHT:
```JS
import src_containers_404 from '../src/containers/404'
```
WRONG:
```JS
import src_containers_404 from '..\src\containers\404'
```

Now, when arriving at `\404` node thinks `\4` is an Octal. I have made [PR #191](https://github.com/nozzle/react-static/pull/191) to fix the issue.
