### ISSUE TITLE
add support to deploy to gh-pages 

### ISSUE THREAD

**Issue by killvung** [nozzle/react-static#185]
Not sure whether this has been done or not, but apparently I was trying to use the techniques found from 
https://medium.freecodecamp.org/surge-vs-github-pages-deploying-a-create-react-app-project-c0ecbf317089
and 
https://github.com/rafrex/spa-github-pages 

to deploy the react-static generated site to github through gh-pages. 

Anyone?

**Comment by tannerlinsley** [comment]
I would suggest just uploading the dist folder to GitHub pushed like you
would any other site. But use the hash router by placing the `type='hash'`
on the Router component.
