### ISSUE TITLE
[Feature]Serving site on Network during dev

### ISSUE THREAD

**Issue by gagan0723** [nozzle/react-static#187]
* Serving files over a network come handy during development on other devices connected to the same network. Here's how [create-react-app does it](https://github.com/facebookincubator/create-react-app/blob/47af4b42cd9d9c77c8bc7b4edd7c5d6fa48f88c3/packages/react-dev-utils/WebpackDevServerUtils.js#L91).
* Launch the default browser.

```react-dev-utils``` provides both the functionality out of the box.

**Comment by EmilTholin** [comment]
Hi @gagan0723! Do you mean in development? Running `build` and then `serve` gives you a url for looking at the site on the network.

**Comment by gagan0723** [comment]
@EmilTholin Yes during development.

**Comment by tannerlinsley** [comment]
This would be cool. Looks like a lot of work?

**Comment by tannerlinsley** [comment]
Closing this for now, but I'd love to see a simpler way of implementing this.  I wonder if the `serve` package does this already?

**Comment by EmilTholin** [comment]
Yes, `build` and `serve` gives you a nice network url, but I don't know of an easy way to open up the webpack-dev-server to the network. The approach in [this answer](https://stackoverflow.com/questions/35412137/how-to-get-access-to-webpack-dev-server-from-devices-in-local-network#answer-45014417) might be worth exploring.
