### ISSUE TITLE
Implement Create React App's eslint setup

### ISSUE THREAD

**Issue by cr101** [nozzle/react-static#19]
Please consider implementing Eslint which does a much better job of explaining JS errors than browsers do which is helpful for everyone but especially beginners.

**Comment by tannerlinsley** [comment]
Have you tried the built-in eslint configuration?

**Comment by cr101** [comment]
@tannerlinsley I have not yet but I've used CRA's eslint and it's incredibly useful. I'm considering porting an app built with CRA over and I'm not sure what the implications would be.

**Comment by tannerlinsley** [comment]
React-Static doesn't prescribe a linter during the build stages, but does ship with an .eslintrc configuration that works with Prettier and eslint. Closing this for now :)

**Comment by hundsim** [comment]
I've been missing this a lot as well. Found the package that includes the shareable ESLint configuration used by Create React App: [eslint-config-react-app](https://www.npmjs.com/package/eslint-config-react-app), and it should be possible to integrate:

"If you want to use this ESLint configuration in a project not built with Create React App, you can install it with following steps..."

Unfortunately though, despite the easy 2-step path to implement those configs, I couldn't get it to work :/

**Comment by JustFly1984** [comment]
Please don't embed eslint-config-react-app.
@hundsim You can install in as devDependency and globaly, extend from it in
.eslintrc Right now I can say that this config is not required for
development at all, since we have fresh react-tools config.

2018-03-27 4:56 GMT+08:00 hundsim <notifications@github.com>:
