### ISSUE TITLE
dist no longer accepts environment builds

### ISSUE THREAD

**Issue by poorpaddy** [nozzle/react-static#190]
Before 4.3.1, one could configure their package scripts as to include unique environment specific builds like such:

package.json
```
"dev": "NODE_ENV=dev react-static build",
"cqa": "NODE_ENV=cqa react-static build",
"prod": "NODE_ENV=prod react-static build"
```

In static.config.js
`const env = process.env.NODE_ENV || 'dev';`
```
paths: {
  dist: './dist/' + env + '/',
  devDist: 'local'
}
```

Now builds only output `dist/production` regardless of the above settings.

**Comment by EmilTholin** [comment]
Hi @poorpaddy! `NODE_ENV` is now explicitly set with the [`start` and `build` commands](https://github.com/nozzle/react-static/blob/master/src/commands/index.js#L39-L47). Do you have the option of using another variable than `NODE_ENV` for your own configuration? If not, we might have to rethink this approach.

**Comment by poorpaddy** [comment]
I do not have another option because our automated deployments to each of our environments rely on NODE_ENV.

**Comment by tannerlinsley** [comment]
This is an interesting problem.  There are so many things that rely on the node env viarable, including internal react and react-ssr optimizations. Not sure what to do here yet.

**Comment by poorpaddy** [comment]
I think pigeon holed into 2 specific environments is probably not the most optimal but that's my opinion having worked for several corporations of which zero have had only 2 environments is their SDLC.

**Comment by tannerlinsley** [comment]
This should no longer be an issue. You can use any environment variables you want!
