### ISSUE TITLE
[Propose] Adding F.A.Qs Section

### ISSUE THREAD

**Issue by hql287** [nozzle/react-static#194]
First of all, just wanted to say thanks for building this. I've been following this since the day you published and I have to say that I'm having a much better DX than Gatsby as I'm currently building 2 sites with `react-static` (both are still in progress though). 

However, skimming through the issues, I noticed that a lot of people (myself included) ran into common problems like:

* Path issues
* Loading external scripts
* Adding Google Analytic
* SASS Support

I also noticed that you've already started working on the [project Wiki](https://github.com/nozzle/react-static/wiki/How-to:-Pagination) but it looks like only members can contribute to this, so I would like to propose adding an F.A.Q list to the `README.md` file, where we can refer to common issues (and solutions) like above. 

If this sounds helpful, I can work on a PR for this.

**Comment by tannerlinsley** [comment]
A FAQ would be great! For the time being it could be inline in the readme, but then as it grows, we could link out to nested markdown pages or something. Go for it!
