### ISSUE TITLE
Polyfill needed when using automatic routing in IE11

### ISSUE THREAD

**Issue by thupi** [nozzle/react-static#199]
Hi, i was recently looking for static website generators. I have really like working with React and love react-static's approch to solve this kind of problems.

However, when i switched from blank template to basic i discovered that IE 11 needed a polyfill to work with react-static sites with automatic routing. 

What would be the best practice solution for this issue :-) ?

**Comment by EmilTholin** [comment]
Hi @thupi! I'm not quite sure what API you are missing in IE 11. Do you see an error in the console?

I would guess it's the `Promise` API. You can use e.g. [promise-polyfill](https://www.npmjs.com/package/promise-polyfill).

```javascript
import Promise from 'promise-polyfill'; 
 
if (!window.Promise) {
  window.Promise = Promise;
}
```

**Comment by tannerlinsley** [comment]
Yes this is a great approach.

**Comment by thupi** [comment]
Thansk for the quick response :-) ! I'll do that :-) !
