### ISSUE TITLE
Implement react-error-overlay

### ISSUE THREAD

**Issue by cr101** [nozzle/react-static#20]
Pleased consider implementing [react-error-overlay](https://github.com/facebookincubator/create-react-app/tree/master/packages/react-error-overlay) which is also available on [npm](https://www.npmjs.com/package/react-error-overlay)

**Comment by tannerlinsley** [comment]
Good idea

**Comment by tannerlinsley** [comment]
This looks to be extremely difficult haha. If anyone has experience doing this (hopefully in a less complex way than create-react-app does), feel free to take a swing at it.

**Comment by tannerlinsley** [comment]
Done.
