### ISSUE TITLE
history prop missing on Router in TypeScript example

### ISSUE THREAD

**Issue by corydeppen** [nozzle/react-static#205]
I just created a new app using the TypeScript template and have run into a few issues, including the [existing issue](https://github.com/nozzle/react-static/issues/145) related to the TS definition for `react-static-routes`. My other issue is related to the react-router definitions. After I changed to `src/App.tsx`, I noticed the following TS error related to the use of `<Router>`:

```bash
Type '{ children: Element; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Router> & Readonly<{ children?: ReactNode; }> & Re...'.
  Type '{ children: Element; }' is not assignable to type 'Readonly<RouterProps>'.
    Property 'history' is missing in type '{ children: Element; }'.
```

Since `Router` [expects a `history` prop](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Router.js#L11) as part of [`RouterProps`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-router/index.d.ts#L78), I'm trying to understand how react-static works without specifying this prop and whether it's possible to use TypeScript more strictly in a react-static app.

**Comment by D1no** [comment]
I just did a very quick and shorthand definition file. We only use typescript on containers and data flow.

If you would like, I would welcome to get the definitions file 1:1 what react-static does.

The definitions file is in `src/index.d.ts`
https://github.com/nozzle/react-static/blob/master/src/index.d.ts

This augments the `src/index.js`
https://github.com/nozzle/react-static/blob/master/src/index.js

**Comment by tannerlinsley** [comment]
React static handles the `history` prop under the hood unless you specifically handle it yourself. As for typescript, @D1no hit the nail right on the head. :)

**Comment by corydeppen** [comment]
If react-static handles the `history` prop under the hood, I don't think it's feasible to use the `Router` definition from react-router-dom, as it requires a `history` prop. What if the following was added to the list of react-router overrides to make the prop optional?

```ts
export class Router extends React.Component<{ history?: any }> {}
```

For the react-static-routes issue, I think we'd be able to modify the existing declaration file by adding the following:

```ts
declare module 'react-static-routes' {
  import * as React from 'react';
  export class Routes extends React.Component {}
}
```

**Comment by D1no** [comment]
@corydeppen that sounds like a good Idea — do you want to PR those proposals? Otherwise I'll add those changes.
