### ISSUE TITLE
how to do url params?

### ISSUE THREAD

**Issue by rileylnapier** [nozzle/react-static#206]
looking at react-router docs, it seems you do path = "/order/:id" ~ but it try this and can't seem to get it to route to my order component.

is this possible with react static?

**Comment by rileylnapier** [comment]
also, whenver i seem to use query string params, they get truncated...  

is this a react router thing or a react static thing?

**Comment by tannerlinsley** [comment]
1. react-static routes in the static.config.js are always absolute, so you cannot use any variable patterns in those. If you are wanting to write your own react-router <Route> components, you may want to look into the custom routing section in docs.

2. Query strings should function normally, eg. `<Link to='/blog?page=2'>Page 2</Link>` should navigate you to `/blog?page=2`. Remember that you must have a route defined in your static.config.js to handle that path. :)

**Comment by rileylnapier** [comment]
I was doing `window.location.href = "/order?id=123"`;

and it was changing the path to "https://www.somedomain.com/order"

i can try with using react router things instead

**Comment by tannerlinsley** [comment]
This should be fixed now. Reopen if needed
