### ISSUE TITLE
should we be renaming Helmet to Head?

### ISSUE THREAD

**Issue by rileylnapier** [nozzle/react-static#208]
I feel like renaming a library like this leads to confusion for people who are familiar with the library.  I think it makes more sense to leave the library the name of the library as to let the user of react-static connect the dots for themselves?

I suppose I am free to import Helmet from 'react-helmet' myself... 

anyway... figure i would ask and maybe have chat about it?  in the past i have done this in an attempt to make things more clear to my developers and it always ends up being more confusing that just leaving the names what they are and not abstracting or changing names...

**Comment by EmilTholin** [comment]
Hi @rileylnapier! I personally think it's a good idea to proxy `Helmet` as `Head` like it is now, and suggest to users they use that. This way the same `Helmet` instance will be used in the app and in the meta data rendering in the build step, [which is required for Helmet to work properly](https://github.com/nfl/react-helmet/issues/125).

**Comment by rileylnapier** [comment]
I see.... I suppose it makes sense from a standpoint that we want to encourage / require someone from using the same Helmet across the entire app.  But still not sold on renaming the export.

if renaming the export is a way to encourage usage of the same helmet.  We should introduce a prefix to Helmet like "RS_Helmet" ~ so that if we ever have another library which requires the same import/export across the app we have a standard already.

**Comment by tannerlinsley** [comment]
There is no guaranty that we will always use helmet, in fact we've already
come close to replacing it already. For this reason, we use an internal
name and not the Technology name.

**Comment by rileylnapier** [comment]
fair
