### ISSUE TITLE
Support react-router-redux

### ISSUE THREAD

**Issue by rileylnapier** [nozzle/react-static#211]
So I would like to interact with my routing via redux.

A few things came up.  In the readme, its mentioned that I can pass "history" to the router which is used with react-router-redux... But looking at the docs for react-router-redux that uses this method, it says that its not compatible with react-router 4x.

https://github.com/reactjs/react-router-redux

sooo they point me to documentation to use react-redux-router 5.  These documentation tell me to use a new exported "ConnectedRouter" which I think its going to work because you all do some magic behind the scenes with Router right?  Since I import Router from 'react-static' and not 'react-router'?

Any thoughts on this?

**Comment by tannerlinsley** [comment]
Still working on this. Stay tuned

**Comment by mikestopcontinues** [comment]
Very much looking forward to this!

**Comment by happypeter** [comment]
any progress ?

**Comment by happypeter** [comment]
@tannerlinsley

**Comment by tannerlinsley** [comment]
Not yet 😔

**Comment by happypeter** [comment]
getting route info with mapStateToProps's ownProps  and pass it to selectors also helps, when we have not react-router-redux yet

**Comment by robbyemmert** [comment]
Bummer. This is a deal breaker for me. Being tied to a magic router is a no-no for my apps. The flexibility to use whatever router I want would be huge. This should be possible, since what you're concerned with is really isomorphic/render time state management. In theory, you'd just need to pass a different history object in to React Router each time you render a route.

**Comment by dalisoft** [comment]
Any news related to this issue?

**Comment by dalisoft** [comment]
I using `connected-react-router` in CRA, but knew about `react-static` today, loved and now trying to create dev-env (as did with CRA before) with `react-static`.

If there any news about this, would be great.

Thanks for this app :)
