### ISSUE TITLE
React components functions in static routes definition

### ISSUE THREAD

**Issue by Jonarod** [nozzle/react-static#220]
Regarding `static.config.js`, the docs says:

```json
...
component: 'src/containers/Home', // specify the react component that will render this route
...
```

well, I expected this to accept a "react component"... but got it wrong :stuck_out_tongue_winking_eye:

I tried to supply a react class component there, then I got an error:
`TypeError: template.replace is not a function`

I went to see the portion of the code throwing this error  (in `node_modules/react-static/lib/static.js` line 407) and in fact I see `react-static` doesn't expect a component in `component:`, rather it expects a string representing the path of a component.

#### Is it the desired behavior ?
Would it be possible to test if supplied `component:` value is a function?
```
if (typeof template === 'function') {
   // ignore subsequent imports and use provided function instead
}
```
I tried to do it myself in hope to submit a PR but stopped after other side effects. So I ask: what are the consequences of using a function instead of a path ?

**Comment by tannerlinsley** [comment]
This should be better documented. There is in fact a very strict data serialization layer between the config/static code and browser-side code for several reasons. To satisfy that separation, react components for routes cannot be directly passed in the config. The only place in the config that is safe to use react is actually the Document class.

**Comment by Jonarod** [comment]
Hmmm...
Is this immutable ? or is there any hope to see `components:` accept react components ?
In fact it is a bit confusing because the docs also tends to make analogy with `react-router` which accepts react components as routes.

**Comment by tannerlinsley** [comment]
What you're referring to is Auto routing. By passing the source to a
component, react static can Auto build the react router navigation routes
for you. You can of course use manual routing though, where you don't
reference a component, and simply handle your routes using react router as
normal. There is a large section on this in the docs.

**Comment by Jonarod** [comment]
Nope, I got that. 
I am referring to `static.config.js` and the `components:` key we have to ship with each routes.
```js
[{
    path: '/',
    component: 'src/containers/Home', // specify the react component that will render this route
  },
...
```
It was just to my impression that I could throw a function to it instead of a path.

Now yes, if that is intentional and will NOT change, I suggest to update the docs to mention something like: 
```
...
component: 'src/containers/Home', // specify the PATH of a react component that will render this route
...
```

**Comment by tannerlinsley** [comment]
Agreed. If you would like to PR that change, that would be great
