### ISSUE TITLE
Warnings during install

### ISSUE THREAD

**Issue by TVScoundrel** [nozzle/react-static#222]
Out of the box I get a lot of warnings:
`
warning "react-static > babel-loader@7.1.2" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
warning " > eslint-config-react-tools@1.0.10" has unmet peer dependency "eslint-plugin-class-property@^1.0.6".
warning " > eslint-config-react-tools@1.0.10" has unmet peer dependency "eslint-plugin-import@^2.7.0".
warning " > eslint-config-react-tools@1.0.10" has unmet peer dependency "eslint-plugin-jsx-a11y@^5.1.1".
warning " > eslint-config-react-tools@1.0.10" has unmet peer dependency "eslint-plugin-react@^7.1.0".
warning "eslint-config-react-tools > eslint-config-airbnb@15.1.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@^5.1.1".
`
It does not stop the project from being built, but it may be nice to have it fixed anyway?

Thanks for an awesome tool though!

**Comment by EmilTholin** [comment]
Hi @TVScoundrel! This will be fixed when [this is merged](https://github.com/nozzle/react-static/pull/161). There is just a tiny regression in Babel 7 that has to be fixed first.

**Comment by TVScoundrel** [comment]
ah kewl @EmilTholin 🙇
