### ISSUE TITLE
Add a way to specify a non-default `static.config.js` to use

### ISSUE THREAD

**Issue by crubier** [nozzle/react-static#223]
Hi, I would like to be able to configure `react-static` a bit more, because i would like to compile two sites from the same codebase. 

For this I need to be able to put two `static.config.js` files with different names in the root of my project.

Putting two `static.config.js` files in two different directories is not an option, as it breaks up the `node_module` resolution beyond hope of repair (Believe me, I tried... and all I learnt was that `react-static` does waaay too much magic with `node_modules` to my taste)

**Comment by EmilTholin** [comment]
Hi @crubier!

Maybe you could use an environment variable of your own for the time being?

**package.json**
```json
{
  "scripts": {
    "build:first": "cross-env MY_ENV_VAR=first react-static build",
    "build:second": "cross-env MY_ENV_VAR=second react-static build"
  }
}
```

**static.config.js**
```javascript
if (process.env.MY_ENV_VAR === 'first') {
  // ...
} else {
  // ...
}

export default {
  // ...
};
```

**Comment by crubier** [comment]
Ok, this seems like a good idea, but I found a bug while doing this: https://github.com/nozzle/react-static/issues/224

**Comment by tannerlinsley** [comment]
Still need to get to this.
