### ISSUE TITLE
How to build non-minified HTML?

### ISSUE THREAD

**Issue by thecosss** [nozzle/react-static#238]
Is there a way to build clean html files not for production but for further development purposes?

**Comment by EmilTholin** [comment]
Hi @thecosss! That's an interesting use case. What is it that you don't want minified? Wouldn't it work to use something like e.g. [Prettier](https://github.com/prettier/prettier) to make the resulting HTML files readable?

**Comment by thecosss** [comment]
Thanks, I think Prettier would be fine. Maybe you can tell me how to exclude data-reactroot stuff from the build?

**Comment by EmilTholin** [comment]
I'm not entirely sure, but I don't think that can be omitted. It's an attribute added by React in the elements it renders in.

**Comment by tannerlinsley** [comment]
You could easily write a regex to remove react data attributes if you’re
not interested in them.
