### ISSUE TITLE
Anyone out there using this to create sites with 1000+ pages?

### ISSUE THREAD

**Issue by benedfit** [nozzle/react-static#239]
Looking for advice on how to prevent containers from falling over during deployment

**Comment by tannerlinsley** [comment]
Are you hitting memory/CPU limits in your CI or container?

**Comment by benedfit** [comment]
I'm assuming so, it's hard to tell, as the only feedback I'm getting back from the CI or container is that the process was killed

**Comment by derekperkins** [comment]
@benedfit Does the site build work on your local machine? How long does it take? You might try testing it locally in something like VirtualBox where you can limit the CPU / RAM constraints to match your CI.

**Comment by benedfit** [comment]
It does, but I had to up the amount of RAM the process had access to. I'll try the VirtualBox approach to determine where it's falling over, but I'm going to assume it's the Javascript heap running out of memory, because that's what was happening locally at first

**Comment by tannerlinsley** [comment]
Be sure to reopen with your findings! 🤘

**Comment by tannerlinsley** [comment]
In the last few commits, we have improved route generation speeds by about 100x by optimizing some of the loops for extremely large site builds (+100k pages). A new release will be made soon with these changes, which will also include webpack 4 and hopefully babel 7

**Comment by tannerlinsley** [comment]
For reference, there is a large-site test project in the repo that can emulate these circumstances. On my 2017 Macbook Pro, it can generate 100k routes in 96 seconds.

**Comment by bkniffler** [comment]
very cool, if you publish under `@next` or something I'd gladly test it :)

**Comment by bkniffler** [comment]
Just coming here to report that the latest version 6 (not yet pushed to npm unfortunately) is immensely more performant. The initial build takes only 12 seconds for >50000 (fifty-thousand!) pages. What a great achievement @tannerlinsley, thanks.

Please publish to npm! :)

**Comment by bkniffler** [comment]
Ps. What I had to change to make everything work from v5 to v6
- Add `transform-decorators-legacy` plugin to babelrc since I use decorators
- Move the routes tree with children to a flat structure (so no more children, instead a big array with full paths)
- Uncomment my 404 route, for some reason is404 is not working any more

**Comment by tannerlinsley** [comment]
Is404 is being deprecated. Just create a route and set the path to 404

**Comment by bkniffler** [comment]
Hey, just in case you didn't see, could you maybe publish to @next? Would avoid me to publish the current state into its own package `react-static-6`

**Comment by tannerlinsley** [comment]
I did

**Comment by benedfit** [comment]
Is there anywhere to ask questions about changes needed with v6, or is it best to wait until it's out of beta and then raise issues?

**Comment by tannerlinsley** [comment]
Raise issues on GitHub and just tag them in some way for v6

**Comment by hhsnopek** [comment]
Why was the large-site test project removed from the `test` directory? 🤔 
see: bfa8adf57a031c67f7f77100b996f5c978bb502e

**Comment by tannerlinsley** [comment]
Sorry, I moved it to its own repo so I could test it in isolation on
Netlify. You’ll find it now at
https://github.com/tannerlinsley/react-static-large-site. You should be
able to clone it and `yarn link react-static` if you’re working with a
local copy of react-static (after doing `yarn link` in the react-static
repo).
