### ISSUE TITLE
Is there a way to include static .md files?

### ISSUE THREAD

**Issue by neilyoung** [nozzle/react-static#240]
like so?

const about = require("raw!../markdown/about.md");

**Comment by EmilTholin** [comment]
Hi @neilyoung! Maybe the discussion in [this issue](https://github.com/nozzle/react-static/issues/171) can be of some help. I also created [this repository](https://github.com/EmilTholin/react-static-markdown-example) with an added Webpack markdown rule, and an example reading markdown files with Node as well.

**Comment by neilyoung** [comment]
Hi @EmilTholin thanks for the super quick response. But I already have some ready code based on react-markdown, I just need to read the md file as shown....

**Comment by EmilTholin** [comment]
I'm not quite sure how it would be loaded with the `raw` Webpack loader, but maybe I'm misunderstanding you. [Doing it like this](https://github.com/EmilTholin/react-static-markdown-example/blob/master/src/containers/Blog.js#L4) will not work for your use case?

**Comment by neilyoung** [comment]
Well, I only get this on the page where the markdown should appear

/static/about.a5f06498.md

**Comment by EmilTholin** [comment]
Have you [extended your Webpack config with a Markdown rule](https://github.com/EmilTholin/react-static-markdown-example/blob/master/static.config.js#L69-L85), and you still only get the name? That's odd.

**Comment by neilyoung** [comment]
This seems to be an issue. I have studied now your package.json and your static.config. Seems I'm missing _a lot_.. Will report later.. Thanks

**Comment by neilyoung** [comment]
Well... maybe now I'm needing an image loader as well...

The file is there

Module not found: Can't resolve './img/1.png' in '/Users/me/mynewstaticproject/src/markdown'

**Comment by neilyoung** [comment]
Wow.. it works. Thanks

**Comment by neilyoung** [comment]
Hmm. Kind of... Tables are not rendered correctly... I spent a lot of time to style these tables with react-markdown, but it seems, I don't have a way to repeat that. Do you probably  know, how to apply styling to markdown loaded this way?

**Comment by EmilTholin** [comment]
Sorry, I don't have enough experience with `react-markdown` to know what it could be. `marked` uses GFM, so your markdown tables have to comply [with this](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables).

**Comment by neilyoung** [comment]
Thanks for your efforts. Too bad, I really spent a lot of time into this styling and it worked well with Gatsby. I'm having also react-bootstrap aside, so maybe this confuses the table styling. In fact, in HTML there is no special class name bound to the table elements, so I see no way to overwrite it currently. With ReactMarkdown there was a way to provide own renderers, which could add some CSS classes...

But gatsby is a mess if it comes to going productive. Therefore I thought your solution might be worth a look.

I'm stuck here... again....

**Comment by neilyoung** [comment]
Hmm. Even though my tables are edited like GFM tables, they don't appear like so. I have seen, `marked` is also providing support for custom renderers, but it looks so ugly...

**Comment by neilyoung** [comment]
This is what I get

<img width="266" alt="1" src="https://user-images.githubusercontent.com/731020/34053806-7dc3ddc0-e1c8-11e7-8948-bc280f134aa5.png">

This is what I should get

<img width="446" alt="2" src="https://user-images.githubusercontent.com/731020/34053810-81699186-e1c8-11e7-99d2-756098a7f333.png">

**Comment by EmilTholin** [comment]
Interesting. The resulting markup likely differs, so you likely have to do that with a custom renderer, like you mentioned.

**Comment by neilyoung** [comment]
Yepp. Was finally able to achieve this 

<img width="460" alt="3" src="https://user-images.githubusercontent.com/731020/34055923-86ac68e0-e1d1-11e7-8167-a8b6170fbc8b.png">

with this

```
var renderer = new marked.Renderer()

renderer.table = function (header, body) {
  console.log("Table rendered")      
  return '<table class="mdTable"><thead>'+header+'</thead><tbody>' + body + '</tbody></table>';
}  
```
and an arbitrary style created here: http://divtable.com/table-styler/

**Comment by tannerlinsley** [comment]
Nice work!

**Comment by rafi** [comment]
@neilyoung how did you solve the image issue?
