### ISSUE TITLE
Stupid question, I know...

### ISSUE THREAD

**Issue by neilyoung** [nozzle/react-static#244]
but how can I use getSiteProps and getRouteProps with this pattern?

```
export default class Home extends React.Component {

}
```

**Comment by EmilTholin** [comment]
I usually do this:

```javascript
class Home extends React.Component {
  // ...
}

export default getRouteProps(Home)
```

**Comment by neilyoung** [comment]
I see, but I'm totally unfamiliar with the concept of HOC as you are applying it. I just would like to have a central configuration in the static.config.js, which I could use in all my components, like the context pattern of React. And - just because we talk about - how to provide a favicon?

Other than that I can tell you, that I left Gatsby because of the complete impossibility to produce a production version in favour of your solution. It took me the entire afternoon, but everything is running as expected. Well done, this component for static react apps.

**Comment by EmilTholin** [comment]
I guess something like a `RoutePropsProvider` would be cool, but probably a bit to magical and intrusive. I think the `getRouteProps` HOC is explicit, and it's not a big deal to use it on the containers that need it, I don't think.

You could use the [`Head`](https://github.com/nozzle/react-static#head) component in your topmost component, or change the default `Document` in `static.config.js` to add a `favicon`.

**Comment by neilyoung** [comment]
Thanks. Didn't get it, but maybe something will enlighten me soon :)

**Comment by neilyoung** [comment]
Got it. Thanks
