### ISSUE TITLE
Module not found when using index.tsx in root

### ISSUE THREAD

**Issue by corydeppen** [nozzle/react-static#261]
I've run into another issue using the TypeScript example with the latest react-static. If I change `index.js` to `index.tsx` I get the following error:

```bash
Failed to rebuild.
multi ./node_modules/react-hot-loader/patch.js ./node_modules/react-dev-utils/webpackHotDevClient.js (webpack)/hot/only-dev-server.js ./src/index.js
Module not found: Can't resolve 'path\to\src\index.js' in 'path\to\node_modules\react-static\lib\node_modules'
```

I feel like this is another example of an issue that may have been flushed out earlier if the TS example wasn't a hybrid of `js` and `tsx` files. I understand it's possible to mix them, but I'm not sure it's the most common scenario, especially for a new TypeScript project.

**Comment by corydeppen** [comment]
I added the following line to the default export in `static.config.js` and the project compiled without error.

```js
entry: path.join(__dirname, 'src', 'index.tsx'),
```

If this is an appropriate solution, and if you are okay with migrating the remaining components in the TypeScript example to `tsx`, I don't mind submitting a PR.

**Comment by tannerlinsley** [comment]
Just the paths.entry property in the config should do the trick.
