### ISSUE TITLE
Prevent ESLint errors when running tests on Windows

### ISSUE THREAD

**Issue by corydeppen** [nozzle/react-static#264]
Running `yarn test` on Windows displays a stream of `linebreak-style` ESLint errors due to CRLF linebreaks. I've seen numerous GitHub [conversations](https://github.com/airbnb/javascript/pull/1224) about this across various projects, including the note on the [docs page for the ESLint rule](http://eslint.org/docs/rules/linebreak-style#using-this-rule-with-version-control-systems). It seems like a common way to enforce LF linebreaks and prevent linting errors for devs working on Windows is to add a `.gitattributes` file with `* text=auto` and disable the `linebreak-style` rule.

> When text is set to "auto", the path is marked for automatic end-of-line conversion. If Git decides that the content is text, its line endings are converted to LF on checkin. When the file has been committed with CRLF, no conversion is done. ([source](https://git-scm.com/docs/gitattributes#gitattributes-Settostringvalueauto))

Would you accept a PR that will allow the tests to run as expected on Windows?

**Comment by tannerlinsley** [comment]
Sure thing

**Comment by tannerlinsley** [comment]
Going to track this in the PR from here on out
