### ISSUE TITLE
getRouteProps for 404 route

### ISSUE THREAD

**Issue by DanWebb** [nozzle/react-static#271]
I have a route defined like
```
{
	is404: true,
	component: 'src/pages/not-found',
	getProps: async () => ...
}
```
But the route props seem dependant on the path set. As you know, the 404 page will display if I go to any path that isn't defined in the config, so how can I get the props for the 404 route with `getRouteProps(Component)`. Currently, I get the error:

> Warning: getRouteProps could not find any props for route: /404. Either you are missing a getProps function for this route in your static.config.js or you are using the getRouteProps HOC when you don't need to.

Maybe the route props, in this case, should be based on the component being rendered as the 404 component and not the path as the 404 page doesn't have a path?

For some extra context, I'm trying to pull the 404's page content in from a CMS. I know I could pull it in on the components `componentWillMount` hook instead but I'd prefer to handle the data for this page in the same place and way as other pages. Just wondering if this is maybe possible in another way already or being considered?

**Comment by tannerlinsley** [comment]
Good point. I'll get on this

**Comment by tannerlinsley** [comment]
Going to close this for now, (it's on my todo list for the next major version) so, for now, I would suggest using `getSiteProps` to alleviate the need for this feature.
