### ISSUE TITLE
path issue on release version

### ISSUE THREAD

**Issue by darknate** [nozzle/react-static#273]
I have page with address blabla.com/account
When building dev version the route is ok, but on release version i have blahblah.com/account/
For some reason another "/" added in the end of link. 
I need to work with query params like https://blahblah.com/account?key1=value&key2=value, but it doesn't work because of this slash. This link now https://blahblah.com/account/?key1=value&key2=value and of course page can't load.
Any ideas how can i fix this?

**Comment by EmilTholin** [comment]
Hi @darknate! If I understand you correctly, there already is [an issue](https://github.com/nozzle/react-static/issues/204) open for this, which might contain some helpful information until it is solved.

**Comment by tannerlinsley** [comment]
Yes, please reference the above issue for now. Thanks!
