### ISSUE TITLE
how to allow static assset in dist folder when its dynamically loaded?

### ISSUE THREAD

**Issue by adamchenwei** [nozzle/react-static#275]
Currently every time I build, the asset is gone, and I have to add it myself manually into the dist folder... any solution?

**Comment by EmilTholin** [comment]
Hi @adamchenwei! Have you tried putting your static assets [in the `/public` folder](https://github.com/nozzle/react-static#project-setup)?

**Comment by adamchenwei** [comment]
silly me... can't believe I missed that... thanks
