### ISSUE TITLE
Query in url problem

### ISSUE THREAD

**Issue by jan0991** [nozzle/react-static#278]
On my old site I used a bit wired queries in the links, so I need to make my links looks like:

> http://site.localhost/post/amazing-slug/?i=b3-cc6d-3e-718c2

I have route setup for `/post/amazing-slug/`

Visiting full url on dev-server it loads spinner and gives following error:

`getRouteProps could not find any props for route: /post/amazing-slug/?i=b3-cc6d-3e-718c2. Either you are missing a getProps function for this route in your static.config.js or you are using the getRouteProps HOC when you don't need to.`

When visiting the same url on exported(build) pages(served via nginx) it's just white screen but I can see that network request sent back correct response for the route `/post/amazing-slug/`

Is this a bug or correct behavior? Because if route can't be handled shouldn't we serve 404 instead of blanks :) ? cheers.

**Comment by EmilTholin** [comment]
Hi @jan0991! This happens because the `getRouteProps` HOC [fetches the route data of `pathname + search`](https://github.com/nozzle/react-static/blob/master/src/index.js#L270-L271), and since you probably don't have a `/post/amazing-slug/?i=b3-cc6d-3e-718c2` route in your `static.config.js`, you get [the error](https://github.com/nozzle/react-static/blob/master/src/index.js#L287-L291).

Maybe `getRouteProps` could be extended with an option to ignore `search`, or maybe it could be discarded. I haven't looked into it enough.

**Comment by lottamus** [comment]
@EmilTholin should query strings be considered as part of the route path? Or perhaps a fallback if `pathname + search` isn't found to look for just pathname?

**Comment by EmilTholin** [comment]
I'm sure there are reasons for including `search` that I'm not aware of, but just looking for `pathname` as a fallback sounds like a good idea. Might be worth exploring.

**Comment by jan0991** [comment]
How about simply passing optional function to `getRouteProps` and then generating path like:
   ``` 
export function getRouteProps (Comp, customFunc) {
     ...
    const path = customFunc ? customFunc(this.props.location) : pathJoin(`${pathname}${search}`)
```
This not only solves search query issue but also enables dynamic route props fetching(maybe solution to this already exists, I couldn't find it).

For completeness sake, using solution above in the project looks like:

```
const customPath = (originalPath) => {  
    if (originalPath.search.length >= 1) {
        const base = originalPath.search.split("?i=")
        return base[1]
    }
  // can fetch data for any route here.
}
export default getRouteProps(Post, customPath)
```

**Comment by tannerlinsley** [comment]
The reason for including search is so RS can support static export of param'ed routes.  For instance, if you are creating 100 pages of blog posts, each of those pages should be exported. RS paths and files are creating using `path` + `search`, but not `hash`. 

Let's see where that gets us on the discussion :)

**Comment by ppd1990** [comment]
Consider a route that dynamically parses the url parameters. For example `search?text=something`.
It would be quite useful to be able to ignore the search bit for the route props and then handle `?text=something` in the component itself.

**Comment by tannerlinsley** [comment]
I agree. But this could result in pagination by query to not be statically
exported.

**Comment by tannerlinsley** [comment]
I've removed all search params from the path matching algo, so you should be free to use them to your advantage.  My recommendation for the pagination scenario is to simply not rely on search parameters for static export, and instead use the path.
