### ISSUE TITLE
[antd example] Compile error: "Can't resolve 'less-loader'

### ISSUE THREAD

**Issue by loganpowell** [nozzle/react-static#282]
@D1no Thank you so much for putting an example in using Ant.Design! I love this UI library and really want to work with it and your set up has got me most of the way there. I don't know typescript and have been banging my head and google all day trying to figure out what might be wrong with [my setup](https://github.com/loganpowell/census-academy/blob/master/static.config.js)

Here is the error that I'm getting when trying to `react-static build`:

```
ERROR in ./node_modules/antd/lib/layout/style/index.js
Module not found: Error: Can't resolve 'less-loader' in 'C:\Users\surface\AppData\Roaming\npm\node_modules\react-static\lib\node_modules'
 @ ./node_modules/antd/lib/layout/style/index.js 5:0-23
 @ ./src/App.js
 @ ./src/index.js

... repeats for every less file in the antd/lib for what I can tell

```
I've removed the `.tsx` functionality because I don't know what I'm doing there, but I probably broke something while removing those references. I'm very sorry if I did something stupid here. I'm only just out of a coding bootcamp...

`yarn start` works as intended

**Comment by EmilTholin** [comment]
Hi @loganpowell! Does `yarn build` work for you? It might be that `react-static build` uses the globally installed `react-static`, and `yarn build` uses the `react-static` in the project folder.

**Comment by loganpowell** [comment]
Hi @EmilTholin! yes, that works!
