### ISSUE TITLE
Link does not pass through query params defined on to

### ISSUE THREAD

**Issue by kildareflare** [nozzle/react-static#285]
Given this code:
```
    <Link
      to={{
        pathname: `projects/${props.project.id}`,
        query: { length: props.length, index: props.index },
      }}
    >
```
I was expecting the following string to be created
`"/projects/someId?length=5,index=1"`

But instead I just get this
`"/projects/someId"`

I'm guessing that the react-static version of Link is not deep cloning the React to parameter.
I'm aware I can inline the query params, but just wanted to check if this was by design?

**Comment by EmilTholin** [comment]
Hi @kildareflare! `[Link](https://github.com/nozzle/react-static/blob/master/src/links.js#L28-L31) is indeed a custom component`. Could you install `react-router` and use `Link` from that and see if you get the same result?

**Comment by kildareflare** [comment]
Can do - will I lose any functionality that way though?
What was the rationale behind creating a custom Link component that wraps the original?

**Comment by EmilTholin** [comment]
I think the rational behind creating a custom Link component was so that local hash routes would work as well, which the Link component from `react-router-dom` doesn't support.

If the Link from `react-router-dom` should work for you, then we would know there is a bug.

**Comment by tannerlinsley** [comment]
If this becomes a primary use case, then we can create a more full-fledged proxy for the Link component, but for now, you should be able to just import the react-router version and be fine.  Closing for now, but feel free to keep discussing and we can reopen if we gain any actionable insight :)
