### ISSUE TITLE
Split vendor and app into separate files

### ISSUE THREAD

**Issue by blinkcat** [nozzle/react-static#286]
I really like react-static! 
but, it would be beneficial for splitting the js bundle into app and vendor files. 
Because vendor dependencies rarely change, app code changes often. splitting into two files will be good for long term caching and loading speed.

**Comment by tannerlinsley** [comment]
Not a bad idea. For now I would say adding a plugin to your webpack config
should do the trick until we can figure out a more permanent option.
Thoughts?

**Comment by blinkcat** [comment]
@tannerlinsley thank you, I will take a try.

**Comment by tannerlinsley** [comment]
Closing this for now, but your PR is still encouraged and welcome!
