### ISSUE TITLE
Object.values is not a function

### ISSUE THREAD

**Issue by rileylnapier** [nozzle/react-static#287]
hi, looking at the code of /usr/src/app/node_modules/react-static/lib/static.js:178:32

seems to have

```js
  Object.values(route.initialProps).forEach(function (prop) {
```

and the engines package.json

```
"engines": {
    "node": ">=6.10.0"
}
```

but looks like Object.values is only available behind --harmony flag until node 7.  
https://stackoverflow.com/a/40421941

thoughts?  do i need a pollyfill?

**Comment by rileylnapier** [comment]
updating my node version is not going to really work... im on node 6.9.1

**Comment by rileylnapier** [comment]
or can we update the "engines" field to say you need node 7?

**Comment by rileylnapier** [comment]
i ended up using a polyfill..

**Comment by tannerlinsley** [comment]
We should really just refactor that to use object keys and map...

**Comment by rileylnapier** [comment]
Fair.  If I get time I’ll update it.

**Comment by rileylnapier** [comment]
@tannerlinsley looks like this was updated but didn't get pushed to npm maybe?  the version i have 4.8.3 /lib/static.js:178 has Object.values

but when i updated my fork to fix it:

/src/static.js:40 is Object.keys().map

~ so did we forget to transpile something before publishing to npm????

**Comment by tannerlinsley** [comment]
No I must have forgotten to push it. I'll do that ASAP

**Comment by tannerlinsley** [comment]
A new version has been published.
