### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by neilyoung** [nozzle/react-static#288]
Out of the sudden, after several succesful `npm start build` I'm getting this error since today on productive build (no problem on debug)

```
ReferenceError: document is not defined
    at Object.<anonymous> (/Users/me/myApp/node_modules/domkit/builtinStyle.js:3:18)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/me/myApp/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/me/myApp/node_modules/domkit/getVendorPropertyName.js:3:20)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/me/myApp/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myapp-java-dashboard@0.0.4 build: `react-static build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myapp-java-dashboard@0.0.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2018-01-09T16_53_26_006Z-debug.log

```

Any idea, where to search?

**Comment by tannerlinsley** [comment]
This is usually a result of your code (or a library you're importing) relying on the browser's `document` variable in a place that runs before react actually mounts.

A simple approach to fix this is to search for instance of `document` and replace them with this:
```javascript
if (typeof document !== 'undefined') {
  ... use document
}
```

If that doesn't work, make sure any libraries you are importing that use `document` immediately are proxied like so:
```javascript
let MyLibrary
if (typeof document !== 'undefined') {
  MyLibrary = require('my-library').default
}
```

**Comment by neilyoung** [comment]
@tannerlinsley Thank for the quick response. Indeed, it is one of the libraries. With step by step reverting changes from the last commit I could narrow the failing library. I'm not making use of `document` but for sure a library I'm using. Your hint was helpful, because after getting rid of the `document` problem, there was another problem with `navigator`. Could solve it by following your advice.

Thanks

**Comment by neilyoung** [comment]
BTW: If not mentioned elsewhere it should be made known, that it is a good practice to run `npm run build` more often and not only, if it comes to a production build :) I was not doing this just for one week and --- boom

**Comment by neilyoung** [comment]
@tannerlinsley May I ask you, how your proxy approach would look like, if the failing module is bound like so?

`import { PulseLoader } from 'halogenium'`

**Comment by neilyoung** [comment]
OK, found it:

```
let PulseLoader
if (typeof document !== 'undefined')
  PulseLoader = require('halogenium/lib/PulseLoader')

```

**Comment by neilyoung** [comment]
Again: Same solution, but very hard to find this time

**Comment by JoseFMP** [comment]
For me this issue is suddenly happening without any obvious reason.
I did not install any new package. I looked for any usage of `document`. Nothing.

**Comment by luqiuan** [comment]
@JoseFMP has you solved?

**Comment by luqiuan** [comment]
@JoseFMP has you solved?

**Comment by SleeplessByte** [comment]
This is not stack-overflow. Whilst I personally am okay with small support requests, external modules that have nothing to do with React Static that are coded in a way where they don't support SSR out of the box are not a great fit for SSR-based projects, such as React Static.
