### ISSUE TITLE
'react-static build' fails when bundleAnalyzer is true

### ISSUE THREAD

**Issue by blinkcat** [nozzle/react-static#290]
## Reproduce

1. `react-static create`
2. select the basic template and enter
3. set bundleAnalyzer:true in static.config.js 
4. `yarn build`

then, errors can be seen in the console
```sh
$ react-static build

=> Copying public directory...
=> [✓] Public directory copied: 1.283ms
=> Building Routes...
=> [✓] Routes Built: 748.612ms
=> Bundling App...
Webpack Bundle Analyzer is started at http://127.0.0.1:8888
Use Ctrl+C to close it
=> [✓] App Bundled: 5106.728ms
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8888
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error Command failed with exit code 1.
```
react-static version: 4.8.1
node version: 8.9.4
Webpack Bundle Analyzer seems to run twice.

**Comment by rileylnapier** [comment]
i ran into this previously.  we should only be doing bundle analyzer when stage === 'prod' ~ since stage === 'node' doesn't matter so much.  

should be

config.bundleAnalyzer && !isNode ? new BundleAnalyzerPlugin() : null

im in a fork right now, i'll update it

**Comment by blinkcat** [comment]
thank you, @rileylnapier 😀

**Comment by rileylnapier** [comment]
this got merged this morning.  should have fix published sometime soon:  https://github.com/nozzle/react-static/pull/292

**Comment by tannerlinsley** [comment]
Released!

**Comment by blinkcat** [comment]
fixed in v4.8.4

**Comment by blinkcat** [comment]
another problem! Webpack Bundle Analyzer works. 
but, index.html in dist folder isn't be created correctly!
```html
<head>
	<link href="/styles.200f581b.css" rel="stylesheet">
</head>data:application/octet-stream;base64,PCFET0NUWVBFIGh0bWw+CjxodG1sPgogIDxoZWFkPgogICAgPG1ldGEgY2hhcnNldD0iVVRGLTgiPgogICAgPHRpdGxlPjwlPSBodG1sV2VicGFja1BsdWdpbi5vcHRpb25zLnRpdGxlICU+PC90aXRsZT4KICA8L2hlYWQ+CiAgPGJvZHk+CiAgPC9ib2R5Pgo8L2h0bWw+
<script
 type="text/javascript" src="/app.200f581b.js" async></script>
```
os: ubuntu
react-static: 4.8.4
template: basic
Could you take a look at this? @rileylnapier @tannerlinsley

**Comment by rileylnapier** [comment]
yes, will take a look

**Comment by rileylnapier** [comment]
i was able to generate it just fine... what was your error?

i also do this... can't see why that would be an issue though?

![image](https://user-images.githubusercontent.com/7017640/34887340-027596d6-f77b-11e7-83ca-32c38789819e.png)

**Comment by rileylnapier** [comment]
oh but you mean its not server rendering the html pages?

**Comment by blinkcat** [comment]
I created a [demo repo](https://github.com/blinkcat/my-static-site), @rileylnapier 
it is the react-static basic template.
I only added [  bundleAnalyzer:true](https://github.com/blinkcat/my-static-site/blob/9124c3b4eab87c9254803cac986340f35dad3138/static.config.js#L38) in static.config.js.
 after 'yarn build', you can see the issue I mentioned above, [here](https://github.com/blinkcat/my-static-site/blob/master/dist/index.html).

**Comment by rileylnapier** [comment]
hey, what exactly is the issue.  not sure i understand... just linking a file isn't really letting me know whats the problem.

**Comment by blinkcat** [comment]
sorry, I was so busy these days.
I found that I could solve the problem by changing the analyzerMode of BundleAnalyzerPlugin from 'server' to 'static'.
so, I close this issue now.
