### ISSUE TITLE
Is dev server restart to register static.config.js changes expected?

### ISSUE THREAD

**Issue by mbbender** [nozzle/react-static#291]
I'll preface with I'm new to React and modern javascript development in general... coming from PHP so this could easily be related to a simple configuration or expected behavior.

I seem to have to stop and restart `react-static start` or `yarn start` in order for changes in static.config.js to register (other app files seem to hot reload in general as expected) and I occasionally get some error message for hot reload about getRouteProps not being high enough or something to be included in hot reload.... I'll add the specific error message when I get it again, but thought maybe it's related.

**Comment by EmilTholin** [comment]
Hi @mbbender! You are absolutely right. The dev server requires a restart if `static.config.js` is changed.

**Comment by mbbender** [comment]
Thanks @EmilTholin
