### ISSUE TITLE
Side effect imports fail build

### ISSUE THREAD

**Issue by mjsisley** [nozzle/react-static#293]
RxJS patches the `Observable` w/ `add` imports to keep bundle sizes low.
The below works in development, but fails at build time with `TypeError: action$.ofType(...).mergeMap is not a function`.

```js
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/mergeMap';
import 'rxjs/add/observable/of';
import 'rxjs/add/operator/delay';
import 'rxjs/add/operator/mapTo';

const pingEpic = action$ =>
  action$.ofType('PING').mergeMap(action =>
    Observable.of(null)
      .delay(action.payload || 1000) // Asynchronously wait 1000ms then continue
      .mapTo({ type: 'PONG' }),
  );
```

Surprisingly, `import rxjs` in place of the `add` imports, which patches all functionality leads to a working build.

**Comment by tannerlinsley** [comment]
Do those side effects expect the browsers global window variable to be
available? If so, the node build will fail. The way around that is doing a
conditional check to make sure the type of document is not undefined, then
requiring your side effects in that conditional block.

**Comment by mjsisley** [comment]
This is something besides the `window` issue. 

I believe this is related to having two copies of rxjs present in the Node context. I should have noted I was using a webpack config based off of the `dynamic imports w/ srr` example in this repo. This was related to `externals` in the config. 
 
Adding https://github.com/jayphelps/webpack-rxjs-externals to the externals of the webpack config in the node context results in a passing build.

**Comment by tannerlinsley** [comment]
💯
