### ISSUE TITLE
Raw Html Flash between route change

### ISSUE THREAD

**Issue by adamchenwei** [nozzle/react-static#298]
React-static version 4.8.3
React version 16.0.0

The result is running the actual final build with `npm run build`. not `npm start` as it will load the dev environment loader.

Between transition of route, I experiencing this flash of raw html...
What is the cause? Is there a solution? Any hint?

NOTE: I used the styled-component example as the base code, because all my styling is load through styled-components.

in the example, I switch from `/about` route to `/contact` route. and below shows what happened.
![abc](https://user-images.githubusercontent.com/4201698/34918485-f7e77d2c-f920-11e7-810a-b26e1fdd01e3.gif)

`static-config.js`

```
import axios from 'axios'
import {content} from 'content';
export default {
  getSiteProps: () => ({
    siteTitle: content.site.siteName.casual,
  }),
  siteRoot: 'http://site.com',
  getRoutes: async () => {
    return [
      {
        path: '/',
        component: 'src/containers/BlogListingPage',
      },
      {
        path: '/about',
        component: 'src/containers/AboutPage',
      },
      {
        path: '/contact',
        component: 'src/containers/ContactPage',
      },
      {
        path: '/blogs',
        component: 'src/containers/BlogPage',
        getProps: () => ({
          blogs: content.blogs,
        }),
        children: [
          {
            path: '/all',
            component: 'src/containers/BlogListingPage',
          },
          ...content.blogs.map(blog => ({
            path: `/detail/${blog.route.name}`,
            component: 'src/containers/BlogPage',
            getProps: () => ({
              blogRef: blog.route.name,
              blog: blog,
            }),
          }))
        ],
      },
    ]
  },
}

```

**Comment by tannerlinsley** [comment]
You'll need to paste your config and more information. There are a few
potential causes for that.

**Comment by adamchenwei** [comment]
@tannerlinsley here you go! and may I know how should I really start debugging it? And if possible list the causes that you already know and where to look for, so I am aware in the future, thanks a lot!

**Comment by tannerlinsley** [comment]
- Are there any error in the console?
- When you click your link, are you sure React-Static is doing an in-app route change to that page? Or is it requesting the HTML page from your server (this can be seen by looking at the network panel.  If this is the case, it could mean there was a problem mounting react on first-page view)

**Comment by adamchenwei** [comment]
@tannerlinsley 
1. nop no error, everything runs!
2. every time switch route, I saw network tabs shows its loading corresponding new app.js file as well as, oh, I forgot to mention, I also load the bootstrap.css in the intial App.js file like this

```
<Head>
        <title>My Site</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous" />
      </Head>
```

**Comment by tannerlinsley** [comment]
Yep. That smells like a full page navigation instead of using the Link
component.

**Comment by adamchenwei** [comment]
That maybe the reason.... gotcha. so if I loading page correctly with Link, I guess I shouldn't be experiencing the nacked html?

**Comment by tannerlinsley** [comment]
Yep
