### ISSUE TITLE
question: will the site still work if JavaScript is completely disabled?

### ISSUE THREAD

**Issue by omouse** [nozzle/react-static#30]
just wondering before I dive into using this, will my site still work if JavaScript is completely disabled?

**Comment by derekperkins** [comment]
@omouse Yes. The static output of `react-static` is the same as you would get out of Jekyll, Hugo or any non-interactive static site generator. If JavaScript IS enabled, then React mounts asynchronously and makes the experience better, but it isn't required for basic functionality.

**Comment by derekperkins** [comment]
Feel free to test it out on nozzle.io
