### ISSUE TITLE
Axios vs. Fetch

### ISSUE THREAD

**Issue by mjsisley** [nozzle/react-static#300]
Why is `axios` used as a dependency instead of just using `fetch`?

**Comment by tannerlinsley** [comment]
This was an early decision that wasn't made based on anything much more than habit.  If you want to use something like `fetch`, then we can talk about the pros and cons here and also how it could be implemented.  (*If* we decide that it is, it will certainly be some type of interface that would allow for any request module to be used, not just those two). 

Actionable thoughts:
- What benefits would it provide?
- Seemingly one benefit would be a smaller bundle size, but is this size negligible?

**Comment by mjsisley** [comment]
* Axios has better browser support and an ever so slightly cleaner API (one less `then` in the chain).
* `fetch` has the following browser support: https://caniuse.com/#feat=fetch. Would need polyfill for older browsers.

Apollo link allows for configuring what to use for fetch (example below): https://www.apollographql.com/docs/link/#graphql-tools. Could see this added as a config option to `static.config.js` and defaulting to `fetch` if not specified.

The main benefit would likely be bundle size. `axios` is 35.57kb non-gzipped (w/ webpack-bundle-analyzer). Possibly non-negligible among overall dependencies depending on the use case. However, if a user would prefer to use something besides `axios` for fetching (`fetch`, `request`, something else), it would be nice to be able to not ship multiple libraries to achieve the same functionality.

**Comment by tannerlinsley** [comment]
What is axios’ size gzipped? If it’s small, I don’t think we should worry
about it until the next major iteration.

**Comment by mjsisley** [comment]
About 5kb gzipped. I would say not mission critical and next major version is certainly fine if you decide it is a good idea.

**Comment by tannerlinsley** [comment]
Awesome. Thanks for looking into this. I've got it slated for next major
version. 🤘

**Comment by JamesMessinger** [comment]
> I've got it slated for next major version. 🤘

@tannerlinsley - Was this ever done?  Is there a way to replace the Axios dependency with another HTTP library or the browser's built-in fetch API?

**Comment by tannerlinsley** [comment]
Not yet actually. It could be a non breaking change in this version though.
