### ISSUE TITLE
Same component for all routes using "*"

### ISSUE THREAD

**Issue by amirhouieh** [nozzle/react-static#301]
I am trying to make one page app with multiple path, but resolve them all into one component with different scroll-height. So I expected having the getRoutes like bellow would work: 
```
       {
            path: "*",
            component: "./components/Home.tsx",
            getProps: () => someData
        }
``` 
But no! it does not render `Home` component. 

*Note I have it working by defining all the routes explicitly and use `Home` for all of them. But this cause to re-mount the component we switch between paths and I do not desire this.

**Comment by tannerlinsley** [comment]
The routes located in the static config are not react-router routes, nor do they employ any type of variable or wildcard system.  They *must be absolute paths to pages that you want to be exported*. You are of course allowed to use "Custom Routing" (see the Readme for more info), where you can *handle* some or all routes using the same component.

But to re-emphasize, the routes in your static config must be static paths.

**Comment by amirhouieh** [comment]
@tannerlinsley tnx. I had already tried that but the problem was I did not know how to resolve data on build time (something like that you can do `getRoutes` and pass the data down to the component). Anyhow I ended up doing something as you said (Custom routing) and `prefetch`:
```
//static.config.js
getRoutes: async () => {
	const data = await getData();
	return [
		{
			path: '/data',
			getProps: data
		}
	]
}
```
and then 
```
//Home.tsx
componentWillMount() {
	prefetch("/data")
		.then(({initialProps})=>{
			this.setState({
                            isFetched: true,
                            data: initalProps
                         })
		})
}
```
I am afraid am doing something stupid here and there is a better way to do it?
