### ISSUE TITLE
Googlebot - TypeError: undefined is not a function.

### ISSUE THREAD

**Issue by meandillar** [nozzle/react-static#306]
I've recently built a react-static site which is deployed with netlify. I get no errors at build/deploy time or when viewing the live site but Googlebot seems to have trouble with it.

![screen shot 2018-01-21 at 11 18 18 pm](https://user-images.githubusercontent.com/11494288/35193024-d2ad2480-ff01-11e7-8cb6-c2f08534a2dd.png)

I've tried using "Fetch as Google" in the google search console and it shows the same errors. Any ideas on what may cause this? Thanks in advance.

**Comment by meandillar** [comment]
Looks like I just needed an ES6 polyfill. Sorry for the bother.

**Comment by amirhouieh** [comment]
@meandillar facing same issue (using typescript)! could you please point me out where to add ES6 polyfill? I have tried adding it to `.babelrc` but does not help.
