### ISSUE TITLE
Discussion on plugin system

### ISSUE THREAD

**Issue by mikestopcontinues** [nozzle/react-static#309]
Generating a static site isn't only a matter of routes and flat files. Sometimes you need to generate files that don't lend themselves to `react-router` routes:

1. Resized images
2. RSS feeds
3. .htaccess redirect rules
4. Downloaded/locally-cached resources

I can imagine writing generated files directly to `/dist` during `getSiteProps()` or `getProps()`. But that feels incredibly dirty, both because it's relying on side-effects and because it's circumventing whatever resource conservation `react-static` has or will someday have.

So what's the recommended way for handling these situations?

**Comment by tannerlinsley** [comment]
This is a great question. To preface some of my ideas, React-Static's goal is to have as little configuration as possible, but still provide the necessary but optional customization in areas that warrant it.  A good example of this is the way the Document and Webpack customization is handled. It's not necessary all the time, but when it becomes such, it's easy as pie :)

With that said, let's discuss this cool stuff!

1. Resized Images.  I would love to support some type of image system in RS, but we would likely need to cater to a lot of different scenarios. The most basic IMO would be some type of webpack image loader that does resizing at build time and allows optional importing of those resized images. Maybe a component to load those different sizes? Along those same lines is something like Gatsby's image plugin that integrates with all of the different CMS and media-as-a-service platforms. More than likely a user's CMS will also store a significant portion of the site's images, so how do we support that? A base loader than can be extended to support specific services?
2. RSS feeds shouldn't be too hard. In fact, they could easily be built manually right now by hooking into one of the before/after build hooks. Surely there is a way we could integrate this process or possibly incapsulate it into some type of.... plugin 😢 (for lack of a better term, more on this later).
3. .htaccess rules could probably be handled very similarly to the XML sitemap, though the difference being that the sitemap is fully rewritten on every build, and I could see some individuals wanting to freely edit and own that same htaccess file. Thoughts?
4. Owning up to the spirit of RS again, the system allows you to do whatever you'd like, so at the entry level, one is free to download/cache/store their own files and then use those files in their build system. This might result in faster dev builds (depending on the size of your data and or the amount of times you need to restart the dev server or refresh that data). In the far future, again, I could see there being some time of caching plugin for development and builds that could increase the speed of those two operations, but it's the very free nature of RS that would make it hard to cover all of the use cases (most of which are introduced when trying to integrate with another CMS)

In the beginning, the idea of RS was all based around bring-your-own-routes with their corresponding data. How you achieved those routes and data pairings is up to you. If we continue to follow that spirit with these concepts, I think maybe 2 or 3 of them could be achieved without messing with the internals, and for the other 1 or 2, it may be the first time some type of "plugin" system is needed.  

My idea of a plugin system would very static.config.js based. I imagine you could simply import a plugin and stick it into a plugins array. A plugin would have the exposure of the entire RS public api (mostly the config), and could do many things in unison there that would be non-trivial for a user to compose piece by piece in their own config. 

So of these features, which is the most important to you? How you would you envision using such a feature?

**Comment by mikestopcontinues** [comment]
Thanks for the awesome reply! To your overarching point, I really, really like that with RS, I can just code, so I'm all in favor of keeping the API transparent.

Thinking about a plugin system, it seems RS is already half-way there with `static.config.js`. 

It would be really intuitive for a user abstracting code to a plugin to pull pieces out of the main config file into an identically-structured import. (Maybe wrapped with `plugin(opts) => {}`). That way, at each hook, RS can iterate through the plugins, ending with the user's own config. 

To the same end, passing in the config object to all hooks would be awesome. In fact, you could probably just replace the `{ dev }` argument  with `config` everywhere it appears, and set `config.dev`.

I guess the biggest issue is where would new hooks offer the most bang for their buck.

One easy win might be `async onInit(config)`. It would allow "source" plugin to attach retrieved data (or a data retrieval API) to the config object for use in `getSiteProps()` and `getRoutes()`. While I would rather import a helper into `static.config.js` myself, this hook might go a long way toward offering users pluggable solutions.

But coming back around to the use-cases I raised above, I can envision using `onBuild()` and `onStart()` to write generated files to `/dist`, especially with access to `config.routes`. But that solution won't keep the results up-to-date if a user adds/changes source content. The solution might be to have the webpackDevServer generate files on demand.

For this, I think it would be really cool to have a hook like:

```js
async getFiles(config) {
  return [{
    path: `/file.ext`,
    async getFile() { return "string, buffer, etc"; },
  }];
}
```

During dev, RS could use middleware to serve the files as routes. And during build, RS could iterate through the routes and write the files to disk. This would actually account for all four of the use-cases above, especially because a user can manually cache expensive results of `getFile()` during dev.

A super-powered version of this would be to allow the user to create parameterized routes with something like `async getMiddleware(config) => []`. During dev, RS could serve the files directly, and during build, RS could wrap the user's middleware, saving any requested route to disk.

(By the way, about the images use-case, webpack might work, though big files tend to slow the rebuild pipeline to a crawl. The solution, I think, would be to request the original, static images during dev and only `require` them for transformation during build. But that said, if I had the option of `getFiles()` or `getMiddleware()` for the other types of generated files, I would likely stick the images there as well.)

Anyway, I'm excited to hear what you think. RS is by far the best solution out there, and I'm happy to help fill it out!

**Comment by mikestopcontinues** [comment]
Hey, any thoughts on this?

**Comment by tor-ocean** [comment]
What I enjoy about react-static is templates and examples over plugins. This makes it easier to follow what is going on and fix issues or address special needs as they come up. Plugin systems are often complex and poorly documented, maybe because they target a smaller/more advanced group of users, but most users will occasionally run into problems that require debugging plugins.

If anything, it would be nice to get even more examples, and more convenient ways to use them - for example, view a diff against the basic template. That would make it easier to combine features of different templates, and probably make plugins superfluous.

**Comment by tannerlinsley** [comment]
So far my thoughts are leaning towards keeping the react-static api very lean and improving the way people use and interact with the examples. I've heard some great ideas here and elsewhere about improving the documentation for each example to show linear changes that are made to accomplish each one. We could also make a new `Guides` section in the documentation that instead shows how to implement other popular concepts step by step (ultimately pointing them to the examples for a finished product).

**Comment by tannerlinsley** [comment]
Closing this for now, but will keep track of the discussion in the `next` project in the Projects panel

**Comment by rileylnapier** [comment]
I wonder if there is a good filesystem diffing we could do to compare examples.

Say we have a core example folder, then we compare that to examples and have some mardown or HTML diff viewable so people see what files are different?

Sometimes looking through examples can be hard to know what files are different?


Or maybe this means the readme examples should have a more strict readme format explaining the example in more detail??
