### ISSUE TITLE
Integrate npm releases with GitHub releases

### ISSUE THREAD

**Issue by derekperkins** [nozzle/react-static#31]
There are some pretty significant changes happening with each of these point releases, but it isn't documented anywhere.

**Comment by derekperkins** [comment]
These are the most popular options on npm:
- https://www.npmjs.com/package/ghreleases
- https://www.npmjs.com/package/release-it
- https://www.npmjs.com/package/release

**Comment by tannerlinsley** [comment]
For now there is a simple `postpublish: 'git push --tags'` script in the package that should take care of the sync.

**Comment by derekperkins** [comment]
What about release notes?

**Comment by tannerlinsley** [comment]
Okay... ;)

**Comment by tannerlinsley** [comment]
Release Notes are synced with the changelog on releases now 👍.
