### ISSUE TITLE
Build ReferenceError: localStorage is not defined.

### ISSUE THREAD

**Issue by LySofDev** [nozzle/react-static#313]
Greetings,

I'm trying to build an application built with React-Static. I have a Redux store connected which uses localStorage in a middleware function to store values in browser memory. This functionality is available with the development server and I've used a mock for testing with Jest.

Upon running `yarn build`, I receive the fatal error: `ReferenceError: localStorage is not defined`.

Could you recommend a strategy to resolve this build error? I have been unable to find a solution reading up on similar issues with Next.js and others.

**Comment by tannerlinsley** [comment]
React-Static apps must be node-safe.  This means any calls to libraries or global variables that would normally reside on `window` or `document` must be put behind a feature block that required `document` to be present:
```javascript
if (typeof document !== 'undefined') {
  // use document.thing or window.thing
}
```

**Comment by LySofDev** [comment]
Thank you! My build was successful upon adding the above conditional.

**Comment by TimMcCauley** [comment]
Confirmed!
