### ISSUE TITLE
Loading behavior 

### ISSUE THREAD

**Issue by kations** [nozzle/react-static#316]
When I click on a <Link> there is a delay till all props are loaded. 

Would it be possible to load the new route and add a loading prop to it?
So we have every time fast navigation and can add a loading indicator inline the new page.

In my point of view it would be a much smoother experience 👍 would be great if its possible

**Comment by tannerlinsley** [comment]
Coming in the next few days. Stay tuned b

**Comment by kations** [comment]
Nice one @tannerlinsley ! 👍 working on my 3rd react-static site, building websites make fun again

**Comment by tannerlinsley** [comment]
🙌

**Comment by tannerlinsley** [comment]
You can try this out in the latest beta. Along with a few other awesome goodies. Let me know if you see speed increase!

**Comment by tannerlinsley** [comment]
Considering this is Master now going to close this
