### ISSUE TITLE
[Feature Request] Start project from custom template

### ISSUE THREAD

**Issue by mjsisley** [nozzle/react-static#323]
Starting a new project from various examples is great. But what about a project that needs a more complicated setup or would like to start new projects from a personalized starting point?

The create-react-app ecosystem has a number of tools that allow specifying a template when starting a project:
* https://github.com/stoyan/craft
* https://github.com/likun7981/create-custom-react-app
* https://github.com/cebroker/craft

Maybe worth adding the ability to specify your own template with the CLI.

**Comment by tannerlinsley** [comment]
This would be a great addition. Things that would need to be done to make this work:
- Add a static.config.js file
- Add the react-static scripts to package.json
- Add the `.babelrc` file
- Install/ensure react-static and other depenencies
- Optionally add the eslint config?

Each of those items could interfere with an existing project, which makes this a very difficult task. If we're talking about what could happen right now, a simple migration guide would be sufficient IMO. This seems like the time spent to get this right would probably not be worth the benefit. But a migration guide... absolutely.

**Comment by mjsisley** [comment]
I think I wasn't clear enough (though a migration guide from create-react-app would be good). Those `create-react-app` items are only for reference/ inspiration.

Currently, running `react-static create` does the following: "Prompts to select one of the templates located in this repository's examples/ directory."

I'm suggesting that the CLI should be adjusted to use conforming templates that aren't stored in this repo. Something like: `react-static create --template XXX` (where XXX is ideally a remote repo, npm package, or local path). 

Because the CLI is already set up to take a template as a starting point, I would assume that it wouldn't take too long to allow a directory from somewhere besides the `/examples` folder in this repo to be used as a template. It would be up to the user to assure that the template is a valid template for `react-static` (maybe adding checks for the existence of the necessary files for a valid react-static template is worth it... and an error message if it doesn't meet the spec).

**Comment by tannerlinsley** [comment]
That would be cool! I imagine there could be a `custom` option in the
templates that would allow you to enter a url or a git repo. If you’d like
to work on that, that would be awesome. Thoughts?

**Comment by mjsisley** [comment]
Ah yeah, adding a `custom` option to the list would work better than the flag (or maybe have both options).

Yeah, I will find time to put together a PR in the future (though probably won't have time for a few weeks). Thought I would throw out the idea now though (after pulling boilerplate from multiple examples together).

**Comment by tannerlinsley** [comment]
Great Idea. I’ll leave this open for you to resolve then.

**Comment by tannerlinsley** [comment]
This is now possible :)
