### ISSUE TITLE
Problem with scroll after hash link navigation

### ISSUE THREAD

**Issue by ek1z** [nozzle/react-static#324]
Noticed immobile scrolling following an anchor link navigation (**beta9**). After some debugging narrowed it down to [scrollTo](https://github.com/nozzle/react-static/blob/master/src/utils/ScrollTo.js) function's undefined _duration_ variable -> step() enters the infinite land of loopiness.

[master/src/index.js#L500](https://github.com/nozzle/react-static/blob/master/src/index.js#L500)

```
const { hash, scrollToHashDuration } = this.props.location
```

should maybe be something along the lines of

```
const {
  location: {
    hash
  },
  scrollToHashDuration
} = this.props
```

**Comment by tannerlinsley** [comment]
Should be fixed in the next beta :) Thanks!
