### ISSUE TITLE
How to disable automatic scroll to top?

### ISSUE THREAD

**Issue by Balvajs** [nozzle/react-static#329]
I would like to disable automatic scroll to top for some routes, or at least disable it overall.
Example: I have page and I want to navigate between two tabs on that page, so in fact I am just jumping between two subpages. But if you have to scroll a little to get to tabs, automatic scroll to top is ruining the experience.

Is there a way how to disable it?

**Comment by tannerlinsley** [comment]
Yes there is. I'll document it for you

**Comment by tannerlinsley** [comment]
There are two new options on the Router for disabling automatic scroll-to-top and scroll-to-hash: https://github.com/nozzle/react-static/blob/master/docs/api.md#components

But you'll probably want to use the new `scrollToTop={false}` prop on your links :)
https://github.com/nozzle/react-static/blob/master/docs/api.md#link
