### ISSUE TITLE
The Basic template has an error

### ISSUE THREAD

**Issue by AndrianMauricio** [nozzle/react-static#333]
**Step to reporduce:**
1. Create a new project using static template
2. Run `yarn start` and navigate to http://localhost:300
3. Click Blog link

**Actual Result:**
Nothing happens and the next error appears in the console:
```
Uncaught (in promise) TypeError: (0 , _reactStatic.getRouteData) is not a function
  at eval (Blog.js?015f:6)
  at Object.../../../../src/containers/Blog.js (2.app.2b8b9b49.js:7)
  at __webpack_require__ (app.2b8b9b49.js:708)
  at fn (app.2b8b9b49.js:113)
  at <anonymous>
```

**Expected Result**
A list of blog posts is revealed.

**Comment by pdjota** [comment]
Maybe a dup of https://github.com/nozzle/react-static/issues/326 
Did you try with version 5.0.0 ? The beta versions are unstable

getSiteData and getRouteData were deprecated in v 5
https://github.com/nozzle/react-static/blob/master/CHANGELOG.md

**Comment by AndrianMauricio** [comment]
Yes, that was the problem. Thank you very much.
