### ISSUE TITLE
Link issues

### ISSUE THREAD

**Issue by mjsisley** [nozzle/react-static#338]
`Link` is called a super-powered version of `react-router`'s `Link` in the docs, but actually modifies behavior (and this isn't completely documented).

The to object from `react-router`: https://reacttraining.com/react-router/web/api/Link/to-object
The to object here is shown as `to: {path: '/x/', query: {}}` in `react-static` docs.

I think it would be good if it was possible to have the option to use the `to` in the exact way it is used by the `react-router` component (I would prefer to not have to import different versions of Link depending on the case).

The following example from react-router's docs: https://reacttraining.com/react-router/web/example/modal-gallery has the following example.
```
      <Link
        key={id}
        to={{
          pathname: `/img/${i.id}`,
          state: { modal: true }
        }}
      >
        <p>{title}</p>
      </Link>
```
This doesn't work. Leaving "as is" causes the routes to try to navigate to an object. Changing `pathname` to `path` (as shown in the docs) leads to an href of `/` on the rendered anchor. (it does work on earlier versions of `react-static`).

Perhaps, adding a `defaultTo` prop to the `Link` component or a `useDefaultTo` to the `to` prop object is worth it.

Thoughts?

**Comment by tannerlinsley** [comment]
I've updated the code and the docs to use and show the usage of react-router exactly. `path` is still supported, but `pathname` is now preferred. All appropriate props and keys should now be forwarding directly to react-router. 

If you're still having trouble after updating to the latest version, please reopen this issue :)

**Comment by mjsisley** [comment]
Thanks! Clears up the intended behavior in the docs. Looks like after the next release, using `pathname` will work as desired.

I would point out that `path` doesn't appear like it will work because it forwards that value to the `react-router` `Link` component, and that only works with `pathname`.

Need to change the `to` object passed along to use `pathname` if you want to allow the end user to use `path` here: https://github.com/nozzle/react-static/blob/fb7e7f87940a072645838301f200ecfbc5284eab/src/index.js#L755-L757

**Comment by tannerlinsley** [comment]
You are correct. Been a crazy day! I'll get on that.

**Comment by mjsisley** [comment]
Thanks for always being so quick on the response! No rush.

**Comment by tannerlinsley** [comment]
Done!
