### ISSUE TITLE
Prefetch methods don't work when using create-react-app

### ISSUE THREAD

**Issue by aobretin** [nozzle/react-static#34]
When trying to integrate react-static with a project using create-react-app all prefetch methods like 'getroutes' or 'siteprops' have a busted endpoint (localhost:3000/undefined/getroutes)

**Comment by tannerlinsley** [comment]
You cannot use `create-react-app` to build a `react-static` site. `react-static` uses very a very different build system. Please use the `react-static` CLI :)
