### ISSUE TITLE
siteRoot > https://example.comrouteInfo.js

### ISSUE THREAD

**Issue by tazaka** [nozzle/react-static#342]
Hello,

if i set siteRoot : 
`siteRoot: 'https://example.com'`

then in index.html is generated wrong path e.g.:
`<link rel="preload" as="script" href="https://example.comrouteInfo.js"/>`

React Static - v5.0.3

**Comment by tannerlinsley** [comment]
Add a slash for now. I will be sure to normalize this route asap :)

**Comment by tazaka** [comment]
if i add slash to end > siteRoot: 'https://example.com/' < is automatically removed...
result > https://example.comrouteInfo.js

in API doc [says this ](https://github.com/nozzle/react-static/blob/master/docs/api.md#siteroot): _Any trailing slashes will be removed automatically_.

**Comment by mbbender** [comment]
This still seems to be a problem for me as well.

**Comment by mbbender** [comment]
@tazaka Were you able to resolve this issue?
