### ISSUE TITLE
Invariant Violation: Browser history needs a DOM on `npm run build`

### ISSUE THREAD

**Issue by JustFly1984** [nozzle/react-static#343]
React 16, Node 9.4.0, Mac OSX

I'm migrating from CRA to react-static.

I've setted up `react-static-routes` and importing everything from `react-static` instead of `react-router-dom` fro sure.

```
[BABEL] Note: The code generator has deoptimised the styling of "/Users/justfly/projects/taxi-static/dist/static.266c1799.js" as it exceeds the max of "500KB".
{ Invariant Violation: Browser history needs a DOM
    at invariant (/Users/justfly/projects/taxi-static/node_modules/invariant/invariant.js:42:15)
    at createBrowserHistory (/Users/justfly/projects/taxi-static/node_modules/history/createBrowserHistory.js:49:27)
    at Object.defineProperty.value (/Users/justfly/projects/taxi-static/dist/static.266c1799.js:4453:15)
    at __webpack_require__ (/Users/justfly/projects/taxi-static/dist/static.266c1799.js:30:30)
    at Object.defineProperty.value (/Users/justfly/projects/taxi-static/dist/static.266c1799.js:8741:16)
    at __webpack_require__ (/Users/justfly/projects/taxi-static/dist/static.266c1799.js:30:30)
    at Object.<anonymous> (/Users/justfly/projects/taxi-static/dist/static.266c1799.js:8496:16)
    at __webpack_require__ (/Users/justfly/projects/taxi-static/dist/static.266c1799.js:30:30)
    at Object.defineProperty.value (/Users/justfly/projects/taxi-static/dist/static.266c1799.js:73:18)
    at /Users/justfly/projects/taxi-static/dist/static.266c1799.js:11:17 name: 'Invariant Violation', framesToPop: 1 }
```

**Comment by JustFly1984** [comment]
I solved an issue.

The reason was that I had two instances of Router in my app - one for main app, and second for modal window. I could not use BrowserRoutes, cos both instances required the same history object created by createBrowserHistory, and in my case it was instantiated on server side, which leads to an error.

Solution is simple refactor to history instantiation:
```
let history

if (typeof document !== 'undefined') {
  const createBrowserHistory = require('history/createBrowserHistory').default

  history = createBrowserHistory()
}

export default history
```

and correct instantiation of Router guarded by ` typeof document !== 'undefined'`:

```
class App extends Component {
  render = () =>
    typeof document !== 'undefined'
      ? (
        <Provider
          store={store}
        >
          <Router history={history}>
            <Intl>
              <Routes />
            </Intl>
          </Router>
        </Provider>
      ) : (
        <Provider
          store={store}
        >
          <Router>
            <Intl>
              <Routes />
            </Intl>
          </Router>
        </Provider>
      )
}
```

**Comment by tannerlinsley** [comment]
Excellent!

**Comment by AradAshrafi** [comment]
actually, i have a similar problem with meteor, and I was getting frustrated because all other solutions that I've found did not solve my problem
my error in meteor was: Invariant Violation: Browser history needs a DOM  
:D
thanks a lot :)

**Comment by aronddadi** [comment]
thanks

**Comment by hutber** [comment]
Sadly this doesn't help in my isomorphic set up

**Comment by karinamachado** [comment]
@JustFly1984 Hi, I am learning react, I have the same problem. My question is: what file I can write this code?  Thanks. :)

let history
if (typeof document !== 'undefined') {
  const createBrowserHistory = require('history/createBrowserHistory').default
  history = createBrowserHistory()
}
export default history

**Comment by joaopedromattos** [comment]
> @JustFly1984 Hi, I am learning react, I have the same problem. My question is: what file I can write this code? Thanks. :)
> 
> let history
> if (typeof document !== 'undefined') {
> const createBrowserHistory = require('history/createBrowserHistory').default
> history = createBrowserHistory()
> }
> export default history

I want to know that too! I have the same issue and I don't have any clue about in what file should I write this code.

**Comment by noenif** [comment]
> actually, I have a similar problem with meteor, and I was getting frustrated because all other solutions that I've found did not solve my problem
> my error in meteor was: Invariant Violation: Browser history needs a DOM
> -- at createBrowserHistory
> :D
> thanks a lot :)

I add
![image](https://user-images.githubusercontent.com/25174520/93962070-79447600-fd8c-11ea-9bc2-555eb1cffbe1.png)
