### ISSUE TITLE
Bootstrap template

### ISSUE THREAD

**Issue by ukozdan** [nozzle/react-static#344]
Great framework, thanks for your work! Any chance of a Bootstrap 4 template, or do you consider it unnecessary, or too easy to set up?

**Comment by tannerlinsley** [comment]
It would be very easy to set up from the `basic` template. 

- Add the bootstrap css to the head of your custom `Document` component in `static.config.js`
- Use the classes in your markup :)

**Comment by Tansley** [comment]
Hey, Tanner, I am using the Netlify template where is how do you add bootstrap to your `static.config.js` is it at `getSiteData`?

**Comment by tannerlinsley** [comment]
It would be in the config.Document. You would add the script and link tags like it says in the bootstrap instructions

**Comment by Tansley** [comment]
Thanks, I will



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality&>

**Comment by Tansley** [comment]
Is it the `static.config.js` file or the `config.yml` file?



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality&>

**Comment by Tansley** [comment]
Is it the `static.config.js` file or the `config.yml` file?

**Comment by tannerlinsley** [comment]
static.config.js is the only config file for react static

**Comment by Tansley** [comment]
Just copy and paste them anywhere in the file?
