### ISSUE TITLE
Custom routes flash 404 with non-static-routing

### ISSUE THREAD

**Issue by mjsisley** [nozzle/react-static#345]
* If a siteRoot isn't specified, it is now `null` by default on build, which breaks everything.
Assume this is a bug.

* Custom routes (non static) now flash the static 404 before rendering.
Are these [docs](https://github.com/nozzle/react-static/blob/b47a551823df15e233948c0ce73e2f1e16fb2745/docs/concepts.md#non-static-routing) still intended to be valid? 
If so, I think the custom route 404 flashing is a bug. 
If not, maybe the docs should be updated to state that all routes must be defined in the static config for expected behavior. The PRPL route could be suggested (render a shell statically and the rest dynamically once data was fetched on the client).

I haven't dug through the commits, but I assume the custom route stuff is related to the new [automatic code splitting](https://github.com/nozzle/react-static/blob/b47a551823df15e233948c0ce73e2f1e16fb2745/docs/concepts.md#non-static-routing).

**Comment by tannerlinsley** [comment]
I'll dive into this asap. The site root prob should be simple to fix. The
latter, not sure yet.

**Comment by tannerlinsley** [comment]
Yes those docs for non-static routing should be the same. Is that where you're seeing the flash? Are you using the `<Switch>` component?

**Comment by mjsisley** [comment]
In dev, everything is fine.

In prod, routes that aren't defined in the static config flash the 404 (easiest to see in dev tools profile... as after cache it is very fast). A 404 for the route also logs in the console/ network requests.

The code is of the same pattern as the docs:

```
Import {Switch, Routes as StaticRoutes} from 'react-static'
import RouteNotStatic from './RouteNotStatic'

export default () => <Switch>
<RouteNotStatic />
<StaticRoutes />
</Switch>
```

**Comment by tannerlinsley** [comment]
I think in this case, the server is serving the 404 page on load simply
because the page isn't found. Once react mounts though, the dynamic route
kicks in. Have you tried disabling the 404 route?

**Comment by mjsisley** [comment]
That is definitely the case. However, this would lead to 404 responses that then render a page.

Tthis can be handled at the DNS level (w/ netlify all routes that would be 404 typically can be routed to index.html) though. So if custom and static routes are in use, a config like this at the DNS level is really required to avoid 404 responses (that are then replaced with the custom route after mounting). It is fine with me if this is required to use both static and custom routes together properly (maybe add to docs).

We still want to have a 404 to exist if the route isn't defined statically or dynamically. This would need to be done at the dynamic level, so something like:
```js
import {Switch, Routes as StaticRoutes} from 'react-static'
import RouteNotStatic from './RouteNotStatic'
import NotFoundRoute from './NotFoundRoute'

export default () => <Switch>
<RouteNotStatic />
<StaticRoutes />
<NotFoundRoute />
</Switch>
```

However, in the most recent version of `react-static`, the above use case doesn't work as `<StaticRoutes />` prevents <NotFoundRoute />` from being reached, even if there is no 404 route defined in `static.config.js`

**Comment by tannerlinsley** [comment]
I'll work up an example for this and hopefully offer some insights or
tooling changes.

**Comment by tannerlinsley** [comment]
Please see the new docs at https://github.com/nozzle/react-static/blob/master/docs/concepts.md#non-static-routing and the new example at https://github.com/nozzle/react-static/tree/master/examples/non-static-routing

**Comment by mjsisley** [comment]
Thanks! You the best.

So it comes down to configuring the server in one of two ways... and both have an unavoidable tradeoff. 

Option 1:
Serve 404.html if not static route matches... and render content anyways if a route matches dynamically. (false negative 404 response at the network request level).

Option 2:
Serve index.html if no static route matches... and render a 404 type page if no route matches dynamically (false positive 200 response at the network request level).

Default SPA behavior is Option 2. With `react-static`, we can use either. Not totally sure what the implications are for SEO.

Anyways, thanks for adding the docs and example!

**Comment by tannerlinsley** [comment]
You bet!
