### ISSUE TITLE
siteRoot declaration causes asstes url corruption on deploy to HTTPS netlify

### ISSUE THREAD

**Issue by JustFly1984** [nozzle/react-static#347]
I've set my siteRoot to `https://www.taximow.com` in `static.config.js`

After deploy, I navigated to `http://www.taximow.com` and my site loaded correctly.
I've enforced SSL, and navigated to `https://www.taximow.com` and I get network errors on each asset. - js, css, webp. - all of them.

I checked network tab and I found that links to assets has been changed

<img width="1092" alt="screenshot 2018-02-04 22 51 03" src="https://user-images.githubusercontent.com/2255993/35780096-aa06502c-0a11-11e8-8a61-b7b2cbabf3c3.png">

I commented out siteRoot  in `static.config.js`, redeployed, and things get back to normal. Except I do not have sitemap.xml

**Comment by lottamus** [comment]
Perhaps these scripts should be served via `://{siteRoot}` to inherit the protocol.

**Comment by JustFly1984** [comment]
Where should I change it?

**Comment by tannerlinsley** [comment]
Are your URL's perhaps missing the `https://` prefix?

**Comment by tannerlinsley** [comment]
Fantastic. haha. I'll take another look.

**Comment by JustFly1984** [comment]
My global and local deps are updated.

**Comment by tannerlinsley** [comment]
Using the latest version, I am not seeing any errors using any variation of `siteRoot`. With slash, without, http, and https, on and off netlify (with and without their asset optimization). If you have any other instructions or a repo I could clone and look at, then that would be great, but without it, I can't replicate this.

<img width="594" alt="screen shot 2018-02-05 at 9 29 59 am" src="https://user-images.githubusercontent.com/5580297/35816056-2904c936-0a57-11e8-90b5-92be2b95d999.png">

**Comment by jasonlafferty** [comment]
@tannerlinsley i can see the same issue as me. you have `https:/nozzle.io/routeInfo.js` which the browsers will make a request for `https://nozzle.io/nozzle.io/routeInfo.js`.

**Comment by tannerlinsley** [comment]
Holy crap! How did I not see that!!! hahah A fix will be out in a jiffy jig peeps. My bad!

**Comment by lottamus** [comment]
@tannerlinsley the issue is the use of `path.join` when the public path is the siteRoot

https://github.com/nozzle/react-static/blob/master/src/static.js#L221

**Comment by tannerlinsley** [comment]
Yeah, just seeing that now :/

**Comment by tannerlinsley** [comment]
Okay, I've published version `5.1.2` that should fix it. Looking for at least two confirmations. Go!

**Comment by tannerlinsley** [comment]
Reopen if issues persist!
