### ISSUE TITLE
App does not rendering static. No changes among src and direct dependencies.

### ISSUE THREAD

**Issue by JustFly1984** [nozzle/react-static#348]
Guys, I’m going through minimum steps: 
1) creating fresh `react-static create` with redux example
2) building dist `yarn build`
3) running `yarn serve` and opening https://localhost:3000 in chrome.
4) Inspecting a source code and seeing example’s html rendered statically, as it should be.

5) replacing `./src` with my `./src`,
6) replacing default routes for my routes,
7) carefully adding all dependencies to package.json (no devDependencies)
8 ) `yarn install` all dependencies,
9) running `yarn build`
```
Justfly:static justfly$ yarn build
yarn run v1.3.2
$ react-static build

=> Copying public directory...
=> [✓] Public directory copied: 41.360ms
=> Building Routes...
=> [✓] Routes Built: 4.590ms
=> Bundling App...
=> [✓] App Bundled: 30119.054ms
=> Exporting Routes...
[BABEL] Note: The code generator has deoptimised the styling of "/Users/justfly/projects/static/dist/static.afa030fe.js" as it exceeds the max of "500KB".
Production store

      => Warning: No 'siteRoot' defined in 'static.config.js'!
      => This is required for both absolute url's and a sitemap.xml to be exported.

=> [✓] Routes Exported: 2459.209ms
=> Site is ready for production!: 32628.293ms
✨  Done in 38.94s.
```

10) running `yarn serve`
11) opening `https://localhost:3000
12) Seeing my app loaded without static rendering!

```
<!DOCTYPE html><html lang="en-US" data-reactroot=""><head><title data-react-helmet="true"></title><link rel="preload" as="script" href="/routeInfo.js"/><link rel="preload" as="script" href="/bootstrap.e4b7ed11.js"/><link rel="preload" as="script" href="/main.ae06dcb0.js"/><link rel="stylesheet" href="/styles.0224e2b5.css"/><meta charSet="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/></head><body><div id="root"></div><script type="text/javascript">
                window.__routeData = {"path":"/","propsMap":{},"initialProps":{},"siteData":{"title":"React Static"}};</script><script defer="" type="text/javascript" src="/bootstrap.e4b7ed11.js"></script><script defer="" type="text/javascript" src="/main.ae06dcb0.js"></script></body></html>
```

As you can see - `<div id="root"></div>` is empty.

Deploy to hosting successful, but main goal is not achieved.

This is an app deployed to netlify.com [https://www.taximow.com](https://www.taximow.com)

**Comment by mjsisley** [comment]
To clarify on step 6, you replaced your routes in `static.config.js`?

**Comment by tannerlinsley** [comment]
Please share with us your config.

**Comment by JustFly1984** [comment]
That was an issue with Intl misconfiguration in my app. Tanner thank you for help with debug.

**Comment by mantastrunce** [comment]
Hi @JustFly1984, could tell us what was the misconfiguration? Because we are having the same issue.

**Comment by JustFly1984** [comment]
There was my custom code issue, Tanner helped me to find exact component with advice to comment out all the components from top one, and uncomment it one by one until app is broken again.

**Comment by JustFly1984** [comment]
I would love to know how to use react-persist with react-static

2018-07-17 3:36 GMT-05:00 Mantas Truncė <notifications@github.com>:

**Comment by mantastrunce** [comment]
We would too @JustFly1984 😅

**Comment by JoseFMP** [comment]
Could you share what was the problem? Same issue here but no clue why.

**Comment by tannerlinsley** [comment]
@JoseFMP paste a link to your repo/reproduction code so we can take a look

**Comment by praneybehl** [comment]
H all @tannerlinsley , I'm in stuck in the same boat. Was there an explanation on why is it happening?
I have drilled down to to the fact that when I start adding components from a custom UI components library, the static build stops working. The issue is that it fails silently so there is it's a bit difficult to find what and where to look for the issue?

Some level of information on how the above issues were dealt with, would be really helpful.

**Comment by sw-yx** [comment]
@praneybehl can you make a new issue with your repro please? this is likely very off topic given this thread is rather old
