### ISSUE TITLE
Bad href in script tags when `siteRoot` is specified

### ISSUE THREAD

**Issue by kaladivo** [nozzle/react-static#349]
It seems that react-static is generating bad url for scripts when `siteRoot` in `static.config.js` is specified. 

Here is the badly generated code in header: 
```
<link rel="preload" as="script" href="http://localhost:3000routeInfo.js"/>
<link rel="preload" as="script" href="http://localhost:3000bootstrap.f1c42d93.js"/>
<link rel="preload" as="script" href="http://localhost:3000templates/src/pages/Team.9f940754.js"/>
<link rel="preload" as="script" href="http://localhost:3000main.5a09e3d5.js"/>
```

and once more at the bottom of the `body` tag: 
```
<script defer="" type="text/javascript" src="http://localhost:3000bootstrap.f1c42d93.js"></script>
<script defer="" type="text/javascript" src="http://localhost:3000templates/src/pages/Team.9f940754.js"></script>
<script defer="" type="text/javascript" src="http://localhost:3000main.5a09e3d5.js"></script>
```
The slash after the site's url is missing. I've tried to put different values in `siteRoot` `http://localhost:8000` and `http://localhost:8000/` but react-static  still does not generate proper urls.

**Comment by tannerlinsley** [comment]
This was supposed to fixed in a recent release. Are you all the way up to date on both your global and local react-static dependencies?

**Comment by JustFly1984** [comment]
same as #347

**Comment by kaladivo** [comment]
After upgrading to 5.1.1 the problem is exactly the same as in #347.
