### ISSUE TITLE
Configurable dist and public folders

### ISSUE THREAD

**Issue by tauren** [nozzle/react-static#35]
I'm trying to use `react-static` to deploy a site on [GitLab Pages](https://about.gitlab.com/features/pages/). The great thing about Git**Lab** pages compared to Git**Hub** pages is GitLab provides a CI server that can run any static generator to build your site. 

However, GitLab requires the website artifacts must be in the `/public` folder. So I want to build to the `/public` folder instead of the `/dist` folder. But there is already a `/public` folder in `react-static`. It would be nice if both directories could be configurable. Of course, I can rename/move/copy folders and files, but configurable folder names seems like a reasonable feature of `react-static`.

**Comment by tannerlinsley** [comment]
I'll look into this. In the meantime, I highly suggest just renaming your directories in your build script to satisfy your hosting.

**Comment by tannerlinsley** [comment]
For the time being, these are going to remain static directories. But quite possibly, we'll consider this again in the near future.
