### ISSUE TITLE
Why is fontsLoader there but not loaded anywhere by default?

### ISSUE THREAD

**Issue by chibicode** [nozzle/react-static#350]
Hi there, I noticed there's [`src/rules/fontsLoader.js`](https://github.com/nozzle/react-static/blob/master/src/webpack/rules/fontsLoader.js), but it's not loaded by [`src/rules/index.js`](https://github.com/nozzle/react-static/blob/master/src/webpack/rules/index.js). Is there a reason for this? This might be preventing libraries like [typefaces](https://github.com/KyleAMathews/typefaces) to load for me. It's also not listed on [the docs](https://github.com/nozzle/react-static/blob/master/docs/api.md#webpack). I can customize the webpack config but I feel like it should be included by default.

I might have misunderstood and it might be the case that [`src/rules/fileLoader.js`](https://github.com/nozzle/react-static/blob/master/src/webpack/rules/fileLoader.js) takes care of loading fonts. But then in that case why is `fontsLoader.js` there?

**Comment by chibicode** [comment]
Actually font loading is now working after I re-started the server. But still wondering why `fontsLoader` is there...

**Comment by tannerlinsley** [comment]
Good question. It should be removed.
