### ISSUE TITLE
Active class for "/" route not switching off

### ISSUE THREAD

**Issue by pnloyd** [nozzle/react-static#351]
Tested with the vanilla "sass" template. Start the app and navigate to a page besides "Home",
observe that the `<a ...>Home</a>` retains the `active` class when it is no longer the active page. Expected behavior is `active` class is removed.

react-static: 5.1.1
npm: 3.5.2

**Comment by tannerlinsley** [comment]
Don't you have to add the exact prop for that functionality?

**Comment by pnloyd** [comment]
Hmm I'm not familiar with React router, I'll go educate myself and close the issue assuming I made a mistake. Thanks!
