### ISSUE TITLE
Yarn build fails on Netlify

### ISSUE THREAD

**Issue by mattiascibien** [nozzle/react-static#352]
Hello, 

i have tried to create a starter site using `react-static create` (basic template) and all was fine under my Win10 dev machine.

However when trying to deploy on netlify (which is runnin linux) I get the following error:
```
6:03:12 PM: $ react-static build
6:03:13 PM: module.js:540
6:03:13 PM:     throw err;
6:03:13 PM:     ^
6:03:13 PM: Error: Cannot find module 'set-immediate-shim'
6:03:13 PM:     at Function.Module._resolveFilename (module.js:538:15)
6:03:13 PM:     at Function.Module._load (module.js:468:25)
6:03:13 PM:     at Module.require (module.js:587:17)
6:03:13 PM:     at require (internal/module.js:11:18)
6:03:13 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/readdirp/readdirp.js:7:18)
6:03:13 PM:     at Module._compile (module.js:643:30)
6:03:13 PM:     at Module._extensions..js (module.js:654:10)
6:03:13 PM:     at Object.require.extensions.(anonymous function) [as .js] (/opt/build/repo/node_modules/babel-register/lib/node.js:152:7)
6:03:13 PM:     at Module.load (module.js:556:32)
6:03:13 PM:     at tryModuleLoad (module.js:499:12)
6:03:13 PM: error Command failed with exit code 1.
```

**Comment by tannerlinsley** [comment]
`set-immediate-shim` isn't a direct dependency of React-Static. So that's very strange...
- Does your site build and run fine in production locally? `react-static build --staging && yarn serve`
- What version of node / npm / yarn are you running? You may need to use an `.nvmrc` in netlify to specifiy the right node version (I would use 8)

<img width="770" alt="screen shot 2018-02-06 at 10 17 27 am" src="https://user-images.githubusercontent.com/5580297/35873463-feebf9dc-0b26-11e8-9235-5013c0cab4ee.png">
[YourGiftCard.pdf](https://github.com/nozzle/react-static/files/1700059/YourGiftCard.pdf)

**Comment by mattiascibien** [comment]
Hello. I nave Trier gran vuole locally in both win10 and bash for Windows and they both work. I am using nvmrc with node 8.9.4 and yarn 1.3.2 which are the very same versions I have locally.

**Comment by tannerlinsley** [comment]
If you have a repo I could test with to replicate the problem that would be great.

**Comment by mattiascibien** [comment]
I'll try as soon as I can. Thanks for the help

**Comment by mattiascibien** [comment]
Hello,

I have pushed the work I did here https://github.com/mattiascibien/react-netlify-problem-demo

**Comment by hellojere** [comment]
Facing the same issue as well. Brand new project created on top of the Prismic example, only added Styled Components so far.

**Comment by mbbender** [comment]
A project I recently had building on netlify is now throwing similar issues complaining about `async-each`. 

I also tried out a netlify starter project based on create-react-app and their own starter package is also failing to build on netlify.

Both the netlify and react-static projects build fine for me locally. Have tried various combinations of yarn/npm/node versions with no luck. I'm thinking something might be up on netlify's side.

**Comment by kations** [comment]
Had the same problem a few days ago.  A .nvmrc in the root of my project with just 8 in it solved it.

**Comment by mattiascibien** [comment]
@kations event with 8 in nvmrc i have the same issue.

**Comment by mbbender** [comment]
I took Yarn out of the mix, deleted yarn lock file and made sure my netlify build command was an `npm run` vs `yarn` command... cleared cache and ran with a `v8` first successfully and just changed to `v9.4.0` and ran fine pre/post cache clearing.  Might be worth trying to set YARN_VERSION build env var to see if that would help if you are intent on using yarn.

**Comment by mattiascibien** [comment]
@mbbender I have already YARN_VERSION 1.3.2. I'll try to commit using npm maybe

**Comment by mbbender** [comment]
I might try and older version of yarn I mean... I just took yarn out of the other project that was giving me trouble and it also now works.

**Comment by mbbender** [comment]
Just got this from netlify:

> We currently have a suboptimal setting in place which we're working to remove which is probably what's breaking your build.  You'll want to override it in this case and I think that will clear up the problem for you.
>
>The setting we set is "--ignore-optional" and to override that, set a YARN_FLAGS Build Environment Variable (most easily on your build & deploy settings page, second configuration card - also possible in netlify.toml if you use that).
>
>You should set it to "--no-ignore-optional" and I suspect your build will work better.  We'll change the default shortly, but for the meantime, that should help your build succeed.
>
>Let me know how it goes!

**Comment by mattiascibien** [comment]
With that setting everything worked fine.

**Comment by mattiascibien** [comment]
Thanks to everyone do the help
