### ISSUE TITLE
SiteRoot with sub-route prefix breaks site links

### ISSUE THREAD

**Issue by lukaszblasz** [nozzle/react-static#353]
SiteRoot is not working correctly:

I have notices that setting  siteRoot: '/test1/test2/'
end with following paths in my index.html
```
<link rel="preload" as="script" href="/test1/test2/test1/test2/bootstrap.a36313ea.js"/>
<link rel="preload" as="script" href="/test1/test2/test1/test2/templates/src/pages/Home.cb9be321.js"/

<script defer="" type="text/javascript" src="/test1/test2/bootstrap.a36313ea.js">
<script defer="" type="text/javascript" src="/test1/test2/templates/src/pages/Home.cb9be321.js">
```
also im getting 404 for routeInfo.js, looks like that it is completly not using siteRoot, call is for
```
/routeInfo.js
```

**Comment by tannerlinsley** [comment]
Looks very unrelated to react static.

**Comment by lukaszblasz** [comment]
Sorry from previous topic it was unrelated and caused by some browser extebnsions i belive. But i have found something else, related to SiteRoot. Please see updated description.

**Comment by tannerlinsley** [comment]
A site root must be a protocol prefixed URL including a domain and suffix. It cannot be a path.

**Comment by lukaszblasz** [comment]
Ok, So it is not possible with react-static to have application in some nested folder on my http server. I wanted to put my application to /root/apps/testapp but without siteRoot specified, paths are absolute and page is calling resources from /root/ directy.

It will be usefull to be able to set path we want and after compilation get proper paths for resources. Currently i will need to have another domain pointing to my /root/apps/testapp catalog as a root of my application, which doesnet solve my problem, with hosting multiple applications on different paths on the same domain.

**Comment by tannerlinsley** [comment]
So, I can work on resolving this issue. Stay tuned.

**Comment by sriksm19** [comment]
any workarounds for now?

**Comment by tannerlinsley** [comment]
Not yet. This is an interesting problem that may take some time to figure out.

**Comment by sriksm19** [comment]
Ok. Create-react-app does it though with the homepage field in package.json
Might help i suppose

On 17-Feb-2018 12:09 AM, "Tanner Linsley" <notifications@github.com> wrote:

Not yet. This is an interesting problem that may take some time to figure
out.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nozzle/react-static/issues/353#issuecomment-366322047>,
or mute the thread

**Comment by JoshClose** [comment]
Requests for `/staticData/...` don't use `siteRoot` either.

**Comment by tannerlinsley** [comment]
Now tracking this issue in #419.
