### ISSUE TITLE
getSiteProps function disappeared

### ISSUE THREAD

**Issue by adamchenwei** [nozzle/react-static#355]
getSiteProps function suddenly throw not found error 
![image](https://user-images.githubusercontent.com/4201698/35919678-dde2af52-0be3-11e8-8b49-53203d4d1e7c.png)

and its from example app for `styled-component` 's Home.js

`import { getSiteProps } from 'react-static'`

What is going on? and I do not see that on doc anywhere, seems its a breaking change somehow?

**Comment by adamchenwei** [comment]
can we have more detailed document where there is breaking change? Its really a time costing task to debug

**Comment by lottamus** [comment]
What version of react-static are you running?

`getSiteProps` was changed to `withSiteProps` in v5: https://github.com/nozzle/react-static/blob/master/CHANGELOG.md#500

**Comment by adamchenwei** [comment]
@lottamus thanks for the info! that's helpful to know that its already indicated in change log.

**Comment by neilyoung** [comment]
> What version of react-static are you running?
> 
> `getSiteProps` was changed to `withSiteProps` in v5: https://github.com/nozzle/react-static/blob/master/CHANGELOG.md#500

But the link you are quoting doesn't mention anything about this..

It really sucks, I'm having had a running environment on macOS with 5.9.12. Switching to Ubuntu, having the same 5.9.12 I cannot even create or compile the simplest basic app anymore...

**Comment by SleeplessByte** [comment]
@neilyoung React Static is at version 7 right now (and has been for the past year); it will be very hard to go back to version 5 and see what's failing.

**Comment by neilyoung** [comment]
Sure. Some projects live longer :)
Never mind.

**Comment by SleeplessByte** [comment]
Absolutely! Its just technically hard for me to help out even though I'd like to.

**Comment by neilyoung** [comment]
Don't worry. Thanks for your empathy :)
