### ISSUE TITLE
Error: Prop `href` did not match. Server

### ISSUE THREAD

**Issue by bernatfortet** [nozzle/react-static#356]
Hi! I'm getting on the built version of my react-static app.
`Prop `href` did not match. Server`

![image](https://user-images.githubusercontent.com/390010/35932610-f4223478-0bec-11e8-89c6-983078b16c39.png)

I found a SO issue: https://stackoverflow.com/questions/47336589/warning-prop-href-did-not-match-using-react-server-side-rendering

But the solution that they present doesn't apply to my case. All my links are properly formatted.

Thanks (I ❤️ react-static btw!)

**Comment by tannerlinsley** [comment]
Looks like that's because of the `siteRoot` prefixing. I'm not sure how to alleviate this just yet.

**Comment by bernatfortet** [comment]
Ok, it's not really affecting navigation but it's there. Let me know if you have some ideas on how to fix it. I can play around with it.
Thanks!

**Comment by tannerlinsley** [comment]
This may not be an error we can get away from if you use the `siteRoot` option :( In reality, it's just react warning that the html was altered in some way after the render was performed, which, if you use siteRoot, it totally is :) haha. I'm open to suggestions, but the effort that would go into engineering the `siteRoot` into the react runtime (and applying it only in production builds) would be a non-trivial task at the moment.

**Comment by bernatfortet** [comment]
All good then 👍
