### ISSUE TITLE
Can we use appendChild as oppose to append for IE11 support?

### ISSUE THREAD

**Issue by dsirnk** [nozzle/react-static#357]
https://github.com/nozzle/react-static/blob/d934eb333b1918458856b95fcba1e2c23a61d60d/src/index.js#L47

Not sure if babel-polyfill should be taking care of this or not.
However, document.body.append is throwing a TypeError on IE11

![image](https://user-images.githubusercontent.com/1551059/35947014-f7a1c748-0c33-11e8-8d4b-72a88b7e9a42.png)

Thank you,

P.S.: This generator is amazing. Kudos to all the contributors.

**Comment by tannerlinsley** [comment]
If you’d like I would accept a PR that checks to see if the append exists
or not, and if it doesn’t, uses the old appendChild syntax. You up for it?

**Comment by StephanBijzitter** [comment]
Thanks, I just noticed this issue myself. After updating to the latest version everything is working as expected!
