### ISSUE TITLE
Proposal: Allow the config file to be written in Typescript

### ISSUE THREAD

**Issue by rachel-church** [nozzle/react-static#358]
It looks like the filename `static.config.js` is hardcoded into `utils.js::getConfig`. Are there any plans to allow the config file to be written in typescript similar to how you can write Webpack configs?
https://webpack.js.org/configuration/configuration-languages/#typescript

**Comment by tannerlinsley** [comment]
It uses babel register to allow es6 in the config. Not sure how this would
work though. Any ideas?

**Comment by rachel-church** [comment]
I have almost gotten it to work by editing `utils.js` to look for either `static.config.js` or `static.config.ts`. Using a sample project I added `ts-node` as a dependency made a `static.config.ts` and a `tsconfig.json` file. It builds just fine until I try and import other `*.ts` files into `static.config.ts` (such as a webpack config function).

**Comment by tannerlinsley** [comment]
It think this would mean the config file would need to be fully precompiled using a the standard typescript cli or the webpack typescript loader.

**Comment by tannerlinsley** [comment]
At this point, I think I've discovered the best way to do this would be to write your own miniscript that runs before react-static that compiles a `static.config.ts` file into a `static.config.js` file, then runs react-static.

**Comment by PeterKottas** [comment]
As of babel 7, it now compiles typescript no problem. Might it make sense to reopen this?

**Comment by tannerlinsley** [comment]
Yeah. I'm not sure what it would take to support, but sounds viable. What would it take to make this happen?

**Comment by PeterKottas** [comment]
It's quite simple, it just needs 
```
{
    "presets": [
        "@babel/env",
        "@babel/preset-typescript"
    ],
    "plugins": [
        "@babel/proposal-class-properties",
        "@babel/proposal-object-rest-spread"
    ]
}
```

You then need to run babel with --extensions .ts,.tsx

That should do it.

**Comment by tannerlinsley** [comment]
This would essentially be running typescript for everyone by default right? Is it possible to just add that to your own `.babelrc` and call it good?

**Comment by tannerlinsley** [comment]
We do use `babelRegister` under the hood to do this though.

**Comment by PeterKottas** [comment]
> We do use `babelRegister` under the hood to do this though.

Yeah that's what I though. Just adding it for me would be simple enough. I am just afraid there are some internals that expect it to be js. For example, right now, if I just rename it to ts, it falls apart saying it can't find it. I know I could create build step that would first compile ts to js. But that's slightly barbaric. Especially when react-static config is not per say "build only". It touches actual app stuff. Props and what have you. That's the main reason why it seems like it would benefit from proper ts support. Also I must say, after checking out some of your presentations (which were very good) I totally got you framed like a typescript guy :) I was surprised rs is not entirely written in ts. It's so amazing for coding productivity, I can't even stand plain js anymore :p

**Comment by tannerlinsley** [comment]
Haha, well I'm flattered! I wish was a typescript guy, but sadly haven't invested the time to migrate my brain and projects yet. I'm well aware of the benefits, but haven't necessarily felt them first-hand yet. I suspect in the next year I will make the move, but for now, I need to be productive with the muscle memory I have... :(

I'm more than happy to merge any ideas that would make what you're attempting possible, as long as it doesn't change the experience or incur any overhead for non-TS users.

**Comment by PeterKottas** [comment]
Haha, okay that makes sense then! Just consider my voice another one of those that will hopefully one day lure you to the typescript camp. Awesome doesn't even begin to describe it. I spit out 50% more code this way and save another 50% while debugging as most of the time, I find bugs while still in editor.

Roger that, I'll be happy to contribute. Especially the d.ts definitely needs some love. I can do that first.

**Comment by tannerlinsley** [comment]
That sounds like a great plan. Can't wait to be converted ;)

**Comment by PeterKottas** [comment]
It was very easy for me, came from c++ / c# so I was praying for ts even before it existed. Made the switch right away then. Ok as per our discussion on the second issue, I'll be happy to contribute once v6 lands. Things I can do is:
- Improve d.ts
- Fix and improve ts example (the one we have right now is not rly showing the full potential imho)
- Look into supporting config as ts file

**Comment by tannerlinsley** [comment]
I agree, the current TS example is not very fleshed out. Would love to upgrade that and get the typescript plugin for v6 working.

**Comment by jlee1201** [comment]
#978 is supposed to have enabled ts for the config file, but haven't been able to get it to work.  Will try to look more deeply into this in the near future.

**Comment by sw-yx** [comment]
@jlee1201 as far as i know its not released yet, check the release dates.

**Comment by jlee1201** [comment]
actually @sw-yx -- I was able to get this working with *ts-node* to parse my *static.config.ts* sucessfully.

* `yarn add ts-node`
* `npx ts-node ./node_modules/react-static/bin/react-static {start|build|export|...}` works if you have a static.config.ts.  No need to precompile to js anymore

I just added the variations of the above to my package.json scripts and everything seems to work now thanks to #978 .

**Comment by sw-yx** [comment]
sly dog! good to know.

**Comment by jlee1201** [comment]
> actually @sw-yx -- I was able to get this working with _ts-node_ to parse my _static.config.ts_ sucessfully.
> 
> * `yarn add ts-node`
> * `npx ts-node ./node_modules/react-static/bin/react-static {start|build|export|...}` works if you have a static.config.ts.  No need to precompile to js anymore
> 
> I just added the variations of the above to my package.json scripts and everything seems to work now thanks to #978 .

This way just got broken with the 7.0.6 release :(

**Comment by tannerlinsley** [comment]
This has been temporarily disabled. Will be added back shortly.
