### ISSUE TITLE
Unable to import images from src folder

### ISSUE THREAD

**Issue by malonehedges** [nozzle/react-static#36]
Currently trying to `import` images, but without extra configuration am unable to get it to build.

```
...
=> [✓] App Bundled: 3521.463ms
=> Exporting Routes...
{ SyntaxError: /Users/malonehedges/projectPath/src/assets/myimage.png: Unexpected character '�' (1:0)
> 1 | �PNG
    | ^
...
```

"Add example configuring webpack to import images from the src folder"?

**Comment by tannerlinsley** [comment]
I’ll look into this asap

**Comment by whmountains** [comment]
I can't import images either, but the symptoms are slightly different:

```js
import photo from '../assets/starry-night.jpg'
```

`photo` now returns a base64 data url for the broken image icon.  lolwat?

**Comment by D1no** [comment]
Have you looked at: https://github.com/nozzle/react-static/issues/24#issuecomment-337013966 ?

**Comment by DanWebb** [comment]
I know an example config is requested but is there a reason this isn't built in? Gatsby enables it by default actually [suggests using](https://www.gatsbyjs.org/docs/adding-images-fonts-files/) this method to import assets for seemingly valid reasons.

Sorry if this is already being worked on it was just something I expected to be able to do, maybe I'm spoilt.

**Comment by tannerlinsley** [comment]
This should be fixed in the latest version. Please upgrade both global and local packages to version 2.0.0

Make sure you import and use the `withFileLoader` from react-static's plugins in your `static.config.js` file:
```javascript
import axios from 'axios'
//
import withCss from 'react-static/lib/plugins/withCssLoader'
import withFiles from 'react-static/lib/plugins/withFileLoader'

export default {
  getSiteProps: () => ({
    title: 'React Static',
  }),
  getRoutes: async () => {
    const { data: posts } = await axios.get('https://jsonplaceholder.typicode.com/posts')
    return [
      {
        path: '/',
        component: 'src/containers/Home',
      },
      {
        path: '/about',
        component: 'src/containers/About',
      },
      {
        path: '/blog',
        component: 'src/containers/Blog',
        getProps: () => ({
          posts,
        }),
        children: posts.map(post => ({
          path: `/post/${post.id}`,
          component: 'src/containers/Post',
          getProps: () => ({
            post,
          }),
        })),
      },
      {
        is404: true,
        component: 'src/containers/404',
      },
    ]
  },
  webpack: [withCss, withFiles],
}

```

Then you can simply import images in your js
```javascript
import logo from './logo.png'
```

**Comment by Burnett2k** [comment]
I know this is an old issue, but I'm curious what is the recommended method now of including images into your website? I've tried putting them in the /src folder and referencing them, but the new images folder doesn't seem to get published on my local build.  I looked through the docs and didn't see any info about how to handle files or assets.
