### ISSUE TITLE
[Discussion] PRPL pattern with dynamic routes

### ISSUE THREAD

**Issue by mjsisley** [nozzle/react-static#360]
Let's say we have a group of dynamic child routes following `/invoices/:id` that all have a shared app shell. Ideally, a pre-rendered shell would be displayed if a route matching this pattern was the entry point (and the :id specific stuff could loaded and displayed dynamically).

Something like configuring redirects on a static host to resolve`/invoices/*` to a pre-rendered `invoiceShell.html` should work (and then the rest of the routing could be handled dynamically).

To use this method with `react-static`, we could define the shell in a component, and then render a dummy route in the `static.config.js` that would never be intended for ultimate use on its own.

I imagine this is difficult (impossible) to handle with `react-static`. Does the above approach sound like the best option to you?

**Comment by tannerlinsley** [comment]
If you're shell is heavy enough or contains vital SEO then yes that would
work. But you would merely be increasing perceived performance no? This is
also something that would need to live on the server redirect level. So
it's just barely out of reach for react statics domain

**Comment by tannerlinsley** [comment]
You could also use a query parameter. That would ensure the correct page
loads without a redirect.

**Comment by mjsisley** [comment]
Yeah, I believe the primary benefit of the app shell is perceived performance b/c less time to first paint (and like you point out, potential SEO impact). Yeah, I assumed it was outside of `react-static`'s domain, but thought I would confirm. So query params or server redirects it is for this. Thanks!
