### ISSUE TITLE
5.1.8 spits warnings: Can only update a mounted or mounting component

### ISSUE THREAD

**Issue by ppd1990** [nozzle/react-static#364]
react-static 5.1.8 spits out tons of warnings on the console (and thus breaks things in my project):

```
Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

Please check the code for the InitialLoading component.
```

This happens for tons of components and does not happen with 5.1.7. Can be reproduced with the basic template.

**Comment by tannerlinsley** [comment]
I'll look into it

**Comment by tannerlinsley** [comment]
I'll look into it

**Comment by ppd1990** [comment]
My index.js was not set up for the new react-hoc-loader. After copying from the examples, the warnings went away. Maybe that's something for the migration guide?

**Comment by tannerlinsley** [comment]
Yeah, we should probably document that, although, the old format of using RHL is said to still work on their documentation. So it shouldn't have been necessary. 🤔
