### ISSUE TITLE
how do i configure for purifycss-webpack?

### ISSUE THREAD

**Issue by sriksm19** [nozzle/react-static#369]

**Comment by tannerlinsley** [comment]
Please provide us with more information on your issue, otherwise it will be closed.

**Comment by sriksm19** [comment]
i would like to integrate purifycss-webpack plugin, which removes unused css. but it seems like they need to access the html file for it. since theres no html in public folder etc, how do i go about it? any alternative?

**Comment by tannerlinsley** [comment]
I'm not sure how this would fit into react-static right now considering the ending html file templates for each page are built using the `Document` class in your config. So webpack-html-plugin isn't used at all. If your plugin relies on it, then it won't work for now. We can look into other solutions down the road through.

**Comment by sriksm19** [comment]
Ohk.
