### ISSUE TITLE
Missing dependencies 

### ISSUE THREAD

**Issue by josephdburdick** [nozzle/react-static#37]
Hello, great work on this. I'm tinkering with this setup and found some a warning highlight in Atom at the initial React import of the App.js and index.js (I didn't check all container files),  notifying that it couldn't find the following dependencies:

- eslint-plugin-jsx-a11y 
- eslint-plugin-react 
- eslint-plugin-import

Here's what I did to solve it:
```
yarn add eslint-plugin-jsx-a11y eslint-plugin-react eslint-plugin-import
```

I'm no longer experiencing these issues after installing those dependencies. Should this be included in the package.json or handled internally within react-static instead?

**Comment by tannerlinsley** [comment]
I recently updated the library. Could you verify you are running version `1.3.1` and that you are using a freshly created project?

**Comment by josephdburdick** [comment]
I'm no longer experiencing this problem after upgrading to `1.3.1` and creating a new project. Thanks!
