### ISSUE TITLE
I get a build error when animating routes

### ISSUE THREAD

**Issue by ineghi** [nozzle/react-static#370]
When I try to animate the routes using the code from the concerned exemple, i get an error during the build process:

```
a.type.toLowerCase is not a function at a.renderDOM
```
As I have updated everything to work with hot reload 4, I got the impression that getContext clashes with React 16.

Someone knows what it could be ?

**Comment by tannerlinsley** [comment]
After upgrading to the latest version, is a fresh install of the animated routes still doing this?

**Comment by tannerlinsley** [comment]
I can't replicate this. Closing for now.
