### ISSUE TITLE
Code-split routeInfo.js to help with extremely large builds

### ISSUE THREAD

**Issue by fmujakitz** [nozzle/react-static#371]
Build that contains 100k+ pages creates significantly large routeInfo.js, which contains entries for every registered route.

Is there any way to overcome this obstacle?

Btw, really cool lib. Kudos!

**Comment by fmujakitz** [comment]
After taking a closer look at the source, saw that RS is outputting all prop/route mappings to routeInfo.js

Would it be more efficient to output routeInfo per route?

**Comment by fmujakitz** [comment]
Oops :)

**Comment by tannerlinsley** [comment]
A few things: 
- The route info file contains a list of all statically-generated routes
- It also contains each routes corresponding hashes for retrieving the least amount of data as possible to displaying it.
- This data needs to be fetched before *any* subsequent navigation can happen after the first load, so we can know what data we need t load for the route.

Here's an idea. I'm not sure it will work, but it's a good brain-storming start.  We could these route hashes in a file per route, in separate directory at the root called `__routes` So the route hashes for the `blog/post-1` path would live at `/__routes/blog/post-1`. And it would contain the hashes for each data file it needs to fetch to display that path.

The benefit to this would be that there is no `routeInfo.js` file to download for each session, thus very large sites would work well.

The downside to this is there would be added latency to download the specific path's routeInfo file, then finally requesting the assets. Whereas currently, the assets can be fetched immediately when a new path is being navigated to.

**Comment by fmujakitz** [comment]
Yes. Agree with latency issue, that would be bad. But I think that route specific hashes approach could work.

Is there a way to track all links that are present on single current page? Played around a bit, and concluded that everything works fine when /blog/routeInfo.js contains only subsequent routes. It doesn't need to know every existing route?

Also, having more than 1k subsequent routes per page is usually bad, the files would never grow that big.

So, current route with all current subsequent info. Navigating to the next page is possible. No latency because assets can be downloaded immediately. And next subsequent routeInfo can be downloaded too.

Not sure it will work, but maybe it's an option.

**Comment by tannerlinsley** [comment]
That's a genius solution. I'll play around with the idea a bit more
locally.

**Comment by FullstackJack** [comment]
+1 Would love to see large site support. Curious, how much time does a 100k article site take to build and how much disk space does that use?

**Comment by tannerlinsley** [comment]
That totally depends on many factors. Including but not limited to: speed
of data download and prep, template complexity, CPU speed, storage write
speed. There is a test script that has some parameters in the
static.config.js that you can play with. It generates a large fake site
while simulating complex CPU actions.

**Comment by FullstackJack** [comment]
Awesome, I'm going to give that a spin. This project is the answer to our prayers.

**Comment by tannerlinsley** [comment]
@fmujakitz, please join the slack organization and ping me when you can. I'd like to discuss some of this in more detail asap.

**Comment by tannerlinsley** [comment]
Done!
