### ISSUE TITLE
Styled JSX Implementation

### ISSUE THREAD

**Issue by eruby94** [nozzle/react-static#375]
I know there is an example with styled components, but I would prefer to use styled jsx for the sake of scoped styles (and migration from next.js).

I have no trouble with getting styled jsx into a react static project, but cannot figure out how to set up the SSR implementation within static.config.js

My understanding would be that it should work to do the following: 
```jsx
import flush from 'styled-jsx/server'

export default {
    Document: class CustomHtml extends Component {
    render () {
      const { Html, Head, Body, children } = this.props
      const styles = flush()
      return (
        <Html>
          <Head>
            <title>Book Tower</title>
            <meta charSet="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico?v=2" />
            {styles}
          </Head>
          <Body>
            {children}
          </Body>
        </Html>
      )
    }
  },
}
```

After trying this, it does not seem to work (flush returns an empty array), and this produces a flash of unstyled content as a result

Any help would be appreciated 🙏

**Comment by tannerlinsley** [comment]
You'll likely want to implement your `flush` mechanism in the
`renderToHtml` function right after rendering the app to a string (much
like the styled-components example). You can then pass your flushed styled
through using the `renderMeta` and embed the styles in your document.

**Comment by eruby94** [comment]
So I believe I have done it as you suggest, but still have a flash of unstyled content. I'll get a basic example demonstrating this tomorrow when I'm back at work, but here's what the static config renderToHtml looks like now:

```jsx
renderToHtml: (render, Comp, meta) => {
    const html = render(<Comp />)
    const styles = flush()
    meta.styleTags = styles
    return html
  },
```

I believe there is a difference because the flush method does not take any parameters. Perhaps I should just use more specific classNames and use the styled components...I do feel like there should be a way to get this working though

**Comment by tannerlinsley** [comment]
There definitely is. Do you have your work so far in a repo I could take a
look at?

**Comment by eruby94** [comment]
Browsers tested in: Safari 10.1.2, and Chrome 63.0.3239.84
