### ISSUE TITLE
When site is updated and staticData json files change, application requests missing files

### ISSUE THREAD

**Issue by Trolleymusic** [nozzle/react-static#376]
### Is this a bug report?

Yes / kind of?

### Environment

1. React Static: v5.1.8
2. Node: v8.9.0
3. Yarn v1.3.2 / NPM v5.6.0

OS / Browser: any, I'm on Chrome & Safari on OSX 10.13.3

### Steps to Reproduce / Example / Explanation

I have a route, eg:

```
/my-routes/route-1
```

And when I build and deploy, information about that route ends up at

```
/staticData/random-hash.json
```

But when the content changes and I rebuild and redeploy

```
/staticData/different-random-hash.json
```

This becomes an issue in a browser when an existing session is running, when browsing, the browser continues to request non-existent files.

```
Error: There was an error retrieving a prop for this route! hashID: Z1OkurK
main.7bf4f1fc.js:6 Error: Request failed with status code 404
```

But this happens once for each page in the site, so in this case 120 times on navigating to a page.

Additionally, incomplete data is passed to react components which triggers errors in those components.

---

On speaking in the Slack group

> tannerlinsley [1:55 PM]
> It sounds like the route info file needs a hash suffix 

For which I will open a pull request in a moment...

**Comment by tannerlinsley** [comment]
Should be fixed now :)
