### ISSUE TITLE
Package.json proxy configuration expected to work?

### ISSUE THREAD

**Issue by mbbender** [nozzle/react-static#380]
I'm trying to use the proxy setting to redirect fetch and axios calls locally to a dev server with my API calls but it doesn't seem to be taking in my react-static project. Would a call to fetch not in the static.config.js file be expected to accept this proxy setting? Proxying is working with a basic create-react-app, just not in my react-static project.

**Comment by tannerlinsley** [comment]
Could you give me an example of what you're trying to do?

**Comment by mbbender** [comment]
In a click handler on a button
```
fetch('/.netlify/functions/hello')
      .then(response => response.json())
      .then(json => this.setState({loading: false, msg: json.msg}));
```


package.json
```
"proxy": {
    "/.netlify/functions": {
      "target": "http://localhost:9000",
      "pathRewrite": {
        "^/\\.netlify/functions": ""
      }
    }
  }
```

**Comment by mbbender** [comment]
Just trying to recreate https://github.com/netlify/create-react-app-lambda in my existing react-static project.

**Comment by tannerlinsley** [comment]
Try this in your static.config.js:

```javascript
export default {
  ...
  devServer: {
    proxy: {
    "/.netlify/functions": {
      "target": "http://localhost:9000",
      "pathRewrite": {
        "^/\\.netlify/functions": ""
      }
    }
  }
  },
}
```

**Comment by mbbender** [comment]
Success! Thank you.
