### ISSUE TITLE
Styled-System 1.x with code-splitting causes styling deformities

### ISSUE THREAD

**Issue by karland** [nozzle/react-static#387]
I have converted a simple website with three pages from using react-static 4.8.3 to using 5.1.10. It worked smoothly without issue and the site showed up as expected when viewed on `localhost:3000`. 

However, building it with `yarn build --staging` destroys the formatting of the resulting three pages. I am using nothing fancy by `styled-components` and [`grid-styled`](https://github.com/jxnblk/grid-styled). The problem is that my "css"-components are broken up wrongly and some required css is only available for the initial index.html after I called the other pages. This means the styled components are sitting in the wrong containers.

**Comment by tannerlinsley** [comment]
`grid-styled` has undocumented issue with code splitting. https://timber.io ran into the same issue just last week.  Something about `grid-styled` produces side effects that clobber any attempt for code-splitting. We should probably file an issue there.

**Comment by karland** [comment]
Thanks for the fast response. I am happy to file an issue at `grid-styled`. Are you convinced that the issue does not originate somehow with the way `react-static` is applying the code-splitting? `grid-styled` is not doing anything fancy. It provides for some grid components such as `<Box />` and `<Flex />` that it again generates from an underlying library called [`styled-system`](https://github.com/jxnblk/styled-system).

Somehow the code for styling the Boxes ended up in the wrong container or did not make it into the Home container... I wonder why?

Other than that, I think in general `react-static` should provide for a switch that prevents automatic code-splitting, so that `react-static` is still producing at least a working (but less efficient website), if an underlying library is producing issues. What do you think?

**Comment by tannerlinsley** [comment]
Not a bad idea! As for the error. All we know is that grid styled was the
culprit. It could be styled system it uses or any other dependent it has,
not necessarily styled grid itself. If you wanted to test styled system
that might narrow down the problem.

**Comment by karland** [comment]
Glad you like the idea for a switch.

Concerning the error, it indeed seems to originate from `styled-system`. `grid-styled` is dependent on 
"styled-system": "^1.1.1".

I forced yarn to use an updated version of `styled-system` and the code-splitting problem was gone. 

```
  "resolutions": {
    "styled-system": "^2.0.2"
   }
```

(Unfortunately, due to not fitting dependencies, other issues were introduced, but at least we know the cause of the issue)

cc @jxnblk

**Comment by tannerlinsley** [comment]
Good to Hear!
