### ISSUE TITLE
Not hot reloading

### ISSUE THREAD

**Issue by josephdburdick** [nozzle/react-static#39]
Hi, I was under the impression that saving a file would automatically reload a browser running the site while using `react-static start`. Is this not the case? Data is changed, I can see that when I manually reload, but the browser does not "hot reload" on it's own when I save any template/data. Please advise. Thanks!

**Comment by tannerlinsley** [comment]
Changes to data are not hot reloadable. But changes to your app are.

**Comment by tannerlinsley** [comment]
This may be possible in the future, but so far there is no reliable way to do this while still supporting a data agnostic framework.

**Comment by josephdburdick** [comment]
All changes, whether data, style, or markup are not hot reloading for me.

**Comment by tannerlinsley** [comment]
If you can point me to your repo, I could help you find out why.

**Comment by josephdburdick** [comment]
If you insist I upload what I have to Github I will but I have only started a new project. I chose the `styled-components` option, edited a few lines of CSS in `App.js`, the text inside `Home.jsx`, and nothing else. It doesn't reload.

**Comment by tannerlinsley** [comment]
Before you do that, what version of node and react-static are you using?

**Comment by josephdburdick** [comment]
I am running 
- react-static@1.3.1
- node@8.1.4

**Comment by josephdburdick** [comment]
@tannerlinsley let me know if there's anything else you'd like me to try. Thanks!
