### ISSUE TITLE
Add support for multiple websites

### ISSUE THREAD

**Issue by StephanBijzitter** [nozzle/react-static#391]
Hello!

Absolutely loving react-static for a single static website, but now I want a second website that re-uses a few components from the first website.

I'd love to export an array from `static.config.js` to build any amount websites. Currently, I'm simply using a custom bash script to replace the file by copying each config from a config directory over it, and then re-running react-static.

Maybe I just missed something in the documentation, but if I didn't, I am hereby requesting this feature! :-)

**Comment by tannerlinsley** [comment]
This is an interesting idea. Personally I think what you're doing for a workaround is exactly how I would do it too. I don't think this will land in v5, but I'll definitely keep it in the roadmap for v6.

**Comment by lilbumblebear** [comment]
@SleeplessByte is this still on the roadmap?

**Comment by SleeplessByte** [comment]
Not actively, but we can add it back. 

We internally have some changes scheduled allowing "multiple config" in `static.config` (for example, we currently must change our `staging` values all the time, this would solve that). I kinda have some premonition that those changes might actually enable the use-case as listed above!

**Comment by lilbumblebear** [comment]
Cool!  We have just converted over to react-static and LOVE it.  Thanks for all your work!

**Comment by ahtremblay** [comment]
@SleeplessByte Is this now supported?
