### ISSUE TITLE
Document browser compatibility

### ISSUE THREAD

**Issue by StephanBijzitter** [nozzle/react-static#392]
I'm having trouble finding a list for browser compatibility. I've just tested a build on IE11 and found that Promise is not defined. Now, adding the polyfill is no problem at all, but it would be nice to know this beforehand! 

If it makes a difference, I am using https://github.com/nozzle/react-static/tree/master/examples/dynamic-imports

**Comment by tannerlinsley** [comment]
Yeah we still need to add a section for this. React static should work
anywhere that react does, with a few exceptions to adding polyfills.
