### ISSUE TITLE
Empty root after building with nested prismic data

### ISSUE THREAD

**Issue by MarijnBrosens** [nozzle/react-static#396]
Steps:
1. react-static create (basic prismic)
2. yarn build
3. check in browser > works
----
4. add my own endpoint
5. bypass the transformer
6. yarn build > gives empty root

`<!DOCTYPE html><html lang="en" data-reactroot=""><head><meta charSet="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/></head><body><div id="root"></div><script type="text/javascript" src="/app.2889e28e.js"></script></body></html>`

It looks like react-static can't handle the nested prismic data

The reason i don't want to map this data is because i'm using `RichText` from `prismic-reactjs`

Is there a solution for this?

**Comment by tannerlinsley** [comment]
Can you post a link to the repo or code that you're referring to?

**Comment by MarijnBrosens** [comment]
I found the bug, i had `window` in my code!

Solved it with this snippet:
```
if (typeof window === 'undefined') {
  global.window = {
    innerWidth: 0,
  };
}
```
