### ISSUE TITLE
Load external CSS

### ISSUE THREAD

**Issue by calvinrbnspiess** [nozzle/react-static#40]
I would like to use external CSS with `react-static` to migrate from `create-react-app` completely. Actually it is very straightforward to load fonts via the [typefaces](https://github.com/KyleAMathews/typefaces) packages and then adding them via simple module imports. The problem is that those imports require appropiate css-loaders which are not included inside of react-static.

```javascript
import 'typeface-montserrat'; // typeface-montserrat/index.css
```

After a few hours of trying I feel closer to the solution and replaced nearly all webpack loaders with  a custom toolchain to support those `.css` imports, but it still does not work properly. I think it would be a good idea to support css imports out of the box, because the setup is not easy and requires extended knowledge about the project itself & the underlying toolchain.

It seems that you have to add the css-loaders before the `file-loader` (like in [create-react-app](https://github.com/facebookincubator/create-react-app/blob/991b092c893b916e6fd34e408e96a395d47b6008/packages/react-scripts/config/webpack.config.dev.js#L187)), so I had to swap all loaders with a custom configuration in a hacky way. The provided ` webpackConfigurator` gives us no option to insert the loaders in a specific order.

I already tried just using the `style-loader` and `css-loader`.

Here is my actual static.config.js: 
```javascript
import NODE_MODULES from 'react-static/dist/paths';

export default {
	[...],
	webpack: (webpackConfigurator, { dev }) => {
		webpackConfigurator._config.module.rules = [];
		webpackConfigurator.merge({
			module: {
				rules: [
					{
						test: /\.(js|jsx)$/,
						exclude: NODE_MODULES,
						use: [
							{
								loader: 'babel-loader',
							},
						],
					},
					{
						test: [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/],
						loader: 'url-loader',
						options: {
							limit: 10000,
						},
					},
					{
						test: /\.css$/,
						use: [
							'style-loader',
							{ loader: 'css-loader', options: { importLoaders: 1 } },
							{
								loader: 'postcss-loader',
								options: {
									config: {
										path: './postcss.config.js',
									},
								},
							},
						],
					},
					{
						exclude: [/\.js$/, /\.html$/, /\.json$/],
						loader: require.resolve('file-loader'),
						options: {
							name: '[name].[hash:8].[ext]',
						},
					},
				],
			},
		});
	},
};
```

I also had to configure postcss properly and install some dependencies. Still it does not work yet:
```Failed to rebuild.
./node_modules/typeface-montserrat/index.css
Module build failed: Error: Expected a backslash preceding the semicolon.
```

I will go for sleep now, maybe I will get it working tomorrow. Nevertheless, it would be great if react-static would support this out-of-the-box.

**Comment by tannerlinsley** [comment]
So the unique thing to remember about react-static is that components are being both imported via a node environment and a webpack/browser environment. I think what is happening is the webpack environment is set up correctly, but the node env is not, and is thus choking on the css import.  We could look into alleviating this slightly by creating a backend webpack build that can run in node, then use that for SSR instead. In fact, that seems like something that we should be doing anyway...

**Comment by calvinrbnspiess** [comment]
Right, that would be a meaningful explanation and definitely a good idea. Is there any way to support you in implementing it?

**Comment by tannerlinsley** [comment]
This should be fixed in the latest version. Please upgrade both global and local packages to version 2.0.0

Make sure you import and use the `withCssLoader` from react-static's plugins in your `static.config.js` file:
```javascript
import axios from 'axios'
//
import withCss from 'react-static/lib/plugins/withCssLoader'
import withFiles from 'react-static/lib/plugins/withFileLoader'

export default {
  getSiteProps: () => ({
    title: 'React Static',
  }),
  getRoutes: async () => {
    const { data: posts } = await axios.get('https://jsonplaceholder.typicode.com/posts')
    return [
      {
        path: '/',
        component: 'src/containers/Home',
      },
      {
        path: '/about',
        component: 'src/containers/About',
      },
      {
        path: '/blog',
        component: 'src/containers/Blog',
        getProps: () => ({
          posts,
        }),
        children: posts.map(post => ({
          path: `/post/${post.id}`,
          component: 'src/containers/Post',
          getProps: () => ({
            post,
          }),
        })),
      },
      {
        is404: true,
        component: 'src/containers/404',
      },
    ]
  },
  webpack: [withCss, withFiles],
}

```

Then you can simply import css in your js
```javascript
import './app.css'
```

**Comment by mhjey** [comment]
How do I get to this plugin? Where do I find it?

The plugin docs dont seem to work anymore either so not sure if this is still up to date.
https://github.com/nozzle/react-static/blob/master/docs/plugins.md
