### ISSUE TITLE
window object becomes null 

### ISSUE THREAD

**Issue by adamchenwei** [nozzle/react-static#401]
for some reason, in my component, anytime I refer to `window` object it always `undefined`. But when I typing in the inspector, windows shows available. It only happen when the component is build with react-static.

Why is that? am I not referring to the same `window`?
![image](https://user-images.githubusercontent.com/4201698/36458603-a666eda0-167d-11e8-9daa-e06f8314d819.png)

```

function getWindow() {
  let window = window || null;
  const cachedWindow = window || {};
  console.log('cachedWindow');
  console.log(cachedWindow);
  return cachedWindow;
}

export default getWindow;


```

**Comment by JustFly1984** [comment]
window object does not exist in node.
You need to guard safely with

```
if (typeof document === 'undefined') {
  
}
```

every peace of code which uses window or document to avoid server-side rendering issues.
