### ISSUE TITLE
Since updating to "react-static": "^5" I experience FOUC

### ISSUE THREAD

**Issue by karland** [nozzle/react-static#410]
Hi,

since updating to `"react-static": "^5"` I experience FOUC. I did not have this behaviour in `"react-static": "^4"`.

My styling is pretty basic and only relys on `styled-components`.

Anybody else has made this experience as well?

**Comment by karland** [comment]
Forgot to mention: FOUC only happens for the production built. The development does not show FOUC.

**Comment by tannerlinsley** [comment]
How are you doing your styles?

**Comment by tannerlinsley** [comment]
Are you extracting your styles in the renderToHtml function for your
document during build?

**Comment by karland** [comment]
I am not using renderToHtml. In fact I am not using any CSS/SASS files. My global @font-face and some basic CSS resets are entering per [`styled-components | injectGlobal`](https://www.styled-components.com/docs/api#injectglobal). For styling I a have written some styled components myself and I am using some styled components from `grid-styled` for the grid. 

In the production build it seems that the JS that does the styling is just loaded too late, i.e. after the content, so I get the FOUC.

**Comment by tannerlinsley** [comment]
Please refer to the styled-compoments example config here: https://github.com/nozzle/react-static/blob/master/examples/styled-components/static.config.js#L40. For any css-in-js solutions to work server side, they must be extracted and embedded in the document at render time (https://github.com/nozzle/react-static/blob/master/examples/styled-components/static.config.js#L55)
