### ISSUE TITLE
react-universal-component is swallowing code-split route errors

### ISSUE THREAD

**Issue by rileylnapier** [nozzle/react-static#411]
if a route component has an error, `react-universal-component` is swallowing the error.   it just ends up doing nothing and rendering nothing and gives no indication of the error.

static.js#L375

```js
 const universalOptions = {
      loading: () => null,
      error: () => null,
}
```

means that any route errors just render null.

if anyone is running into this: simple fix... inside dist/react-static-routes.js:7 change to this

```js
const universalOptions = {
  loading: () => null,
  error: props => {
    console.error(props.error);
    return <div>{props.error.message}</div>;
  }
};
```

but really we should have consistent error messaging instead of just a string.  @tannerlinsley mentioned we could pull out a error component from the router to use as error component.

i will PR this when i get a minute after work obligations are done :) . or if someone else wants to take a jab at easy fix??

**Comment by JustFly1984** [comment]
There is a new Error boundaries API `componentDidCatch` Component's method in React 16. It is a best practice to implement a HOC which wraps different parts of your app, so it doesn't crash completely.
