### ISSUE TITLE
Is it possible to build without bundling the main JS assets?

### ISSUE THREAD

**Issue by lottamus** [nozzle/react-static#418]
We are using react-static to build several sites. The main and vendor JS files won't change between sites, but the HTML and react props will.

Is there a way to bundle the JS assets on the first site build then use those files on all subsequent builds?

**Comment by tannerlinsley** [comment]
Currently that is not possible, but that is a very interesting use-case I will consider for the next major version.

**Comment by tannerlinsley** [comment]
We'll track that here: https://github.com/nozzle/react-static/projects/1#card-7782391

**Comment by rileylnapier** [comment]
Being able to reuse a bundle also means we could render single routes at a time or a subset of routes.. Which is beneficial to me :)
