### ISSUE TITLE
The "siteRoot" option should be env-aware

### ISSUE THREAD

**Issue by stephenmathieson** [nozzle/react-static#422]
Currently the `siteRoot` is a static configuration property. This means you're unable to specify different "siteRoots" for your staging/production sites. Would you be open to making the API a bit more flexiable? Perhaps `siteRoot` could be a function that accepts the "env" as a parameter?

```js
export default {
  siteRoot ({ env }) {
    if (env === 'stage') {
      return 'https://stage.example.com'
    }

    if (env === 'production') {
      return 'https://example.com'
    }

    return 'http://localhost:3000'
  },
  getRoutes () {
    // ...
  }
}

**Comment by tannerlinsley** [comment]
Technically `siteRoot` should only be used in production either way, since it rewrites all of your assets to the deployed production location. Is this because you are deploying your staging sites for review?  Currently `siteRoot` is only applied on a non-staging production build.

**Comment by stephenmathieson** [comment]
Yeah, I want to deploy the site to stage.myapp.com for QA/etc. It sounds like the `--stage` flag isn't quite what I want anyway, so I'll close this issue.

Thanks for this tool BTW. I'm loving it =]

**Comment by tannerlinsley** [comment]
Awesome! Thanks man.

**Comment by JustFly1984** [comment]
I've made a config file, which receives siteRoot form
process.env.PUBLIC_URL, and I've set this env variable on netlify and in
package.json's scripts

2018-03-02 3:22 GMT+08:00 Tanner Linsley <notifications@github.com>:

**Comment by tannerlinsley** [comment]
In the latest version, this is now `process.env.REACT_STATIC_PUBLIC_PATH`

**Comment by JustFly1984** [comment]
I just defined PUBLIC_PATH in netlify settings. Where do you define
REACT_STATIC_PUBLIC_PATH ? and where is it used across react-static?

2018-03-03 16:38 GMT+08:00 Tanner Linsley <notifications@github.com>:
