### ISSUE TITLE
siteRoot property is not taken into account for client-side routing

### ISSUE THREAD

**Issue by huberv** [nozzle/react-static#425]
Hi all,

I set up the Nodeschool Passau's website using react-static.

You can find the website's source code in /website folder in the master branch here: https://github.com/nodeschool/passau

The generated website is hosted using the gh-pages feature of github under the url https://nodeschool.io/passau and has the following routes:

```
getRoutes: async () => [
    {
      path: '/',
      component: 'src/containers/Home',
      children: [
        {
          path: 'BeginnersTrack',
          component: 'src/containers/BeginnersTrack'
        },
        {
          path: 'LearningMolecules',
          component: 'src/containers/LearningMolecules'
        }
      ]
    }
```

In order to get the absolute paths working, I defined 

`siteRoot: 'https://nodeschool.io/passau/'`

in the static.config.js. The links to images etc. are then generated correctly and the website works both in dev mode as well as when serving the generated dist/ folder locally.

However, when the site is hosted under https://nodeschool.io/passau, I just saw a flash of the original page and then was always directly redirected to the custom 404 page.

When I debugged the app, I found that react router passes on `location.pathname = "/passau"` to the getComponentForPath() function and - since there's no match using the available paths - redirects to the 404 page.

I think that react-static should recognize that the value of siteRoot ends not with a host name, but includes a path fragment. Subsequently, the path fragment should either be prepended to the route paths at build time or be stripped off react router's location path during runtime.

My current workaround for this issue is that I added 

```
    {
      path: 'passau',
      component: 'src/containers/Home',
      children: [
        {
          path: 'BeginnersTrack',
          component: 'src/containers/BeginnersTrack'
        },
        {
          path: 'LearningMolecules',
          component: 'src/containers/LearningMolecules'
        }
      ]
    }
```
to the routes. When serving locally, the first nested routes are taken and on https://nodeschool.io/passau the second nested routes are taken.

I think you should be able to debug this directly on https://nodeschool.io/passau.

I'd appreciate any advice on how to get rid of my workaround.

**Comment by tannerlinsley** [comment]
We're aware of this issue and are tracking it's progress here: https://github.com/nozzle/react-static/issues/419
