### ISSUE TITLE
basePath set to /undefined

### ISSUE THREAD

**Issue by Jonarod** [nozzle/react-static#426]
After upgrade to `5.3.3` which involves:

> Added config.basePath option for hosting and running react-static sites from a sub-route
> Added config.stagingSiteRoot, config.stagingBasePath, config.devBasePath. Used for overriding the above options in specific environments
> React Router now uses config.basePath for its basename prop
> History instances now use config.basePath for the basename option 

in stage `dev` all paths are prefixed with `/undefined` instead of `/`.
in stage `prod`, some pages fetches blank (without content, but no 404 either).

Also, it is noted that in `production`, there is a flash of the `404` page before loading the homepage `/` surely due to above `/undefined` basepath making funky redirects: in fact in the network tab, the new `routeInfo.js` is called 3 TIMES for the same page fetch...

### Reproduce

Just install the `basic` template and run it in dev, then in the browser console we can see:

```
Warning: You are attempting to use a basename on a page whose URL path does not begin with the basename. Expected path "/" to begin with "/undefined".
```
and all routes are prefixed with `undefined`

in production (hosting in gitlab.com but should be the same in github.com i guess), sub routes are not displayed except `/`, and no log appears in the console whatsoever.

**Comment by tannerlinsley** [comment]
Changes have been rolled back to a stable version. These issues are no longer in production.
