### ISSUE TITLE
How do I use favicons-webpack-plugin with react-static?

### ISSUE THREAD

**Issue by StephanBijzitter** [nozzle/react-static#431]
The plugin runs fine and generates all the required icons, but they are not being inserted in the HTML pages because react-static doesn't seem to use html-webpack-plugin.

What's the alternative in this case?

See: https://github.com/jantimon/favicons-webpack-plugin
And: https://github.com/brunocodutra/webapp-webpack-plugin

Hmm, according to my `yarn.lock` file, `html-webpack-plugin` is actually a dependency of `react-static`. But it's not present in the plugins, so... I'm a bit confused now.

```
        webpack: (previous, {stage, defaultLoaders}) => {
            const clone = {...previous};

            console.log(stage, clone); // Yields nothing related to html-webpack-plugin
```

**Comment by tannerlinsley** [comment]
Correct, react-static does not use the html-webpack-plugin (it should be removed as a dependency), since the actual document base is created using the `config.Document` component and that more advanced asset inline is necessary. I don't know of any way currently to use plugins based on it with react-static.

**Comment by tannerlinsley** [comment]
I would be more than happy to explore ways to support the html-webpack-plugin. Let's discuss here, but going to close for now.

**Comment by StephanBijzitter** [comment]
I found a way to do it with Document. Will clean up and share my solution. It's ugly, but it works.

**Comment by tannerlinsley** [comment]
Awesome. Can’t wait!

**Comment by StephanBijzitter** [comment]
Alright, this is a truncated version of my config!

Currently it doesn't use FaviconsWebpackPlugin in development mode (`yarn start`), because the manifest file won't exist at that time. Somehow, the manifest file does exist when building/staging, so that's a bit weird...

```javascript
module.exports = {
    'default': {
        // Since I have a mono-repo with multiple websites, each website has a custom base configuration.
        ...configuration,

        getSiteData: ({dev}) => {
            if (dev) {
                return configuration.getSiteData;
            } else {
                return configuration.getSiteData().then((data) => {
                    return new Promise((resolve) => {
                        const interval = setInterval(() => {
                            try {
                                const pwa = require('./dist/pwa/stats.json');
                                clearInterval(interval);
                                resolve({...data, pwa});
                            } catch (exception) {}
                        }, 100);
                    });
                });
            }
        },

        Document: ({Html, Head, Body, children, siteData}) => {
            const {pwa} = siteData;
            let metaTags = null;

            if (pwa) {
                const {html, outputFilePrefix} = pwa;
                const manifestLocation = resolve(`./dist/${outputFilePrefix}manifest.json`);
                const manifest = require(manifestLocation);

                if (!manifest.theme_color) {
                    manifest.theme_color = manifest.background_color;

                    manifest.icons.forEach((icon) => {
                        icon.src = `http://localhost:3000/${outputFilePrefix}${icon.src}`;
                    });

                    writeFileSync(manifestLocation, JSON.stringify(manifest));
                }

                html.push(`<link rel="manifest" href="http://localhost:3000/${outputFilePrefix}manifest.json"`);

                metaTags = html.map((data, index) => {
                    const tagName = /^<(\w+)\s/.exec(data)[1];
                    const props = {key: `meta-tag-${index}`};

                    let match;
                    const regexp = new RegExp(/(?:(\w+)="(.+?)")+/g);

                    while ((match = regexp.exec(data)) !== null) {
                        const [, name, value] = match;
                        props[name] = value;
                    }

                    return React.createElement(tagName, props);
                });
            }

            return (
                <Html lang="en-US">
                <Head>
                    <meta charSet="UTF-8" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <meta name="Description" content="This is a sample website"/>
                    {metaTags}
                </Head>
                <Body>{children}</Body>
                </Html>
            );
        },

        webpack: (previous, {stage, defaultLoaders}) => {
            const clone = {...previous};

            clone.plugins.splice(-1, 0, new FaviconsWebpackPlugin({
                logo: resolve('./websites/unknown.com/images/logo.png'),
                prefix: 'pwa/[hash]-',
                emitStats: true,
                statsFilename: 'pwa/stats.json',
                inject: false,
                title: 'Unknown Website',
                background: '#00b8ff',
                display: "fullscreen",
                orientation: "portrait",
                logging: true,
                icons: {
                    ios: true,
                    android: true,
                    appleIcon: true,
                    appleStartup: true,
                    coast: false,
                    favicons: true,
                    firefox: true,
                    opengraph: false,
                    twitter: true,
                    yandex: true,
                    windows: true
                }
            }));

            return clone;
        }
    }
};
```

**Comment by tannerlinsley** [comment]
That's intense! Definitely a cool hack.  I'm not sure if it's something we could easily integrate though...

**Comment by hhsnopek** [comment]
By default, we could generate favicons when `public/favicon.ico` exists. We could have a wrapper function that we expose to developers and we also include in the default `Document` component. Based on the assumption that a `favicon.ico` always exists, we can generate these images. (We can add/create a favicon from the react-static logo and use this as the default in our templates)

To customize this we could pass the full `favicons-webpack-plugin` options object in from the `static.config.js` file... I haven't gotten myself completely familiar with the build process, but is it possible to consume these options before webpack starts?

**Comment by StephanBijzitter** [comment]
If adding support for this kind of behaviour, we'd need to take one or more png files as source files. the favicons library will take the input (and if multiple, will be smart with them) and generate all other .png/.ico files.

Although these plugins are built to be used with with html-webpack-plugin, without that I had to hack quite a few things in. URLs were incorrect in the manifest and I had to convert JSON to React components.

As such, I think maybe it would be wiser to look into `favicons` (https://github.com/evilebottnawi/favicons) itself and have it generate all the needed files/data and then use that in react-static. That way we don't have to rely on a webpack plugin, but a simple node module that can be tailored to react-static much more easily.

So this module would:
- Take one or more source files as input
- Take a configuration object as input
- Generate and write a lot of image files based on input
- Generate and write a lot of manifest files based on input

This would need to be done after `config.getSiteData` resolves but before `config.Document` is run. This would only run if `config.pwa` is defined and if so, it will use the generated data to append to the default Document. To also allow custom Documents to use this, a new parameter `pwa` could be added to its call signature, still giving the developer full customisability if they want that.

This is starting to sound a lot like: https://github.com/nozzle/react-static/issues/309

**Comment by hhsnopek** [comment]
I do think it starts to sound like a plugin but at the same time, I don't think we want to wrap all `html-webpack-plugin` plugins. What we really need is an interface to `html-webpack-plugin` so that we can continue to use any of their plugins without writing and maintaining our own `react-static` plugins

**Comment by tannerlinsley** [comment]
That sounds like an awesome idea. Maybe we fork/clone it. All we need to do
is export the information it catches for use in node, instead of injecting
it into an HTML template. `node-webpack-plugin` or something. Or heck, it
could just be internal to RS for now.

**Comment by StephanBijzitter** [comment]
@brunocodutra you've got quite a bit of experience with `html-webpack-plugin`. What would you say our best option would be?

**Comment by brunocodutra** [comment]
I'm not familiar with `react-static`, so please bear with me if I'm talking nonsense here, but after a quick look at the source code I believe it wouldn't be to hard to interface with `html-webpack-plugin`. 

My suggestion would be to route all the HTML generation logic (basically [exportRoutes](https://github.com/nozzle/react-static/blob/682d35a9c930386133997b86d603b9be85495628/src/static/index.js#L61)) through a custom webpack plugin that simply taps to the `htmlWebpackPluginAfterHtmlProcessing` hook of `html-webpack-plugin`, extracts all data required to call `config.Document` and returns the rendered `html`.

By adding this plugin last in the webpack plugins array, we make sure the html it receives will have been routed through all `html-webpack-plugin`'s plugins the user might have added in her custom webpack config.

If you guys think it would make sense to go down this route I'd be glad to give a helping hand.

**Comment by hhsnopek** [comment]
I found this really neat webpack plugin that will 'virtually write' to webpack's cache. This allows other plugins to access the data, might be useful for this.

Plugin: https://github.com/rmarscher/virtual-module-webpack-plugin

**Comment by DisposaBoy** [comment]
I was surprised to see that `favicons-webpack-plugin` worked in dev mode but not when building so I went ahead and created a little helper that uses `favicons` directly https://github.com/KurokuLabs/react-static-favicons

**Comment by StephanBijzitter** [comment]
@DisposaBoy Looking at your README makes me a very happy man. I'll be sure to try it out tomorrow!
