### ISSUE TITLE
What the main diff between gatsby and react-static? whick one should I use?

### ISSUE THREAD

**Issue by kavanLi** [nozzle/react-static#435]
There is a thing that I don't understand. Is that The gatsby and react-static are developed by same team? What is the main diff with each other? Thanks in advanced.

**Comment by tannerlinsley** [comment]
I think you may enjoy reading this article: https://medium.com/@tannerlinsley/%EF%B8%8F-introducing-react-static-a-progressive-static-site-framework-for-react-3470d2a51ebc
And also this video: https://www.youtube.com/watch?v=OqbJ5swVpDQ
