### ISSUE TITLE
siteRoot removing the TLD (i.,e. '.com' etc) part if having a trailing slash

### ISSUE THREAD

**Issue by sriksm19** [nozzle/react-static#436]
after the update to 5.5 from 5.2, siteRoot now seems to remove the '.com' part as well if trailing slash is present.
for eg: if `siteRoot: 'https://example.com/`, then the paths are all based on `https://example/` instead
whereas `siteRoot: 'https://example.com` generates the routes properly.

**Comment by tannerlinsley** [comment]
Buggggg. I think I'm missing a replacement parameter here. 
https://github.com/nozzle/react-static/blob/master/src/static/getConfig.js#L50
