### ISSUE TITLE
CSS modules broke in the new version

### ISSUE THREAD

**Issue by ViliamKopecky** [nozzle/react-static#437]
Example repo: https://github.com/ViliamKopecky/react-static-css-modules

- `react-static@5.3` works well
- `react-static@5.5` shows 404 after CSS modules hot reload.

![kapture 2018-03-06 at 9 55 30](https://user-images.githubusercontent.com/316435/37022899-9be227ee-2124-11e8-858a-d513cbf3ea8b.gif)

**Comment by ViliamKopecky** [comment]
After more trying. It seems the problem is in hot reloading in general.

- I created the basic template
- `yarn start`
- Edit something in `src/containers/Home.js`
- bam - 404

Editing `src/App.js` works OK. Maybe the issue is with the router.

In `react-static@5.3` it works well.

**Comment by tannerlinsley** [comment]
How should we go about this then. Are gathering more info on the issue?

**Comment by ViliamKopecky** [comment]
I wonder if this does happen to others than me. I tried it on multiple react-static projects, and it behaves this way.

I think it might be related to other issue I am experiencing - 404 pages work differently than before.

`<Link to="this-page-does-not-exist">go to 404</Link>` - it will not make an expected redirect to 404 page. But instead some JS errors get thrown to devtools console.


![kapture 2018-03-06 at 16 56 22](https://user-images.githubusercontent.com/316435/37042816-7ba1e222-215f-11e8-9014-dcc8f570c461.gif)

![screen shot 2018-03-06 at 16 56 36](https://user-images.githubusercontent.com/316435/37042737-5ef8b24a-215f-11e8-84b8-d1e309b8dc94.png)

**Comment by tannerlinsley** [comment]
The 404 stuff should be fixed in my latest release :)

**Comment by tannerlinsley** [comment]
So do you think this css module stuff is related to anything in RS? I'm not sure how to go about debugging it.

**Comment by ViliamKopecky** [comment]
Thank you. Seems the css modules reloading is fixed as well.
