### ISSUE TITLE
Netlify documentation out of date

### ISSUE THREAD

**Issue by hhsnopek** [nozzle/react-static#438]
## Issue
<https://nozzle-react-static.netlify.com> does not display the latest version

### Expected
version 5.3.4

### Result
version 5.1.12

**Comment by hhsnopek** [comment]
My assumption is this has to do with the failing build on netlify, i.e. `npm run builddocs`

**Comment by tannerlinsley** [comment]
Correct. Still figuring out to get gitdocs to work on the ci. I'll push a
manual build and get this fixed

**Comment by tannerlinsley** [comment]
Fixed for now.
