### ISSUE TITLE
Improve Tests

### ISSUE THREAD

**Issue by hhsnopek** [nozzle/react-static#439]
This is an Epic issue containing new tests to be added:

- [x] unit test `static.config.js` options
	- [ ] matches expected output
	- [ ] executes expected functionality
- [ ] unit test Components
	- [ ] matches expected output
	- [ ] executes expected functionality
- [ ] unit test Methods
	- [ ] executes expected functionality
- [ ] unit test Node API
	- [ ] executes expected functionality

*Use this issue to track progress, this ticket will be updated in the future to reflect updated changes

**Comment by tannerlinsley** [comment]
Fantastic!

**Comment by jasonlafferty** [comment]
I can help out here. What is priority for testing? is that list in order?

**Comment by tannerlinsley** [comment]
I've reordered them to reflect priority :)

**Comment by hhsnopek** [comment]
bad bot!
