### ISSUE TITLE
[Error] runtime error on safari 8.0.8, only on development build

### ISSUE THREAD

**Issue by nmrshll** [nozzle/react-static#445]
On safari 8.0.8, MacOS 10.10.5 (yosemite):

[Error] TypeError: Map constructor does not accept arguments
	Map (undefined, line 1032)
	(fonction anonyme)
	eval code
	eval ([native code], line 0)
	../../../../react/cjs/react.development.js (app.bb2cd1dc.js, line 1856)
	__webpack_require__ (app.bb2cd1dc.js, line 679)
	fn (app.bb2cd1dc.js, line 89)
	eval code
	eval ([native code], line 0)
	../../../../react/index.js (app.bb2cd1dc.js, line 1864)
	__webpack_require__ (app.bb2cd1dc.js, line 679)
	fn (app.bb2cd1dc.js, line 89)
	eval code
	eval ([native code], line 0)
	../../../../react-hot-loader/dist/react-hot-loader.development.js (app.bb2cd1dc.js, line 1608)
	__webpack_require__ (app.bb2cd1dc.js, line 679)
	fn (app.bb2cd1dc.js, line 89)
	eval code
	eval ([native code], line 0)
	../../../../react-hot-loader/patch.js (app.bb2cd1dc.js, line 1624)
	__webpack_require__ (app.bb2cd1dc.js, line 679)
	fn (app.bb2cd1dc.js, line 89)
	(fonction anonyme) (app.bb2cd1dc.js, line 2568)
	__webpack_require__ (app.bb2cd1dc.js, line 679)
	(fonction anonyme) (app.bb2cd1dc.js, line 725)
	global code (app.bb2cd1dc.js, line 726)

Steps to reproduce the error:

- run 
  - `react-static create --name=someproject --template=styled-components`
  - `cd someproject`
  - `yarn start`

- Visit `localhost:3000` from safari 8.0.8

This error happens when using:
 - `yarn start && yarn serve`

and does not happen when using:
 - `yarn build && yarn serve`
 - `yarn stage && yarn serve`
(in those cases the page loads normally and displays everything all right)

**Comment by nmrshll** [comment]
So this issue is affecting only the development workflow. There seems to be n issue with production builds, only testing on older safari versions is made more annoying by this error.

It seems to be related to underlying libraries used for the development fast-build and tooling :
 - react.development.js
 - react-hot-loader.develoment.js

Does anyone know of any similar issues raised in other react starter kits / scaffolds ?
Or does anyone have an idea how to proceed to debug / patch this error ?

**Comment by nmrshll** [comment]
I will, thank you. I'll come update this thread when I did.

**Comment by tannerlinsley** [comment]
Awesome. Reopen if needed :)
