### ISSUE TITLE
Support hot-reloading route data

### ISSUE THREAD

**Issue by getDanArias** [nozzle/react-static#452]
I like the premise and benefits presented by `react-static`! 

One area where I am struggling is that I'd like the browser to refresh when there are changes to the Markdown files. I've combined these two examples:

https://github.com/EmilTholin/react-static-markdown-example
https://github.com/pkrawc/react-static-markdown/blob/master/static.config.js

In the first example, you can make changes to the markdown test file, but they are not reflected on the browser until you refresh it.

I plan to store the post in markdown under a folder. Based on the first example, I changed the second example to reading the posts folder inside the `/blog` route path. When I make changes to it, there is no rebuilding, which is great, but I have to manually refresh the browser to see the updated content reflected after a markdown change.

I'd appreciate any insight or guidance on how to achieve this please. It's the only thing I am missing to fully embrace this framework for a blog! 

Thank you for your time!

**Comment by rileylnapier** [comment]
I use a library npm-watch for this

**Comment by tannerlinsley** [comment]
So, as long as you are requesting the data in each routes `getData` method, the data should be up to date on the webpack server. The problem you're experiencing is that this data is cached on the client, so when you move around your site, you are getting stale data. To make this possible a couple things would need to change in React Static:
- The user would need a way of detecting changes to the asset you're using (in this case, watching a markdown file for changes)
- RS would need to define a generic api to notify RS that an "asset" has changed and also be able to notify the client which routes have changed.
- On the client, the `routeInfo` cache for those changed routes would need to be cleared.
- Any components relying on the updated `routeInfo` would need to rerequest it, and naturally, render the component with the updated data.

**Comment by tannerlinsley** [comment]
HA! this is done. :)
