### ISSUE TITLE
Can't resolve 'sass-loader' in ...

### ISSUE THREAD

**Issue by pnloyd** [nozzle/react-static#454]
After creating a fresh site with `react-static create` and choosing the sass template, I get the following build error on doing `react-static start`.

`Module not found: Can't resolve 'sass-loader' in '/usr/local/lib/node_modules/react-static/node_modules'`

I tried completely removing /usr/local/lib/node_modules/react-static and doing `npm install -g react-static` but get the same result. Running `npm list sass-loader` in the site directory gives `sass-loader@6.0.6`.

Versions:
npm - 5.7.1
react-static - 5.5.12

**Comment by pnloyd** [comment]
@tannerlinsley After following your instructions I'm getting the same error. I should note that I was previously using this template without issue, but have since upgraded both npm and react-static. Perhaps this is an issue resulting from a change in npm's behaviour?

**Comment by tannerlinsley** [comment]
Is `sass-loader` a dep in your project?

**Comment by pnloyd** [comment]
Ya, I'm just using the fresh project generated from `react-static create` to diagnose with. It has both sass-loader and node-sass listed and doing `npm list sass-loader` also confirms it's presence.

**Comment by tannerlinsley** [comment]
I'll give it a try. Hang tight.

**Comment by tannerlinsley** [comment]
Just tried with a clean install and works perfectly.... What version of node are you running?

**Comment by pnloyd** [comment]
node@v6.11.4

**Comment by tannerlinsley** [comment]
Also, not sure if this makes a difference, but try running `npm run start` instead of `react-static start`

**Comment by pnloyd** [comment]
`npm run start` worked.

**Comment by tannerlinsley** [comment]
What the.... is your global `react-static` module up to date?

**Comment by pnloyd** [comment]
Ya I deleted the entire folder and did fresh install. This actually makes sense that it may have nothing to do with me upgrading npm because I remember before I was doing `npm run start` instead of `react-static start`

**Comment by pnloyd** [comment]
Also if it makes a difference I did look at the global `react-static folder and there was no `sass-loader`, not sure if that's expected or not.

**Comment by tannerlinsley** [comment]
Interesting. I have an idea on how to make this error show up less. But it will take some tinkering.  Use `npm run` for now. 👍

**Comment by pnloyd** [comment]
Thanks for your help!

**Comment by savinger** [comment]
This error occurred for me. `npm run start` works.
