### ISSUE TITLE
Single page without Router

### ISSUE THREAD

**Issue by mkaczkowski** [nozzle/react-static#455]
Is there any way to generate static page without react-router being injected into code?

In my case I need to generate only one static page (one route only).
My biggest concern is page weight , the less the better.
I think that is should be theoretically possible to get rid of the router from the result code to save extra KBs.

Do you know if it's possible to achieve that with react-static?
Please advise.

Versions:
react-static - 5.5.12

**Comment by mkaczkowski** [comment]
Only a straight-up HTML-only site with react bundle available at runtime so I can use components from React ecosystem. I need static site to be generated to speed up rendering.

**Comment by tannerlinsley** [comment]
Technically you don't have to import anything from React Static. Just export the component you want to render and export a single route. Then the client side bundle will only include what you import.

**Comment by gryzzly** [comment]
@tannerlinsley can’t find this anywhere, sorry! How would I go about creating HTML-only site without client-side bundle at all?

**Comment by FullstackJack** [comment]
Without client-side bundle at all? How do you expect your JavaScript to run after page load?

**Comment by gryzzly** [comment]
@FullstackJack I don’t expect any javascript to run, I want to author:

```
import React from 'react';
function () {
  return <div>Hello World</div>
}
```
and get the rendered html.

I need to run this on a set of components that don’t have event handlers, so no JS interactivity.

The purpose of this is to reuse presentational components from a big stateful/interactive app in a static website.
