### ISSUE TITLE
getRouteInfo() - "Could not load routeInfo for path: undefined"

### ISSUE THREAD

**Issue by mikestopcontinues** [nozzle/react-static#459]
Two thoughts on `getRouteInfo()`:

The first is that it probably shouldn't trigger an error when the query string of a route changes, as RS doesn't handle routes with query strings. For reference, I'm changing the query string with `history.replace({search})`. 

The second thought is that this function should save the original `path` parameter for this error, rather than logging the cleaned path. Purely for easier debugging.

I'm happy to submit a PR.

**Comment by tannerlinsley** [comment]
Absolutely on the logging. The trigger you're referring to is actually in the patched history methods. In your case, the replace method: https://github.com/nozzle/react-static/blob/master/src/client/components/Router.js#L101

**Comment by mikestopcontinues** [comment]
Oh, so I was getting `undefined` because I was only updating the query string and not the path. Does this seem like the right place to break-out if path is undefined? Right now, needsPrefetch is only called from the patched history methods, but just in case it comes up down the line?

https://github.com/nozzle/react-static/blob/master/src/client/methods.js#L149
