### ISSUE TITLE
Magnification kills app.js ? Unexpected Token

### ISSUE THREAD

**Issue by D1no** [nozzle/react-static#46]
![image](https://user-images.githubusercontent.com/2397125/31587178-3edef358-b1dd-11e7-8e58-b6b419a965c1.png)

After building the website, the `app.js` does not run because it breaks at an odd character
```
__esModule",{value:!0}),t.B=t.A=t.gb=t.ga=t.Ï†=void 0;var i=Object.assign||function(e)
                                            ^
                                             \ _ here
```

Is there something in the encoding not set to `UTF-8`?

**Comment by tannerlinsley** [comment]
But that I know of. What is your os, node version etc?

**Comment by D1no** [comment]
OSX High Sierra 10.13
Living in Germany, but Machine is set to english
node: v8.2.1
react-static: latest

## EDIT - I found the issue. Under all that JS we forget to be HTML compliant. I added
```jsx
<Head>
  <meta charSet="UTF-8" />
```
in the static.config and now it works.

Btw, after a two day long pain trip, I finally got your project to handle less files. And one of the reasons why `react-static` would break down in styles during build, is because babel is taking in the style files and choking on the syntax. Something that often happens with mocha/unit tests. I'll post the result to the appropriate issue and file a PR in the next three days with an example.

**Comment by tannerlinsley** [comment]
Awesome. Really appreciate your help

**Comment by D1no** [comment]
Well I am pretty bought in into using react-router v4 and having a solid SEO-focused approach. I hope you guys have the lasting drive to maintain this project well.

![image](https://user-images.githubusercontent.com/2397125/31588286-e4b8dfde-b1ef-11e7-8abf-8c955c17f86f.png)

Best
dino
