### ISSUE TITLE
Release 5.5.14

### ISSUE THREAD

**Issue by denis-sokolov** [nozzle/react-static#463]
Can I haz 5.5.14, please? I would like to use #446 and #449.

![image](https://user-images.githubusercontent.com/113721/37285665-551d0e8a-2608-11e8-9aaf-47f4017a6abf.png)

**Comment by tannerlinsley** [comment]
5.6.0 now available.

**Comment by D1no** [comment]
damn it — I thought I would be quick enough for my maintenance PR for the examples here:
https://github.com/nozzle/react-static/pull/465

**Comment by denis-sokolov** [comment]
Thank you!
