### ISSUE TITLE
Consumable buildMeta.json, general support/api for server-based headers and redirects

### ISSUE THREAD

**Issue by denis-sokolov** [nozzle/react-static#470]
When react-static generates a website for production, js bundles and images have content hashes included in the filenames. This means we can cache them indefinitely with HTTP `Expires` header.

Should we generate [a Netlify `_headers` file](https://www.netlify.com/docs/headers-and-basic-auth/), or, for more customization, expose a flexible API to generate whatever server configuration file the user wants?

This is how my website looks on Webpagetest right now:
![image](https://user-images.githubusercontent.com/113721/37339483-7aa8199a-26c3-11e8-9001-30d976a8d87f.png)

I could configure the server myself as the user of react-static, but I’d prefer this to be a part of react-static for two reasons. First, the project strives to be about focusing on your website and not configuring the moving parts. Second, because unlike react-static, I don’t know all of my static resources and their paths.

**Comment by tannerlinsley** [comment]
Great point. I agree that RS should get you as far as possible without any config, but another goal is also to remain untied to any single static server environment.

If there is a way we could do this that would support every server, then I will 100% want to put it into the RS core. However, if it's going require specific implementations per host, then I would opt to place that information in a some type of optional but recommended post-build script, or even somewhere in the docs.

**Comment by hhsnopek** [comment]
Optionally we could expose a json object containing all the rewrites/headers that can be consumed by `x` (possibly a plugin #309) and output `_headers`, `.htaccess`, etc files during compilation

Exposing this object or outputting this to a file would allow the developer to consume this post-build. We should add this internally into RS so we don't have to post-process files, but we'd need to discuss the best interface for this.

The `_headers` file that netlify consumes is by far the nicest of the bunch that could be made, leaning on their spec we can easily make dev-server directs and output nginx/apache files ... IMO it's not the worst idea to use `_headers` as a base and output the other filetypes if configured to do so

**Comment by D1no** [comment]
Actually, this is something netlify (or some avid user) should contribute as an example template. In the docs, i.e. under a "how to get further", a general point out to `.htaccess`, `headers` and `CDN` role in page load speed should be the hint into the right direction.

IMO as this is opinionated, it's somewhat up to other headless CMSs out there that — such as [GraphCMS](https://graphcms.com/docs/examples/react-static_graphql_request_blog/) — show effort to meet in the middle. Therefore, I'd discard this as a dev ops topic and not web dev one. It's already hard enough to maintain the velocity of the example frameworks...

**Comment by tannerlinsley** [comment]
I could get on board with creating a json file that contains the `_headers` information, and possibly even more meta data about the build/site. After that, RS can dogfood its own interface and default to a Netlify configuration that consumes that low-level meta data. Thoughts?

**Comment by hhsnopek** [comment]
There's a lot of value in providing a consumable meta object that contains data about the site. I am curious about how one could go about adding redirects, rewrites, etc to the dev server, using a similar interface. Reproducing the production environment as close as we can for rewrites/redirects can be pertinent in some cases.

Ideally, I see this following workflow with header, redirects, rewrites, etc
* Write a `_headers`, `_redirects`, or `.htaccess` file

#### Development (`react-static start`):
* React Static dev server, aka webpack-dev-sever, apply my redirects/rewrites
* React Static apply my headers

Sidenote: we should update webpack-dev-server to webpack-serve 😄 

#### Production (`react-static build`):
* Consume the file and generate new redirects/rewrites based on static routes created

I don't think we should by default generate a specific configuration, only if `_headers` file is defined should a `_headers` file be generated. Similarly, if a `_redirects` or `.htaccess` is defined, the output should remain consistent. If none of the files are defined then we should create nothing for consumption; this should be the default.

**Comment by whmountains** [comment]
Some prior art to fuel the discussion:

Gatsby has a [plugin](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-netlify) for this.

Webpack has a [plugin](https://github.com/danethurber/webpack-manifest-plugin) for generating asset manifests.  Gatsby's plugin actually uses this under the hood, grabbing the manifest file and using it to generate the `_headers` file.

There are couple of gists ([1](https://gist.github.com/Kamshak/35630ec21df8dca27de3bb915f2d67e4), [2](https://gist.github.com/tilsammans/8b47cf2d1be994554658f4e412ec9ea4)) showing how to create a webpack plugin that generates the appropriate `_headers` file for Netlify.

**Comment by tannerlinsley** [comment]
Awesome. That's a good indication we're on the right track. It could be cool to use the webpack plugin too, which could get us one step closer to full auto-PWA.
