### ISSUE TITLE
Saas example won't build

### ISSUE THREAD

**Issue by DSalko** [nozzle/react-static#472]
I'm getting an error when trying to `react-build`  saas example. But it works with dev server. Any suggestions?

Thanks.

```
ERROR in ./src/app.scss
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin fo
r the usage example
    at Object.pitch (/Volumes/workspace/_projects/talla/botchain-web/node_modules/extract-text-webpack-plugin/dist/loader.js:57:11)
 @ ./src/App.js 41:0-21
 @ ./src/index.js
```

**Comment by D1no** [comment]
I didn't create the saas example. However, I created the less example. I am not sure, but you could take a look of changing the ExtractTextPlugin to the way the less example uses it. Just with saas.

This is whats currently in the saas example:
https://github.com/nozzle/react-static/blob/afbda932d2160032329d5954ae7a88064afa8cd5/examples/sass/static.config.js#L39-L68

This is how the less example uses the ExtractText plugin:
https://github.com/nozzle/react-static/blob/afbda932d2160032329d5954ae7a88064afa8cd5/examples/less-antdesign/static.config.js#L184-L202

Maybe you could take over the ExtractText config and PR it to the saas example if you make it work. I hope this helps

**Comment by Kacoze** [comment]
If you need, there is my solution for scss with modules:
`webpack: (config, { defaultLoaders, stage }) => {
    config.module.rules = [
      {
        oneOf: [
          {
            test: /\.module.scss$/,
            use:
              stage === 'dev'
                ? [
                  {
                    loader: 'style-loader',
                  },
                  {
                    loader: 'css-loader',
                    options: {
                      modules: true,
                      localIdentName: '[name]__[local]--[hash:base64:5]',
                      sourceMap: true,
                      namedExport: true,
                      camelCase: true,
                      minimize: false,
                    },
                  },
                  {
                    loader: 'sass-loader',
                  },
                ]
                : [
                  {
                    loader: 'style-loader',
                  },
                  {
                    loader: 'css-loader',
                    options: {
                      minimize: true,
                      sourceMap: process.env.REACT_STATIC_DEBUG,
                      modules: true,
                      localIdentName: process.env.REACT_STATIC_DEBUG
                        ? '[name]__[local]--[hash:base64:5]'
                        : undefined,
                    },
                  },
                  {
                    loader: 'sass-loader',
                  },
                ],
          },
          defaultLoaders.cssLoader,
          defaultLoaders.jsLoader,
          defaultLoaders.fileLoader,
        ],
      },
    ]
    return config
  },`

**Comment by DSalko** [comment]
Kacoze, thank you. I think I figured out my problem. I'll try to re-test with up to date react-static too.
