### ISSUE TITLE
Global site config

### ISSUE THREAD

**Issue by unlimit** [nozzle/react-static#477]
Hi! What is the best way to define and use global site config(that depends on env)?

For example I have following config:
`production: {api_key: "123"}`
`development: {api_key: "001"}`

Accordingly to the docs  - `getSiteData` is what I need, but:

1.  I didn't find any examples/notes - how to pass and use `env` with it
2. Is it possible to access SiteData from non-component? Lets say I have api library, that needs `api_key`. Can this library directly access SiteData? 

Thanks!

**Comment by tannerlinsley** [comment]
For keys like that an environment variable is perfect. You can set those a variety of ways:
- In your bash execution: `$ MY_VARIABLE=123 react-static start/build`
- In your `static.config.js` file: `process.env.MY_VARIABLE = '123'`
- Using something like `dotenv` or `cross-env`

**Comment by unlimit** [comment]
@tannerlinsley thank you for detailed answer about `env`.
Ok, I set `MY_VARIABLE`, read it in `static.config.js`. How I can make it global and readable from other files? (That are not react components.)

**Comment by tannerlinsley** [comment]
You can access it in other files now via `process.env.MY_VARIABLE`
