### ISSUE TITLE
Setting `watchOptions.polling` does nothing

### ISSUE THREAD

**Issue by adambuczek** [nozzle/react-static#479]
I use a custom docker image:
```dockerfile
FROM node:latest
RUN yarn global add react-static
```
With this added to `static.config.js`
```js
  webpack: config => {
     config.watchOptions = {
       poll: true,
     }
     return config
   },
```
But changes in files wouldn't trigger rebuild after running development server.
I forked the repository and added:
```js
    watch: true,
    watchOptions: {
      poll: true,
    },
```
to `/src/static/webpack/webpack.config.dev.js`, built it and used my fork as a local dependecy. Still nothing
This worked in other static site generators I used: Next.js, Nuxt,js, brunch.io.

Is polling broken?

**Comment by whmountains** [comment]
Good question.  That sounds frustrating.

`react-static` uses [webpack-dev-server](https://webpack.js.org/configuration/dev-server/) and provides watching options to it directly.  I think that's overriding the configuration you've set in the webpack config.  You can see this happening here: https://github.com/nozzle/react-static/blob/master/src/static/webpack/index.js#L84-L87

We might be able this "just work" as expected by changing the way react-static configures webpack-dev-server, but in the mean time you can get the desired results by configuring the dev server directly.  Try something like this in your `static.config.js`:

```js
module.exports = {
  devServer: {
    watchOptions: {
      ignored: /node_modules/,
      poll: true,
    },
  },
}
```

**Comment by tannerlinsley** [comment]
This would be an easy PR:
```javascript
...config.devServer,
watchOptions: {
  ignored: /node_modules/,
  ...(config.devServer.watchOptions || {})
},
```

**Comment by adambuczek** [comment]
Thanks for making me understand it better! I created a PR https://github.com/nozzle/react-static/pull/493.
