### ISSUE TITLE
CD into target repo when finished creating.

### ISSUE THREAD

**Issue by Pixelatex** [nozzle/react-static#48]
It would be a lot more user-friendly if you auto cd to the created/target repo. 

-why? A lot of new programmers will run the create command and receive the commands to start/deploy. And they will instantly run these commands throwing errors because they are still in the parent directory.

Heck, most lazy programmers (like me) would appreciate this.

**Comment by Maxwell2022** [comment]
You probably don't expect to change directory if you run a command into your shell that is not the `cd` command. That for me is user-friendly or best user experience.

Do you change directory when you do a `git clone`? Do you change directory when you do an `mkdir`?

**Comment by Pixelatex** [comment]
Someone who creates a folder could possibly want to create a few more so here it makes sense to not cd into the created folder. However someone creating a react project will most likely not make more than 1 at that moment, so here user-friendly would be cding into the target repo.

**Comment by sghall** [comment]
You actually can't have it change to the new directory.  A child process cannot change the parent process' working directory.  You will always exit back out to where you entered the command.

https://stackoverflow.com/a/37624361/2631343

**Comment by tannerlinsley** [comment]
Agreed.  The technical aspects aside, I believe it would be an untrusted action to perform in the users terminal session.
