### ISSUE TITLE
Example: Firebase - Module not found: Can't resolve './firebase

### ISSUE THREAD

**Issue by adamchenwei** [nozzle/react-static#481]
Usin the latest react-static to build with `react-create` command with `Select a template below... firebase-auth`. after `npm run start` this is what I got...
![screen shot 2018-03-18 at 3 06 29 pm](https://user-images.githubusercontent.com/4201698/37569816-06f51314-2abe-11e8-9ee4-6f5643439cea.png)

**Comment by whmountains** [comment]
Have you checked to see if that `./firebase` is actually missing?  If it's not there, then you've probably encountered a bug with `react-create`.

If the file is there and you can't see any reason why webpack isn't finding it, then the next step would be to try to reproduce the problem in a new test project.  If the problem goes away in the new project, then try to figure out what's different between the test project and your real project.  Don't forget to come back here and share what you've found in case someone else has the same problem.

If the problem persists in the new project, push it to GitHub and share the link with us.  You might also want to open an issue on ipeters90/react-static and webpack/webpack.

**Comment by adamchenwei** [comment]
ok, let me see what I can do! will get back to you soon!

**Comment by arlair** [comment]
I think it is meant to be reference the package`firebase` and not `./firebase`.

That makes it compile, but there seem to be some other issues when the page is loaded.

**Comment by magnusros** [comment]
Still get this error: Error: Cannot find module "./firebase". When running firebase example

**Comment by ZeroPie** [comment]
I can reproduce this

**Comment by AyyanNiazi** [comment]
How to resolve This issue

./src/loginComponent/adminLog.jsx
Module not found: Can't resolve './config/Fire.js' in 'D:\project 01 bc\project01\src\loginComponent'

**Comment by AyyanNiazi** [comment]
sorry i didnt undrstand

**Comment by kirtanwadekar** [comment]
Module not found: Can't resolve 'firebase/app' in '/home/webcubic8/Desktop/react-redux-app/marioplan/src/config'

someone please help me fix this error. asap

**Comment by Pixelatex** [comment]
Don't necro an old issue and without code or anything we can't even begin to help you.

**Comment by Shahzadkhan99** [comment]
same issue ...

**Comment by Brianorinah** [comment]
> I am having the same issue:
> used:
> -create-react-app
> files:
> -src/app.js
> -src/firebase.js
> import in app.js:
> -import firebase from './firebase';
> error:
> "/src/firebase.js Module not found: Can't resolve 'firebase'"
> 
> **Figured it out. Even though I have installed firebase tools, I still needed to install firebase.
> `npm i firebase` fixed it.

Thanks alot worked for me.It seemed firebase neede an upgrade from v7.2.2 to v7.2.3 to intergrate with firestore.

**Comment by sampathkumart** [comment]
Module not found: Can't resolve 'firebase/app' how to solve this?

**Comment by pelinoloji** [comment]
> I am having the same issue:
> used:
> -create-react-app
> files:
> -src/app.js
> -src/firebase.js
> import in app.js:
> -import firebase from './firebase';
> error:
> "/src/firebase.js Module not found: Can't resolve 'firebase'"
> 
> **Figured it out. Even though I have installed firebase tools, I still needed to install firebase.
> `npm i firebase` fixed it.

Thank you. I had the same problem. I had firebase tools but I realised I didn't have firebase. 
The solution would be `npm i firebase` or `yarn add firebase`

**Comment by rubalIslam** [comment]
npm i firebase solved it thanks a lot

**Comment by diegokaiser** [comment]
> npm i firebase solved it thanks a lot

Solved for me.

Took me almost 3 hours discover this reply.

3 HOURS!
LOVE YOU!

**Comment by mubasshir00** [comment]
in my case, I use yarn instead of npm

**Comment by samudralaAbhiramrao** [comment]
hey everyone when you  have the error as 

Module not found:   Can't resolve './firebase

just do run this command in the terminal and the issue is solved
> npm i firebase 

this is because when you installed your firebse but when the project is closed or out of internet there maybe a chance of occuring this error . So run the above command to fix it

- [ ] Happy "CODING GEEKS"

**Comment by sebass482** [comment]
There are many possible issues here. Mine was fixed by changing my import statement from

**Comment by sebass482** [comment]
There are many possible issues here. Not having the firebase dependency correctly installed or having a wrong import statement are the most probable in this case. My issue was fixed by changing my import statement to 'firebase' instead of './firebase'.

**Comment by FahadAliK** [comment]
use npm install --force firebase

**Comment by jaskaran2017** [comment]
> I am having the same issue:
> used:
> -create-react-app
> files:
> -src/app.js
> -src/firebase.js
> import in app.js:
> -import firebase from './firebase';
> error:
> "/src/firebase.js Module not found: Can't resolve 'firebase'"
> 
> **Figured it out. Even though I have installed firebase tools, I still needed to install firebase.
> `npm i firebase` fixed it.

thanks

**Comment by Ghani57** [comment]
I've run the command "npm install firebase" again and again but still getting this error "Module not found: Can't resolve 'firebase' ". Can anyone help me?

**Comment by Daniel-Amas** [comment]
> I've run the command "npm install firebase" again and again but still getting this error "Module not found: Can't resolve 'firebase' ". Can anyone help me?

I am having the same issue... been having this issue since yesterday. I have installed firebase like a 1000 times now 😂.
Someone help, please.

**Comment by Ghani57** [comment]
> > I've run the command "npm install firebase" again and again but still getting this error "Module not found: Can't resolve 'firebase' ". Can anyone help me?
> 
> I am having the same issue... been having this issue since yesterday. I have installed firebase like a 1000 times now 😂.
> Someone help, please.

Dear I think this problem is due to the versions because when I insert my code in my old project, it worked : )

**Comment by JakobKjaer** [comment]
I get exactly the same problem, does not help with npm install firebase. Have tried up to several times, even deleted node_modules, but get the same error. Hope we find a solution soon!

**Comment by Wajakki** [comment]
I also get exactly the same problem.

**Comment by Hanan11240** [comment]
Try this 'npm i firebase@6.0.2' or higher version of firebase .  It should work.

**Comment by salma-py97** [comment]
Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase`
and install this version instead `npm i firebase@^8.10.0`

**Comment by JakobKjaer** [comment]
When I install another version I get a blank page, I use React.js, I do not know how it can be.

**Comment by Wajakki** [comment]
> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase`
> and install this version instead `npm i firebase@^8.10.0`

Yeah that worked for me. ty

**Comment by fabian-lim** [comment]
> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase`
> and install this version instead `npm i firebase@^8.10.0`

this worked for me too. thanks!

**Comment by Daniel-Amas** [comment]
> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase`
> and install this version instead `npm i firebase@^8.10.0`

Thanks a lot. not sure how but it worked.

**Comment by lisamcgerr** [comment]
This solution worked for me, however, I typed `npm install firebase@8.10.0` removing the ^

**Comment by lisamcgerr** [comment]
This solution worked for me, however, I typed `npm install firebase@8.10.0` removing the ^

> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase`
> and install this version instead `npm i firebase@^8.10.0`

**Comment by JorgeCanul** [comment]
> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase`
> and install this version instead `npm i firebase@^8.10.0`

THis finally worked!!!! Thank you very much!

**Comment by Dipanjan310** [comment]
> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase`
> and install this version instead `npm i firebase@^8.10.0`

u r awesome man...thank u so much..it worked!!❤

**Comment by tundeph** [comment]
> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase`
> and install this version instead `npm i firebase@^8.10.0`

This answer was what worked for me too, I've spent two hours checking everywhere on the internet to no avail until I found this answer. Thank you 🙏

**Comment by thanatly** [comment]
> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase`
> and install this version instead `npm i firebase@^8.10.0`

This worked for me too. I wonder if there is a solution that works with firebase v.9?

**Comment by Javohir-K** [comment]
> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase`
> and install this version instead `npm i firebase@^8.10.0`

This is absolute solution. Thank you very much !

**Comment by rohit-rout** [comment]
> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase`
> and install this version instead `npm i firebase@^8.10.0`

this  solution didn't work! showing the same problem "module not found 'firebase' "  😥😥 plzz help if you have some other solution

**Comment by dds05** [comment]
Tham

> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase`
> and install this version instead `npm i firebase@^8.10.0`

Thankyou Sooo Much

**Comment by Kevin-Cay** [comment]
> npm install firebase@8.10.0
thank you so much, so helpful

**Comment by Kevin-Cay** [comment]
> This solution worked for me, however, I typed `npm install firebase@8.10.0` removing the ^
>
thank you, so helpful

**Comment by t1112000** [comment]
> Các bạn, gỡ cài đặt firebase bạn có trong package.json với cái này `npm uninstall firebase`
> và cài đặt phiên bản này thay thế`npm i firebase@^8.10.0`

Thanks

**Comment by partharoyy** [comment]
> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase`
> and install this version instead `npm i firebase@^8.10.0`

You saved God knows how many projects of mine. Cannot thank you enough. Thank you so so so so infinity much. 🙏🏽🙏🏽🙏🏽🙏🏽🙏🏽🙏🏽🙏🏽🙏🏽

**Comment by nitish166** [comment]
> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase`
> and install this version instead `npm i firebase@^8.10.0`

Thank you very much :)

**Comment by MUHAMMAD-MUNEEB-WASEEM** [comment]
> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase`
> and install this version instead `npm i firebase@^8.10.0`

It works. Thanks!!

**Comment by tejas-dobariya** [comment]
> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase`
> and install this version instead `npm i firebase@^8.10.0`

Thank you brother 
after getting bored for almost 5hrs I find this valuable solution and now my project works absolutely fine...

**Comment by mohammedpythons** [comment]
> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase`
> and install this version instead `npm i firebase@^8.10.0`

i think firebase 9 is having a problem with react 17, anyways this worked for me, thank you so much

**Comment by abdul-wajid-afridi** [comment]
> 
> 
> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase`
> and install this version instead `npm i firebase@^8.10.0`

love u that worked for me and i was stucked for 2 days and the version firebase v9.1.0  does not work for me thanks for this solution

**Comment by mubasshar009** [comment]
> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase`
> and install this version instead `npm i firebase@^8.10.0`

It Worked !!ThankYou

**Comment by Nishkala25** [comment]
> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase`
> and install this version instead `npm i firebase@^8.10.0`

Thank you

**Comment by Shweta-2215** [comment]
> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase` and install this version instead `npm i firebase@^8.10.0`

It worked for me. Thank youuuu!!!!

**Comment by johnikutty** [comment]
Failed to compile
./src/firebase.js
Module not found: Can't resolve 'firebase' in 'D:\NETFLIX-CLONE\netflix-clone\src'

**Comment by mohsin-sh** [comment]
Problem: Module not found: Can't resolve 'firebase'

**Comment by mohsin-sh** [comment]
Problem: Module not found: Can't resolve 'firebase'
Solution: type these commands in your terminal "npm uninstall firebase"
and then use "npm i firebase@^8.10.1"

**Comment by vaibhavnirmal2001** [comment]
> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase` and install this version instead `npm i firebase@^8.10.0`

Thanks for this!!!

**Comment by shahdhairya51** [comment]
> Guys, uninstall the firebase you have in package.json with this `npm uninstall firebase` and install this version instead `npm i firebase@^8.10.0`

love 3000 !! spent 2 hrs searching for this solution
