### ISSUE TITLE
Webpack: run SWPrecacheWebpackPlugin after export of .html files

### ISSUE THREAD

**Issue by jackedgson** [nozzle/react-static#488]
## Issue

Perhaps I'm missing something obvious but I'm trying to add service workers to my app and am doing so with `SWPrecacheWebpackPlugin` which is just a clone of what you have commented out in the repository.

However the `service-worker.js` precache list does not include the `.html` exported files. This is because the webpack plugin is being run before the export of `.html` files.

I'm not super experienced with Webpack so I could be missing something but is it possible to run the plugin post `HTML Exported`?

**Comment by whmountains** [comment]
I'd like to take a look.  Could you post the part of your `static.config.js` where you modify the webpack config, or point me to were I can see it online?

**Comment by tannerlinsley** [comment]
Keep in mind too that the webpack html plugin in react-static is only used during development. In production we do our own html page generation in https://github.com/nozzle/react-static/blob/master/src/static/index.js#L187-L440

**Comment by whmountains** [comment]
> webpack html plugin in react-static is only used during development.

In that case you might have more luck using the sw-precache CLI rather than the webpack plugin.  This is also how we used to do it with create-react-app, until it became officially supported.  These instructions might be useful: https://github.com/jeffposnick/create-react-pwa/tree/master

**Comment by jackedgson** [comment]
I was able to get this functionality working by utilising the CLI and a `sw-precache-config.js` file as proposed by @whmountains. `sw-precache` now runs in the build/stage npm script after the react-static build has completed.

Thanks for the help.

**Comment by whmountains** [comment]
Awesome!  I'm glad you got it working.

Can this issue be closed, or is there more to discuss?

**Comment by jackedgson** [comment]
I'm happy to close it
