### ISSUE TITLE
HTML is not generated when bundleAnazlyer is enabled.

### ISSUE THREAD

**Issue by whmountains** [nozzle/react-static#491]
### Steps to Reproduce

Add `bundleAnalyzer: true` to `static.config.js`

```js
yarn build
```

### Expected behavior

`dist` should contain static routes.

### Actual behavior

`index.html` is missing.  I think the other routes are missing as well, but I haven't checked.

### Suggestion

If `bundleAnalyzer` is a string, `webpack-bundle-analyzer` should run in static mode and save it's output to that path.

**Comment by dalisoft** [comment]
Same issue here :)

**Comment by dalisoft** [comment]
Looks like react-static more bugs than i excepted and errors aren't useful and/or informative
