### ISSUE TITLE
Paths without trailing slash include trailing slash when built

### ISSUE THREAD

**Issue by denis-sokolov** [nozzle/react-static#494]
Summary: static routes without trailing paths get built into `path/index.html` instead of `path.html`.

My website has paths defined without a trailing slash. So do at least [some of the examples](https://github.com/nozzle/react-static/blob/master/examples/animated-routes/static.config.js#L14-L17). So do real websites built on react-static, like nozzle.io.

```js
{
  path: "/about",
  component: "src/About"
},
```

When building for production, react-static places server-side generated HTML into dedicated directories: `dist/about/index.html`. Servers treat this as a convention for a URL with a trailing slash: Apache has this behavior by default as [DirectorySlash On](https://httpd.apache.org/docs/2.4/mod/mod_dir.html#directoryslash) and Netlify treats this as a [mandatory normalization](https://www.netlify.com/docs/redirects/#trailing-slash).  As a result, the servers redirect the user to `/about/`, which is unexpected.

To reproduce, visit [nozzle.io/about](https://nozzle.io/about). Notice the 301 redirect to the URL with the trailing slash. Now click “Home” and “About”. Notice how the client-side code switches to the URL without the trailing slash: `/about`.

This behavior is imperfect because it looks unpolished, and may even confuse users or impact SEO. It also can impact behavior of some scripts, starting with breaking `Route` component path matching. The latter is what caused me to notice theissue.

We can fix this by deploying the routes without a trailing slash to `dist/about.html`. This is a breaking change. We could also evaluate the impact and the usefulness of having both options in the codebase and maybe validate the routes to always be without the trailing slash.

The relevant code is in `static/index.js`. It’s not a recent addition, it’s there since [the very beginning](https://github.com/nozzle/react-static/commit/e01098637b05f25f0f9e8009a4dafbc36b6e9878#diff-efd59cd1bdc5c9ac6d0eaa368f1e149fR81).

https://github.com/nozzle/react-static/blob/6588f6aad17c16e6fceea9e07a326e8d4f3c82ee/src/static/index.js#L423

**Comment by denis-sokolov** [comment]
This is related to #469, but not a duplicate. That issue talks about the `<Route>` and similar features breaking.

This is related to #470, but not a duplicate. Unlike the provider-specific header configuration, the convention for file on disc layout is stronger, and on top we already make a call by creating `index` files in a particular way, vs not doing anything for the header configuration.

This is like a bastard child of #469 and #470.

**Comment by Balvajs** [comment]
I absolutely agree. I would welcome a option to use urls both with and without trailing slash.
Right now I have to manipulate with generated `index.html` using custom Node script. Which works fine, but it feels wrong.

**Comment by tannerlinsley** [comment]
Is anyone still experiencing this? We've done quite a bit of work on paths
and slashes lately.

**Comment by denis-sokolov** [comment]
I don’t have an opportunity to test it right now, but I don’t expect it to be fixed due to the code in questino still being the same:
https://github.com/nozzle/react-static/blob/33279eb563124eb3fad0a419011df9ec5349f4eb/src/static/index.js#L431

Besides, the change in behavior would be breaking backwards-compatibility, so if it is fixed, it’s also very bad. :-)

**Comment by denis-sokolov** [comment]
Bad bot.

**Comment by FullstackJack** [comment]
How on earth is nozzle.io/about/ even working? When I do that with my react-static site on `yarn serve` and Netlify, I get the 404 route filling my whole screen. It loads the proper route for a split second, then it throws the 404. I don't get it. Terrible. I can't deep link to anything.

**Comment by FullstackJack** [comment]
Ok, I figured out my issue. There was an `Unexpected Identifier` error in my console for development builds. It turns out I am writing blog posts with Markdown and in the YAML front matter, I had written a date but it didn't get wrapped in quotes during compilation. I think I might switch to using JSON front matter to be more explicit from now on. Now the trailing slashes work properly. I was banging my head against the wall trying to solve this.
