### ISSUE TITLE
404 Error and Warning for Non-static Routes

### ISSUE THREAD

**Issue by joshuaai** [nozzle/react-static#495]
Thanks again for this awesome library and for maintaining it so well.

I intend using `react-static` for app development with a few static pages and more non-static ones.

However, after setting up the `non-static-routing` template, it throws a `404` error and logs a warning for every route that is not statically matched. This happens in the production build as well.

![image](https://user-images.githubusercontent.com/22121420/37627728-bccc1bdc-2bcd-11e8-87c1-4e1b4cdeaf1c.png)

**Is there a way to make the `xhr` request to `routeInfo.json` not return `404` for non-static routes? This will eliminate the console error.**   

For an app with a lot of non-static routes, flooding the console with 404 error messages and warnings for each of those routes hampers the developer experience.

I'm hoping you can fix this or point to how I can mute them.

Thank you.

**Comment by tannerlinsley** [comment]
The only way we can check if a route is in fact a static route is to check if the `routeInfo` exists, so our only option would be to add a `config.muteMissingRouteInfo` option to opt out of these warnings.

Feel free to propose a PR for it and we'll go from there!

**Comment by zelphir** [comment]
I'm also interested in that, any update?

**Comment by cliffasaurus** [comment]
Updates?

**Comment by jelteliekens** [comment]
Updates?
