### ISSUE TITLE
building interferes with dev server

### ISSUE THREAD

**Issue by denis-sokolov** [nozzle/react-static#497]
With the default configuration `react-static start` and `react-static build` output into the same directory, and this conflict prevents comfortable local development and testing.

https://github.com/nozzle/react-static/blob/86474f41d1501f2a19b253bc1a9c605cb7b94802/src/static/getConfig.js#L24-L30
https://github.com/nozzle/react-static/blob/86474f41d1501f2a19b253bc1a9c605cb7b94802/src/static/getConfig.js#L38

Since b2547a984 we can use the `paths.devDist` option to fix this, but why not have it better by default? Why is the default configuration conflicting one?

**Comment by tannerlinsley** [comment]
We could change the default. This is a change that would need to percolate through a few places, like webpack resolve locations, project .gitignore files, etc...

I am fine if we want to default the dev mode to `devDist`. Tagging as RFI
