### ISSUE TITLE
Question: accessing route data on non-static-routes

### ISSUE THREAD

**Issue by benedfit** [nozzle/react-static#499]
I have a static route as `/something` that has access to route data, and I want to setup non-static routes for `/something/:else`, but what is the best way to get the route data from it's parent?

**Comment by tannerlinsley** [comment]
You must be explicit with the data that each route receives in `static.config.js`, so the answer to this problem is to simply pass the same data to child routes in `getData`.

**Comment by benedfit** [comment]
The child routes in question are numbered in the tens of thousands, so I don't want to define them in the config as the number of created pages would be too large, so I was wondering if there was an "official" way to access the data of a static route via non-static ones

**Comment by tannerlinsley** [comment]
Well, if it's a non static page, you can technically fetch it however you'd
like. You could try to use the prefetch() method if you'd like.

**Comment by benedfit** [comment]
Awesome thank you

**Comment by nechmads** [comment]
Got stuck on the same thing.
Wouldn't it be great if there was a way in static.config.js to tell the route path to ignore everything after the trailing '/'? Similar to what you can do directly with Router.
Then you can simply define a a path under getRoutes like this:
{
        path: '/something/*',  
        component: somethingComponent,
        getData: () => ({
          somethingData,
        }),
      },
