### ISSUE TITLE
Initial `yarn start` fails when public dir is not created

### ISSUE THREAD

**Issue by mattyfresh** [nozzle/react-static#5]
Hey!  Thanks so much for building this!  Been vetting all the possible options for using a static site generator on a work project (next, gatsby, spike, etc) and I this is definitely on the table.  Prima facie the build seems super fast, which is great.

One minor issue when using the `react-static create` command.  When a given example (IE `glamorous`) does not have a `public` dir inside of its root directory, `yarn start` will throw because it automatically attempts to copy that dir whether it exists or not.

I have a potential PR but can't push, so let me know if / how I can pitch in!

Cheers,

MP

**Comment by tannerlinsley** [comment]
It should already be fixed with the latest version. Upgrade to the latest version and try again. You can also just add the `public` directory to your existing project instead of starting a new one :)

**Comment by mattyfresh** [comment]
Ah!  Great, thanks.

**Comment by derekperkins** [comment]
@tannerlinsley

**Comment by tannerlinsley** [comment]
Okay this is fixed for real now.  Forgot that github doesn't add empty directories :(
