### ISSUE TITLE
No hot-reload when the app is not served from 3000

### ISSUE THREAD

**Issue by coisnepe** [nozzle/react-static#50]
**Steps to reproduce:**
- Have something already running on port 3000
- `yarn start` to serve your _react-static_ app
- The log should show:
- > `=> [✓] App serving at http://localhost:3001`
- Go to _http://localhost:3001_, change some text in _App.js_ and save the file

**Expected behavior:**
  The page is reloaded and reflects the changes just made to _App.js_

**Actual behavior:**
Nothing happens!

**Additional comment**
Kill the process running on port 3000, kill the react-static app server and restart it. It should restart on port 3000 and hot-reloading should function as expected.

- npm 5.4.2
- node 8.4.0
- Ubuntu 16.04

**Comment by tannerlinsley** [comment]
Interesting. This is pretty telling.

**Comment by tannerlinsley** [comment]
Closing unless someone can send me a zip that replicates this issue. I've had success on all ports.
