### ISSUE TITLE
`build --debug` silences React warnings

### ISSUE THREAD

**Issue by denis-sokolov** [nozzle/react-static#500]
`react-static build --debug` does not help me debug by silencing React warnings. Namely, React 16 has important [SSR HTML mismatch warnings](https://github.com/facebook/react/issues/10085), but `react-static build --debug` does not show them, because `react-static build --debug` still builds with `process.env.NODE_ENV === 'production'`, and React disables all warnings in that `NODE_ENV`.

**Comment by tannerlinsley** [comment]
This is an interesting problem. Running the flag with anything other that `production` would lead to code that is potentially not what users would expect to get in a final build. 

You could simply do `NODE_ENV = development yarn build --debug`. Does that cover this case?

**Comment by denis-sokolov** [comment]
The workaround does work. To be clear, my issue is not to resolve my workflow, but to potentially improve all users’ workflows. Namely, today react-static users do not see important warnings from the tools they use.

**Comment by tannerlinsley** [comment]
Should we add a second flag to disable minificatoin?

**Comment by denis-sokolov** [comment]
I’m sorry, I don’t understand how that would help. `--debug` disables minification already, I thought it’s the point of `--debug`.

**Comment by tannerlinsley** [comment]
I think your response answers my question then. I agree that debug should turn both minification off and node environment to development. It's about being useful as you said. 👍
