### ISSUE TITLE
Server-side rendering for development server

### ISSUE THREAD

**Issue by denis-sokolov** [nozzle/react-static#502]
A spectrum of problem in my website are only visible when I build my server-side rendered routes. For an example, paths and trailing slashes, React rendering mismatch warnings.

My workflow is to make a change, and run `react-static build --debug`. But this command, for my small website, takes 33 seconds. For deployment that’s nothing, but for interactive development it’s a pain.

I don’t know how hard it would be, but I wonder if we could integrate server-side rendering into the main dev server. I’ve seen at least [react-universally](https://github.com/ctrlplusb/react-universally) use it successfully.

We start the dev server by asking webpack-dev-server:
https://github.com/nozzle/react-static/blob/6588f6aad17c16e6fceea9e07a326e8d4f3c82ee/src/static/webpack/index.js#L179

We server-side render with custom code in a different place:
https://github.com/nozzle/react-static/blob/6588f6aad17c16e6fceea9e07a326e8d4f3c82ee/src/static/index.js#L249

**Comment by tannerlinsley** [comment]
That sounds really interesting. I'd love to hear more conceptually how it could work exactly. I'm still grasping the concept myself ;)

**Comment by denis-sokolov** [comment]
Conceptually it would render the app for a particular route server-side, caching parts in memory. The dev server would then hydrate and take over.

In practice, we would want to defer to the 3rd-party dev server tooling. That’s why, I realize, this is blocked by #503.

**Comment by tannerlinsley** [comment]
Sounds awesome. What else could this enable us to do?

**Comment by denis-sokolov** [comment]
Server-side rendering in development would close #500, allow to run HTML validators and Chrome audits in development.

**Comment by tannerlinsley** [comment]
Yep. Let's make this happen.

**Comment by severen** [comment]
Have you seen the [SSR support](https://github.com/webpack/webpack-dev-middleware#server-side-rendering) in webpack-dev-middleware? It looks like that could be a good place to start.

**Comment by denis-sokolov** [comment]
Bad bot! Stop closing well articulated and debated issues! :-)

**Comment by tannerlinsley** [comment]
Bad bot.
