### ISSUE TITLE
Consider webpack-serve over webpack-dev-server

### ISSUE THREAD

**Issue by denis-sokolov** [nozzle/react-static#503]
It seems webpack-dev-server authors encourage moving to a fresh, better alternative [webpack-serve](https://github.com/webpack-contrib/webpack-serve):

> Use webpack-serve for a fast alternative. Use webpack-dev-server if you need to test on old browsers.

The author of webpack-serve is one of the lead developers of webpack-dev-server.

I don’t know if we want this move, but I want to make sure we know about it and consider it.

**Comment by adambuczek** [comment]
Seeing as static sites are widely used in low-budget projects and those correlate with outdated software I would be pretty unhappy not having an option to test the site on IE 8 and 9.

**Comment by denis-sokolov** [comment]
It will still possible to test the website, just without the hot reloading. Sure, that will be slow, but not impossible: I test react-static server-side rendering without hot reloading today, and it’s not excruciating. Whether or not a site built with react-static would work with old IE is unrelated to this issue.

How much do we support IE 9 today? I argue to leave people with exotic needs behind, so that the rest can enjoy better future. But at the end of the day it is for the leadership of the project to decide the direction.

**Comment by adambuczek** [comment]
I honestly can't argue with that.

**Comment by tannerlinsley** [comment]
I think this is a good idea. Pushing to RFI.

**Comment by denis-sokolov** [comment]
Requires Webpack 4, so will be quite slow to adopt. Let’s revisit after we migrate to Webpack 4 in #466.

**Comment by uturnr** [comment]
This is a message from the future... don't do it!!! 👻
