### ISSUE TITLE
Creating Project with `styled-components` template fails on start because lodash isn't installed

### ISSUE THREAD

**Issue by mfix22** [nozzle/react-static#51]
`yarn add lodash` fixes it. I will try and raise a PR shortly.

**Comment by tannerlinsley** [comment]
No where in the entire repo is there an instance of `lodash`, so I'm very confused.

**Comment by mfix22** [comment]
I am not sure either! I just removed some dependencies that `react-static create` installed and now lodash doesn't show up so at least I got the project up and running.

Here is me trying a fresh `create`:
<img width="581" alt="screenshot 2017-10-16 19 34 53" src="https://user-images.githubusercontent.com/8397708/31644104-220a25a0-b2a9-11e7-873b-6903f69a8e62.png">

**Comment by tannerlinsley** [comment]
This should be fixed in the latest version. Please upgrade both global and local packages to version 2.0.0
