### ISSUE TITLE
Netlify forms do not work

### ISSUE THREAD

**Issue by Unforgiven-wanda** [nozzle/react-static#510]
Hello,
Deploying the basic template for a react-static project on Netlify, and then adding a form example does not work. It seems Netlify somehow does not play nicely with RS and I haven't been able to pinpoint the cause.
The code of my form (just replace the About container with this):
```javascript
import React from 'react';

const encode = (data) => {
        return Object.keys(data)
            .map(key => encodeURIComponent(key) + "=" + encodeURIComponent(data[key]))
            .join("&");
      }

      export default class About extends React.Component {
        constructor(props) {
          super(props);
          this.state = { name: "", email: "", message: "" };
        }

        /* Here’s the juicy bit for posting the form submission */

        handleSubmit = e => {
          fetch("/", {
            method: "POST",
            headers: { "Content-Type": "application/x-www-form-urlencoded" },
            body: encode({ "form-name": "contact", ...this.state })
          })
            .then(() => alert("Success!"))
            .catch(error => alert(error));

          e.preventDefault();
        };

        handleChange = e => this.setState({ [e.target.name]: e.target.value });

        render() {
          const { name, email, message } = this.state;
          return (
            <form onSubmit={this.handleSubmit}>
              <p>
                <label>
                  Your Name: <input type="text" name="name" value={name} onChange={this.handleChange} />
                </label>
              </p>
              <p>
                <label>
                  Your Email: <input type="email" name="email" value={email} onChange={this.handleChange} />
                </label>
              </p>
              <p>
                <label>
                  Message: <textarea name="message" value={message} onChange={this.handleChange} />
                </label>
              </p>
              <p>
                <button type="submit">Send</button>
              </p>
            </form>
          );
        }
      }
```

A `success` alert pops up, meaning the request goes through, but the form panel of Netlify remains empty (as opposed to showing `contact` form submissions)

![d3d4b7e0-3ec7-49bd-b476-ab1f3c82cd5f](https://user-images.githubusercontent.com/4499783/37772859-3c8bcbd2-2ddc-11e8-9888-192b28bc597d.png)

Has anyone encountered a similar issue? If yes, then how did you fix it?
Thank you.

**Comment by tannerlinsley** [comment]
This form works for me.
https://github.com/tannerlinsley/cityviewreceptions/blob/master/src/containers/Home/Contact.js#L148

**Comment by nathanpower** [comment]
I think you are missing the `netlify="true"` or `data-netlify="true"` attribute on the form element @Unforgiven-wanda.

Incidentally, I think netlify just got rid of their default form POST success page (at least it's no longer working for me), so you might have to use your own page or notification when form is submitted.

**Comment by tannerlinsley** [comment]
Yep that's it.

**Comment by danadigun** [comment]
Still not working for me. Using angular though

`  <form name="contact" 
      method="post" 
      data-netlify="true" 
      data-netlify-honeypot="bot-field"
      (ngSubmit)="onSubmit()" novalidate>
    <p>
      <label>Email: 
        <input type="text" name="name">
      </label>
    </p>
    <p>
      <label>Message:
         <textarea name="message"></textarea>
      </label>
    </p>
    <p>
      <button type=”submit”>Send</button>
    </p>
  </form>`

component code
`import { Component, OnInit } from '@angular/core';
import {NgForm} from '@angular/forms';
import { encode } from 'punycode';
import { headersToString } from 'selenium-webdriver/http';
import { $$ } from 'protractor';
declare var $ : any;

@Component({
  selector: 'app-eoi',
  templateUrl: './eoi.component.html',
  styleUrls: ['./eoi.component.css']
})
export class EoiComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

  onSubmit(){
  
    var $form = $(this);
    const url = '/'

    //request
    var request = new Request(url, {
      method : 'POST',
      body : $form.serialize(),
      headers : { "Content-Type": "application/x-www-form-urlencoded" }
    })

    fetch(request).then(function(){
      alert('Form has been submitted')
    }).catch(function(err){
      alert('Unable to submit form');
    })
  }
}
`

**Comment by danadigun** [comment]
Guys netlify form is still not working for me in angular. here's a simple code.


**HTML Code**
```
  <form name="contact" 
      method="post" 
      data-netlify="true" 
      data-netlify-honeypot="bot-field"
      (ngSubmit)="onSubmit()" novalidate>
    <p>
      <label>Email: 
        <input type="text" name="name">
      </label>
    </p>
    <p>
      <label>Message:
         <textarea name="message"></textarea>
      </label>
    </p>
    <p>
      <button type=”submit”>Send</button>
    </p>
  </form>

```
**Component code :**
```
import { Component, OnInit } from '@angular/core';
import {NgForm} from '@angular/forms';
import { encode } from 'punycode';
import { headersToString } from 'selenium-webdriver/http';
import { $$ } from 'protractor';
declare var $ : any;

@Component({
  selector: 'app-eoi',
  templateUrl: './eoi.component.html',
  styleUrls: ['./eoi.component.css']
})
export class EoiComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

  onSubmit(){
  
    var $form = $(this);
    const url = '/'

    //request
    var request = new Request(url, {
      method : 'POST',
      body : $form.serialize(),
      headers : { "Content-Type": "application/x-www-form-urlencoded" }
    })

    fetch(request).then(function(){
      alert('Form has been submitted')
    }).catch(function(err){
      alert('Unable to submit form');
    })
  }
}

```
I have tried everything in the documentation all to no avail. Please what am i getting wrong. Sorry Guys had to post this to a close thread.

**Comment by tannerlinsley** [comment]
React static doesn't support angular. You'll need to submit your question
to netlify or an angular support forum.

**Comment by MilosJo** [comment]
@Unforgiven-wanda Hey, did you manage to solve this?
I am using same code, with create-react-app.
Netlify dashboard doesn't seem to recognize my form.
And I have added `data-netlify="true"`, as well as hidden input, etc.

**Comment by Unforgiven-wanda** [comment]
No, I never did solve this particular issue unfortunately and had to move on pretty quick.
I did however circumvent it by using the MailGun API, catching the form submit event and sending an email through MailGun.

Something like:
```javascript
onFormSubmit() {
const {name, email, message} = this.state
axios({
                method: "post",
                url: `mailgun uri`,
                auth: {
                  username: "api",
                  password: "mailgun password"
                },
                params: {
                  from: `${name} <${email}>`,
                  to: "myownaddress@me.com",
                  subject: "A subject",
                  text: message
                }
              })
}
```
It's a free service so that worked for me.
Hope it helps.

**Comment by sw-yx** [comment]
hi folks i work at Netlify. can always make forms easier to use/better documented

if there is anything you'd like to ask based on this article: https://www.netlify.com/blog/2017/07/20/how-to-integrate-netlifys-form-handling-in-a-react-app/ i'd be happy to modify it

**Comment by tannerlinsley** [comment]
For the record, my netlify forms work great with React Static. I think its important to note that you can also use netlify forms by posting as well. Here is an example: https://github.com/nozzle/nozzle.io/blob/master/src/components/ExitIntent.js#L152-L197

**Comment by sw-yx** [comment]
yea thats covered here just without axios https://www.netlify.com/blog/2017/07/20/how-to-integrate-netlifys-form-handling-in-a-react-app/#form-handling-with-a-stateful-react-form

**Comment by MilosJo** [comment]
Copy/paste static html inside `index.js`, just above `<div id="root></div>` worked for me.
The problem was he couldn't find html form on my `create-react-app`.

@Unforgiven-wanda Worked like charm on Gatsby powered site. Thanks!

**Comment by 3noki** [comment]
Anyone that isn't using a JS framework figure out a solution? I have a very basic form that isn't showing results, I do get redirected to the action page and says the submission was successful, but there is no data in the results

```
<form name="contact" netlify >
    <p>
      <input type="text" name="name" placeholder="Hi, what's your name?" required>
      <span class="required-text"></span>
    </p>
    <p>
      <input type="text" name="phone" placeholder="What's a good phone number?" required>
      <span class="required-text"></span>
    </p>
    <p>
      <input type="text" name="email" placeholder="What's your email address?" required>
      <span class="required-text"></span>
    </p>
    <p>
      <input type="text" name="message" placeholder="Can you tell us a bit about how we can help?" optional>
      <span class="optional-text"></span>
    </p>
    <p>
      <button class="button" style="vertical-align:middle" type="submit"><span>Send</span></button>
    </p>
  </form>
```
