### ISSUE TITLE
tip for overriding 'window' error when trying to 'yarn build' ?

### ISSUE THREAD

**Issue by h0rhay** [nozzle/react-static#518]
Getting this:
```
  ReferenceError: Failed exporting HTML for URL /map/ (src/containers/MapView): window is not defined
```
when running 'yarn build'

It must be because the 'google-map-react' package I'm using is referencing the window somehow..

Is there any way I can stub it out?

I tried setting up an empty var in the offending file.. but no luck
```
const window = {}
```
Any help would be amazing many thanks :)

**Comment by JustFly1984** [comment]
I would recommend you to wrap your render google maps component with
conditional.
Something like :
‘’’
{
   typeof window !== “undefined” && (
    <MyGoogleMap  />
   )
}
‘’’

So it will be ignored on serverside render, and catch up on client side
render

**Comment by h0rhay** [comment]
Thanks so much,

I tried it like this:
```
export class MapContainer extends React.Component {
  render () {
    const style = {
      width: '100%',
      height: '100%',
    }

    return (
      <div>
        {
          typeof window !== 'undefined' && (
            <MapComponent
              google={this.props.google}
              style={style}
              onClick={this.onMapClicked}
            />
          )
        }
      </div>
    )
  }
}
```
App runs fine locally but get the same error when building :(

```
ReferenceError: Failed exporting HTML for URL /map/ (src/containers/MapView): window is not defined
```

**Comment by JustFly1984** [comment]
Which npm package do you use? I use `react-google-maps`, an I do not have issues with rendering.

I guard every use case of `window` or `document` in class methods too.

On other hand, you could try to guard import of the component. for me it was useful to `require` instead of `import` npm `history`:

```
let history // eslint-disable-line

if (typeof document !== 'undefined') {
  const createBrowserHistory = require('history/createBrowserHistory').default

  history = createBrowserHistory()
} else {
  history = void 0
}

export default history
```
You could try to do the same with your Map component in question.

**Comment by h0rhay** [comment]
Yeah I'm using `react-google-maps`
I'm not referring to `window` in any of my code.. So I guessed it must be coming from the library code..

Not sure how the history example will help.. have you got a fuller example?

>I guard every use case of window or document in class methods too

Does that mean you add that 'typeof window' check to every render return for all your components?

**Comment by JustFly1984** [comment]
No, it does means that I guard every Component which uses unguarded window or document under the hood.

If I use window or document in lifecycle methods - I guard it in place.

**Comment by denis-sokolov** [comment]
For your particular case you may find [google-map-react](https://www.npmjs.com/package/google-map-react) useful. It’s a popular, fresh library that renders the map server-side, no problem.

Note that guarding in `render` produces mismatching HTML between the server and the client. Unfortunately these warnings are hidden today, see #500. You can both fix the mismatch and simplify the guards with a reusable wrapper component:

```js
class InBrowserOnly extends React.Component {
  state = { mounted: false }
  componentDidMount() { this.setState({ mounted: true }) }
  render() {
    if (!this.state.mounted) return null;
    return this.props.children;
  }
}

<InBrowserOnly>
  <MapComponent ... />
</InBrowserOnly>
```

**Comment by denis-sokolov** [comment]
Note that the authors of [google-map-react claim](https://www.npmjs.com/package/google-map-react) it renders on the server, so your assumption that it’s because it uses `window` is likely incorrect.

Note that guarding in `render` produces mismatching HTML between the server and the client. Unfortunately these warnings are hidden today, see #500. You can both fix the mismatch and simplify the guards with a reusable wrapper component:

```js
class InBrowserOnly extends React.Component {
  state = { mounted: false }
  componentDidMount() { this.setState({ mounted: true }) }
  render() {
    if (!this.state.mounted) return null;
    return this.props.children;
  }
}

<InBrowserOnly>
  <MapComponent ... />
</InBrowserOnly>
```
