### ISSUE TITLE
routes with getData redirect to 404 when accessed directly without going through home route

### ISSUE THREAD

**Issue by cliffasaurus** [nozzle/react-static#521]
going directly to the `/blog` page
https://react-static-5-6-1-error.netlify.com/blog
redirects to
https://react-static-5-6-1-error.netlify.com/blog/
then 404

**Comment by zelphir** [comment]
Having the same issue after `5.5.14` (that's the latest version where everything works as expected).

Also, but maybe it's better to create a separate ticket: after version `5.3` preact doesn't work anymore.
That's the error:

```
 Error: Invariant Violation: Failed exporting HTML for URL ...: RouterScroller(...): Nothing was returned from render. This usually mean  s a return statement is missing. Or, to render nothing, return null.
```

**Comment by zelphir** [comment]
Found the issue, date is not is not wrapped in a string, so not a valid JSON. I guess you are using the netlifly example with markdown and `gray-matter`.

You can fix the issue doing something like that after this line: https://github.com/nozzle/react-static/blob/master/examples/netlifycms/static.config.js#L21

```js
dataObj.data.date = dataObj.data.date.toString()
```

**Comment by tannerlinsley** [comment]
There may have been a related bug to this that caused the dev server to 404 when it shouldn't. It's been fixed in the latest version.
