### ISSUE TITLE
Preact not working after version 5.3

### ISSUE THREAD

**Issue by zelphir** [nozzle/react-static#522]
After version `5.3` preact doesn't work anymore.
That's the error:

    Error: Invariant Violation: Failed exporting HTML for URL ...: RouterScroller(...):
    Nothing was returned from render. This usually mean  s a return statement is missing.
    Or, to render nothing, return null.

**Comment by zelphir** [comment]
#521  #471

**Comment by tannerlinsley** [comment]
Well, this is weird. I'll need to dig into it more.
