### ISSUE TITLE
Problem loading react@16.3.0-alpha.3

### ISSUE THREAD

**Issue by leimonio** [nozzle/react-static#525]
When running my application (non static routes) with react static cli, react version is getting default version `16.2.0` even if in my `package.json` I have installed `react@16.3.0-alpha.3`. In `node_modules/react` I can also find installed the correct version needed. 
Why is this happening? I would like to use `createContext` API from next react version. Is there any other way I could do it?

**Comment by tannerlinsley** [comment]
React-Static only requires version `^16`, so that should be fine. Try npm/yarn uninstalling react from your project, then reinstalling it with the version you want.

**Comment by leimonio** [comment]
@tannerlinsley tried that already with many different ways. For some reason it keeps loading `react@16.2.0`.

**Comment by zelphir** [comment]
@leimonio you can use resolutions if you using `yarn`, not sure about `npm`.

Add that to your `package.json`:

```json
"resolutions": {
    "d2/left-pad": "1.1.1",
    "c/**/left-pad": "1.1.2"
  }
```

If you are using yarn workspaces you need to add that in the root `package.json`, if not, simply in your app apackage.json`

**Comment by leimonio** [comment]
@zelphir thank you!! `resolutions` worked perfectly and now I get the correct version loaded. As far as the `create-react-context`, is it working fine with `react-router`?
I assume the transition to the new react context API would be really easy by changing `createReactContext ` to `React.createContext`.
