### ISSUE TITLE
error when using 'react-static start' but not when using 'yarn start'

### ISSUE THREAD

**Issue by dan-dr** [nozzle/react-static#529]
I'n getting this error:
`multi C:/Users/Dan/AppData/Local/Yarn/Data/global/node_modules/react-hot-loader/patch.js C:/Users/Dan/AppData/Local/Yarn/Data/global/node_modules/react-dev-utils/webpackHotDevClient.js (webpack)/hot/only-dev-server.js ./src/index.js
Module not found: Can't resolve 'ts-loader' in 'C:\Users\Dan\AppData\Local\Yarn\Data\global\node_modules\react-static\node_modules'`

Now I wouldn't have a problem but when I use yarn, Ctrl+C leaves the process running in the background and I need to manually close it with the task manager.

**Comment by dan-dr** [comment]
It's a fresh install. it seems the `react-static\node_modules` dir is empty in the global module, which is odd.

**Comment by dan-dr** [comment]
Okay so I figured that basically if you want to edit the webpack config with your own loaders (or anything that requires adding modules) you can't use the global `react-static` cli because it can't use those modules. This should probably be stated in the webpack section in the docs.
But again the question of the process running in the background bothers me.

**Comment by dan-dr** [comment]
Related: https://github.com/reactjs/react-router-tutorial/issues/240

**Comment by tannerlinsley** [comment]
The process should be killed, so that sounds like a bug for another issue. We'll add some docs to denote that quirk with running using `react-static` cli as opposed to `yarn` / `npm`
