### ISSUE TITLE
env-aware "siteRoot" option

### ISSUE THREAD

**Issue by rachel-church** [nozzle/react-static#531]
I have three different domains that my production build needs to be deployed to: `https://www.mysite.com`, `https://www.eu.mysite.com`, and `https://www.la.mysite.com`. 

The build is performed using Jenkins and I would like to be able to have the siteRoot determined from either a command line param or environment variable. 

I think siteRoot would need to allow either a string or function. The function would need to be able to accept the "env" as a parameter as suggested in #422

**Comment by tannerlinsley** [comment]
This is easily done in the static.config.js already like so:
```javascript
let siteRoot = 'https://www.mysite.com'
if (process.env.LANG === 'eu') {
  siteRoot = 'https://www.eu.mysite.com'
} else if (process.env.LANG === 'la') {
  siteRoot = 'https://www.la.mysite.com'
}
export default {
  siteRoot
}
```

**Comment by denis-sokolov** [comment]
Yeah, that’s the main benefit of programmatic configs! :-)
