### ISSUE TITLE
wired behaviour after build and state values?

### ISSUE THREAD

**Issue by amirhouieh** [nozzle/react-static#532]
Hi all, sorry for the very vague title, but could not come up with any better. 
I need to generate a SVG `<path>` based on window dimensions. So I have a method which is attach to window on resize
```
...
    updateDimensions = () => {
        this.setState({
            w: window.innerWidth,
            h: window.innerHeight,
        });
    };
...
```
and then in render I have something like:
```
render(){
   const {w, h} = this.state;
   return (
          ...
           <svg><path d={`M${w} ${h} H0 V0 H${w} V${h} Z`} /></svg>
          ...
   )
}
```
this works fine in development but not from build file. While when I console the `w` and `h`, they have the right values, but seems that during build the svg is rendered and stored as hardcoded or something which does not react to state!

**Comment by JustFly1984** [comment]
Make SVG as separate component, and pass w and h as props to this component

**Comment by amirhouieh** [comment]
@JustFly1984 did not work, while I do not understand why would it fix this issue?

**Comment by JustFly1984** [comment]
Do you have errors in console? Looks like your react code does not sync
with DOM. Make your SVG as class and console.log your w and h props from
componentDidMount and render methods

**Comment by tannerlinsley** [comment]
Let's move this discussion to the slack organization. Thanks!
