### ISSUE TITLE
Responsive layouts

### ISSUE THREAD

**Issue by hundsim** [nozzle/react-static#534]
Let's say that for top navigation, we want completely different HTML for desktop vs mobile visitors.

And let's say we want the HTML prerendered, that's why we'd use react-static.

Conditionally showing elements depending on screen width (like libraries such as [react-responsive](https://github.com/contra/react-responsive) ), I guees aren't applicable in static site generators.

What are our options? My rookie conclusion is to apply the pattern provided at the bottom. 

    .desktop-nav {
      display: none;
      @media screen and (min-width: 601px) {
        display: block;
      }  
    }
    .mobile-nav {
      display: none;
      @media screen and (max-width: 600px) {
        display: block;
      }  
    }

P.S. I'm asking here and not on SO as I'm thinking that this is a pretty common scenario and perhaps there are some "react-static recommendations" how to go about doing this?

**Comment by tannerlinsley** [comment]
React Static is rendered server side so there is no viewport. In terms of
CSS, this should not be a problem and you can use whatever approach you
want. However, any libraries or JavaScript that relies on window will not
function during export.

**Comment by cubbuk** [comment]
@hundsim if you still have the issue try to give a default value to be used in media queries during build step. https://github.com/contra/react-responsive#server-rendering
