### ISSUE TITLE
Links don't have active class in static build

### ISSUE THREAD

**Issue by a-p-f** [nozzle/react-static#535]
Link components don't have the active class added in static builds.

Here is a minimally modified clone of the basic template - https://github.com/a-p-f/react_static_link_test. It is deployed here - https://a-p-f.github.io/react_static_link_test/.

The main modification I've made is to make the active nav link green. From the home page, click Blog. Note that the nav link is green (correct behaviour). Now refresh the page. The link is now white (incorrect). 

Note that the "About" link links to "/about" (no trailing slash) but the "Blog" link links to "/blog/" (with trailing slash). The same behaviour is seen on both links. I don't believe this issue is related to https://github.com/nozzle/react-static/issues/494.

**Comment by JustFly1984** [comment]
You need to use <NavLink /> instead of <Link />

<NavLink /> has activeClassName props

**Comment by Balvajs** [comment]
This issue is same as #469.

**Comment by a-p-f** [comment]
Yes, definitely duplicate of #469. Sorry about that.
