### ISSUE TITLE
Difference in 404-page between development and build

### ISSUE THREAD

**Issue by Reggino** [nozzle/react-static#539]
Hi! I said it before, but i'll say it again, thank for this :-)

I ran into a weird issue that took me a while to figure out: 

A 404-page containing components wrapped in `withRouteData()` will render properly in development. However these components will not be shown _at all_ in the production built, when opening the 404 page. (without notices or warnings).

**Comment by tannerlinsley** [comment]
I can't reproduce this. Could you give us some steps to reproduce from one of the templates?

**Comment by Reggino** [comment]
[404_example_with_route-connected_component.zip](https://github.com/nozzle/react-static/files/1929697/404_example_with_route-connected_component.zip)

Sorry for the late reply. 

Steps to reproduce:

- Apply patch to project
- In a terminal: ```cd react-static/examples/redux; npm run start```
- In a browser: Open http://localhost:3000/blah
- Notice the text _blah_ on the 404-page
- In a terminal: ```npm run build; npm run serve```;
- In a browser: Refresh http://localhost:3000/blah
- Notice the text _blah_ is not shown

**Comment by Reggino** [comment]
Some more debugging traced the issue back to the prop `is404` being `undefined` in `RouteData.js`. I'm not really sure where/how to should be fixed.
