### ISSUE TITLE
[Question] - How do you handle forms?

### ISSUE THREAD

**Issue by nealoke** [nozzle/react-static#54]
Hi, you can totally delete this if you think it is inappropriate but I was wondering how you handle your forms with `react-static` as it is static content - eg. no server side script to handle form inputs. I'm currently finished building my static website but don't have a clue on how to actually handle form posts.

Are you just sending out `fetch` or `axios` requests when somebody submits a form? Or am I missing something obvious here?

**Comment by tannerlinsley** [comment]
Yep, as with any other form submission in an SPA, you have to have a backend or a service to send it to. Whether this is your own api, a paid service, etc is all up to you :)

**Comment by derekperkins** [comment]
@nealoke Here are some references
- https://www.netlify.com/blog/2017/07/20/how-to-integrate-netlifys-form-handling-in-a-react-app/
- https://docs.google.com/forms
- https://zapier.com/learn/forms-surveys/best-online-form-builder-software/

Also, if you use a CRM tool like Hubspot, they'll typically have a form component as well.
