### ISSUE TITLE
Link examples sites with source code

### ISSUE THREAD

**Issue by brianrc** [nozzle/react-static#543]
You have lots of links to examples sites, but no links to the example sites with github repos. This is common with other static site generators trying to showcase their usefulness and for a newbie developer it's invaluable.

I'm just trying to make a basic blog site with markdown files using react-static and I'm already frustrated because I can't find readily available source code that does it. 

Please add example sites with source code! It's extremely valuable for newbies.

**Comment by tannerlinsley** [comment]
I'll send out a notice to all of the example owners to PR the source if possible. Good idea :)
