### ISSUE TITLE
Error: Cannot find module 'update-notifier'

### ISSUE THREAD

**Issue by oliviaoddo** [nozzle/react-static#546]
My ci build broke, which installs `react-static`  globally on each build. I ran into this error:

`Error: Cannot find module 'update-notifier'` 

I installed `update-notifier` globally to fix it for now.

**Comment by arlair** [comment]
I think this has been fixed in this merge: https://github.com/nozzle/react-static/pull/545/commits/d7131414e3f7640b57108d63560b5580465fb25f

**Comment by peirceb** [comment]
Same here. 5.5.12 seems to be the last working release.
I had to install update-notifier in my app to get npm run build to work for the time being.

**Comment by rohmanhm** [comment]
I also run into this problem.

I tried to run 
```bash
react-static create
```
But it throws an error

![image](https://user-images.githubusercontent.com/7524911/38536597-4dccc392-3cb4-11e8-8d8f-1bd2a83b18e1.png)

Environment
- Ubuntu@16.04
- react-static@5.7.1

**Comment by ryanhca** [comment]
I ran into this this evening. I globally installed `update-notifier` then I had to install the dep locally as well. Now `yarn start` won't build my project.

**Comment by tannerlinsley** [comment]
I'll cut a release tomorrow

**Comment by tannerlinsley** [comment]
Fixed in latest version

**Comment by rodrigopandini** [comment]
Same here. To works, I had to install `update-notifier` globally via npm first. yarn install globally seems not working in anyway.
So, run
`npm install -g update-notifier`
`npm install -g react-static // or yarn add global react-static`

**Comment by rohmanhm** [comment]
@rodrigopandini Try to update your `react-static` to the latest version. I think it's already fixed.
