### ISSUE TITLE
Possibly add react-require by default?

### ISSUE THREAD

**Issue by tj** [nozzle/react-static#547]
Any interest in having the react-require transform? Personally I find that `import React from 'react'` it gets pretty redundant in React-land but not a huge deal. Happy to send a PR if there's interest!

**Comment by tannerlinsley** [comment]
I’ve looked into this before for a few other projects but I think I’m
sticking with keeping it how it is. If you wanted to contribute an example
that integrates this at the config level, then that would be cool.

**Comment by tj** [comment]
Cool fair enough! I'll close
