### ISSUE TITLE
Lazy load routeData on hydrate

### ISSUE THREAD

**Issue by impaler** [nozzle/react-static#548]
Nice work on react-static, the api is fantastic.

In a common use case, a blog with a bunch of markdown content. Lets say we want to preprocess markdown to html and use it inside a React component with `dangerouslySetInnerHTML`. There does not seem to be a way to not have the content added twice to the static html files when using `getRoutes()` . Once in the actual html from the node rendered component and again in the `<script>window.__routeData={ // all the html again`.

Any way to lazy load this routeData? it seems kind of heavy to include the html content practically twice in the static build for the initial load.

**Comment by tannerlinsley** [comment]
As it stands right now, the HTML is double loaded to avoid a FOUC when
react mounts. If the HTML isn't immediately available, it would only
briefly show the static HTML before react mounts, which would then cause a
blank screen while loading. Then finally the HTML would appear again. It's
quite a process. The only other way to get around this is to use a markdown
webpack loader and manually import the HTML, which probably isn't what
you're wanting.

**Comment by impaler** [comment]
@tannerlinsley I see what you mean, thanks for the suggestion. Yeah thats not really, I guess the doubling up of the content is only a tradeoff for the initial render. Unless you were wanting to make it work with no-js ;)

Ideally though it should be possible include in the static html, route critical css to avoid a flash of unstyled content. I guess it depends on the project though and what magic the components are doing with in state.

**Comment by tannerlinsley** [comment]
Yeah. FOUC is the wrong acronym here. It's more like FONC or flash of no
content 😉
