### ISSUE TITLE
Generating dynamic meta data using Head from static-react seems broken

### ISSUE THREAD

**Issue by dancrisan** [nozzle/react-static#549]
I'm following the example implementation from here https://react-static.js.org/components/#head and I can't get the meta data to update once I go to a different page. Here is how my MetaData component looks like : 

<img width="640" alt="screen shot 2018-04-10 at 9 17 31 am" src="https://user-images.githubusercontent.com/2288335/38574064-b3b838ce-3cac-11e8-96cb-e4dadff6284d.png">

I'm using
- "react": "^16.0.0" 
- "react-dom": "^16.0.0"
- "react-hot-loader": "^4.0.0-beta.21" 
- "react-static": "^5.4.0"

I have 3 pages where I declare my component and the meta data values depending on the page 

<img width="781" alt="screen shot 2018-04-10 at 9 20 47 am" src="https://user-images.githubusercontent.com/2288335/38574294-5709391a-3cad-11e8-971b-76a0f414667e.png">

I can't see those meta datas in the "view source code" though, for example I would expect to see at least the title in there : 

<img width="363" alt="screen shot 2018-04-10 at 10 54 34 am" src="https://user-images.githubusercontent.com/2288335/38574458-b35ff226-3cad-11e8-97a5-c7fb85552234.png">

However what's strange is that if I'm under the root www.mywebiste.com, I'll be able to see the meta data properly. It just doesn't propagate correctly when I'm on the www.mywebsite.com/myblog page.

Let me know if you need more infos, 
Thanks! 
Dan

**Comment by tannerlinsley** [comment]
Just to verify, you are using the `Head` component, not `Helmet` correct? I realize you may have taken the screenshots above before you made that change? ;)

**Comment by samelliott89** [comment]
Hey guys, also seeing this issue. Any timeline for a fix?

**Comment by lukehaas** [comment]
Also seeing this.

**Comment by floringogianu** [comment]
Having the same issue.
