### ISSUE TITLE
Re-Add <meta charSet="UTF-8" /> ?

### ISSUE THREAD

**Issue by D1no** [nozzle/react-static#55]
https://github.com/nozzle/react-static/blob/755d9887c6772ab62751d1d389a06d41d6c75e1b/src/RootComponents.js#L8-L10

To fulfil browser encoding, we should probably keep the encoding standard in the root? Per https://github.com/nozzle/react-static/pull/47

**Comment by tannerlinsley** [comment]
Oops. Looks like I may have overwritten that. It's back now :)

**Comment by D1no** [comment]
😅👌
