### ISSUE TITLE
Fresh custom-routing template builds 404 content on non-home routes

### ISSUE THREAD

**Issue by ryangiglio** [nozzle/react-static#550]
Using `react-static@5.7.1`

When running `yarn build` on a freshly created `custom-routing` template project, all the pages except the home route are built with the 404 page content.

Steps to repro:
`yarn global add react-static` (and `yarn global add update-notifier` to work around #546)

`react-static create -n routing-test -t custom-routing`

`cd routing-test`

(`yarn add update-notifier` to work around #546 again)

`yarn build`

`yarn serve`

If you look in the `/dist` folder, the homepage index.html seem to build correctly, but the index files in `/blog`, `/about`, etc all have the 404 page's "404 - Oh no's! We couldn't find that page :(" content.

If you view the pages at `localhost:3000` and reload the site on any route other than the homepage, you can see the 404 content flash before the React kicks in and loads the actual content.

**Comment by tannerlinsley** [comment]
Fixed in latest version. Because of a recent change the `path` prop for each route needs to have the preceeding `/` removed to match. :)

**Comment by chardy** [comment]
I removed the preceeding / but still having 404 content flash before the React kicks in. I tried many combination, but flashing of 404 content always occurs.

Can show us sample of the static.config.js for this?

**Comment by FullstackJack** [comment]
I believe I have this same problem. Just discovered my PROD build has 404 static render for posts but looks fine when viewed. This is ruining SEO, the whole reason to use react-static. 😥
