### ISSUE TITLE
Undesirable scroll-to-top on page refresh

### ISSUE THREAD

**Issue by Cinamonas** [nozzle/react-static#551]
First of all, thanks for React-Static – it’s great 👏

There’s one undesirable effect, though:

If I scroll down the page and refresh it, after the refresh the page scrolls back to the top with an animation (this can be seen on [react-static.js.org](https://react-static.js.org/)). And I expect scroll position to stay exactly where it was before the refresh – that’s how it behaves on browsers out of the box.

I’m aware of [props that are available on `Router` component](https://github.com/nozzle/react-static/blob/5fe177934381da6a79e15d4c5d96ef5d77a6a35d/docs/components.md#router), but I was still not able to work around this behaviour:

- If I set `autoScrollToTop={false}`, I lose auto scroll-to-top when the site path changes. Interestingly, it does not fix the scroll-to-top on page refresh, which still happens with this prop off.
- If I set `autoScrollToHash={false}`, the issue disappears, but then I lose animated scroll to hash, which some of my pages use. So it seems that scroll to hash is triggered on page refresh and that makes the page scroll back to the top.

Do you agree that this should be fixed?

**Comment by Cinamonas** [comment]
@tannerlinsley, yes. That how I would approach this.

**Comment by tannerlinsley** [comment]
Would you be up to submitting a PR for this?

**Comment by Cinamonas** [comment]
@tannerlinsley, done ☝️
