### ISSUE TITLE
`Router` component catches and shows (to users/clients) errors in production

### ISSUE THREAD

**Issue by jasonlafferty** [nozzle/react-static#553]
The error print out appears to ship with the production build of `react-static`.
<img width="1263" alt="screen shot 2018-04-10 at 14 57 02" src="https://user-images.githubusercontent.com/10165683/38624494-18707756-3da0-11e8-967c-878253d18c7b.png">

Also as `react-static` is catching the errors they are not getting to the top of our app where caught errors in production are sent to Sentry (https://sentry.io/welcome/)

We have fixed this by catching errors before they bubble to the `react-static` `<Router/>` component, but would prefer to change the behaviour of `react-static`.

Version: v5.6.7
https://github.com/nozzle/react-static/blob/v5.6.7/src/client/components/Router.js

### Suggested solution
`ErrorCatch` component that in development wraps the `<ResolvedRouter />` with a component that has `componentDidCatch` and prints out the UI. And in production it just returns `this.props.children`, so it doesn't have component with a `componentDidCatch` method and the error can bubble to the `<App />`/top level component. 

If people want to maintain the existing behaviour, errors shown in production, maybe a prop on the `<ResolvedRouter />` component  like `showErrorsInProduction={true}` could be an option.

**Comment by tannerlinsley** [comment]
Sounds good to me. If you want to PR a fix that keeps them on in
development, but turns them off in production (with that prop to force them
on), then I’ll merge it :)

**Comment by jasonlafferty** [comment]
👍 sounds good will do
