### ISSUE TITLE
NetlifyCMS example login does not work

### ISSUE THREAD

**Issue by luchoster** [nozzle/react-static#558]
### Bug
When starting a new project with the NetlifyCMS template, and after enabling the Identity in Netlify, I get an email to accept the invitation for the CMS user.
So far so good, everything works up until this point.

### Issue

After getting the email, I get a link with an `invitation_token` that redirects me to the website so I can create a password for my user (ex. `https://example.netlify.com/#invite_token=AB1C123`), when I visit that link, nothing happens, I just get the home page.

### Environment

1.  `react-static -v`: 5.7.5
2.  `node -v`: 9.4.0
3.  `yarn --version or npm -v`: `yarn 1.5.1` `npm 5.7.1`
4.  Operating system: Ubuntu 17.10 / macOS 10.12
5.  Browser and version (if relevant): Chrome / any

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  Create new project or Click on the Launch to Netlify button
2.  Follow all the instructions and invite a new user
3.  After getting the email that "You've been invited to join ... ", click the 'Accept invite' link

### Expected Behavior

After getting the email and clicking the 'Accept Invitation' link, I should get redirected to the home page and it should pop up a modal with a password input, to create the user's pwd.

### [Reproducible Demo](https://github.com/luchoster/test-static.git)

**Comment by kevinmanncito** [comment]
Found a workaround that will get you logged into netlify cms. The link that gets sent to you in your email takes you to something like `site-name.netlify.com/#access_code=123ABC456` If you then change the url to `site-name.netlify.com/admin/#access_code=123ABC456` everything will work. It feels like to me there is something off with the script in the admin/index.html file. Still trying to find a solution.

**Comment by luchoster** [comment]
@kevinmanncito great find!!!
Yes that worked for me. But that's not normal behavior. I'll try to look into it a bit more too. Hopefully we can find the right solution.

Thanks again!

**Comment by runandrew** [comment]
I am running into the same problem. I believe it's due to the `index.html` not having the `netlify-identity` widget. I have been doing the workaround of manually changing `domain.com/#token` to `domain.com/admin#token`. I really dislike doing this because if I want a client to sign up for a new account, this is a very poor experience to change the URL's.

I'm currently looking on how to add the widget to the homepage. But I would love to hear if there is an alternative!

**Comment by cdock1029** [comment]
You could add the widget to `Document`  in `static.config.js`

```javascript
Document: class CustomHtml extends React.Component {
    render() {
      const { Html, Head, Body, children, renderMeta } = this.props
      return (
        <Html>
          <Head>
            <meta charSet="UTF-8" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <script
              src="https://identity.netlify.com/v1/netlify-identity-widget.js"
              defer
            />
          </Head>
          <Body>{children}</Body>
        </Html>
      )
    }
  },

```

**Comment by luchoster** [comment]
@cdock1029 Didn't think of that. I'll give it a shot, thanks.

**Comment by emzero** [comment]
Yes, workarounds are great. But please fix! It supposed to work out-of-the-box. 

If not, please remove the netlifycms template option when creating a new site!
