### ISSUE TITLE
 Cannot find module 'react-static-routes' on Windows

### ISSUE THREAD

**Issue by will-hart** [nozzle/react-static#56]
Using version react-static 1.4.1 on Windows 10, I get an error on `yarn build`. It doesn't occur on `yarn start`.

    D:\Code 
    λ react-static create
    
    ? What should we name this project? test-www
    ? Select a template below... styled-components
    => Creating new react-static project...
    => Installing dependencies...
    
    ...

    => [✓] Project "test-www" created: 41882.103ms

    => To get started:

    cd test-www

    yarn start - Start the development server
    yarn build - Build for production
    yarn serve - Test a production build locally

    D:\Code 
    λ cd test-www

    D:\Code\test-www  (react-static-starter@1.0.0)
    λ yarn build
    yarn build v1.0.0
    $ react-static build
    
    => Copying public directory...
    => [✓] Public directory copied: 1.851ms
    => Building Routes...
    => [✓] Routes Built: 97.737ms
    => Bundling App...
    => [✓] App Bundled: 3563.956ms
    => Exporting Routes...
    { Error: Cannot find module 'react-static-routes'
        at Function.Module._resolveFilename (module.js:527:15)
        at Function.Module._load (module.js:476:23)
        at Module.require (module.js:568:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (D:/Code/playbook-www/src/App.js:5:1)
        at Module._compile (module.js:624:30)
        at loader (D:\Code\playbook-www\node_modules\babel-register\lib\node.js:144:5)
        at Object.require.extensions.(anonymous function) [as .js] (D:\Code\playbook-www\node_modules\babel-register\lib\node.js:154:7)
        at Module.load (module.js:545:32)
        at tryModuleLoad (module.js:508:12) code: 'MODULE_NOT_FOUND' }
    error Command failed with exit code 1.

**Comment by corsek** [comment]
I have the same problem with react-static 1.4.1 on Windows 10

**Comment by tannerlinsley** [comment]
Unfortunately I don't have a windows machine to test this on currently, but the next release I'm working on has a whole new way of more reliably compiling those routes, so my guess is this will be fixed in the next release.

Stay tuned :)

**Comment by tannerlinsley** [comment]
This should be fixed in the latest version. Please test by upgrading both your global and local packages to version 2.0.0.

**Comment by DanWebb** [comment]
Just a note for others searching for this issue, this error will appear on build if you install react-static-routes as a dependency. Don't do `npm i -S react-static-routes`.
