### ISSUE TITLE
Navigating (via "back") to a page that isn't linked shows 404

### ISSUE THREAD

**Issue by Leeds-eBooks** [nozzle/react-static#569]
After refreshing a page, and then navigating to another page that has no link to it in the current page (e.g. by clicking the browser's "Back" button), we get a 404 instead of the desired page.

Discussed in Slack, @tannerlinsley said:

>Because there was no link to the parent page, the data and template was not prefetched.
>which uncovers a bug in react-static
>if a page is navigated to without being preloaded first, then navigation should be suspended until the page is ready to be rendered

### Environment

1.  `react-static -v`: 5.7.3
2.  `node -v`: 9.8.0
3.  `yarn --version or npm -v`: 1.6.0
4.  Operating system: macOS
5.  Browser and version (if relevant): Firefox 59

### Steps to Reproduce the problem

1. Go to https://www.arcpublications.co.uk/orbita/books/ (Everything under the "orbita" path is created using react-static)
2. Click on one of the round images.
3. Refresh the page.
4. Go back in your browser.

### Expected Behavior

The browser should navigate back to https://www.arcpublications.co.uk/orbita/books/

### Actual Behavior

We get 404.

### Reproducible Demo

https://github.com/leeds-ebooks/arc-orbita

### Workaround

This problem goes away if I do the following: https://github.com/Leeds-eBooks/arc-orbita/commit/9e68f56ee394cf0423a7b0024c261f3e819f5e9a#diff-f0454bdda20786a7a4b1227a92417b8d

**Comment by abroccoli** [comment]
+1

This issue also presents itself when attempting to do redirects. When no link is added to preload the page that will be redirected to, redirects will show the 404 page until the page is refreshed.

This can be avoided with the workaround that Leeds-ebooks posted, make Links to that pages that could be redirected to and don't provide anything for the user to actually click on and navigate to that page.

```
<div>
   <Link to={`/rfi/oops`}/>
   <Link to={`/rfi/thankyou`}/>
   <Link to={`/rfi/additional`}/>
   <Link to={`/rfi/review`}/>
</div>
```

**Comment by danilobuerger** [comment]
Not stale, reproducible with v6.

**Comment by tannerlinsley** [comment]
One idea is to add a minimum latency to all router actions that are local
to the site. In that latency we can just double check for the existence of
a routeInfo.json. If we find one, we can load it up and be good to go, if
we don’t, then we can just let the router play it’s course. Thoughts?

**Comment by benedfit** [comment]
Can also replicate
