### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by kations** [nozzle/react-static#579]
Local build works, its just the Basic example deployed over git to netlify.

I got the following error:

8:32:00 PM:   Error: /opt/build/repo/static.config.js:1
8:32:00 PM:   (function (exports, require, module, __filename, __dirname) { import axios fro  m 'axios';
8:32:00 PM:                                                                 ^^^^^^
8:32:00 PM:   SyntaxError: Unexpected token import
8:32:00 PM:   
8:32:00 PM:   - vm.js:80 createScript
8:32:01 PM:     vm.js:80:10
8:32:01 PM:   
8:32:01 PM:   - vm.js:139 Object.runInThisContext
8:32:01 PM:     vm.js:139:10
8:32:01 PM:   
8:32:01 PM:   - module.js:616 Module._compile
8:32:01 PM:     module.js:616:28

Any ideas?

**Comment by tannerlinsley** [comment]
Double check your .babelrc is in tact

**Comment by thislogancall** [comment]
@kations Were you able to resolve this? I'm getting something similar after upgrading to react-static 5.8.2, from 5.6.1. `yarn start` works just fine, only get the error when running `yarn build`

**Comment by luisfuertes** [comment]
I have tried to add `"presets": ["env", "react", "stage-0"]`to my `.babelrc` but i cant build my project. `yarn start` works fine, but on `yarn run build`:
![captura de pantalla 2018-07-17 a las 14 02 58](https://user-images.githubusercontent.com/18212615/42816202-57a7809c-89ca-11e8-935e-458a99ec0f89.png)
