### ISSUE TITLE
Managing i18n

### ISSUE THREAD

**Issue by coisnepe** [nozzle/react-static#58]
How would you recommend dealing with i18n?

**Comment by D1no** [comment]
Same question. The only real solution seems to have a yourdomain.com/en/something structure.

**Comment by derekperkins** [comment]
You should still be able to use something like https://github.com/yahoo/react-intl, and source the translations either from your bundle or from an external file that you load at runtime when your component mounts.

If you're talking about statically rendering i18n pages, they'll have to have their own route, like @D1no mentioned.

Does that answer your question?

**Comment by tannerlinsley** [comment]
This is all really great. There really isn't anything special about using an i18n solution in react-static other than what @derekperkins mentioned: your site will be exported in whatever the default language is unless you build in internationalization paths. Theoretically, you could easily export every single language you support by defining your paths once per language. This could multiply out quickly, but it's possible :)

**Comment by sapjax** [comment]
@derekperkins If handle i18n in front-end, seems it's not good for SEO ?

**Comment by rohmanhm** [comment]
@tannerlinsley  Do you mind to add template/example for using i18n in `react-static`?
I think it will be nice. 😃

**Comment by likethemammal** [comment]
I'd love to see the suggested way to handle the `locales` directory, and maybe show integration with a translation API to handle multiple locales.

Would also like to see the code to integrate with SSR specifically. Gatsby has a great article walking through their setup: https://www.gatsbyjs.org/blog/2017-10-17-building-i18n-with-gatsby/
