### ISSUE TITLE
Error when loading fonts with webfontloader and ES6 modules

### ISSUE THREAD

**Issue by EE2dev** [nozzle/react-static#584]
Hi,

I have the same issue as https://github.com/nozzle/react-static/issues/116, however the solution doesn't work since I am using ES6 modules not commonJS.

In particular:
I am trying to use webfontloader to load async my google fonts:

```
import { Webfont } from "webfontloader";

	function animate(myText){
		WebFont.load({
			google: { families: ["Indie Flower"]},
			fontactive: function(familyName, fvd){ //This is called once font has been rendered in browser
				display(myText);
			},
		});
	}
```
When I build it with npm, it shows the error message: `ReferenceError: window is not defined`
Any help would be greatly appreciated, thank you in advance!

**Comment by tannerlinsley** [comment]
https://react-static.js.org/docs/concepts#writing-universal-node-safe-code 

You must write node-safe code.

**Comment by EE2dev** [comment]
The window object doesn’t come from my code but from the webfonloader. When I build it for Rollup the error occurs. 

Is your suggestion to adjust the code in webfontloader ? Because in my build the import es6 statements come first and are hoisted, so I cannot add a condition before.

**Comment by Vadorequest** [comment]
@EE2dev You cannot use `import` but you can use `require` to conditionally import if window exists.

But I agree it's an issue for universal apps, but it's something to report to webfontloader directly.

**Comment by Vadorequest** [comment]
See https://github.com/typekit/webfontloader/issues/383
