### ISSUE TITLE
Usage of `webpack.EnvironmentPlugin` is too aggressive

### ISSUE THREAD

**Issue by knpwrs** [nozzle/react-static#585]
### Are you reporting a bug?

Yes.

### Environment

1.  `react-static -v`: unknown option -v
2.  `node -v`: v9.9.0
3.  `yarn --version or npm -v`: npm 6.0.0
4.  Operating system: macOS 10.13.4
5.  Browser and version (if relevant):

### Steps to Reproduce the problem

I am referring to this line: https://github.com/nozzle/react-static/blob/6150e22262dd321b65069bd5d4071fbe855b95bd/src/static/webpack/webpack.config.dev.js#L44

That configuration is far too aggressive. There came a point in my development I needed to supply custom logic to override an environment variable and I erroneously put my instance of `DefinePlugin` after the default instance of `EnvironmentPlugin`, causing the value to be set before my custom value can be injected. While there are workarounds (e.g., override `process.env.{VAR}` directly) I would argue that the configuration is too aggressive to begin with.

### Expected Behavior

`react-static`, as a tool, should only explicitly inject the environment variables it specifically cares about. This will make it easier for users to extend the configuration with their own plugin instances and can even prevent other potential bugs.

**Comment by tannerlinsley** [comment]
So if you wanted to add your own environment variable to your app, how would that look? Currently, all you have to do is assign it to `process.env`.

**Comment by knpwrs** [comment]
You would set up another instance of `webpack.DefinePlugin` or `webpack.EnvironmentPlugin`. The issue I was running into was that this framework's instance of `webpack.EnvironmentPlugin` was inlining a particular variable before my plugin stance was able to.

There's a _potential_ (albeit unlikely) scenario with the current configuration where an environment variable which was not supposed to be made public can end up in a public build as well. This would be a secondary concern.

**Comment by lottamus** [comment]
Why add another instance of `webpack.EnvironmentPlugin`? 

Just override the one thats already there:

```
  for (const index in config.plugins) {
    if (config.plugins[index] instanceof webpack.EnvironmentPlugin) {
      config.plugins[index] = new webpack.EnvironmentPlugin({
        ...config.plugins[index].defaultValues,
        NODE_ENV: 'production',
      });
    }
  }
```
