### ISSUE TITLE
Sass example cannot be built

### ISSUE THREAD

**Issue by Reggino** [nozzle/react-static#588]
### Environment

1.  `react-static -v`: 5.8.2+
2.  `node -v`: n.a.
3.  `yarn --version or npm -v`: n.a.
4.  Operating system: n.a.

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1. `cd examples/sass`
2. `npm run build`

### Expected Behavior

A successfull build

### Actual behaviour

```
ERROR in <path to>.scss
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.pitch ( <path to project>/node_modules/extract-text-webpack-plugin/dist/loader.js:57:11)
 @ ./dist/react-static-routes.js
 @ ./src/App.tsx
 @ ./src/index.tsx


```

**Comment by huygn** [comment]
I got same issue with both sass & tailwindcss example

**Comment by mkamuiru** [comment]
I got the same issue and I found some forums talking about replacing "extract-text-webpack-plugin" with "MiniCssExtractPlugin". Any thoughts on how to incorporate this?

https://github.com/webpack-contrib/mini-css-extract-plugin

**Comment by j4p3** [comment]
Chiming in to confirm that the `sass` template does not build with:

```
react-static v5.9.1
npm v5.6.0
node v9.10.0
extract-text-webpack-plugin v3.0.2
node-sass v4.9.0
sass-loader v7.0.1
```

I don't have enough visibility into what `react-static` is doing with the `webpack` config function to diagnose why this isn't working.

**Comment by JustFly1984** [comment]
The issue is with refactored webpack.config.js and exactly with isNode
variable. Please roll back to 5.8.1 - this is last version which is not
affected by webpack.config.js refactoring

2018-05-04 3:59 GMT+08:00 JP <notifications@github.com>:

**Comment by kgcreative** [comment]
adding:
```
config.plugins.push(new ExtractTextPlugin('styles.css'))
```
as the last line in the `  webpack: (config, { defaultLoaders, stage }) => {` entry, right before `return config` worked for me.

**Comment by Pixelatex** [comment]
@kgcreative that indeed fixed it for me! thanks

**Comment by maplethorpej** [comment]
@kgcreative's fix works, but I had to install the package first and then import it: `import ExtractTextPlugin from 'extract-text-webpack-plugin'`
