### ISSUE TITLE
Question: How to best handle images in css?

### ISSUE THREAD

**Issue by nechmads** [nozzle/react-static#59]
What's the best practice of importing and using images, especially when you want to use them as background images of elements.
For example:
If I use CSS in JS or Glamorous and point the url to an image under src folder, this image is never copied to dest and in such ends up with 404.

I know I can just put all images in the public folder, but it this the best way?

**Comment by nechmads** [comment]
Follow up question:
When I import a svg file everything works fine in development, but when trying to run build, the process fails with errors trying to parse the svg file.

**Comment by tannerlinsley** [comment]
Working on a fix for this in the next release. Stay tuned.

**Comment by nechmads** [comment]
Thanks!! Really looking forward. Re-builfing our website and prefer to do it with React-Static instead of Gatsby.

**Comment by tannerlinsley** [comment]
There is now import support for imagesm Fixed with the latest version. `yarn upgrade react-static@2`
