### ISSUE TITLE
Serve assets from its own location

### ISSUE THREAD

**Issue by ricardomccerqueira** [nozzle/react-static#591]
### Are you reporting a bug?
"No"

### Is this a feature request?
"Yes"

I'd like to be able to separate assets from my views.
Ideally, I want the site to be in its domain and my assets on a CDN, something like this:

www.website.com/page/index.html
assets.website.com/timestamp/{assets go in here}

What I would probably do, is have 2 configurable things:

**REACT_STATIC_ASSET_PATH**
If it exists, instead of putting assets on the root, with would put them on a folder:

`REACT_STATIC_ASSET_PATH='/assets'` would result in this:
www.website.com/page/assets/{css-js-imgs-in-here}

**REACT_STATIC_ASSET_URL**
if it exists, it would make the references to the asset be absolute, to this url.

`REACT_STATIC_ASSET_PATH='/assets'`
`REACT_STATIC_ASSET_URL='https://assets.website.com'`

 would result on this:
assets.website.com/page/assets/{css-js-imgs-in-here}

**Comment by tannerlinsley** [comment]
This could be interesting and cool, but would be a pretty involved change I think. With that said, feel free to mock this up, but proceed with caution. Not sure how much work this would be or if it will end up making it in, but I'd like to be convinced :)

**Comment by ricardomccerqueira** [comment]
Will do :) serving assets from our CDN is quite an important thing for us here at uSwitch, so will put good effort into making this the best way possible.

I'll have time for this next week, and will ping you guys on slack to make sure I stay on the right track.

**Comment by lottamus** [comment]
I've got an open PR for this already if you want to check it out: https://github.com/nozzle/react-static/pull/602

Right now it supports relative asset paths. It won't be too much more work to add support for absolute paths
