### ISSUE TITLE
Can process.env.REACT_STATIC_ENV ever be 'node'?

### ISSUE THREAD

**Issue by knpwrs** [nozzle/react-static#600]
According to [this page](https://github.com/nozzle/react-static/blob/b6d1fd5d5c40005425ca95cfb6c203b2eadd31fc/docs/concepts.md#environment-variables) `process.env.REACT_STATIC_ENV` is set to `'node'` when being built for SSR; however, for me it is set to `'production'` when building for SSR (when running `npm run build`). This is causing my check of that variable to fail. I did a quick search across the codebase and I can't find anywhere that variable is set to anything other than `'production'` or `'development'`. Am I missing something?

### Are you reporting a bug?

Yes

### Environment

1.  `react-static -v`: unknown option `-v`
2.  `node -v`: v9.9.0
3.  `yarn --version or npm -v`: npm v6.0.0
4.  Operating system: macOS 10.13.4

**Comment by tannerlinsley** [comment]
You are correct. The client will either be in production or development. In
the config there is use of a stage variable that can be node though.
