### ISSUE TITLE
Warning: getDefaultProps is only used on classic React.createClass definitions

### ISSUE THREAD

**Issue by 0x80** [nozzle/react-static#607]
During the build phase there are a lot of errors. They do not seem to be real errors since the build still finishes and I can serve the files.

> Error: Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named   `defaultProps` instead.

I've tried to figure out where they come from with `grep -rnwl './node_modules' -e 'getDefaultProps'` but I didn't find it yet. 

### Environment

1.  `react-static -v`:  error: unknown option `-v'
2.  `node -v`: v9.11.1
3.  `yarn --version or npm -v`: 1.6.0
4.  Operating system: MacOS 10.13.4

### Steps to Reproduce the problem

1.  run create using less-antdesign template
2.  run `yarn build`

**Comment by tannerlinsley** [comment]
React static does not use the deprecated createClass utility. Not sure
where this is coming from, but it's not React Static. I would suggest
commenting out or removing dependencies until the error no longer displays
to find the culprit.

**Comment by 0x80** [comment]
@tannerlinsley Aren't the examples supposed to build without errors / warnings? It doesn't give a very nice impression to newcomers. 

If boilerplates do not have official support maybe consider making them external (like Gatsby uses a Github url for its CLI), so it's clear they are not the responsibility of react-static.

**Comment by tannerlinsley** [comment]
Absolutely. They are the responsibly of react static. If you are
experiencing this bug on a clean install then we need to know what template
you are using or be able to look at your repo/codr for reproduction. To our
knowledge and tests, we have never seen this problem, so the better you can
help us reproduce it, the faster we can solve the issue.

**Comment by 0x80** [comment]
This is on a clean install. The steps to reproduce are as I reported them above. 

And `react-static -v` gives an error, but --version tells me 5.9.1
