### ISSUE TITLE
IE11 Blank Page

### ISSUE THREAD

**Issue by Ericky14** [nozzle/react-static#611]
When running ```react-static start``` and using IE11, all I get is a blank page with no console errors. If I use ```react-static build```, it seems to work.

I believe this to be an issue with dev mode not being transpiled to ES5. If this is indeed the issue, is there any way to run dev while transpiling to ES5?

**Comment by tannerlinsley** [comment]
Are you seeing any errors in the console?
Do you have a `.babelrc` file in your project root that points to react-statics preset?
Have you tried installing and importing `babel-polyfill`?

**Comment by Ericky14** [comment]
There are no errors in the console.
I do have a ```.babelrc``` that extends the one from react-static.
I also have tried installing and importing ```babel-polyfill```.
Not sure what else to try at this point.

**Comment by Ericky14** [comment]
This was apparently an error with one or more of the many dependencies in my project.
I fixed it by adding the BabelEnginePlugin to webpack.

**Comment by abonventre** [comment]
@Ericky14 How did you add BabelEnginePlugin?  I am struggling to get this implementation to work.  Any guidance to how you did so would be greatly appreciated.  I tried importing polyfill as well and did not have any luck either.

**Comment by Ericky14** [comment]
@abonventre 
This is what I have on my static.config for webpack config.
```
    webpack: (config, args) => {
        config.plugins.push(
            new BabelEnginePlugin(
                {
                    presets: ['env', 'stage-0'],
                    plugins: [
                        'transform-decorators-legacy',
                        'babel-plugin-styled-components'
                    ]
                },
                {
                    verbose: false
                }
            )
        );

        if (args.stage === 'prod') {
            for (var i = 0; i < config.plugins.length; i++) {
                let plugin = config.plugins[i];

                if (plugin.constructor.name === 'UglifyJsPlugin') {
                    config.plugins.splice(i, 1);

                    config.plugins.push(
                        new uglify({
                            uglifyOptions: {
                                mangle: false,
                                compress: {
                                    hoist_props: false
                                }
                            }
                        })
                    );
                }
            }

            config.entry = ['babel-polyfill', config.entry];
        } else if (args.stage === 'dev') {
            config.entry = ['babel-polyfill', ...config.entry];
        }

        return config;
    }
```
