### ISSUE TITLE
yarn build failed in windows

### ISSUE THREAD

**Issue by zjxpcyc** [nozzle/react-static#612]
### Are you reporting a bug?
Yes

### Environment

1.  `react-static -v`: 5.7.2
2.  `node -v`: v8.7.0
3.  `yarn --version or npm -v`: 1.1.0
4.  Operating system: windows 10 x64
5.  Browser and version (if relevant): chrome 63.0.3239.132 x64

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  react-static create an-project
2.  make a route as like /foo/:param
3.  yarn build 

Then, I got an error `E:\somepath\:param contains invalid WIN32 path characters.`

### Expected Behavior

Build successful

**Comment by rohmanhm** [comment]
Any code example how you make a route?

**Comment by rohmanhm** [comment]
Maybe this is a related issue https://github.com/nozzle/react-static/issues/206

**Comment by zjxpcyc** [comment]
@rohmanhm 
For example in `static.confg.js` 
```javascript
getRoutes: () => {
  return [
    {
      path: '/foo/:param',
      component: 'src/some/component',
    }
  ];
}
```

This route can run successfully in dev mode, but failed when build.
I try it in centos (linux), both mode can be successful. But got an 404 error when refresh page in product mode.

**Comment by tannerlinsley** [comment]
You cannot have statically-exported dynamic route paths in a static website. You can however, use the `<Route>` component to handle dynamic routes in your app at runtime, but these routes will not be statically exported unless a route that uses them is defined in the static.config.js

**Comment by zjxpcyc** [comment]
Ok, thanks!
