### ISSUE TITLE
Feature: Add option to only build static files and disable JS

### ISSUE THREAD

**Issue by insanetisane** [nozzle/react-static#618]
It would be great to have the option to not include the SPA on the client. This would give us some more options for the end user. While the client side routing is fast, it can sometimes use more bandwidth than necessary for the end user and possibly more memory which could be a problem for some devices.

Disabling the SPA could result in a better result for the end user in some cases.

**Comment by dan-dr** [comment]
Couldn't this be easily solved by simply not mounting the component and just exporting it from `src/index.js` ?

**Comment by tannerlinsley** [comment]
Not stale.

**Comment by tannerlinsley** [comment]
Not stale

**Comment by Pixelatex** [comment]
Not stale

**Comment by Dragomir-Ivanov** [comment]
Not stale

**Comment by tannerlinsley** [comment]
After some deep thinking on this subject, I don't think it's going to be possible to do this any time soon. Going to move this issue into the vault for now. We may revisit this in future breaking versions of React Static
