### ISSUE TITLE
Controlling the order of CSS loading when using Document

### ISSUE THREAD

**Issue by jamesplease** [nozzle/react-static#622]
### Is this a feature request?

The `Document` configuration option is really useful. I'm using it to load some vendor CSS.

However, this vendor CSS is loaded _after_ the site's CSS. This is the opposite of how most people load their CSS, I think: they load vendor things first, and then their application CSS. This is important because of the way that the prioritization works in CSS: rules that are loaded later take precedence over things that are loaded first when the specificity is the same.

A quick look suggested that there's no way to load the site's CSS after the custom CSS, which is why I'm opening this issue.

### Environment

1.  `react-static -v`: 5.9.5
2.  `node -v`: 10.1.0
3.  `yarn --version or npm -v`: 6.0.1
4.  Operating system: macOS

Thanks for reading!

**Comment by mrchief** [comment]
I just reported the same here: https://spectrum.chat/thread/a5a2d029-a5d4-4654-b85c-d89528714141

**Comment by BrianKopp** [comment]
Seconding this. Here is my Document from static-config.js.
  Document: ({ Html, Head, Body, children, siteData, renderMeta }) => (
    <Html>
      <Head>
		    <meta name="description" content="" />
		    <meta name="keywords" content="" />
		    <meta charSet="UTF-8"/>
		    <meta name="author" content="Brian Kopp"/>
		    <meta name="viewport" content="width=device-width, initial-scale=1"/>
		    <link type="text/css" rel="stylesheet" media="all" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,600i,700,700i"/>
		    <link type="text/css" rel="stylesheet" media="all" href="https://fonts.googleapis.com/css?family=Dosis:400,500,600,700,800"/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"/>
      </Head>
      <Body>
        {children}
       </Body>
    </Html>
  ),


And then here is my built Head.

<head>
    <link rel="preload" as="script" href="/bootstrap.f06a5a0c.js" />
    <link rel="preload" as="script" href="/templates/src/containers/Home.1babb5ac.js" />
    <link rel="preload" as="script" href="/main.623824a5.js" />
    <link rel="preload" as="style" href="/styles.743c69dc.css" />
    <link rel="stylesheet" href="/styles.743c69dc.css" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta charSet="UTF-8" />
    <meta name="author" content="Md. Junaid Khan Pathan" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link type="text/css" rel="stylesheet" media="all" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,600i,700,700i" />
    <link type="text/css" rel="stylesheet" media="all" href="https://fonts.googleapis.com/css?family=Dosis:400,500,600,700,800" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css" />
</head>



I'd be happy to submit a PR with an option to change this.

**Comment by tannerlinsley** [comment]
We'll look into some ways to control where your CSS gets placed. This will be challenging to design an API that makes sense though... Any suggestions?

**Comment by jamesplease** [comment]
The simplest solution is to just reverse the order of the CSS loading, as a breaking change. The current loading order should not be the default, in my opniion.

Then, it is less of an issue to design an API to support modifying the order, as very few developers will want it another way.

**Comment by tannerlinsley** [comment]
Would you like to PR that change?

**Comment by jamesplease** [comment]
Sure thing, @tannerlinsley !

**Comment by jamesplease** [comment]
Huh. Look at that. This has already been changed in the latest version. But maybe you knew that @tannerlinsley and just wanted me to look at my CSS more closely 😝 

Since I can't reproduce this, I'm going to close it out for now. But it's early AM on a Saturday, and I may be missing something, so if someone else can reproduce it, just let me know and I'll reopen this.

Thanks all!

**Comment by BrianKopp** [comment]
Which latest version are you checking? I'm running the current npm react-static@next which is 6.0.0-beta.14, and it is still putting my app css before my head included css (for me, it's Materialize). So the Materialize css is overriding my app css, when it should be the other way around.

**Comment by jamesplease** [comment]
I'm using v5.9.7.

**Comment by mrchief** [comment]
5.9.7 has this issue. I can confirm that.

**Comment by jamesplease** [comment]
Weird, I wasn’t able to reproduce. Maybe I changed something in my site to get around it? I forget...

If anyone has a link to a repo that reproduces this, I’d be happy to take a look.

**Comment by mrchief** [comment]
It’s easy - just start a new project using the react-static generator and use the code snippet I posted in my top comment.

**Comment by BrianKopp** [comment]
Here is a repo I put together to reproduce. react-static create basic, update static.config.js, and then npm run build. Notice dist/index.html has cloudflare CSS **after** CSS created e.g. in app.css.

[https://github.com/BrianKopp/reactstaticissue622](url)

**Comment by BrianKopp** [comment]
I've got a PR prepared to fix this issue. Put a thread over on Spectrum asking how and when you all would like a PR submitted. Thanks!
