### ISSUE TITLE
How do you make examples installable?

### ISSUE THREAD

**Issue by KyleAMathews** [nozzle/react-static#624]
BTW, quick question. We're looking into making our Gatsby examples installable from the CLI and noticed react-static does this (very nicely!). Was curious how you do that — is it possible to pull a sub-tree of a git repo? Our starters are separate repos to make it easy to do a shallow clone.

**Comment by tannerlinsley** [comment]
Unfortunately, all of the react-static examples are packaged with the repo to NPM for now 😢. However, we still support installation of non-packaged templates through some handy git-cloning! I assume that is the code you'll want to see 😄: https://github.com/nozzle/react-static/blob/master/src/commands/create.js#L150-L167.

There's some good nuggets in there for other stuff too, like using local directories as starting templates too.  Hope that helps!?

**Comment by KyleAMathews** [comment]
Ah ok :-) I was wondering if you'd figured out something special :-D

We do something similar for `gatsby new` — https://github.com/gatsbyjs/gatsby/blob/07ea26c978001e0825195d5e2320d85eb79dd337/packages/gatsby-cli/src/init-starter.js#L125-L127

We've done some brainstorming how to automatically copy out example/starter code from the monorepo to their own repos here https://github.com/gatsbyjs/gatsby/issues/1545

Thanks!

**Comment by tannerlinsley** [comment]
No problem! Honestly, what this reminded me of is my hope and prayer that Netlify will someday support sub-directory locations for their "Deploy to Netlify" button. Currently you can only use repo roots 😞.
