### ISSUE TITLE
Head Meta Not Rendering In Static PROD or STAGING Build

### ISSUE THREAD

**Issue by FullstackJack** [nozzle/react-static#625]
Hi,

I'm including a `SocialMeta` component in my `Post` container to wrap up a bunch of meta tags into a dumb component, this works properly in `development` build, meta gets updated when I navigate to the page. When the `yarn build` or `yarn stage` command gets run, the post meta data is completely missing. This is not good for obvious reasons including social shares.

Using latest `react-static` @ `5.9.7`.

__SocialMeta.js__
```
import React from 'react';
import { Head } from 'react-static';

export default ({
  author,
  description,
  publishedAt,
  siteName,
  title,
  url,
}) => (
  <Head>
    <title>{`${title} | ${siteName}`}</title>
    {description && <meta name="description" content={description} />}
    {author && <meta property="article:author" content={author} />}
    {description && <meta property="og:description" content={description} />}
    {siteName && <meta property="og:site_name" content={siteName} />}
    <meta property="og:type" content="article" />
    <meta property="og:title" content={title} />
    <meta property="article:published_time" content={publishedAt} />
    {url && <meta property="og:url" content={url} />}
  </Head>
);
```

__static.config.js__
``` 
 renderToHtml: async (render, Comp, meta) => {
    const html = render(<Comp />);
    const { css } = renderStaticOptimized(() => html);
    meta.glamStyles = css;
    return html;
  },
  Document: class CustomDocument extends Component {
    render () {
      const {
        Html,
        Head,
        Body,
        children,
        renderMeta,
      } = this.props;
      return (
        <Html>
          <Head>
            <meta charSet="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <style dangerouslySetInnerHTML={{ __html: renderMeta.glamStyles }} />
            <link rel="stylesheet" href="/vendor/highlight/styles/atom-one-dark.css" />
            <script src="/vendor/highlight/highlight.pack.js" />
          </Head>
          <Body>
            {children}
            <div id="modal-root" />
          </Body>
        </Html>
      );
    }
  },
```

**Comment by FullstackJack** [comment]
This is bizarre to say the least, when I create a new glamorous react-static project, I can render static meta data from Post. I'll need to keep investigating, I have no idea where this bug would manifest itself. Why would React Helmet not render the meta tags in the static render...?

**Comment by FullstackJack** [comment]
It looks like the static render is rendering a 404 page but it's getting immediately replaced with the blog article so it doesn't get any of the static HTML. Could this have anything to do with siteRoot? I set the siteRoot and stageSiteRoot because the console was complaining about it, but it seems buggy.

**Comment by FullstackJack** [comment]
That was a son of a gun to track down, but it was because of a line of code that referenced `window`. I should have known.

```
const hljs = window.hljs
```
It totally failed silently though. Ugh.

**Comment by blakeperdue** [comment]
@FullstackJack glad you figured it out. It's not clear to me exactly how you're using a custom `Head` component within a route. Do you mind posting a full example as I'm stuck figuring out how to add custom, dynamic meta tags for dynamic routes (think blog posts that are pulled from an API). Would really appreciate a little guidance! Thanks.
