### ISSUE TITLE
Sitemap does not include slash between siteRoot and routes when disableRoutePrefixing is true

### ISSUE THREAD

**Issue by rachel-church** [nozzle/react-static#626]
### Are you reporting a bug?
Yes

### Environment

1.  `react-static -v`: 5.9.7
2.  `node -v`: v8.9.4
3.  `yarn --version`: 1.5.1
4.  Operating system: Mac High Sierra

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**
(Using the 'basic' example template)
1.  Add a `siteRoot` to static.config.js with or without a trailing slash
2. Add `disableRoutePrefixing: true,` to `static.config.js`
3. Ensure there are one or more routes
4. Update `package.json` to have `"react-static": "^5.9.7"` and update dependencies
5. Run `yarn build` and then look at the resulting `sitemap.xml`

### Expected Behavior
`sitemap.xml` should include `<loc>{siteRoot}/404/</loc>`

### Actual Behavior
`sitemap.xml` includes `<loc>{siteRoot}404/</loc>` (Without slash between the root and route)

**Comment by rachel-church** [comment]
The latest version of react-static has some updates to how sitemaps are created. This issue may or may not have been fixed as a side effect. It would probably be a good idea to have some unit tests to validate

**Comment by tannerlinsley** [comment]
Would you be willing to help out on those?
