### ISSUE TITLE
is404 route does not reive props from getData function

### ISSUE THREAD

**Issue by davidpfahler** [nozzle/react-static#628]
**Update**: This bug only occurs in dev, i.e. running `npm start`, not in production, i.e. running `npm run stage` / `npm run build`.

---

### Are you reporting a bug?

Yes, as described in https://spectrum.chat/thread/75c9b9b7-3e58-4cf8-8363-e49c0b9a795a, the getData function should be called and props be provided to the component, bug it isn't / they aren't. 

### Environment

1.  `react-static -v`: unkown option '-v' (but it's 5.9.7)
2.  `node -v`: v10.1.0
3.  `yarn --version or npm -v`: npm 6.1.0
4.  Operating system: macOS High Sierra 10.13.4

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  add a route to your routes with `is404: true` and a `getData` function which retuns an object with some properties
2.  use `RouteData` component in your 404 component
3.  `props` will be an empty object in your 404 component

### Expected Behavior

`props` should have the data provided by `getData`

**Comment by pscanf** [comment]
I found the same bug, even when using `path: "404"` instead of `is404`.

**Comment by tannerlinsley** [comment]
Looking into it now.

**Comment by pscanf** [comment]
Ok, my bad. I realised I hadn't wrapped the 404 component in `withRouteData` 🤦‍♂️ .  Wrapping it of course works. It might not be the case for @davidpfahler though.

Sorry for the incorrect report.

**Comment by tannerlinsley** [comment]
`is404` will be deprecated in version 6. Just use `path: '404'`.

**Comment by ostrebler** [comment]
It works with `withRouteData` HOC but still not with the RouteData component.
