### ISSUE TITLE
Getting Build time Error, Reference Error: Element is not defined

### ISSUE THREAD

**Issue by brahmaforces** [nozzle/react-static#629]
brahmaforces@brahmaforces:~/websites/test-site$ react-static build --staging --debug
DEBUG - Resolved static.config.js:
{ entry: '/home/brahmaforces/websites/test-site/src/index.js',
  getSiteData: [Function: getSiteData],
  renderToHtml: [Function: renderToHtml],
  prefetchRate: 3,
  disableRouteInfoWarning: false,
  disableRoutePrefixing: false,
  outputFileRate: 10,
  getRoutes: [Function],
  paths: 
   { ROOT: '/home/brahmaforces/websites/test-site',
     LOCAL_NODE_MODULES: '/home/brahmaforces/.nvm/versions/node/v8.9.4/lib/node_modules/react-static/node_modules',
     SRC: '/home/brahmaforces/websites/test-site/src',
     DIST: '/home/brahmaforces/websites/test-site/dist',
     PUBLIC: '/home/brahmaforces/websites/test-site/public',
     NODE_MODULES: '/home/brahmaforces/websites/test-site/node_modules',
     PACKAGE: '/home/brahmaforces/websites/test-site/package.json',
     HTML_TEMPLATE: '/home/brahmaforces/websites/test-site/dist/index.html',
     STATIC_DATA: '/home/brahmaforces/websites/test-site/dist/staticData' },
  siteRoot: '',
  stagingSiteRoot: '',
  basePath: '',
  stagingBasePath: '',
  devBasePath: '',
  extractCssChunks: false,
  inlineCss: false }

=> Info: No 'siteRoot' is defined in 'static.config.js'. This is suggested for absolute url's and a sitemap.xml to be automatically generated.

=> Copying public directory...
=> [✓] Public directory copied: 15.434ms
=> Building Routes...
=> [✓] Routes Built: 16.497ms
=> Bundling App...
=> [✓] App Bundled: 37073.420ms
=> Fetching Site Data...
=> [✓] Site Data Downloaded: 0.173ms
=> Fetching Route Data...
=> [========] 8/8 100% 8000/s 0.0s 
=> [✓] Route Data Downloaded: 5.298ms
=> Exporting Route Data...
=> [✓] Route Data Exported: 1.051ms

  ReferenceError: Element is not defined
  
  - uikit.js:432 
    [test-site]/[uikit]/dist/js/uikit.js:432:19
  
  - uikit.js:4 ref
    [test-site]/[uikit]/dist/js/uikit.js:4:85
  
  - uikit.js:7 Object.<anonymous>
    [test-site]/[uikit]/dist/js/uikit.js:7:2
  
  - module.js:643 Module._compile
    module.js:643:30
  
  - module.js:654 Module._extensions..js
    module.js:654:10
  
  - node.js:152 Object.require.extensions.(anonymous function) [as .js]
    [lib]/[react-static]/[babel-register]/lib/node.js:152:7
  
  - module.js:556 Module.load
    module.js:556:32
  
  - module.js:499 tryModuleLoad
    module.js:499:12
  
  - module.js:491 Function.Module._load
    module.js:491:3
  
  - module.js:587 Module.require
    module.js:587:17

### Environment

1.  `react-static -v`:
2.  `node -v`:
3.  `yarn --version or npm -v`:
4.  Operating system:
5.  Browser and version (if relevant):

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  ...
2.  ...
3.  ...

**Comment by tannerlinsley** [comment]
This is likely an issue with `uikit` relying on `document` or `window` during SSR. Try guarding the import with a `typeof document !== 'undefined'` condition.

https://react-static.js.org/docs/concepts/#writing-universal-node-safe-code
