### ISSUE TITLE
Build process always breaks on SVG files

### ISSUE THREAD

**Issue by nechmads** [nozzle/react-static#63]
Hi.
Whenever I add a SVG file to the project (under the src folder or outside of it) and try to build, the build process fails while trying to parse the SVG XML.

I tried to config WebPack with the file-loader using the WebConfigurator but I'm still getting the same result.

Worth mentioning that in development time everything seems to work fine. I can @import the SVG into a javascript file and display it using an IMG tag.

Anyone knows what configuration/setting I'm missing here?

**Comment by tannerlinsley** [comment]
We're working on a fix for this. Hang tight :)

**Comment by tannerlinsley** [comment]
Fixed with the latest version. `yarn upgrade react-static@2`
