### ISSUE TITLE
[feature] noindex on parent but not on children

### ISSUE THREAD

**Issue by dan-dr** [nozzle/react-static#638]
If I define a route defined as such:
```javascript
      {
        path: '/articles',
        children: articles
          .map(article => ({
            path: `/${article.slug.current}`,
            component: 'src/containers/Article',
            getData: () => ({ article, showComments: true }),
          })),
      },
```

The problem is that in the sitemap, i have an entry for `/articles` as well as for each article.
If I use `noindex: true` on the parent, both it and it's children won't get indexed, no matter if I `noindex: false` on the children.

Is there a way that i'm not aware of to index only the children?

**Comment by benedfit** [comment]
You could use the `Head` component (https://github.com/nozzle/react-static/blob/master/docs/components.md#head) and add a robots meta tag yourself (https://developers.google.com/search/reference/robots_meta_tag)

The page in question would still appear in the sitemap.xml, but Google would ignore it
