### ISSUE TITLE
Sass support?

### ISSUE THREAD

**Issue by alexiscordova** [nozzle/react-static#64]
Most likely related to #24, but I'm running into an error when trying to import Sass (.scss) files in react-static. I'm attempting to modify the built-in webpack config, per the docs, with the following:

```js
webpack: webpackConfigurator => {
    webpackConfigurator.merge({
      module: {
        rules: [
          {
            test: /\.scss/,
            use: ExtractTextPlugin.extract({
              fallback: 'style-loader',
              use: [
                {
                  loader: 'css-loader',
                  options: {
                    minimize: true,
                    importLoaders: 1
                  }
                },
                {
                  loader: 'sass-loader'
                }
              ]
            })
          }
        ]
      },
      plugins: [
        new ExtractTextPlugin({
          filename: 'public/[name].css',
          disable: process.env.NODE_ENV === 'development'
        })
      ]
    })
  }
```

In App.js, I have a single line of `import './style.scss'` which has some nested Sass, for testing purposes.

However, when running `react-static start`, I receive the following error:
```
Module not found: Can't resolve 'sass-loader' in '/usr/local/lib/node_modules/react-static/dist/node_modules'
```

I'm looking to have a "global" Sass file for shared styling, and have the ability to import Sass files at the component level.

**Comment by D1no** [comment]
Put this at the top of your static.config.js: https://github.com/nozzle/react-static/issues/24#issuecomment-337013966

**Comment by alexiscordova** [comment]
@D1no No dice, still get the same error.

**Comment by D1no** [comment]
I'll share my `static.config.js`. You need to replace the less loader stuff with sass.

```bash
yarn add --dev autoprefixer extract-text-webpack-plugin less less-loader postcss-import postcss-loader
```

`static.config.js`
```js
import React, { Component } from 'react'
import { ServerStyleSheet } from 'styled-components'

// *******************************************************************
require("babel-register");

// Don't pre-process these extensions
const ignoreExtInBabelPreProcess = [
  '.css',
  '.scss',
  '.sass',
  '.pcss',
  '.stylus',
  '.styl',
  '.less',
  '.sss',
  '.gif',
  '.jpeg',
  '.jpg',
  '.png',
  '.svg',
  '.mp4',
  '.webm',
  '.ogv',
  '.ts',
  '.tsx',
];

// Collect all preview handler incase we want to change this later via
// registerBabelIgnoreExtHandlers([".someOtherExt"]);
let prevExtensionHandler = {};

// Our null handler to be assigned to required/imported files in the code
// that meets our ignore list
function newNullReturnHandler() { }

// Necessary to change extensions later down the road
function rewind() {
  for (const ext in prevExtensionHandler) {
    if (prevExtensionHandler[ext] === undefined) {
      delete require.extensions[ext]
    } else {
      require.extensions[ext] = prevExtensionHandler[ext]
    }
  }

  prevExtensionHandler = {}
}

// Registering the handlers
function registerBabelIgnoreExtHandlers(extensions = ignoreExtInBabelPreProcess, handler = newNullReturnHandler) {
  rewind();

  for (const ext of extensions) {
    prevExtensionHandler[ext] = require.extensions[ext];
    require.extensions[ext] = handler
  }
}

// Register the handlers as by the default list above or use
// registerBabelIgnoreExtHandlers([".someOtherExt", ".someExt"]);
registerBabelIgnoreExtHandlers();

// *******************************************************************

// Require needed ExtractTextPlugin
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const path = require('path');
const fs = require('fs');

export default {
  getRoutes: async () => {
    // 
  },
  Html: class CustomHtml extends Component {
    render() {
      const { Html, Head, Body, children } = this.props;

      const sheet = new ServerStyleSheet();
      const newChildren = sheet.collectStyles(children);
      const styleTags = sheet.getStyleElement();

      return (
        <Html lang="de-DE">
          <Head>
            <meta charSet="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />

// This is the exported css from webpack:
            <link href="index.css" rel="stylesheet" />
//
            {styleTags}
          </Head>
          <Body>{newChildren}</Body>
        </Html>
      )
    }
  },

  webpack: (webpackConfigurator, { dev }) => {

    webpackConfigurator.merge({
      module: {
        rules: [
          {
            test: /\.css$/,
            use: ExtractTextPlugin.extract({
              fallback: 'style-loader',
              use: [ 'css-loader', 'postcss-loader' ]
            })
          },
          {
            test: /\.less$/,
            use: ExtractTextPlugin.extract({
              fallback: 'style-loader',
              use: [
                { loader: 'css-loader', options: { importLoaders:  1, sourceMap: dev } },
                {
                  loader: 'postcss-loader',
                  options: {
                    sourceMap: dev,
                    ident: 'postcss',
                    plugins: (loader) => [
                      require('postcss-import')({ root: loader.resourcePath }),
                      require('autoprefixer')(),
                    ]
                  }
                },
                {
                  loader: "less-loader",
                  options: {
                    sourceMap: dev,
                    paths: [
                      path.resolve(__dirname, "node_modules/andt/lib/style")
                    ]
                  }
                }
              ]
            })
          }
        ]
      },
      plugins: [
        new ExtractTextPlugin({
          filename: 'index.css',
          disable: false,
          allChunks: true
        })
      ]
    })


  },
}
```

**Comment by tannerlinsley** [comment]
All of this will be solved very soon. Hoping by the end of today haha. I'm working on moving the node builds to a webpack environment. This way you can rely on webpack resolution and loaders doing their job across the entire build process.  

One of the changes that this will bring is the ability to specify which webpack config you are altering by using the `stage` variable instead of the `dev` variable in the webpack callback. This way you can get really fine grained. 

Stay tuned. Really sorry about this. But hey, that's open source right ;)

**Comment by D1no** [comment]
When you found a working solution, please post your static config here. File managment is really an after thought of react-static right now and we need a few example usecases to get the underlying properly spects for contributions/PRs.

**Comment by alexiscordova** [comment]
@D1no I might be off on this, but I think the reason less-loader works is because it allows you to specify the Less resolver (e.g., `options: { paths: [path.resolver(__dirname, "node_modules")] }` while sass-loader does not.

@tannerlinsley Looking forward to the update!

**Comment by D1no** [comment]
No, it should work without it. This is just a way to decide between using the webpack or less loader. The node_modules part is only left because I searched and replaced the string to the andt library. Give it a shot — otherwise just wait what @tannerlinsley has got for us

**Comment by tannerlinsley** [comment]
The changes I'm working on will also restructure a lot of the code to make it easier to contribute. I'd love if you guys could help me support the 90% use case out of the box with some new build-in module loaders and what not. 

I want to support, at the very least:
- Basic css importing.
- Image importing (including svg and inlining)

Shouldn't take that much work.

**Comment by D1no** [comment]
Sounds like a plan 👍

**Comment by tannerlinsley** [comment]
Hey guys, can you upgrade to `react-static@next` (should resolve to an alpha release) and play around with it a bit?

The static export is now running through a webpack build (so there is no wonky node module resolution or loading going on). 

Let me know what you see or find out. Hopefully this lays the foundation for some really good webpack upgrades to the whole system.

**Comment by tannerlinsley** [comment]
You should also join the slack org where chat is happening: https://react-chat-signup.herokuapp.com/

I'm in the #react-static channel.

**Comment by tannerlinsley** [comment]
Version 2.0.0 is now released with better support for webpack configs. Let's get a sass plugin ready so we can close this issue :)

**Comment by alexiscordova** [comment]
I tested this on a fresh install, and Sass support seems to be working:

First, install the following: `npm install -D sass-loader node-sass`

`sassLoader.js`
```js
import ExtractTextPlugin from 'extract-text-webpack-plugin'

export default function (config, { stage }) {
  config.module.rules.push(
    stage === 'dev' ? {
      test: /\.scss/,
      use: [
        'style-loader',
        {
          loader: 'css-loader',
          options: {
            importLoaders: 1,
          },
        },
        'sass-loader',
      ],
    } : {
      test: /\.scss/,
      use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: [
          {
            loader: 'css-loader',
            options: {
              minimize: true,
              importLoaders: 1,
            },
          },
          'sass-loader',
        ],
      }),
    },
  )

  return config
}
```

When running `npm run build`, this will add your CSS-compiled Sass code to `styles.css`, which may not be the behavior you want. To make it a separate file, you can add the following to `sassLoader.js`:

```js
config.plugins.push(
  new ExtractTextPlugin({
    filename: '[YOUR_FILENAME].css',
  }),
)
```

This will create a CSS file with whatever name you chose; you can also create a custom path (e.g., `styles/`) where you want your files to live. This example can easily be extended to support loaders for Less, PostCSS (Autoprefixer, et al), etc.,  as well as whatever plugins you may need. This also seems like the approach for adding/editing things like webpack extension and alias support, entry and output paths, etc. (#35)

This may be a separate issue, but I have some concerns about some of the content in the built-in CSS loader—having hard-coded Autoprefixer values seems problematic—and the documentation would most likely need to be expanded with examples on how to build your own custom loaders/plugins, but for the sake of issue specificity I think this works.

**Comment by tannerlinsley** [comment]
I stole the CSS rules right out of create react app. We can always tweak
them though.

**Comment by alexiscordova** [comment]
@tannerlinsley I can do some tests to see if a basic css-loader will handle the basic use case for react-static. As far as Sass support, I believe this can be closed unless you see a reason why it shouldn't be.

**Comment by tannerlinsley** [comment]
Awesome. Sounds good
