### ISSUE TITLE
Feature Request: Basic PWA support

### ISSUE THREAD

**Issue by spences10** [nozzle/react-static#644]
Hi,

I'd like to be able to implement the Webpack plugins available to give some offline caching capabilities.

I have tried implelenting several plugins for Webpack 

```
sw-precache-webpack-plugin
webpack-manifest-plugin
```

And also `offline-plugin`

All resulting in `window not defined` errors.

An example of a basic PWA setup would be most appreciated.

**Comment by hellojere** [comment]
There's no window object in node. 

Please see the documentation: 
https://github.com/nozzle/react-static/blob/master/docs/concepts.md#writing-universal-node-safe-code

**Comment by DanielRuf** [comment]
Would also like to see PWA support.

**Comment by JustFly1984** [comment]
I would love to see PWA support too

**Comment by tannerlinsley** [comment]
This will likely come last on the list for v6. Again, it's very hard to set up a PWA configuration that works for almost everyone out of the box. So this needs to be thought out. Any suggestions on where to start?

**Comment by spences10** [comment]
I guess with:

```
sw-precache-webpack-plugin
webpack-manifest-plugin
# and
offline-plugin
```

But I don't think I'm the best person to be giving direction here as I haven't really been able to make any progress with this on my own initiative.

**Comment by joltmode** [comment]
@tannerlinsley my suggestion would be to look at how Gatsby does it...

**Comment by JustFly1984** [comment]
Bad bot! not stale

**Comment by JustFly1984** [comment]
reopen

**Comment by awidjaja** [comment]
I would like to move out of gatsby to react-static (there's so much silent build failure problem with their v2), but PWA support is a must.

**Comment by tannerlinsley** [comment]
I would love to have pwa support but cannot write it on my own. If you or
anyone else on this thread would like to contribute to this features, then
submit your ideas!

**Comment by DanielRuf** [comment]
In general you can always use solutions like https://pwabuilder.com or solutions by Google.

**Comment by JustFly1984** [comment]
create-react-app seems like going with this PWA solution:
https://github.com/facebook/create-react-app/pull/4169

**Comment by DanielRuf** [comment]
Exactly, this is one of the solutions by Google: https://github.com/GoogleChrome/workbox
