### ISSUE TITLE
routeInfo not passed in dev builds, only prod builds

### ISSUE THREAD

**Issue by dlopuch** [nozzle/react-static#647]
### Are you reporting a bug?
Yes.

On dev builds, it seems that routeInfo is not being passed to:

- the config's `Document` prop -- https://react-static.js.org/docs/config#document
- the config's `route.getData()` function -- https://react-static.js.org/docs/config#route

Dev builds it's always undefined, but it seems to be there in prod builds.

### Environment

1.  `react-static -v`: 5.9.7 
2.  `node -v`: v8.6.0
3.  `yarn --version or npm -v`: npm 6.0.1
4.  Operating system: OS-X

### Steps to Reproduce the problem

For the Document, add a static.config.js Document like so:

```jsx
  Document: ({ Html, Head, Body, children, siteData, renderMeta, routeInfo }) => (
    <Html lang="en-US">
    <Head>
      <meta charSet="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
    <Body>
      routeInfo: {JSON.stringify(routeInfo)}
    </Body>
    </Html>
  ),
```

in dev builds, nothing appears.  In prod builds, you get it.

For the route.getData(), it's a bit more complicated... the [docs](https://react-static.js.org/docs/config#route) say it should be called `resolvedRoute`, but it seems to be just called `route`.  Can reproduce by creating a route like this:

```javascript
  getRoutes: async () => {
    ...
    return [
      {
        path: '/',
        component: 'src/containers/Home',
        getData: async ({route, resolvedRoute, dev}) => {
          console.log("getData() called: route:" + route);
          console.log("getData() called: resolvedRoute:" + resolvedRoute);
        },
      },
...
```

Running the build in dev mode vs. prod mode, you'll see that:

1. `resolvedRoute` is always undefined (docs are wrong, or misleading)
1. `route` is only filled in in prod builds

### Expected Behavior

Expect the routeInfo to be available in all cases.

My use-case: trying to inject [Open Graph](http://ogp.me/) tags into my pages, which require an `og:url` tag.  Trying to just use the route's path for the opengraph URL.

**Comment by CoenWarmer** [comment]
This bug is really biting us; I'd contribute a PR but as I'm seeing a lot of movement on v6 betas I'm not sure how to proceed. Any workaround for 5.9.7 in the interim?

**Comment by tannerlinsley** [comment]
Unfortunately, we cannot pass the routeInfo to the Document prop in dev (because the same html template is used in the dev server for every page, unlike prod, where they are generated uniquely). But I can absolutely look into the `getData` problem.
