### ISSUE TITLE
Intermittent dynamic route error

### ISSUE THREAD

**Issue by cdock1029** [nozzle/react-static#649]
### Are you reporting a bug?
Yes

I have a single non-static `/admin` route. 

[Like this commenter on Spectrum describes](https://spectrum.chat/?t=35024ee8-3a03-48db-9ea0-d6c88cf539e9), I'm seeing an error (*sometimes*) when loading the admin route:

```js
Uncaught (in promise) TypeError: Cannot set property 'templateLoaded' of undefined
```

I can navigate successfully on client, and load page from server. Every so often upon a reload of the app, then navigating to `/admin` I see that error. 

The Spectrum comment is addressing something else with more complex dynamic routes. But mine is a single route, as per the non-static route example, showing the same error. 

Caching bug? Race condition? 

Location of error: 

https://github.com/nozzle/react-static/blob/63e2eb69ffc47263cf3e6de504d9778063f7ae29/src/client/methods.js#L209

### Environment

1.  `react-static -v`: `5.9.7`
2.  `node -v`: `v9.11.1`
3.  `yarn --version or npm -v`: `npm: 6.1.0`
4.  Operating system: `macOS Sierra 10.12.6`
5.  Browser and version (if relevant): `Chrome 69.0.3472.3`

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  Load app, any route (/admin should work)
2.  Navigate around, works
3.  Reload app... sometimes client navigation to /admin produces error above.

`static.config.js`
```js
getRoutes: async () => {
    const value = await admin
      .database()
      .ref('health')
      .once('value')
      .then(snap => snap.val())
    // const snap = await snapPromise
    console.log({ value })
    const membersLoad = loadEntity('members')
    const eventsLoad = loadEntity('events')
    const linksLoad = loadEntity('links')

    const [members, events, links] = await Promise.all([
      membersLoad,
      eventsLoad,
      linksLoad,
    ])

    return [
      {
        path: '/',
        component: 'src/containers/Events',
        getData: () => ({ events }),
      },
      {
        path: '/members',
        component: 'src/containers/Members',
        getData: () => ({ members }),
      },
      {
        path: '/links',
        component: 'src/containers/Links',
        getData: () => ({ links }),
      },
      {
        is404: true,
        component: 'src/containers/404',
      },
    ]
  },
```

`App.js`
```jsx
const Admin = universal(() => import('../containers/Admin'))
const App = () => (
  <Router>
    <div id="app">
      <Header />
      <div id="content">
        <Switch>
          <Route path="/admin" component={Admin} />
          <Routes />
        </Switch>
      </div>
    </div>
  </Router>
)
```

`Admin.js`
```jsx
import React from 'react'
import { AuthConsumer, AuthProvider } from '../components/Auth'

class Admin extends React.Component {
  render() {
    return (
      <div
        css={`
          margin-top: 2em;
        `}
      >
        <AuthProvider>
          <AuthConsumer>
            {({ user, signOut }) => {
              return (
                <div>
                  <ul>
                    <li>{user.email}</li>
                    <li>{user.displayName}</li>
                  </ul>
                  <pre>{JSON.stringify({ user }, null, 2)}</pre>
                  <button onClick={signOut}>Sign Out</button>
                </div>
              )
            }}
          </AuthConsumer>
        </AuthProvider>
      </div>
    )
  }
}

export default Admin

```

### Expected Behavior

Always works, error never shows.

**Comment by tannerlinsley** [comment]
Neither. It's a case the code doesn't handle non static pages being
navigated to.

**Comment by tannerlinsley** [comment]
Still not sure what to do here. Any suggestions on a path forward?

**Comment by cdock1029** [comment]
So in my use case I'm thinking I must have resolved it by setting `prefetch={false}`, I'll have to check again, but I haven't seen the error.. 

It's an admin route which I don't want to prefetch anyways. 

Maybe just bail if route is non-static... ?

**Comment by cmontgomerymt** [comment]
Any updates on how to handle this? I have this issue in v6.
