### ISSUE TITLE
Older version is installed in the created folder

### ISSUE THREAD

**Issue by sghall** [nozzle/react-static#65]
Hey, the yarn.lock files have version 1.2.5 in them so you get that version installed (if using yarn) in the created site even if you'e using the latest cli.  Probably better not to commit these lock files or you have to make sure they get regenerated.  Or is this by design, possibly?

Basic:
https://github.com/nozzle/react-static/blob/815606d4835658ab55a719bf1bdf01890221c9da/examples/basic/yarn.lock#L4958

Custom Routing:
https://github.com/nozzle/react-static/blob/815606d4835658ab55a719bf1bdf01890221c9da/examples/custom-routing/yarn.lock#L4717

**Comment by tannerlinsley** [comment]
No definitely a mistake on my part.

**Comment by gagan0723** [comment]
It may be the case the latest build of ``` react-static ``` is not in sync with npm.

**Comment by tannerlinsley** [comment]
The `yarn.lock` files are no longer included and also ignored. Shouldn't be a problem anymore.
