### ISSUE TITLE
Yarn build results to broken or jumbled pages

### ISSUE THREAD

**Issue by micchyboy** [nozzle/react-static#650]
Why does the pages result to broken or jumbled pages? But when a route navigation is clicked it suddenly fixes? Looking at console here is an error message that I cannot understand why:
<img width="775" alt="screen shot 2018-06-29 at 11 19 05 pm" src="https://user-images.githubusercontent.com/6582041/42100482-e7c8f524-7bf2-11e8-9e26-18f2c1e7ff91.png">

**Comment by tannerlinsley** [comment]
We'll need more info on how to reproduce this issue. Please reopen with more details, thanks!
