### ISSUE TITLE
Rewriting a dynamic route to a static one erases the static route

### ISSUE THREAD

**Issue by richtera** [nozzle/react-static#651]
Adding something like this:
```
          <Route exact path="/unit/:unit" render={(props) => (
            <Redirect to={{
              pathname: `/unit`,
              state: {
                stage: props.match.params.unit
              }
            }} />
          )} />
```
which will route ```/unit/:unit``` to ```/unit``` while setting location.state to publish the unit.
This will trigger the error
```
Could not load routeInfo for path: unit/cpce1. If this is a static route, make sure any link to this page is valid! If this is not a static route, you can desregard this warning.
```
but at the time this happens and state 43 happens the location will already have been rewritten and it will then proceed to remove /unit out of the static route list.

### Environment

1.  `react-static -v`: 5.9.7 (BTW it's react-static --version not -v)
2.  `node -v`: v9.11.1
3.  `yarn --version or npm -v`: 1.7.0
4.  Operating system: Mac OS 10.13.5 (17F77)
5.  Browser and version (if relevant): Chrome Version 67.0.3396.87 (Official Build) (64-bit)

### Steps to Reproduce the problem

See above.

### Expected Behavior

A routing error should not affect the routing table.

### Reproducible Demo

See above.

**Comment by richtera** [comment]
Here is an image of the piece of code:
![image](https://user-images.githubusercontent.com/708186/42114874-b91874d6-7bbe-11e8-82bf-378b35e25911.png)
The case 43: drops through but the value of path is already the rewritten path.

**Comment by tannerlinsley** [comment]
Any suggestions on how to handle this in the library?

**Comment by richtera** [comment]
@tannerlinsley I am not exactly sure, but maybe not altering the routeInfoByPath if routeInfo is null?

**Comment by tannerlinsley** [comment]
That would probably work great. Would you like to PR that and test it?
