### ISSUE TITLE
Routing issues when there are special characters in the URL

### ISSUE THREAD

**Issue by rachel-church** [nozzle/react-static#652]
### Are you reporting a bug?
Yes

Refreshing a page with a special character in the pathname will result in 404. 
_Example_: (`/résumé`)
- Not reproducible when running a dev build (`yarn start`)
- The same page serves correctly if you go to it via a link. Subsequent page refreshes will fail.

### Environment
-  `react-static -v`: 5.9.7
-  `node -v`: v8.9.4
-  `yarn --version`: 1.5.1

### Steps to Reproduce the problem
Using the _basic_ react-static example:
1. Update the route '/blog' in `static.config.js` to be '/blóg' (Just add any special character)
2. Update the link in `App.js` and `containers/Post.js` to link to `/blóg` instead of `/blog`
3. Run the app using `yarn stage && yarn serve`
4. From any page click 'Blog' in the header. The page should work and show the lists of posts.
5. Refresh the page - 404 or blank screen will be shown

### Expected Behavior
Refreshing a page with a special character in the URL should not cause a 404

### Reproducible Demo
https://github.com/rachel-church/react-static-issue652-demo

**Comment by tannerlinsley** [comment]
This is a tough one. Wouldn't this depend on your server settings?

**Comment by rachel-church** [comment]
Running https://github.com/rachel-church/react-static-issue652-demo with `yarn build && yarn serve` fails. We have the same issue serving the app with Nginx. `serve` had some issues in 2016 with special characters but has since fixed it. It looks like the GET requests correctly receive the route data but the component for the route is not displayed.

**Comment by danilobuerger** [comment]
I can reproduce this with v6. Just create a page named `blög.js` or similar. With `react-static build` the correct files are created and on browser load it also delivers the right file but then the 404 page is mounted and rendered. So it seems this is not a server problem but a routing problem.

**Comment by danilobuerger** [comment]
Found the bug, PR incoming.
