### ISSUE TITLE
error: unknown option `-v`

### ISSUE THREAD

**Issue by hellojere** [nozzle/react-static#655]
### Are you reporting a bug?

Yes. 

Running `react-static --version` gives the expected result of `5.9.7` whereas running `react-static -v` results to `error: unknown option '-v'`

Also running `react-static -h` gives an option for this as `-V, --version  output the version number` (capital V) whereas elsewhere in the documentation it's `-v` (lower case). 

### Environment

1.  `react-static -v`: 5.9.7
2.  `node -v`: v10.5.0
3.  `yarn --version`: 1.7.0
4.  Operating system: macOS Mojave Version 10.14 Beta (18A314k)

### Steps to Reproduce the problem

`react-static -v`

### Expected Behavior

Same as `react-static --version` resulting in `5.9.7`

**Comment by kurdin** [comment]
@hellojere  
try `react-static -V`

**Comment by hellojere** [comment]
That'd didn't work either earlier, but seems to be fixed now.
