### ISSUE TITLE
Help with migrating to v6

### ISSUE THREAD

**Issue by benedfit** [nozzle/react-static#656]
I'm in the process of testing out testing out v6. I've hit a few blockers, so wonder if someone could take a look at my code and provide some assistance?

## Error when using a HOC with react-static-routes

Since migrating from 5.9.7 The following HOC (https://github.com/newhighsco/destiny-clan-warfare/blob/feature/react-static-6/src/App.js#L37) is causing the following error

![screen shot 2018-07-06 at 09 08 28](https://user-images.githubusercontent.com/580859/42367461-3a403570-80fc-11e8-9a79-12a631d2b75e.png)

## Using Stylus, CSS modules, and config.extractCssChunks

I currently have the following setup (https://github.com/newhighsco/destiny-clan-warfare/blob/feature/react-static-6/static.config.js#L351) that utilises, Stylus, CSS modules, and extracCSSChunks, however it looks like I am not setup correctly now for v6, and I have experienced the following errors:

![screen shot 2018-07-06 at 09 24 42](https://user-images.githubusercontent.com/580859/42368254-736f8f2e-80fe-11e8-83fc-0c7dfed2b3e8.png)
![screen shot 2018-07-06 at 09 32 11](https://user-images.githubusercontent.com/580859/42368649-8043cb24-80ff-11e8-951c-e869cd0c7d4f.png)

Thanks in advance

**Comment by kurdin** [comment]
I was trying out v6 and I had the same React errors with some of `Ant Design` components, some of them works fine, other throw `cannot no call a class as function` error. Rolled back to 5.9.7

**Comment by ScriptedAlchemy** [comment]
Flush chunks is in my domain, ill pull your repo down soon and see if theres anything on my end

**Comment by tannerlinsley** [comment]
Going to track this in #601

**Comment by benedfit** [comment]
@ScriptedAlchemy @tannerlinsley I'm getting further, but I'm still seeing the "No `outputPath` was provided as an option to `flushChunks`" error on the latest beta version

**Comment by ScriptedAlchemy** [comment]
Ill pull down https://github.com/newhighsco/destiny-clan-warfare/blob/feature/react-static-6/src/App.js#L37 and see whats up

**Comment by benedfit** [comment]
@ScriptedAlchemy anything look obviously wrong with my setup?

**Comment by ScriptedAlchemy** [comment]
Silly one. But try deleting node modules and all lock files. Clean install?
