### ISSUE TITLE
Slow startup performance

### ISSUE THREAD

**Issue by KidkArolis** [nozzle/react-static#657]
### Environment

1.  `react-static -v`: 5.9.7
2.  `node -v`: v10.5.0
3.  `npm -v`: 6.1.0
4.  Operating system: macos 10.13.4

### Steps to Reproduce the problem

1. Generate a new site with `react-static create`
2.  Run `time npm start` and wait til it prints out `App serving at` and stop with cmd+c

### Expected Behavior

It starts up in a reasonable amount of time.. 1s, 5s, 10s.

Instead, it takes 52s for me for this to start up. To be more precise, it takes almost 50s to start the build process:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/324440/42478748-c7f3b1fc-83cd-11e8-9155-820a09e357a1.png">

Is this just my setup? Or is this typical. I suspect babel.. compiling node bits or smth? I will try and profile in more detail, but was just wondering if this is a known issue.

**Comment by tannerlinsley** [comment]
How many routes do you have in your site? Have you tried using the beta
version at `react-static@next`?

**Comment by KidkArolis** [comment]
It's just the basic template with 4-5 routes and 100 blog posts.

**Comment by tannerlinsley** [comment]
That's way too long for just 105 routes and 4 templates. I can't replicate
that on my machine. It only takes a few seconds to serve.

**Comment by KidkArolis** [comment]
I looked a bit more into what's causing this and it's `require('babel-register')` - it's taking tens of seconds for that require to kick in. I think it's to do with babel cache, I had that before, I think babel 7 improves this. Until then.. hm.. need to figure out where babel-register stores it's cache.. or what else is going on there.

**Comment by KidkArolis** [comment]
I think it's this issue.. https://github.com/babel/babel/issues/5667

**Comment by KidkArolis** [comment]
Ok, `rm ~/.babel.json` "fixes" it, brings the overall build time back to <5s.

**Comment by pwmckenna** [comment]
may I suggest using the BABEL_CACHE_PATH env var. you can use it to manually point to where babel 7 will put it (./node_modules/.cache)

**Comment by solutionprovider9174** [comment]
I don't have babel.json in my end on windows 7 and node 12 with react-static, i have .cache directory on node module. 
But yet 45seconds for starting and 30seconds for editing saving in my end. 
Really stressed for this. how can optimize this for less than 3~4seconds for developing well?

I already tried to follow this 
https://github.com/babel/babel/issues/5667
But nothing good for now.
