### ISSUE TITLE
Installing @next breaks react-static

### ISSUE THREAD

**Issue by spences10** [nozzle/react-static#684]
### Are you reporting a bug?

Yes

![image](https://user-images.githubusercontent.com/234708/42763865-1dc94b26-890c-11e8-896d-1bbce147708e.png)

Tried to initialise a new version of `react-static@next` to get some file changes to update https://github.com/nozzle/react-static/pull/682 but was getting the above error message on my Windows 10 environment using Windows Subsystem Linux, I thought it may have been my environment until I tried the same on my MBP 2015

Then thought rather than `npx` why not try straight up installing and trying from there: 

![image](https://user-images.githubusercontent.com/234708/42763662-a9300e94-890b-11e8-9955-0c641edf893d.png)

### Environment

1.  `react-static -v`: `error: unknown option -v'`
2.  `node -v`: 10.3.0
3.  `yarn --version or npm -v`: 6.1.0
4.  Operating system: Windows 10 w/ WSL (Ubuntu) and Macos 
5.  Browser and version (if relevant):

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

As per the screenshots

**Comment by danilobuerger** [comment]
@spences10 Already fixed in master, see https://github.com/nozzle/react-static/commit/f791d6e25e485d99458b083105d7fcec94ac8265

**Comment by spences10** [comment]
Thanks @danilobuerger is there a way for me to use that now? `npm i react-static@next` is still `@6.0.0-beta.14`

**Comment by tannerlinsley** [comment]
I'll cut a beta asap

**Comment by danilobuerger** [comment]
I would advise waiting for the next beta, but just fyi:
1. Clone this repo,
2. `yarn && yarn run build`
3. Use as local dependency in your project

**Comment by spences10** [comment]
>I'll cut a beta asap

Don't rush on my part @tannerlinsley 🙏

**Comment by tannerlinsley** [comment]
Try the latest beta

**Comment by tannerlinsley** [comment]
Reopen is necessary
