### ISSUE TITLE
Development Environment Sample Build

### ISSUE THREAD

**Issue by BrianKopp** [nozzle/react-static#687]
### Are you reporting a bug?

Yes.

I'm trying to setup an environment to implement and test a change related to issue 622. I followed the instructions in CONTRIBUTING.md, but I get errors when I run "yarn test-sample-build".

I did this on a fresh installation of Ubuntu 16.04, only adding yarn, npm, and git from apt. 

I cloned the repo, then ran "yarn", "yarn watch", and "yarn link". Then on "yarn test-sample-build", I get the following output.

![image](https://user-images.githubusercontent.com/6773852/42911025-0296c10e-8aaf-11e8-82fe-e3ad4e1437d8.png)

### Environment

1.  `react-static -v`: react-static: command not found 
2.  `node -v`: 8.11.3
3.  `yarn --version or npm -v`: 1.7
4.  Operating system: Ubuntu 16.04
5.  Browser and version (if relevant): N/A

**Comment by tannerlinsley** [comment]
The test sample has not yet been migrated to v6. I'll do this and update
the contributing guide.

**Comment by BrianKopp** [comment]
Great thanks! If you get one or a couple of them ported, I can try to work on some others. I'd like to try to contribute if possible.

**Comment by tannerlinsley** [comment]
The easiest way is to use the examples in the examples directory. First
yarn link in the repo root. Then yarn start. Then in an example run yarn.
Then run yarn link react-static. That will make the example use the local
version of react-static.

**Comment by BrianKopp** [comment]
Oh, ok thanks. For some reason, running the yarn test-sample-build bombed out on the "yarn" command inside the examples/basic directory. If I run yarn start, then in a separate terminal run yarn, yarn link react-static, and yarn build, then I get a success on the basic example (even though there is still an error on the yarn command).

Ultimately what I'm getting at is that I want to test the material-ui example since that's closest to my use case in issue 622. There I'm getting an Invariant Violation. Is this a known issue?
![image](https://user-images.githubusercontent.com/6773852/42954919-fa2eaf9c-8b42-11e8-8957-1342f47d3fea.png)

**Comment by tannerlinsley** [comment]
That is not a known issue and will likely need to be debugged.

**Comment by Kosai106** [comment]
@BrianKopp Regarding your latest comment, there's already have an issue open for that. https://github.com/nozzle/react-static/issues/693 which, for some reason, still haven't gotten any comments from the devs.

**Comment by tannerlinsley** [comment]
We're going to track this problem in #693. Thanks.
