### ISSUE TITLE
On link click page loads in  a scrolled state.

### ISSUE THREAD

**Issue by naquiuddin** [nozzle/react-static#69]
Please go to this link http://websitestaticreact.s3-website-us-east-1.amazonaws.com/ and click on the flute link. Website changes to new page but renders in a scrolled state.

**Comment by naquiuddin** [comment]
I just came across this https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/scroll-restoration.md

@tannerlinsley Do we have to manually do this with scrollTo?

**Comment by tannerlinsley** [comment]
I have used several react-router hash link components and scrolling components.  A quick google or github search will show you plenty of them.

**Comment by tannerlinsley** [comment]
https://github.com/rafrex/react-router-hash-link
