### ISSUE TITLE
TypeError: Failed exporting HTML for URL About (src/pages/About.js): Cannot read property 'href' of undefined

### ISSUE THREAD

**Issue by ronanlevesque** [nozzle/react-static#693]
I just updated to `react-static@v6.0.0-beta.16`, and now `yarn build` will throw the following error for any file that my `pages` folder will contain:

```
TypeError: Failed exporting HTML for URL About (src/pages/About.js): Cannot read property 'href' of undefined
```

### Environment

1.  `react-static -v`: 6.0.0-beta.16
2.  `node -v`: 8.10.0
3.  `yarn --version`: 1.6.0
4.  Operating system: macOS High Sierra

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  `yarn add react-static@v6.0.0-beta.16`
2.  `yarn build`

**Comment by Kosai106** [comment]
I think I've found the piece of code causing the issue.

`react-static/src/client/components/Router.js`

```jsx
 if (typeof window !== 'undefined') {
  routeInfo = window.__routeInfo
  const href = decodeURIComponent(window.location.href)
  path = cleanPath(href)
}
```

**Comment by Kosai106** [comment]
Still not fixed and shouldn't be closed.

**Comment by treyhuffine** [comment]
I'm seeing the same issue

**Comment by bradysheridan** [comment]
Hey @ronanlevesque, did you ever find a solution?

**Comment by Kosai106** [comment]
@bradysheridan No, we never found a workaround - We switched to Gatsby instead.

**Comment by tannerlinsley** [comment]
The original issue https://github.com/nozzle/react-static/issues/693#issuecomment-408405975 was fixed, but I guess we missed a statement about that.

If you're still having issues, its likely a migration issue (which we are more than willing to help with). Please paste a link to your repo or project where we can take a look and reproduce the problem.

All fresh React Static installations are functioning properly.

**Comment by Ziinc** [comment]
Thanks @tannerlinsley  for the clarification. It my global installation version that was lagging behind by a few versions that caused the problem.

**Comment by E-Wagner** [comment]
@tannerlinsley I'm having the same issue, would you mind looking at my project: 
https://github.com/E-Wagner/fellow
I've been working many hours on this but it broke unexpectedly..

**Comment by TimMcCauley** [comment]
This happened to me after installing `react-helmet@6.0.0` - removing it let me build again.

**Comment by Ankush0102** [comment]
TypeError: Failed exporting HTML for URL manage-account (__react_static_root__/src/pages/manage-account.js): Cannot read property 'c'   of undefined

**Comment by Ankush0102** [comment]
this is the error i'm getting, tried to debug still cant figure out what is the issue here

**Comment by larissa-n** [comment]
It might also be an old `<Router>` component (if you migrated from an older version of react-static) like [here](https://stackoverflow.com/questions/55202110/error-failed-exporting-html-for-url-about-src-pages-about-js-invariant-faile).

Or if you have `React.Suspense` & `React.lazy()` inside of any page, it will also cause the same error (v.7.6.2).
 
It seems that this error can mean many different things. Any chance that errors messages could be more specific?
