### ISSUE TITLE
Examples missing about/home and other pages

### ISSUE THREAD

**Issue by fahimk** [nozzle/react-static#695]
Just tried the dynamic-imports example locally and none of the pages seem to load. Looking at the static.config.js it seems like there isn't a home/about page listed there.

https://github.com/nozzle/react-static/blob/master/examples/dynamic-imports/static.config.js

Is that intentional?

**Comment by tannerlinsley** [comment]
Yes. With the new beta 6 version you no longer need to register pages in
the config if they can be simply represented by placing a component file in
the pages/ directory with the file path of the route

**Comment by mjsisley** [comment]
The examples are broken because version 5 of react-static is specified in https://github.com/nozzle/react-static/blob/master/examples/dynamic-imports/package.json

**Comment by JustFly1984** [comment]
What about dynamic pages? Currently I have my dynamic pages in `src/pages` together with static pages, and if I try to move them to another directory, I got failed build. Could it be an issue?
