### ISSUE TITLE
Clicking on a Link to a route that does not exist fails to show 404

### ISSUE THREAD

**Issue by jujubarr** [nozzle/react-static#696]
### Are you reporting a bug?

Yes

### Is this a feature request?

No

### Environment

1.  `react-static -v`: 5.9.7
2.  `node -v`: v9.2.0
3.  `yarn --version`: 1.3.2
4.  Operating system: iOS

### Steps to Reproduce the problem

Using the React-Static - Redux Example

1.  Add a new Link to a route that does not exist in App.js
2.  Update 404.js to use routeData from posts
3.  add getData posts to static.confic.js
4. run `yarn build && yarn serve`
5. Click on 404 Link in header

When user clicks on the Link, the page becomes blank. 
404 page will render on manual refresh or when entering `http://localhost:3000/pageNotFound` manually in the browser.

### Expected Behavior

When user clicks on the Link, Url should change to `http://localhost:3000/pageNotFound` and 404 page should be rendered if route does not exist.

### Reproducible Demo
https://github.com/jujubarr/react-static-issue-696

**Comment by jefelewis** [comment]
I second this. Is there any fix to this? I haven't been able to figure out why.
