### ISSUE TITLE
SiteData (withSiteData) works in dev mode, but not in production (live) mode.

### ISSUE THREAD

**Issue by arminas-a** [nozzle/react-static#697]
### Are you reporting a bug?

Yes.

### Is this a feature request?

No.

### Environment

1.  react-static -v: 5.9.7
2.  node -v: v9.2.0
3.  yarn --version: 1.3.2
4.  Operating system: iOS

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  Have a folder of markdown files.
2.  Add that folder to getSiteData.
3.  Iterate folder in a component to provide data.

### Expected Behavior

SiteData (withSiteData) should work( and show data in component) in both development (which works), and production mode (which doesn't work).

### Reproducible Demo

Repo (master): https://github.com/noderidge/Noderidge
Live: https://www.noderidge.com/

**Comment by lottamus** [comment]
At first glance I see you're loading the route component from "src/components/home/index.jsx" but it should be "src/pages/home/index.jsx": https://github.com/noderidge/Noderidge/blob/master/static.config.js#L105

This means the route "/" won't have an associated route JSON file that react uses to render the page.

How it works:
1. You load "https://www.noderidge.com/"
2. The browser fetches "/index.html"
3. The script tags in "index.html" tell the browser to fetch the JS containing the react app, the JSON file containing the route data, and CSS
4. The react App mounts and tries to render the page using the route data

If the route data isn't found, it will render a blank white page. This is why you might see a flicker of the actual content (from the html file) and then a blank white page (what react renders).

If you disable JavaScript (blocking react from mounting), you will see that the generated HTML is correct.

![image](https://user-images.githubusercontent.com/7423098/43535358-5ed56f3a-957f-11e8-9d8b-7f4866d52f57.png)

**Comment by arminas-a** [comment]
Thanks!
