### ISSUE TITLE
[6.0.0-beta.16] Bug with nested pages

### ISSUE THREAD

**Issue by bkniffler** [nozzle/react-static#698]
Hey, 
Running current examples (and also my react-static projects) with @6.0.0-beta.16 currently don't work well as soon as you hit nested pages like https://jolly-payne-39a5f2.netlify.com/blog/post/1/

You can see that it looks for all kinds of paths relatively to the current location (`https://jolly-payne-39a5f2.netlify.com/blog/post/1/staticData/2iGX7h.json`) instead of relatively to the root.

**Comment by nozzle** [comment]
Info: `master` branch now points to 5.x.x and the `v6` branch to 6.0.0-beta.

**Comment by tannerlinsley** [comment]
This problem is now resolved in the v6 branch.
