### ISSUE TITLE
Sass does not works in development

### ISSUE THREAD

**Issue by DavidTorrijos** [nozzle/react-static#709]
Hi guys,
I'm trying to include sass files in the basic base example but the files are invisibles for the base...

I have installed "node-sass" and "sass-loader" like in your sass example. Also, I have included the pluggin "react-static-plugin-sass" at my static.config.js, but when I try to import any scss file, nothing happens.

This is my package.json and my static.config.js:
```
{
  "name": "react-static-example-basic",
  "version": "1.0.1",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "start": "react-static start",
    "stage": "react-static build --staging",
    "build": "react-static build",
    "serve": "serve dist -p 3000"
  },
  "dependencies": {
    "axios": "^0.16.2",
    "node-sass": "^4.9.3",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-hot-loader": "^4.0.0-beta.21",
    "react-router": "^4.2.0",
    "react-static": "^5",
    "sass-loader": "^7.1.0"
  },
  "devDependencies": {
    "eslint-config-react-tools": "1.x.x",
    "serve": "^6.1.0"
  }
}
```

```
import axios from 'axios'

export default {
  plugins: ['react-static-plugin-sass'],
  getSiteData: () => ({
    title: 'React Static'
  }),
  getRoutes: async () => {
    return [
      {
        path: '/',
        component: 'src/containers/Home'
      },
      {
        path: '/demo',
        component: 'src/containers/Demo'
      },
      {
        is404: true,
        component: 'src/containers/404'
      }
    ]
  }
}
```

I know that you have a sass demo, but I have started with the basic one and I have some lines there. I wouldn't like starting with a new base again.

Thank you!

**Comment by tannerlinsley** [comment]
The sass-loader is not published yet and is still under active development for v6. Stay tuned for when it is officially released. For the latest stable version you can refer to this example: https://github.com/nozzle/react-static/tree/v5.9.5/examples/sass

**Comment by ScriptedAlchemy** [comment]
https://github.com/nozzle/react-static/pull/733
