### ISSUE TITLE
Question : Best way to show / hide a component based on path

### ISSUE THREAD

**Issue by purplefish32** [nozzle/react-static#71]
What is the best way to show/hide a component based on path (route/url).
I would like to hide a menu on a /login route.
I have been messing around with getRouteProps and getSiteProps but am clearly stuck due do my lack of javascipt skills.
Can you please point me in the right direction, even better provide an example in the docs ?.
Awsome work by the way :1st_place_medal:

**Comment by tannerlinsley** [comment]
This is a question better suited for the slack channel. Join here: https://react-chat-signup.herokuapp.com/
