### ISSUE TITLE
Feature: Disable Javascript

### ISSUE THREAD

**Issue by benedfit** [nozzle/react-static#711]
I have a large site, with pages that have lots of data and markup. Prefetching, and the fact that JS handles all the navigation, is bringing a serious negative experience to users of my site, where they mostly end up being served the 404 page rather than pages loading, because the router hasn’t finished prefetching the link they have clicked on. 

Is there any way I can leave all the routing and navigation to the browser?

**Comment by benedfit** [comment]
They are being generated. A hard refresh will load them. 

Try visiting https://destinyclanwarfare.com, especially on a slower connection, and you’ll More than likely hit a 404 page when trying to browse (especially if trying to browse quickly) around the site

**Comment by Herohtar** [comment]
Ah, I see what you mean... I can trigger it by scrolling down one of the long pages that seemingly loads as you scroll and then quickly clicking a link to another page.

**Comment by derekperkins** [comment]
@benedfit That's a pretty significant routing bug you uncovered. It's supposed to behave like @Herohtar described.

@tannerlinsley Any idea what's causing that?

**Comment by tannerlinsley** [comment]
Going to track this in #618
