### ISSUE TITLE
Make routeInfo.json cachable by adding BUILD_ID

### ISSUE THREAD

**Issue by Rusfighter** [nozzle/react-static#717]
### Is this a feature request?
Yes,

The idea is to add a postfix to all /page/routeInfo.json such that it becomes /page/routeInfo.BUILD_ID.json where BUILD ID is some build identifier. This gives an ability to use browse caching to cache the localProps for unlimited time in the browser (and CDN). 

I guess this isn't possible yet, and I would love to create a PR if someone could give me a direction where to look for.

Ilija

**Comment by tannerlinsley** [comment]
We'll accept a PR for this if opened. Closing for now.
