### ISSUE TITLE
NavBar/Footer are hidden on dynamic routes in production

### ISSUE THREAD

**Issue by luisfuertes** [nozzle/react-static#718]
I have this Paths file:
```
import {
  Register,
} from '../components/pages/'
import StaticRoutes from 'react-static-routes'

const Paths = (
  <Switch>
    <Route exact path="/registro" component={Register} />
    <StaticRoutes />
  </Switch>

export default Paths
```

My Pages index: 
```
import universal from 'react-universal-component'

const Login = universal(import('./auth/login/'))
const Register = universal(import('./auth/register/'))

export {
  Register
}
```

And my App.js
```
const App = () => (
  <Provider store={store}>
    <Router>
      <ThemeProvider theme={theme}>
        <div className="content">
          <NavBar />
          <div className="emp-container">{Paths}</div>
          <Footer />
          <Modal />
        </div>
      </ThemeProvider>
    </Router>
  </Provider>
)

export default hot(module)(App)
```

In localhost all work fine. But in production (`react-static build`), when i navigate to dynamic route, only render the `<div className="emp-container">{Paths}</div>` and `<NavBar />,  <Footer />, <Modal />` dont are rendered (It do not appear in html inspector). With static routes all works fine.

Versions: 
```
"react": "^16.0.0",
"react-static": "^5.9.7",
```

**Comment by luisfuertes** [comment]
I update to react-static v.6.0.0-beta.15 o 6.0.0-beta.16 but have this error: `Cannot read property 'DIST' of undefined`

```
=> Cleaning dist...
  TypeError: Cannot read property 'DIST' of undefined
  
  - bundle.js:95 _callee$
    [my_web]/[react-static]/lib/commands/bundle.js:95:57
  
  - runtime.js:62 tryCatch
    [my_web]/[runtime]/[regenerator-runtime]/runtime.js:62:40
  
  - runtime.js:288 Generator.invoke [as _invoke]
    [my_web]/[runtime]/[regenerator-runtime]/runtime.js:288:22
  
  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [my_web]/[runtime]/[regenerator-runtime]/runtime.js:114:21
  
  - bundle.js:30 asyncGeneratorStep
    [my_web]/[react-static]/lib/commands/bundle.js:30:103
  
  - bundle.js:32 _next
    [my_web]/[react-static]/lib/commands/bundle.js:32:194
  
  
  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7
  
  - module.js:695 Function.Module.runMain
    module.js:695:11
  
  - bootstrap_node.js:188 startup
    bootstrap_node.js:188:16
```

**Comment by JustFly1984** [comment]
This is the same issue as #701

**Comment by luisfuertes** [comment]
@JustFly1984 ye, issue with new version, but i need solve the origina issue in my current version

**Comment by luisfuertes** [comment]
Ok, if i remove `withRouteData` of my NavBar component, it show OK. But i cant navigate without history prop (I navigate in redux action, not from <Link> component)

**Comment by luisfuertes** [comment]
How can i get `history` prop without `withRouteData` connect? 

I supose `withRouteData` is only for components inside a react-static `<Route />` element, is correct?

My `<NavBar />` isnt in react-static `<Route />` element because is presented in all routes. How can i create a "global" `<NavBar />` with history prop without `withRouteData` connect?

**Comment by tannerlinsley** [comment]
`withRouteData` and `RouteData` only need to be inside the `<Router>` component. If all you are looking for is the history object though, you can get it with the `withRouter` HOC.

```javascript
import { withRouter } from 'react-static' // or react-router

withRouter(({ history }) => (
  // use history
))
```

**Comment by luisfuertes** [comment]
> `withRouteData` and `RouteData` only need to be inside the `<Router>` component. If all you are looking for is the history object though, you can get it with the `withRouter` HOC.
> 
> ```js
> import { withRouter } from 'react-static' // or react-router
> 
> withRouter(({ history }) => (
>   // use history
> ))
> ```

In what version? In `react-static v5.9.7` function dont resolve 
```
withRouter(props => {
    console.log('withRouter rops: ', props)
}
```
Never show withRouter log

**Comment by tannerlinsley** [comment]
It should work with all versions

**Comment by luisfuertes** [comment]
@tannerlinsley only in `withRouteData` components? Or in all files, like redux actions file?

You can try it in: https://github.com/luisfuertes/react-static-demo
