### ISSUE TITLE
Support Redirects via redirect(), <Redirect>, and route.redirect

### ISSUE THREAD

**Issue by tzookb** [nozzle/react-static#72]
I have my sales page, that has several versions.

I want to let users open my urls but get to specific pages like this:

```
site.com/?page=about
=>
site.com/about

site.com/?page=home1
=>
site.com/home1
```

in the current situation, its easy to define routes, but how would handle the task above?

Thanks! 👍

**Comment by tannerlinsley** [comment]
If you are wanting redirects, they are easiest implemented at the server level for now, but we will adding support for redirect generation to react-static very soon.

**Comment by tzookb** [comment]
Hey guys

Yes just wanted to have simple redirects.
Tried with <Redirect> it worked but with an annoying warning.

Sure using server is the easiest, but planned to just throw it into S3

Currently have issues with images but will solve that soon

Thanks!

**Comment by depadiernos** [comment]
Netlify has a really simple way of doing redirects with a _redirects file. Check out https://www.netlify.com/docs/redirects/.

**Comment by derekperkins** [comment]
Redirects are simple on any server if they are page driven (as opposed to parameter driven). It wouldn't be difficult to have `react-static` output files like this that work great.

```
<!DOCTYPE html>
<html>
    <head>
        <title>...</title>
        <link rel="canonical" href="..."/>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta http-equiv="refresh" content="0; url=..." />
    </head>
</html>
```

If you're wanting parameter driven redirects, I don't think there is anything `react-static` can do for you. Most hosting services have redirect services in place, or you could alternatively set up page rules in Cloudflare.
