### ISSUE TITLE
Production build of SASS template doesn't work with CSS Modules

### ISSUE THREAD

**Issue by bryancallahan** [nozzle/react-static#722]
### Bug Report

Yes, full steps to reproduce below. After enabling CSS Modules, they don't work when refreshing for the SASS template.

### Environment

1.  `react-static -v`:  5.9.7
2.  `node -v`: v10.9.0
3.  `npm -v`: 6.2.0
4.  Operating system: Mac OS X 10.13.6
5.  Browser and version (if relevant): Version 68.0.3440.106 (Official Build) (64-bit) -- all browsers 

### Steps to Reproduce the problem

![image](https://user-images.githubusercontent.com/2325847/44891306-69343800-ac93-11e8-8617-abbc082fb292.png)

![image](https://user-images.githubusercontent.com/2325847/44891313-73563680-ac93-11e8-9abf-d7d5ad376be3.png)

![image](https://user-images.githubusercontent.com/2325847/44891319-7a7d4480-ac93-11e8-9608-9f5913a8ab2c.png)

![image](https://user-images.githubusercontent.com/2325847/44891322-80732580-ac93-11e8-8264-e0baa11cd9a1.png)

![image](https://user-images.githubusercontent.com/2325847/44891331-8e28ab00-ac93-11e8-887d-6e698b2cb4a6.png)

![image](https://user-images.githubusercontent.com/2325847/44891335-954fb900-ac93-11e8-9cac-f5b917fb87b8.png)

### Expected Behavior

In Step 9 there should be a red box in Figure (a) and Figure (b).

**Comment by nozzle** [comment]
Info: `master` branch now points to 5.x.x and the `v6` branch to 6.0.0-beta.

**Comment by nozzle** [comment]
Looks like you accidentally got the latest beta version of react-static instead of the stable 5.x version. Please try your project creation again using v 5.x :)

**Comment by ScriptedAlchemy** [comment]
https://github.com/nozzle/react-static/pull/733
