### ISSUE TITLE
Client script placement problem

### ISSUE THREAD

**Issue by neilyoung** [nozzle/react-static#726]
### Environment

1.  `react-static -v`: Actually react-static -V, result: 5.9.7
2.  `node -v`: v9.4.0
3.  `yarn --version or npm -v`: 6.1.0
4.  Operating system: macOS High Sierra
5.  Browser and version (if relevant):

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  Follow https://react-static.js.org/docs/config/, section "Document". Paste this into yours static.config.json:
```

export default {
 
  Document: ({ Html, Head, Body, children, siteData, renderMeta }) => (
    <Html lang="en-US">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>


      <Body>{children}</Body>
    </Html>
  )
}
```

2.  npm start
3.  Catch error "ReferenceError: React is not defined"

### Expected Behavior
Shouldn't produce this error

**Comment by JustFly1984** [comment]
Since you are using JSX in the file, it is required to `import React from 'react'` on top of the file.

**Comment by neilyoung** [comment]
Ah, yes. Thanks for the answer. Did learn that already later the evening yesterday from another post. Forgot to close this here...
