### ISSUE TITLE
`create` command installs wrong react-static version

### ISSUE THREAD

**Issue by lexaurin** [nozzle/react-static#728]
### Are you reporting a bug?
All versions of `react-static create` starts always project with **the newest stable version** of react-static which ends up with incompatibility errors between created project and react-static build.

I.e. when I install `react-static 6.0.0-beta.16` it creates project with `react-static 5.9.7`
When I install `react-static 4.8.5`, for example, it also creates project with `5.9.7`. And then fails with `4.8.5` build of course.

### Environment

1.  `react-static -v`: `error: unknown option -v` ¯\_(ツ)_/¯
    - `react-static --version`: `6.0.0-beta.16`
    - `yarn react-static --version # inside project`: `5.9.7`
2.  `node -v`: `v8.9.4`
3.  `yarn --version or npm -v`: `1.9.4`
4.  Operating system: `macOS`
5.  Browser and version (if relevant): `Chrome 68`

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1. `yarn global add react-static@v6.0.0-beta.13`
2. `react-static create -n test-foo -t basic && cd test-foo`
3. `yarn start`
4. open http://localhost:3000
5. Page content is not diplayed; error in console "Could not load routeInfo" "[404] routeInfo" 

![image](https://user-images.githubusercontent.com/428302/45033430-cc87e680-b054-11e8-8f30-f454824ca725.png)

### Expected Behavior
When I install specific version of react-static it should also create t**he same (compatible) version of react-static** in new projects.

**Comment by nozzle** [comment]
Info: `master` branch now points to 5.x.x and the `v6` branch to 6.0.0-beta.

**Comment by tannerlinsley** [comment]
Fixed!

**Comment by lexaurin** [comment]
Thanks 👍 👍
