### ISSUE TITLE
Maintainers and Contributors

### ISSUE THREAD

**Issue by bkniffler** [nozzle/react-static#731]
I know that this is a free, open-source project and I appreciate all the time and effort this has been put into by you and the collaborators. Currently react-static v16 is in beta and there is still errors that I constantly fight with (using react-static in production), some of them already fixed in PRs and while it kinda works, I find myself to work with ugly workarounds like patching react-static files by overwriting them inside the node_modules folder.

Maybe it could help to call for maintainers with publish and PR merge rights? I believe that react-static is a great solution for statical page building and there is people commiting and participating in the development, adding maintainers could help getting to v16 and future updates a lot faster.

**Comment by tannerlinsley** [comment]
I have a day reserved for React Static coming up. I'll put this on my list of things to address. Thanks!

**Comment by JustFly1984** [comment]
Can I apply for maintainer's role?

**Comment by bkniffler** [comment]
Yeah @sw-yx, that would be a great first step. Travis is already set up, so adding an automated publishing pipeline for @canary tag shouldn't be too much of an issue, especially if someone PR'd the travis-ci.yml :)

**Comment by tannerlinsley** [comment]
If someone would like to PR that travis setup then I’d be happy to help
with the publish keys

**Comment by tannerlinsley** [comment]
Unfortunately, I made a veeeerrrry bad mistake of writing v6 on master. In all reality, master should remain up to date with the stable public release of React Static. This will change next version. I am still figuring out how to cherry pick the commits for v5 into another branch...

**Comment by nozzle** [comment]
Info: `master` branch now points to 5.x.x and the `v6` branch to 6.0.0-beta.

**Comment by cdock1029** [comment]
Not to derail thread but curious why you feel was a mistake to develop on master?

Seems like this reduces complexity and can then just cut tagged release branches / public releases from them.. patch these release branches with bug fixes as needed, merge back to master..

https://reallifeprogramming.com/git-process-that-works-say-no-to-gitflow-50bf2038ccf7

**Comment by tannerlinsley** [comment]
Mostly this has to do with a lot of the CI and github experience for users.
If @latest points at 5.x, then I think users expect to be able to see
master reflect the latest stable version. This also keeps the CI in sync
for things like building the website/docs properly for existing users and
keeps issues like we’ve seen in the last few weeks where people are trying
to install plugins that don’t exist yet, or use features in v6 that aren’t
fully complete. Turns out these people had no idea they were using v6,
because they were simply referring to the master branch for docs, examples,
and code.

I know there are ways to develop @next on master and likewise keep older
versions on their own branches (v5), but given the circumstances and
current CI setup, I think it made more sense to do a v6 branch etc.

**Comment by ScriptedAlchemy** [comment]
Tanner, if you need help maintaining RS - I could potentially help with some of the smaller issues.

I got some capacity problems at the moment, but then things cool down, I can lend a hand in the maintenance.

**Comment by tannerlinsley** [comment]
All of everyones help here is extremely appreciated. I am 💯 for adding more maintainers and moving forward as long as we can check these boxes off:

- [ ] Automate testing and releases based on PR's
- [ ] Draft some better maintainer/contributor guidelines
- [ ] Find some time to walk each new maintainer through the v6 codebase and vision for the future of the library

**Comment by Pixelatex** [comment]
I'll also be interested in becoming a maintainer :) time to give something back to react-static

**Comment by tannerlinsley** [comment]
Alright guys. I'm planning a react-static live-stream / group chat for all those interested in being a maintainer/contributor.

I will be going through the following agenda items:
- React-Static's past, motivation, goals, and future
- How we want to automate/collaborate on Github and NPM
- Architectural overview
- Code Overview
- Specific implementations for complex parts of RS
- The v6 plugin system, how it probably needs to evolve even more.
- "PR", the marketing kind ;) and other various community-bound discussions.

I plan on using something Google hangouts or zoom.us and I plan on recording the meeting for future maintainers/contributors to watch. 

Browse the source beforehand. The more you are familiar with the inner workings of RS, the more productive we can be!

Bring questions, but most importantly, bring ideas and solutions on how we can make RS work more smoothly.

I plan on doing this meeting sometime during the day this week between the hours of 9:30 and 2 MST. I plan on the entire meeting going for about an hour, but am okay if we go over by another hour.

If you have specific times that work best for you, speak now!

**Comment by ScriptedAlchemy** [comment]
if we can do later on in the week, that will be ideal for me :) Will be on the hangout for sure

**Comment by mmcshinsky** [comment]
Between those hours are perfect.

**Comment by sw-yx** [comment]
if you could give a day's heads up on twitter too that'd be great

**Comment by JustFly1984** [comment]
Yes, I'm interested too!

**Comment by tannerlinsley** [comment]
I think we're going to tentatively shoot for Wednesday, 10AM MST. The hangout will be hosted here: https://hangouts.google.com/call/kxtrzI_sFswXNW3ZUD7vAAEE (I hope those links don't expire)

**Comment by JustFly1984** [comment]
Damn, I will be in the road. Hope to see recording after.

**Comment by loganfromlogan** [comment]
Dang, I'll be at the Framework Summit then. I'll have to check out the recording afterwards.

**Comment by farskid** [comment]
Time and date works for me :) Excited to be a part of it.

**Comment by tannerlinsley** [comment]
For those who cannot make the meeting tomorrow, I will gladly do a second mini-meeting as long as we can find a time that works for a majority of you. Comment with your available times :)

**Comment by bkniffler** [comment]
I can't participate unfortunately but I'd be super happy if you could record it and make it available somewhere!

**Comment by sw-yx** [comment]
literally any other time this week would work, haha. you picked the one period i'm traveling. but i'll dial in tmr

**Comment by ScriptedAlchemy** [comment]
For those who miss it, I also don’t mind getting on a call and doing a recap :)

**Comment by Pixelatex** [comment]
I would love to dial in but I have a meeting that evening :/ another day would work nicely for me though!

**Comment by tannerlinsley** [comment]
Meeting starts in 2 hours!

**Comment by tannerlinsley** [comment]
https://hangouts.google.com/hangouts/_/iqoe3qoxdnenjiwn3qxbperzn4e

**Comment by ajschmidt8** [comment]
@tannerlinsley, i missed this! please let me know if you will be doing another. maybe during the upcoming 3 day weekend?

**Comment by tannerlinsley** [comment]
# Agenda

- Motivation & Goals
- Library Overview
- Code & Architecture
- Todos
    - Collaboration on Github and NPM
        - PR descriptions, labels, triaging issues
        - Contributor Doc / Guidelines
    - Release Automation
        - Travis - Run Tests
        - Push the release to the proper branch (branch + PR description / notes)
            - Master
            - Release
            - Beta
            - Next
    - React-Router ⇒ Reach Router
        - Own Router API
            - `navigate()`
            - <Router/>
            - <Link/>
            - <Route/>
    - V6
        - React 16-ify
        - Plugin API (2nd iteration) (client-side plugins)
        - Test `pages` directory support (nested routes)
        - Improve testing
        - Dogfood/experimenting v6 in our own sites
        - `react-static-plugin-gatsby-plugin`
            - Use a gatsby plugin in react-static
            - API translation layer Gatsby API ⇒ React-Static API
            - Not everything will be supported, but some will
    - **"PR"**, the marketing kind ;) and other various community-bound discussions.
        - Design Good Sites / Marketing material for RS
        - Documentation - needs a big upgrade, too sparse, no search, more branded
        - Gatsby + Next backed by funding, large companies.
        - Open Source Future of RS, Netlify cares about RS (because it's truly OSS)
        - CodeSandbox (I'm working on one right now [https://codesandbox.io/s/72n304yq40](https://codesandbox.io/s/72n304yq40))
        - Examples into users hands quickly
        - Be active on Twitter, tag @reactstaticjs
        - Spectrum.chat/react-static

## Motivation & Goals

Other SSG's were either too heavy, too dirty, or diverged from React

- "Just React"
- Reduce pain and complexity, not LOC
- Library Size & Complexity
- Power = Flexibility
- Speed

## Library Overview

React-Static is a tool to handle the common SSG pains of

- Bundling / Code-Splitting
- CSS strategies (imports, css-in-js, webpack, loaders)
- Iterative Development (Hot Reloading)
- Routing
- Preloading JSON, Templates/Chunks
- Asset Pipelining (Public folders, imports, webpack resolves)
- Static Exporting
- Progressive Enhancement
- Speed, auto-optimizations

It does this using the following tools:

- React / ReactDOM
- Babel
- Webpack
- React-Universal-Component (`import('../myComponent.js') = chunk`)
    - webpack-flush-chunks (reports chunk names)
    - extract-css-chunks-webpack-plugin (css support)
    - The best.
- React-Router (Reach-Router)
- React-hot-loader
- [Socket.io](http://socket.io) (hot-data-reloading)

Roughly, these are the lifecycles for each stage:

- Start
    - Subscribe to Config
        - Defaults & Overrides
        - Resolve Paths
        - Resolve Plugins
        - `hook('config')`
    - Clean `temp` directory
    - Fetch `siteData`
    - Create `index.html` placeholder from `Document`
    - Subscribes to and prepare Routes
        - Routes built and normalized from config and `pages` directory
    - Extract Templates from all routes
    - Bundle for Dev and start the webpack development server
        - JIT Middleware for `siteData` and `routeData`
        - Socket for hot-data-reloading is provided as well

- Bundle
    - Build Config (same as in `start`)
    - Clean `dist` directory (same as dev
    - Fetch `siteData`
    - Prepare Routes (same as in `start`)
    - Extract Templates from all routes
    - Copy Public Files
    - Bundle for node and production

- Export
    - Build Config (if not already built)
    - Prepare Routes (if not already prepared)
    - Export Routes
        - Fetch `siteData`
        - Fetch `routeData`
        - Write data to JSON
            - Route-split
            - Shared Data (woah...)
        - Multi-threaded `renderToString`
            - Page-specific data is embedded in HTML for initial page speed

- Client
    - HTML is rendered
    - React Mounts on existing HTML
        - First load `RouteData` and `SiteData` use JSON embedded in HTML
    - `Link` / `Prefetch` used to preload templates and JSON
    - `History` is monkeypatched to disallow route changes until required webpack chunks and JSON are loaded
    - All data is cached in the session and made available to `RouteData` on the fly

**Comment by farskid** [comment]
@tannerlinsley I'm willing to help and be a maintainer 👍

**Comment by Pixelatex** [comment]
:hand: Willing and ready to help!

**Comment by tannerlinsley** [comment]
Did ya miss our contributor onboarding call? Watch the call whenever you have time!

https://www.youtube.com/watch?v=z8dtYF7CMMY

We discuss in length the ins and outs of ReactStatic and how you can help contribute to its future right now! #react #oss #Hacktoberfest2018 #JAMstack #javascript



https://twitter.com/ReactStaticJS/status/1047548731665436672

**Comment by tannerlinsley** [comment]
I've added everyone who attended the meeting as a collaborator on the project up this point! Thanks guys!

**Comment by ScriptedAlchemy** [comment]
Thanks Tanner!

**Comment by tannerlinsley** [comment]
Also, I've created a Project here: https://github.com/nozzle/react-static/projects/2 to help us all coordinate on the library. If you are a contributor you should be able to add, edit and link cards there!

**Comment by farskid** [comment]
@tannerlinsley Thanks for the invitation. Let's get to work :)

**Comment by krvajal** [comment]
> I've added everyone who attended the meeting as a collaborator on the project up this point! Thanks guys!
@tannerlinsley I wasn't added. Can you add me, please?

**Comment by max-allen** [comment]
> > I've added everyone who attended the meeting as a collaborator on the project up this point! Thanks guys!
> 
> @tannerlinsley I wasn't added. Can you add me, please?

@tannerlinsley Me as well!

**Comment by tannerlinsley** [comment]
@max-allen Added 😄

**Comment by tannerlinsley** [comment]
@krvajal Added 🎉

**Comment by sw-yx** [comment]
should this be a weekly meeting? im currently trying to formally get some time from work to do this, and i know not everyone can commit to this same level of commitment. but i dont know how else oss groups are run.

**Comment by tannerlinsley** [comment]
I would gladly do one off meetings whenever needed. We can always record them for posterity too.

**Comment by Pixelatex** [comment]
We could plan a meeting around a single subject, like the plugins for example.

**Comment by tannerlinsley** [comment]
To better help all of us work together more closely, I've created a private slack organization where we can have private chats, ping each other more quickly, and have more fast-paced creative conversations.

Please send an email to tannerlinsley[at]gmail.com from the email you'd like me to send an invite to.

**Comment by JustFly1984** [comment]
Hey guys sorry, only now I had time to watch all 2 hours of first hangout meeting. So I have followup questions:

What about dynamic routes in context of Reach-router and other context of v6 ? I do have many pages which is allowed for authorized users only.

How did you test multithreading on netlify? They told me that they provide only single core for deploying.

**Comment by tannerlinsley** [comment]
Dynamic routes will still work just fine in v6. If we do end up switching to Reach Router, I have no doubt it will be just as good, or possibly better at handling dynamic routes than react-router, but haven't gotten that far yet.

Multithreading doesn't come out of the box on netlify so they say, but I've seen even free plans running on a mulit-core. For testing, they gave me a standard enterprise box which comes with 6 cores (I think). I've been using https://github.com/tannerlinsley/react-static-large-site-test to do that.

**Comment by tannerlinsley** [comment]
FYI: https://twitter.com/tannerlinsley/status/1052198459460055040

@ 8:15 MST (in 30 minutes) I’ll be live-streaming how @ReactStaticJS’s browser-client works and how #react #suspense has already helped shape v6 into a better library.

Watch/chat here: https://t.co/XKwRRGvrgw
