### ISSUE TITLE
[v6] Production issue with initial render on a nested route

### ISSUE THREAD

**Issue by mjsisley** [nozzle/react-static#739]
### Are you reporting a bug?
Yes

### Environment

1.  `react-static -v`: 6.0.0-beta.20
2.  `node -v`: 9.6.1
3.  `yarn --version or npm -v`: yarn 1.9.4
4.  Operating system: MacOS High Sierra 10.13.6

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!** 
Using `styled-components` template.

1.  `yarn build`
2.  `yarn serve`
3. Initial render from `http://localhost:3000/blog/post/1/` -> Console: https://www.dropbox.com/s/uxj01o5h3t343mm/Screenshot%202018-09-08%2018.38.57.png?dl=0
4. Navigate to "Blog" through interface -> Console: https://www.dropbox.com/s/x0dghcfl04rzxly/Screenshot%202018-09-08%2018.38.00.png?dl=0

Note: The same errors occur with an initial render from `http://localhost:3000/about` and navigation to "Blog" when using `serve: ^6.1`, but don't occur for `http://localhost:3000/about` if `serve: ^10` is used.

### Expected Behavior
All routing works without errors as in development (`yarn start`)

**Comment by tannerlinsley** [comment]
Could you try to replicate this again with the latest stable version of RS?

**Comment by mjsisley** [comment]
With v6.0.0-beta.25

Console on first load from a nested route (blog/post/1):
https://www.dropbox.com/s/y74ntkibu040mil/Screenshot%202018-10-14%2020.43.18.png?dl=0

Screenshot of console after navigation to another route (index, blog, about):
https://www.dropbox.com/s/mjpvecfovds1woe/Screenshot%202018-10-14%2020.44.24.png?dl=0

**Comment by mjsisley** [comment]
No errors occurring with production build in v6.0.0-beta.29. Great! Closing this issue.
