### ISSUE TITLE
Problem with dynamic routes in PROD

### ISSUE THREAD

**Issue by luisfuertes** [nozzle/react-static#744]
### Error
Dynamic routes fail in ditribution build. When i click a `<Link>` with dynamic route have the next error: 
![captura de pantalla 2018-09-11 a las 16 09 04](https://user-images.githubusercontent.com/18212615/45365566-1173c600-b5dd-11e8-8de5-aefdd75bbc19.png)

**Error is in file:** 
`./node_modules/react-static/lib/client/methods.js`
Line 16: prefetchData
In case 2: routeInfo = _context4.sent; context4.sent is html code instead of an Object
![captura de pantalla 2018-09-06 a las 13 38 02](https://user-images.githubusercontent.com/18212615/45365225-56e3c380-b5dc-11e8-98b5-0fdff09881bb.png)

### Environment
1.  `react-static -v`:  `v5.9.7`
2.  `node -v`: `v8.11.1`
3.  `yarn --version or npm -v`: `v1.9.4`
4.  Operating system: `Mac OS High Sierra v10.13.6`
5.  `react -v`: `v16.0.0`

### Steps to Reproduce the problem
**Base your steps off of any freshly installed react-static template!**
1.  yarn run build or react-static build
2.  deploy dist folder in prod server
3.  onClick on `<Link>` with dynamic route

### My code: 

Paths file:
```
import {
  Register,
} from '../components/pages/'
import StaticRoutes from 'react-static-routes'

const Paths = (
  <Switch>
    <Route exact path="/registro" component={Register} />
    <StaticRoutes />
  </Switch>

export default Paths
```

My Pages index: 
```
import universal from 'react-universal-component'

const Login = universal(import('./auth/login/'))
const Register = universal(import('./auth/register/'))

export {
  Register
}
```

And my App.js
```
const App = () => (
  <Provider store={store}>
    <Router>
      <ThemeProvider theme={theme}>
        <div className="content">
          <NavBar />
          <div className="emp-container">{Paths}</div>
          <Footer />
          <Modal />
        </div>
      </ThemeProvider>
    </Router>
  </Provider>
)

export default hot(module)(App)
```

**Comment by tannerlinsley** [comment]
Could you provide a link to a basic example or repo where we can replicate this problem?

**Comment by luisfuertes** [comment]
I have been able to do this, it does not give the same error but it does not load the dynamic route either

https://github.com/luisfuertes/react-static-demo

**Comment by benedfit** [comment]
@luisfuertes have you tried adding `prefetch={false}` to any `<Links />` referencing dynamic links? I have found this prevents errors on sites where I use them

**Comment by luisfuertes** [comment]
thanks for anwer. I have tried to add but it didnt work

**Comment by sharat9211** [comment]
I am also facing this issue. Can work on it but will need some help to get started

**Comment by tannerlinsley** [comment]
I've figured out that this is a core issue with the prefetching
architecture in v5. Aside from rewriting v5, there won't be much we can do
other than move on to v6 where we have a new architecture that fixes this.

**Comment by javobal** [comment]
#835 Seems to work
