### ISSUE TITLE
All urls without / have by default 301 Moved Permanently on Netlify

### ISSUE THREAD

**Issue by tb** [nozzle/react-static#749]
All urls without / have by default 301 Moved Permanently on Netlify

I would expect react static generates files structure of that there are no 301 Moved Permanently when using urls without /

ATM I have too add `_redirects` file with entries like:
 /my-page  /my-page/    200

### Environment

1.  `react-static -v`: 5.9.7
2.  `node -v`: v9.0.0
3.  `npm -v`: 5.5.1
4.  Operating system: Mac OS
5.  Browser and version (if relevant): Chrome

### Steps to Reproduce the problem

Redirect Checker

1. Open http://www.redirect-checker.org/index.php
2. Paste any not root URL on any react static site i.e. https://react-static.js.org/docs/concepts

or browser

1. Open new tab in browser
2. Paste https://react-static.js.org/docs/concepts

### Expected Behavior

No 301 Moved Permanently on using urls without /

**Comment by Herohtar** [comment]
I think that's actually an issue with how Netlify configures their hosting.

**Comment by tb** [comment]
@Herohtar Thanks! Unchecking Pretty URLs on Netlify worked
