### ISSUE TITLE
Not all files have sourcemaps generated during build

### ISSUE THREAD

**Issue by MarijnBrosens** [nozzle/react-static#755]
Hi,

For the error logging that I use I need sourcemaps for every javascript file. Currently it seems that sourcemaps are only created for static.js and styles.css.

I have tried to set the devtools option in webpack to false and injected the SourceMapDevToolPlugin with no result.

Is it possible to generate sourcemaps for every .js file that gets created in the current react-static setup? I'm open to helping out with this if it's an issue, but I don't really know where to start looking.

### Environment

1.  `react-static -v`: 5.9.7
2.  `node -v`: v8.0.0
3.  `yarn --version`: 1.7.0
4.  Operating system: MacOS High Sierra
5.  Browser and version (if relevant): /

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1. react-static: basic template
2. yarn build
3. No sourcemaps for /dist/main.js and other containers

<img width="255" alt="screen shot 2018-09-18 at 17 44 37" src="https://user-images.githubusercontent.com/5678434/45699681-d5a3a800-bb6a-11e8-8761-b83b34dca0c2.png">

### Expected Behavior

Sourcemaps for every js file.

(https://spectrum.chat/thread/01da543e-e713-42e8-8c46-903b4e894a24)

**Comment by tannerlinsley** [comment]
A fix for this needs to definitely happen soon. Would love to see a proposal or even a PR for this here!

**Comment by jslowack** [comment]
@tannerlinsley any idea where to start? I'm guessing this issue has something to do with the chunkFileName configuration and its sourcemapping. WDYT?

https://github.com/nozzle/react-static/blob/cd0a60d805c372788a0fedfd3efd97430a0055a3/src/static/index.js#L247

https://github.com/nozzle/react-static/blob/cd0a60d805c372788a0fedfd3efd97430a0055a3/src/static/webpack/webpack.config.prod.js#L39

**Comment by jslowack** [comment]
I've created a PR that fixes this issue: https://github.com/nozzle/react-static/pull/782
