### ISSUE TITLE
Problem with NetlifyCMS local build

### ISSUE THREAD

**Issue by kosirm** [nozzle/react-static#756]
Hi, I just found this project and I'm really excited how good it is (react-static). Everything worked like a charm, until I tried NetlifyCMS example. I used "Deploy to netlify" button from github to deploy to netlify... and it is working great! Then I cloned my repo and tried to build it localy (with localy I mean c9.io ubuntu box)... and I get these errors :
```
infocube:~/workspace/react-static-netlifycms (master) $ yarn build
yarn run v1.9.4
$ react-static build
  Error: /home/ubuntu/workspace/react-static-netlifycms/static.config.js:41
  export default {
  ^^^^^^
  SyntaxError: Unexpected token export
    - vm.js:79 new Script
    vm.js:79:7
    - vm.js:251 createScript
    vm.js:251:10
    - vm.js:303 Object.runInThisContext
    vm.js:303:10
    - loader.js:657 Module._compile
    internal/modules/cjs/loader.js:657:28
    - node.js:144 loader
    [global]/[babel-register]/lib/node.js:144:5
    - node.js:154 Object.require.extensions.(anonymous function) [as .js]
    [global]/[babel-register]/lib/node.js:154:7
  - loader.js:599 Module.load
    internal/modules/cjs/loader.js:599:32
    - loader.js:538 tryModuleLoad
    internal/modules/cjs/loader.js:538:12
    - loader.js:530 Function.Module._load
    internal/modules/cjs/loader.js:530:3
    - loader.js:637 Module.require
    internal/modules/cjs/loader.js:637:17

=> Info: No 'siteRoot' is defined in 'static.config.js'. This is suggested for absolute url's and a sitemap.xml to be automatically generated.

  TypeError: Cannot read property 'DIST' of undefined
    - bundle.js:82 _callee$
    [global]/[react-static]/lib/commands/bundle.js:82:58
  - runtime.js:62 tryCatch
    [global]/[regenerator-runtime]/runtime.js:62:40
  - runtime.js:296 Generator.invoke [as _invoke]
    [global]/[regenerator-runtime]/runtime.js:296:22
    - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [global]/[regenerator-runtime]/runtime.js:114:21
    - bundle.js:31 step
    [global]/[react-static]/lib/commands/bundle.js:31:191
    - bundle.js:31 
    [global]/[react-static]/lib/commands/bundle.js:31:437
    - new Promise
    - bundle.js:31 
    [global]/[react-static]/lib/commands/bundle.js:31:99
    - bundle.js:128 build
    [global]/[react-static]/lib/commands/bundle.js:128:17
    - build.js:33 Object._callee$
    [global]/[react-static]/lib/commands/build.js:33:41
  

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
I tryed to run it also on windows localy, and I got exactly the same error.

What am I doing wrong?

I managed to work with this example through Gitlab Web IDE. I still don't understand how come that example is built on netlify without problems, **but locally ... no way**. I also noticed that netlify-cms version 
[is still 1](https://github.com/nozzle/react-static/blob/ade3291e01c640f7ff825f3dfc311896a7befaaf/examples/netlifycms/public/admin/index.html#L16), even if with #751 it was bumped to 2.1 ... correct me if I'm wrong.
When I changed it to the latest version, everything (new uploadcare widget /media library, etc) is working fine.

**Comment by kosirm** [comment]
Hi, I managed to work with this example through Gitlab Web IDE. I still don't understand how come that example is built on netlify without problems, but locally no way. I also noticed that netlify-cms version is still 1, even if with #751 it was bumped to 2.1
When I changed it to the latest version, everything (new uploadcare widget /media library, etc) is working fine.

**Comment by Pixelatex** [comment]
I think your node version is outdated or missing entirely. Run a node -v on the machines you're using.
