### ISSUE TITLE
Using yarn workspaces the build does not contain expected `Head` usage

### ISSUE THREAD

**Issue by AubreyHewes** [nozzle/react-static#762]
### Are you reporting a bug?
Yes

When using [yarn workspaces](https://yarnpkg.com/en/docs/workspaces) the build does not contain expected `<Head/>` usage. I.e. expected `<title/>` is not in the build output.

It seems that this package or an upstream package requires physical presence of dependencies within the cwd. The build works, but the `<Head />` is not applied.
 
See synopsis at https://github.com/AubreyHewes/react-static-yarn-workspaces-build-error

### Environment

1.  `react-static -v`:

````shell
$ react-static -V # you need to update the issue template as it is a capital V ;-)
5.9.7
````

2.  `node -v`:
````shell
$ node -v
v8.12.0
````
3.  `yarn --version or npm -v`:

````shell
$ yarn --version
1.9.4
````

4.  Operating system:

````shell
$ lsb_release --description  && uname -a
Description:	Ubuntu 17.10
Linux alita 4.13.0-46-generic #51-Ubuntu SMP Tue Jun 12 12:36:29 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
````

### Steps to Reproduce the problem

See https://github.com/AubreyHewes/react-static-yarn-workspaces-build-error

**Base your steps off of any freshly installed react-static template!**

See above repo (react-static basic template)

### Expected Behavior

Build output contains `<Head/>` i.e. custom `<title/>`

### Reproducible Demo

https://github.com/AubreyHewes/react-static-yarn-workspaces-build-error

`git checkout tags/step2` as master is the workaround (nohoist)

**Comment by tannerlinsley** [comment]
Hmm, yeah this could be a problem. Interally, everything is either using one of `required.resolve`, `require`, or a webpack array of locations to be used. I've never used workspaces, so this is all new to me. If I showed you some code in the source, would you be able to help me diagnose this?

**Comment by AubreyHewes** [comment]
@tannerlinsley Yeah no problem.

I noticed that in the webpack (prod) config there are hard coded locations
i.e. https://github.com/nozzle/react-static/blob/47a1e672cca1dbbc094d5e47bf6ae13af906df55/src/static/webpack/webpack.config.prod.js#L35

Though I am unsure, in the above case, if it is the problem and if so what the solution should be..
Possibly recur up if expected packages are not found..?

**Comment by tannerlinsley** [comment]
Yeah, would you like to give that a try?

To test this out, you could just go into `node_modules/react-static/lib/static/webpack/webpack.config.prod.js` and modify that line (it may be a bit babelified, but it's doable).

Would could try:
- Removing it. This would default the context to cwd. Even if that works, we should find a way to dynamically set the context to be correct.
- Changing it to your cwd manually. Almost the same as above.
- Detecting workspaces and setting it manually to the correct directory. This seems a bit fragile, but we could still try it out.

If changing that doesn't work, then it may be a combination of other fields that also need to be more dynamic. My guess is anywhere node_modules is used. I do think it's strange that it's working though, but the head is the only thing that doesn't work right.

One last thing that could help is if you tried this same experiment but with the react-static v6 beta.

**Comment by AubreyHewes** [comment]
@tannerlinsley Yeah will give it a go. 

I agree it is strange that the build works except the `Head`

**Comment by AubreyHewes** [comment]
@tannerlinsley 

 * Removing `context` does not help
 * Changing `context` to expected workspace does not help
 * Changing `context` to expected workspace and adding paths to `modules` does not help
 * Removing `context` and adding paths to `modules` does not help

In all cases `renderToStringAndExtract` does not have the required title

    // Extract head calls using Helmet synchronously right after renderToString
    // to not introduce any race conditions in the meta data rendering
    var helmet = _reactHelmet2.default.renderStatic();
        console.log(helmet.title.toString());

Will have to debug it more to find a possible reason.. It still seems it is due to the possible directory locations (normal and yarn workspaces-nohoist works)

**Comment by AubreyHewes** [comment]
v6.0.0-beta.22 has the same problem

still digging ;-)

**Comment by AubreyHewes** [comment]
Extra (missing) information; I did not originally state that the dev version works as expected when used in yarn workspaces...

i.e. ` cd client && yarn run start` (based on issue repo)

So I am now looking at the differences between the dev and prod webpack configs and also how the `node_modules/react-static/lib/static/index.js` works which is not used in dev

**Comment by AubreyHewes** [comment]
So I seem to have found where it breaks.. still no idea why.

When rendering in yarn workspaces react-helmet `Component.rewind()` does not contain a `mappedState`  https://github.com/nfl/react-helmet/blob/b22e2f4075971f8b80568cd9911a2143f602add1/src/Helmet.js#L68 and so fallbacks to a default state.

````
[react-static] renderToStringAndExtract appHtml <div data-reactroot=""><nav><a class="active" aria-current="page" href="/">Home</a></nav><div class="content"><div><h1 style="text-align:center">Welcome to</h1><img src="/static/logo.9ff8fc2e.png" alt=""/></div></div></div>
  Error: [object Object]
      at renderToStringAndExtract (/app/node_modules/react-static/lib/static/index.js:521:35)
      at Object.renderToHtml (/app/node_modules/react-static/lib/static/getConfig.js:280:14)
      at _callee8$ (/app/node_modules/react-static/lib/static/index.js:559:39)
      at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime  /runtime.js:114:21)
      at step (/app/node_modules/react-static/lib/static/index.js:92:191)
      at /app/node_modules/react-static/lib/static/index.js:92:437
      at new Promise (<anonymous>)
      at /app/node_modules/react-static/lib/static/index.js:92:99

[react-helmet] renderStatic/rewind mappedState undefined
  Error: [object Object]
      at Function.Helmet._class.rewind (/app/node_modules/react-helmet/lib/Helmet.js:262:17)
      at renderToStringAndExtract (/app/node_modules/react-static/lib/static/index.js:539:62)
      at Object.renderToHtml (/app/node_modules/react-static/lib/static/getConfig.js:280:14)
      at _callee8$ (/app/node_modules/react-static/lib/static/index.js:559:39)
      at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime  /runtime.js:114:21)
      at step (/app/node_modules/react-static/lib/static/index.js:92:191)
      at /app/node_modules/react-static/lib/static/index.js:92:437
      at new Promise (<anonymous>)

[react-helmet] renderStatic/rewind NO MAPPED STATE; FALLBACK

[react-static] renderToStringAndExtract helmet.title <title data-react-helmet="true"></title>
````

Possibly an upstream issue with `react-dom/server` ?

Still digging; -)

**Comment by tannerlinsley** [comment]
Wow, this rabbit hole is deep! Keep digging!

**Comment by AubreyHewes** [comment]
:rabbit:

**Comment by AubreyHewes** [comment]
debugging this is a :hankey: :cloud_with_lightning_and_rain:

**Comment by AubreyHewes** [comment]
The baker said, "stale? have some nice fresh rogge!" Unfortunately, I have not had the time to dig into this any further. Our current solution is to CI with extra "nohoist".
I will get back in to this when I have the time. @tannerlinsley You can close this if you want as I can not say when I will have the time to continue this.

**Comment by tannerlinsley** [comment]
`nohoist` is the recommended solution for now. Thanks for your help @AubreyHewes!
