### ISSUE TITLE
[FR] Incremental builds / build subset of pages

### ISSUE THREAD

**Issue by NeoLegends** [nozzle/react-static#764]
I'm currently trying to build something like an e-commerce-site with react-static. The site has lots of items (think 5k+) and each of these shall get its own site. The items can be updated through a CMS and the site should be rebuilt through CI.

The problem: Right now, whenever some item is changed through the CMS, the whole site needs to be rebuilt, even though only a single route is affected. This stretches build times unnecessarily. 

The question / feature request: Is there a way to tell react-static to only rebuild a subset of the pages or a single page?

**Comment by benedfit** [comment]
My kingdom for partial rebuilds

**Comment by JustFly1984** [comment]
I’m also working on e-comers website, and I’m also interested in partial rebuilds, although currently I’m deploying my project to netlify, and I do not see how it possible to deploy partial rebuilds to netlify. I have around 400+ products right now, and last deploy to netlify took around 12 minutes

**Comment by NeoLegends** [comment]
While netlify is great for most cases, other options such as S3 buckets may be more suitable for cases like these with an enormous amount of files. Might want to try that instead.

**Comment by jlee1201** [comment]
looks similar to what was desired in #163 .  @rileylnapier -- were you able to achieve what you were going for?  I'm definitely interested in this as well

**Comment by JustFly1984** [comment]
Yes, we are moving in this direction. We are actually using AWS mobile hub with graphQL, but we having several issues with amplify-cli. Definitely will look to move deploy from netlify to aws S3, but for that we need to wait till our issues with graphQL is resolved on their side and react-static will get partial rebuild) I hope so!

**Comment by Rusfighter** [comment]
I think this issue is related to it: https://github.com/nozzle/react-static/issues/717

If you adding/updating products you only need to rebuild the routeInfo.json for that product, the html for the product and the catalogue. 
One way to do this is to use an AWS bucket/google storage to only reupload the necessary files.

**Comment by NeoLegends** [comment]
> The most we have discussed however is merely the capability to re-export routes with new data. There are no plans to support partial rebuilds where templates, imports, or basically anything in the webpack bundle is changed 

This is definetely understandable and I would not have expected otherwise. Good to hear this is one of the goals of the project!

**Comment by JustFly1984** [comment]
Not stale

**Comment by kmcaloon** [comment]
Hey all, so according to this spectrum thread this issue should not be marked as "Done" within the project board.

 https://spectrum.chat/react-static/general/status-on-incremental-builds~90cedb9b-3e15-4eec-be7c-3ccb473615eb

**Comment by tannerlinsley** [comment]
That's just StaleBot keeping us on our toes. 😉

**Comment by tannerlinsley** [comment]
But to be clear, you can in fact do reexports of your site in v6 already without rebundling.

- `react-static bundle` - Bundles your app (mostly webpack) and preps it for export
- `react-static export` - Fetches your routes and data and exports your site to html+json. If templates have changed, this will break your site if you don't rebundle.
- `react-static build` - Does both `bundle` and `build` steps together

**Comment by tannerlinsley** [comment]
FYI, we just shipped a very experimental flag to the export command:

```sh
react-static export --incremental
```

This mode allows you to return only a subset of routes in `getRoutes` that should be re-exported. Here is the gist: https://gist.github.com/tannerlinsley/d8d167fc1afd9ee62ae5c55b115c29e5

We're still working on the details, but this should become more stable as more people try it. We will then document it as a stable feature.

**Comment by tannerlinsley** [comment]
Offical: https://github.com/nozzle/react-static/blob/master/docs/guides/incremental-builds.md

**Comment by benedfit** [comment]
@tannerlinsley I think I've found one bug, and I have one request:

Request: Could the incremental flag also be passed to `config.onBuild`? I'm aware I could check`process.env.REACT_STATIC_INCREMENTAL`, but it would be nice for it to share the same flags as `getRoutes`

Bug (potentially): When I run `react-static export --incremental`, and `buildXML` runs the resulting `<loc>` elements display `undefined` rather than the value from `config.siteRoot`. I've yet to determine whether this is a problem with my project or something that happens out of the box. I'll try to get around to testing it later today or tomorrow to confirm
