### ISSUE TITLE
TypeScript template results in extract-text-webpack-plugin error

### ISSUE THREAD

**Issue by kennu** [nozzle/react-static#767]
The default typescript template generates a project that fails to build.

### Environment

1.  `react-static --version`: 5.9.8
2.  `node -v`: v8.11.3
3.  `yarn --version`: 1.9.4
4.  Operating system: macOS High Sierra

### Steps to Reproduce the problem

1.  react-static create -n my-static-site -t typescript
2.  cd my-static-site
3.  yarn build

Result:

    Error: Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-  text-webpack-plugin for the usage example

### Expected Behavior

Expect the generated project to build successfully.

**Comment by tannerlinsley** [comment]
That plugin was just updated, so we'll take a look at this.

**Comment by johot** [comment]
I'm also seeing this, have no idea how to fix it myself :( Hope to get a fix up soon, this library looks sooo great! (Moving from gatsby to this)

**Comment by johot** [comment]
Follow up:

I actually managed to do a temporary fix, i replaced `defaultLoaders.cssLoader` in `static.config.js` with:
```
const ExtractTextPlugin = require("extract-text-webpack-plugin");
...
//defaultLoaders.cssLoader,
          {
            test: /\.css$/,
            use: ExtractTextPlugin.extract({
              fallback: "style-loader",
              use: "css-loader"
            })
          },
...
 config.plugins = [new ExtractTextPlugin("styles.css")];
```

But it feels like `defaultLoaders.cssLoader` should handle this right?

**Comment by PeterKottas** [comment]
Also bear in mind this would have to change to [MiniCssExtractPlugin](https://github.com/webpack-contrib/mini-css-extract-plugin) for v6 anyways. Depending on how far away that is, it might make sense to wait for that.

**Comment by tannerlinsley** [comment]
Does this still happen in the latest v6 beta?

**Comment by ScriptedAlchemy** [comment]
Extract text plugin should be dead by now. I hope. Use extract css chunks Webpack plugin or mini css if you don’t care about hot reloading css in dev. 

There is considerations of myself joining Webpack contribution team and taking over maintainance of miniCSS. So either way, it’s my code.  If u use RS5 use the V2of extract css chunks Webpack plugin

**Comment by tannerlinsley** [comment]
Since templates are deprecated, and there is a typescript plugin now, shall we close this?

**Comment by kennu** [comment]
At least I am happy to move on if there is now a new solution.

**Comment by tannerlinsley** [comment]
Yeah, I think that's the best option. The plugin will offer a lot more flexibility than an example that will get outdated. Let's track any issues with the plugin there from here on out: https://gitlab.com/Vinnl/react-static-plugin-typescript
