### ISSUE TITLE
Most templates fail to start / build out of the box

### ISSUE THREAD

**Issue by sharmashivanand** [nozzle/react-static#772]
So after spending quite a few hours, I decided to test every template instead of giving up.

I used the following environment. The template firebase-auth even failed to `create`. I've uploaded an 11mb archive to https://www.binaryturf.com/wp-content/uploads/2018/09/react-static-template-test.tar.bz2 with all the template code, 

Each folder has two files `start.log` and `build.log` inside each template folder (minus the node_modules else it was reaching about 3GB).

Additionally the top directory has test report and the environment details (mentioning the same here in as well)

Apologize if I made any stupid errors during testing. All templates were out of the box except for the addition of `siteRoot` var in `static.config.js`. I'm happy to test more on request. I'm not going to try some on a vanilla debian vm to see if there's something I can use.

The following was the environment:

```react-static: 6.0.0-beta.22
node: v10.11.0
yarn: 1.10.1
{ npm: '6.4.1',
  ares: '1.14.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.33.0',
  node: '10.11.0',
  openssl: '1.1.0i',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.0',
  v8: '6.8.275.32-node.28',
  zlib: '1.2.11' }
macOS High Sierra 10.13.3 (17D102)```

**Comment by tannerlinsley** [comment]
Almost all of the errors I'm seeing in these logs are babel related. It appears either a babel plugin is missing entirely, or one of them is misbehaving on your machine.

If you remove the `siteRoot` modification, do any more of them build?

**Comment by shivanandwp** [comment]
This certainly needs some verification. I wouldn't have gone through the pain of all this testing if it worked on wither of my Win 10, Mac High Sierra, Ubuntu WSL or Arch OSes.
