### ISSUE TITLE
Create a new project on Windows

### ISSUE THREAD

**Issue by jlramosr** [nozzle/react-static#774]
Hi!

I have a problem when I gonna create a new project on Windows 10:

![2018-09-28_13h21_19](https://user-images.githubusercontent.com/6153618/46205568-645db500-c321-11e8-98db-e8242ef9b109.png)

The error message is **No element indexed by 5**

I hope you can help me. Thanks!!

**Comment by jlramosr** [comment]
With version 5.9.8 it works perfectly.

**Comment by spences10** [comment]
Hey @jlramosr not relating to a solution here for this so apologies first!

Have you thought about using Windows Subsystem Linux for development?

I started using it around a year ago now (with the Fall Creators Update) and have never looked back, if you're interested take a look at these posts:

This goes over getting it installed:
https://medium.com/@philippealmoore/level-up-your-windows-web-dev-game-with-wsl-8f9e3ecd8290

And this is my setup:
https://blog.scottspence.me/wsl-setup

Also published as via freeCodeCamp:
https://medium.freecodecamp.org/automating-your-windows-subsystem-linux-setup-df4c9a7b0e7b

**Comment by Burnett2k** [comment]
I'm having the same problem. Windows should work OOTB IMO. I will switch back to gatsby rather than install a Linux subsystem.

**Comment by Herohtar** [comment]
It works out of the box on the stable branch. I wouldn't judge a project based on it's beta.

**Comment by Burnett2k** [comment]
Ah I see.  I didn't realize I was pulling down the beta when I did npm install. I will try and switch to the beta assuming they will fix the windows issue in version 6... It seems like it should pull stable by default rather than the beta?

**Comment by Herohtar** [comment]
They had some issues with tagging, but I thought @tannerlinsley had sorted it out.

**Comment by Burnett2k** [comment]
It doesn't appear so. I just had to run `npm install -g react@static@1.9.8` to get the latest build.  And it is now working for me so thanks for the heads up!

**Comment by jlramosr** [comment]
I have installed version 5.9.8 as @Burnett2k says. When I create a new project now, I have not any problems (thanks!). But when I run it with `npm start` I received the next message:

```
Error: Cannot find module '@babel/runtime/core-js/object/keys'

  - module.js:548 Function.Module._resolveFilename
    module.js:548:15

  - module.js:475 Function.Module._load
    module.js:475:25

  - module.js:597 Module.require
    module.js:597:17

  - module.js:11 require
    internal/module.js:11:18

  - transitions.js:10 Object.<anonymous>
    [my-static-site]/[material-ui]/styles/transitions.js:10:36

  - module.js:653 Module._compile
    module.js:653:30

  - module.js:664 Module._extensions..js
    module.js:664:10

  - node.js:152 Object.require.extensions.(anonymous function) [as .js]
    [my-static-site]/[babel-register]/lib/node.js:152:7

  - module.js:566 Module.load
    module.js:566:32

  - module.js:506 tryModuleLoad
    module.js:506:12


  TypeError: Cannot read property 'DIST' of undefined

  - start.js:70 Object._callee$
    [my-static-site]/[react-static]/lib/commands/start.js:70:58

  - runtime.js:62 tryCatch
    [my-static-site]/[babel-runtime]/[regenerator-runtime]/runtime.js:62:40

  - runtime.js:296 Generator.invoke [as _invoke]
    [my-static-site]/[babel-runtime]/[regenerator-runtime]/runtime.js:296:22

  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [my-static-site]/[babel-runtime]/[regenerator-runtime]/runtime.js:114:21

  - start.js:33 step
    [my-static-site]/[react-static]/lib/commands/start.js:33:191

  - start.js:33
    [my-static-site]/[react-static]/lib/commands/start.js:33:437

  - new Promise

  - start.js:33 Object.<anonymous>
    [my-static-site]/[react-static]/lib/commands/start.js:33:99

  - start.js:116 Object.start [as default]
    [my-static-site]/[react-static]/lib/commands/start.js:116:17

  - react-static-start:17 Object.<anonymous>
    [my-static-site]/[react-static]/bin/react-static-start:17:11


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-static-material-ui@1.0.0 start: `react-static start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-static-material-ui@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Thanks for all your help.

**Comment by Burnett2k** [comment]
Turns out I spoke to soon. Installing @5.9.8 allowed me to create the project, but I still get the same error when I try and actually run it using the markdown template. Here is the error:

`$ npm start

┌─────────────────────────────────────────────────────────────────────┐
│                       npm update check failed                       │
│                 Try running with sudo or get access                 │
│                to the local update config store via                 │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\Sawyer Burnett\.config │
└─────────────────────────────────────────────────────────────────────┘

> react-static-example-basic@1.0.1 start C:\git-repos\reactstatic\sawyer
> react-static start

C:\git-repos\reactstatic\sawyer\node_modules\source-map\lib\array-set.js:109
  throw new Error('No element indexed by ' + aIdx);
  ^

Error: No element indexed by 5
    at ArraySet_at [as at] (C:\git-repos\reactstatic\sawyer\node_modules\source-map\lib\array-set.js:109:9)
    at BasicSourceMapConsumer.<anonymous> (C:\git-repos\reactstatic\sawyer\node_modules\source-map\lib\source-map-consumer.js:143:67)
    at Array.map (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (C:\git-repos\reactstatic\sawyer\node_modules\source-map\lib\source-map-consumer.js:142:14)
    at buildMappingData (C:\git-repos\reactstatic\sawyer\node_modules\@babel\core\lib\transformation\file\merge-map.js:155:12)
    at mergeSourceMap (C:\git-repos\reactstatic\sawyer\node_modules\@babel\core\lib\transformation\file\merge-map.js:21:17)
    at generateCode (C:\git-repos\reactstatic\sawyer\node_modules\@babel\core\lib\transformation\file\generate.js:74:39)
    at runSync (C:\git-repos\reactstatic\sawyer\node_modules\@babel\core\lib\transformation\index.js:50:51)
    at transformSync (C:\git-repos\reactstatic\sawyer\node_modules\@babel\core\lib\transform.js:43:38)
    at Object.transform (C:\git-repos\reactstatic\sawyer\node_modules\@babel\core\lib\transform.js:22:38)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-static-example-basic@1.0.1 start: `react-static start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-static-example-basic@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by tannerlinsley** [comment]
FYI, the latest tag has been fixed. https://unpkg.com/react-static@latest once again points to https://unpkg.com/react-static@5.9.9/. Sorry for that.

As for this issue, I'm not sure what it is exactly, but it appears that babel is choking on some array-set usage. I've never seen this, and the error is pretty vague. Is there any more information you can give us? Have you upgraded to the latest stable node and npm version?

**Comment by Herohtar** [comment]
I cannot reproduce either of @jlramosr or @Burnett2k's issues with 5.9.8 on Windows using the markdown and material-ui templates. However, the array-set issue does happen for me with `6.0.0-beta.22` on the latest node.js and npm.

**Comment by jlramosr** [comment]
Exactly! I forgot to mention I had to uninstall version 5.9.8 at first and then install version 5.9.9 as @Burnett2k says.
