### ISSUE TITLE
@latest and @next point to wrong versions on npm

### ISSUE THREAD

**Issue by Herohtar** [nozzle/react-static#781]
### Problem

npm currently has `6.0.0-beta.22` listed as the current version for `@latest`, while `@next` is pointing at `6.0.0-beta.21`.

### Expected Behavior

`@latest` should point to the current stable version (`5.9.8`) and `@next` should point at the current beta.

**Comment by tannerlinsley** [comment]
Fixed. https://unpkg.com/react-static@latest => https://unpkg.com/react-static@5.9.9
