### ISSUE TITLE
Release Automation

### ISSUE THREAD

**Issue by tannerlinsley** [nozzle/react-static#784]
### Environment

1.  `react-static -v`:
2.  `node -v`:
3.  `yarn --version or npm -v`:
4.  Operating system:
5.  Browser and version (if relevant):

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  ...
2.  ...
3.  ...

**Comment by tannerlinsley** [comment]
I know that almost all of @kentcdodds's libraries implement semantic-release. We could probably learn from him how to set this up correctly.

**Comment by izilla** [comment]
Environment point 1 should be `react-static -V` not `react-static -v`

**Comment by farskid** [comment]
might be worth it to take a look at https://bumped.github.io/ as well.
