### ISSUE TITLE
PR descriptions and notes

### ISSUE THREAD

**Issue by ScriptedAlchemy** [nozzle/react-static#785]
To discuss formats of PRs, release notes, and other things related to the code collaboration conventions of this project and repo

Commitizen enforcement?

**Comment by tannerlinsley** [comment]
I like the idea of Commitizen :) https://github.com/commitizen/cz-cli

**Comment by ScriptedAlchemy** [comment]
Awesome, ill start working on a branch. Might be a great time to build a react static custom template for asking questions and such

**Comment by ScriptedAlchemy** [comment]
What do we want the prompts to be in?

Heres a few examples - its built on Inquirer.js (https://github.com/SBoudrias/Inquirer.js/) so we just need to follow its api

https://github.com/sparkbox/cz-sparkbox/blob/master/index.js
https://github.com/commitizen/cz-conventional-changelog/blob/master/engine.js

I have already installed commitizen and set it up - just need to start the discussion around what prompts we want to follow

Ill likely fork cz-conventional-changelog into a package inside RS monorepo.
