### ISSUE TITLE
Build routes from directory

### ISSUE THREAD

**Issue by Pixelatex** [nozzle/react-static#787]
Possible suggestions:

- Blacklist/whitelist? files
- Support sub routes
- Support route naming(url/slug) without the need to define them in the config file.

**Comment by tannerlinsley** [comment]
As far as I have tested, 1st level pages work great and their routes are created successfully. I simply haven't tested sub-routes yet. I believe they should theoretically work, since it is a glob callback already here: https://github.com/nozzle/react-static/blob/v6/src/static/getRoutes.js#L144-L164

**Comment by JustFly1984** [comment]
not stale
