### ISSUE TITLE
Cannot Create

### ISSUE THREAD

**Issue by izilla** [nozzle/react-static#789]
Fresh install of `yarn` and `react-static`

## Environment

```shell
> react-static -V
5.9.12
> yarn -v
1.10.1
> node -v
v8.10.0
> 
```

## Steps to Reproduce

```shell
> brew install yarn
...
> yarn global add react-static
yarn global v1.10.1
[1/4] 🔍  Resolving packages...
warning react-static > autoprefixer > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning react-static > css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning react-static > webpack-bundle-analyzer > bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
warning react-static > css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning react-static > css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed "react-static@5.9.12" with binaries:
      - react-static
✨  Done in 20.24s.
> mkdir static-site
> cd static-site
> react-static create
react-static-create(1) does not exist, try --help
```

Am I missing anything necessary in `yarn` for this to work?

**Comment by Pixelatex** [comment]
@izilla I can't reproduce this one. Are there other global packages that do work for you?

**Comment by Pixelatex** [comment]
Could be related to yarn itself. Try installing it with npm or check this post:

https://github.com/yarnpkg/yarn/issues/648

Seems like this has plagued yarn users since 2016 0.o

**Comment by izilla** [comment]
Yeah looks like on my work computer yarn v1.9.4 was installed I updated to v1.10.1 and I can repro the behavior I will try installing v1.9.4 on my local machine to see if that will work

**Comment by izilla** [comment]
OK so I worked around the issue with NPM. Could not find an easy way through `brew` to downgrade yarn since I did not have it installed. So I removed it `brew remove yarn` and installed it with npm `npm install yarn@1.9.4`. I can now run `react-static create` without issues.

**Comment by tannerlinsley** [comment]
Huzzah!

**Comment by Pixelatex** [comment]
@tannerlinsley another reason to move to npm? :p

**Comment by tannerlinsley** [comment]
Maybe... maybe it's a sign from above haha 😇

**Comment by sthciN** [comment]
First uninstall previous package, then while reinstalling put `--save` and it works.
