### ISSUE TITLE
[Plugins] react-static-plugin-gatsby-compat

### ISSUE THREAD

**Issue by sw-yx** [nozzle/react-static#792]
deleting as id like to work on other things, please open another issue if you wish

**Comment by farskid** [comment]
@sw-yx Should it be replicating a similar interface or providing a codemod?

**Comment by sw-yx** [comment]
decided not to take lead on this, am closing and removing the suggestion for now.

**Comment by Pixelatex** [comment]
Maybe keep the suggestion alive if someone else wants to pick it up?

**Comment by tannerlinsley** [comment]
I say we get more plugins and the API fleshed out a bit more before we go heads down on this. Feel free to open a new issue, but let's not prioritize it too much unless it's a clear win for the community.
