### ISSUE TITLE
[v6] - Routing - webpack alias doesnt seem to work when building the HTML

### ISSUE THREAD

**Issue by digitalkaoz** [nozzle/react-static#793]
building the assets with webpack works fine, but when the build process tries to build the HTML pages i get the following error:

```
Error: Failed exporting HTML for URL 404 (src/pages/404.jsx): Could not load React-Static routes! Please double check your webpack configuration for consistency and restart/rebuil  d your app. If this error persists, it is likely a webpack resolve.alias problem and you should file an issue at "https://github.com/nozzle/react-static/issues" ASAP.

  - routes.js:2 module.exports
    [app]/[react-static]/routes.js:2:9

  - react-dom-server.node.production.min.js:28 d
    [app]/[react-dom]/cjs/react-dom-server.node.production.min.js:28:492

  - react-dom-server.node.production.min.js:30 ua
    [app]/[react-dom]/cjs/react-dom-server.node.production.min.js:30:494

  - react-dom-server.node.production.min.js:35 a.render
    [app]/[react-dom]/cjs/react-dom-server.node.production.min.js:35:48

  - react-dom-server.node.production.min.js:34 a.read
    [app]/[react-dom]/cjs/react-dom-server.node.production.min.js:34:288

  - react-dom-server.node.production.min.js:45 renderToString
    [app]/[react-dom]/cjs/react-dom-server.node.production.min.js:45:6

  - exportRoute.js:131 renderToStringAndExtract
    [app]/[react-static]/src/static/exportRoute.js:131:21
```
i was unable to find the correct spot of this bug, the development server works fine...

**Comment by Pixelatex** [comment]
Is it on the v6 branch? Or the 5.x.x?

**Comment by dontmakemethink** [comment]
In my case it's v6.

**Comment by tannerlinsley** [comment]
This is happening for me too. Again, not sure why just yet.

**Comment by tannerlinsley** [comment]
This could be because webpack `alias's` are not being taken into account in the node environment while using the `static.____.js` bundle.

**Comment by tannerlinsley** [comment]
I think I found the issue with `nodeExternals` not bundling react-static, thus it is not being aliased. I also might have uncovered a small optimization to be made for exporting speed :)

**Comment by tannerlinsley** [comment]
I just pushed a @6.0.0-beta.25 which should (hopefully) fix the issues

**Comment by tannerlinsley** [comment]
Reopen if needed!

**Comment by tannerlinsley** [comment]
cd21cb05563cc20a17a1f11ae8692516778af4ab

**Comment by digitalkaoz** [comment]
@tannerlinsley sadly not, the issue remains the same

**Comment by tannerlinsley** [comment]
Double check please. All three projects that were experiencing that problem are now building

**Comment by dontmakemethink** [comment]
Unfortunately, it doesn't work.

1. I've changed the version to `"react-static": "6.0.0-beta.25"`, updated node modules and it wasn't working.

2. I upgraded react-static (globally) and created a new project with `basic` template.

Still the same.

**Comment by ScottSmith95** [comment]
This just popped up for me too, even after my site built several times.

**Comment by digitalkaoz** [comment]
@tannerlinsley i wrapped my head around this and i think i know what the problem is.

during webpack compilation of everything the webpack alias works as expected but this is written into the `webpack bundle`:

```js
Object.defineProperty(exports, "Routes", {
  enumerable: true,
  get: function get() {
    return _routes.default;
  }
});

var _routes = _interopRequireDefault(__webpack_require__(111));

/* 111 */
/***/ (function(module, exports) {
module.exports = require("react-static/routes");
/***/ }),
```

so when trying to dump the static html pages we have no more knowledge about the alias from `react-static/routes` to `react-static-routes.js`

i really dont get it!

**Comment by tannerlinsley** [comment]
Right. I think we can solve the problem by externalizing the require to
react static. That way webpack won't bundle it. I'll try it out in my local
branch and let you know

**Comment by digitalkaoz** [comment]
works now
