### ISSUE TITLE
[Suggestion / feature] Allow gatsby plugins to run on static

### ISSUE THREAD

**Issue by Pixelatex** [nozzle/react-static#796]
Why?
- Help gatsby developers make a transition to react-static
- Great plugins that already exist can be used by our public
- Extend the possible plugins list for RS to offer more choices

We should discuss how this should be handled, a plugin to import gatsby plugins? Native support for gatsby plugins by offering a similar api?

**Comment by Pixelatex** [comment]
@farskid What are your thoughts on we should tackle this?

**Comment by farskid** [comment]
@Pixelatex I can think of two different approaches here:

1. Replication Gatsby plugin interface. This is the easiest way in terms of DX but are we gonna have any conflicts regarding plugin permissions, available data, ...?

2. Providing a codemod with a fixed checklist of items for converting a Gatsby plugin into react-static.

**Comment by tannerlinsley** [comment]
I think it's valuable to note that the internals of each library are different enough that there will likely never be a 1:1 api for most plugins. 

If I'm being honest, I don't think a compat plugin would be much better than simply looking at the gatsby plugins and just converting them to our own versions. Thoughts?

**Comment by farskid** [comment]
If it's as different as not being able to automate, I'd say converting and listing somewhere is way easier.

**Comment by Pixelatex** [comment]
Hmm... I am indeed starting to wonder if the time spent on this will be worth it. Considering we could instead develop our own plugins instead... We could fork interesting plugins and rewire them for RS. (if this will not be an issue to the original creators)

**Comment by tannerlinsley** [comment]
Regardless, it would be beneficial to build a list of gatsby plugins that would be easy wins for react-static right now. Given that their list is fairly mature and fleshed out, we could use it to ensure that our API is covering all if not most of the bases it should.

**Comment by tannerlinsley** [comment]
Sound good. Here it is.  As for including them in this repo, that would require something like lerna... That would be a big development change, but maybe it would be good?

**Comment by Pixelatex** [comment]
Could also split our examples then using lerna? Or what that be taking it 2 far you think?

**Comment by tannerlinsley** [comment]
Possibly. We ship the examples with the repo right now as templates... not sure how that would work with lerna

**Comment by Pixelatex** [comment]
If we could have it install the examples when you need them, then we could also use the same logic to make some sort of 'react-static plugin list' that allows you to quickly install official plugins to your repo?

**Comment by tannerlinsley** [comment]
Hmm yeah. That would make installation faster (less to download). I think Lerna would be a good idea. Want to make a separate issue for that?

**Comment by Pixelatex** [comment]
Yup, on it
