### ISSUE TITLE
[feature] Implement Lerna to split plugins/examples

### ISSUE THREAD

**Issue by Pixelatex** [nozzle/react-static#797]
The idea:

We could include our plugins in this repository and turn it into a mono repository.
If we do this, we could also remove the examples from the core package and add them as their own packages, reducing the size. To accomplish this we could use https://github.com/lerna/lerna

We could pull these packages separately only when needed during the 'create' process and for plugins add some sort of list/install command that auto includes the plugin for you.

**Comment by Pixelatex** [comment]
Ticket opened after discussing this subject in issue #796.

**Comment by tannerlinsley** [comment]
This would also mean we should move back to using NPM instead of Yarn. Thoughts?

**Comment by Pixelatex** [comment]
I'm actually in favor of using npm, not really seeing much benefit to using yarn atm.

**Comment by Pixelatex** [comment]
A quick google shows that it's possible to run lerna with yarn albeit not being the most simple way to do it, it seems...

Source: https://medium.com/trabe/monorepo-setup-with-lerna-and-yarn-workspaces-5d747d7c0e91

**Comment by tannerlinsley** [comment]
I'm backpedalling on the NPM switch. Because I've got a working lerna branch with Yarn :)

**Comment by tannerlinsley** [comment]
Also, if we use yarn workspaces with lerna, we can have even more dependency sharing and quicker install times!

**Comment by tannerlinsley** [comment]
Also, this gives us a fairly easy way forward, since we can basically copy whatever gatsby has done for package infra. They are also using lerna and yarn workspaces.

**Comment by tannerlinsley** [comment]
The v6 branch is now a lerna repo :)

**Comment by Pixelatex** [comment]
You go girl!
