### ISSUE TITLE
Add example that shows TypeScript usage

### ISSUE THREAD

**Issue by D1no** [nozzle/react-static#8]
Our components are all written in TypeScript. Is there support for using TypeScript and possibly typings for react-static?

Glad to have an alternative to next.js and would love to switch.

Great Work!
Dino

**Comment by derekperkins** [comment]
@D1no We don't use Typescript ourselves, so we're not likely to add that anytime soon, but we'd be open to a PR!

**Comment by D1no** [comment]
Thats too bad. That is one of the burning issues of next.js and project groups, that already have a component library or logic. I wrote about it here; related to the blocking PR below
https://github.com/zeit/next.js/issues/2391#issuecomment-325627560
https://github.com/zeit/next.js/pull/2699

Maintaining ecmascript variations is unfortunately quite difficult outside a core team.

**Comment by derekperkins** [comment]
@D1no So you're less interested in having `react-static` type definitions and more interested in making sure that TypeScript compiles during the build cycle?

**Comment by D1no** [comment]
Yes exactly. Since everything is react — I guess the few untyped properties of react-static are discardable. But not being able to to use existing code is quite a bummer

**Comment by derekperkins** [comment]
@tannerlinsley Shouldn't that be possible?

**Comment by tannerlinsley** [comment]
Technically yes. You can use custom webpack loaders, so using a typescript
loader wouldn't be a problem at all. When using the react static browser
components, you won't have type safety. But if someone wanted to submit
types that would not be the case.

**Comment by derekperkins** [comment]
@D1no Does that give you enough to get started?

**Comment by D1no** [comment]
Sure! Thanks!

**Comment by D1no** [comment]
So I gave it a shot now on updating the rule-set for typescript. I get it to compile, but it crashes in the browser. Maybe a Webpack crack can take a look whats missing.

Essentially its about replacing the original babel rule with one that includes a pre-stage with [awesome-typescript-loader](https://github.com/s-panferov/awesome-typescript-loader#the-best-typescript-loader-for-webpack). 

#### Reproduction Repo: https://github.com/D1no/react-static-typescript
The commits detail what I needed to do to get this far.
`clone`
`yarn install`
`yarn start`


______________________


Essential config in `static.config.js`

```js
// For TypeScript Resolution
import { CheckerPlugin, TsConfigPathsPlugin } from "awesome-typescript-loader"

// (...)

  webpack: (webpackConfigurator, { dev }) => {

    // Add .ts & .tsx extension to config
    webpackConfigurator.merge({
      resolve: {
        extensions: ['.ts', '.tsx']
      }
    })

    // We can take a look at the current Webpack Config via webpackConfigurator._config
    // Lets overwrite the default rule resolution for source files found here:
    // https://github.com/nozzle/react-static/blob/master/src/rules.js#L5

    // Update Rule to use awesome-typescript-loader
    // Extending the default ruleset with typescript support (normal webpack rule)
    let typeScriptRule = {
      test: /\.(js|jsx|ts|tsx)$/,
      // Keeping the original exclude path
      exclude: webpackConfigurator._config.module.rules[0].exclude,
      use: [
        {
          loader: 'babel-loader',
        },
        {
          loader: 'awesome-typescript-loader',
        }
      ]
    }

    // Overwrite the first (original js-transform) rule with our extended version
    webpackConfigurator._config.module.rules[0] = typeScriptRule;

    // For async error reporting of as-typescript
    webpackConfigurator.plugin("typescript-checker-plugin", CheckerPlugin)

    // For resolving potential alias paths inside the typescript.json
    webpackConfigurator.plugin("typescript-path-plugin", TsConfigPathsPlugin)

  }

```

Renaming i.e. `Home.js` to `Home.tsx` transpiles without problems
![image](https://user-images.githubusercontent.com/2397125/31396410-9b186436-ade3-11e7-915f-917bb968b0bc.png)

**but** crashes terribly in the browser
![image](https://user-images.githubusercontent.com/2397125/31396455-b7dd84ca-ade3-11e7-9c23-37319ce15bb4.png)

**Comment by gloorx** [comment]
Check this
https://github.com/gloorx/nextjs-typescript-boilerplate

**Comment by tannerlinsley** [comment]
With the latest changes to version 2.0.0, this should now be extremely possible. Using the `webpack` callback you can easily modify or completely replace any aspect of the webpack config to make this work. It might take some fine tuning to get this right, but it's definitely possible now.

**Comment by BjornMelgaard** [comment]
What the current status of this? Can I help?

**Comment by D1no** [comment]
Yes - a webpack config as an example in a static.confog.je would help a lot. I am just blocked right now that I can not even get a breath of air .... far from Open Source :/

**Comment by BjornMelgaard** [comment]
@D1no so, as I understand, it's possible to make example with typescript right now? For example I can modify your Reproduction Repo and it will work?

**Comment by D1no** [comment]
The reproduction repo is on an outdated version of static-react. That needs to be updated and than possibly adapted to the new version according to the changelog. I think a normal webpack setup should do now. But I don’t have access to check myself (out of country atm)

**Comment by corydeppen** [comment]
I don't know that react-static should be advertised as having full TypeScript support yet if it's not possible to completely rename all `.js` component files to `.tsx`. I see the same console errors mentioned earlier when renaming the Home component. Has anyone been able to rename all `.js` component files to `.tsx` and successfully compile and run the TS example?

**Comment by D1no** [comment]
I think that is a harsh assumption. TypeScript, like Babel, is a preprocessor of which presets in babel and compiler options / definition files are an extension. React-Static compiles all .tsx files, allows to use typescripts flexible paths options, includes hot module replacement and compiles — none-the-less — of warnings the typescript language service may throw up in your EDI.

Definition files are very straight forward and I invite anyone to update them along with the changes to the codebase. However, even if those would not exist or overwritten by the user, all typescript code will be transpiled and handled without problems.

So from my point of view, and probably @tannerlinsley's, full support is there. The definition file should be maintained for the language service for which I am happy to see support from any side possible.

Best
Dino
