### ISSUE TITLE
Styled Components dont work in 2.x.x

### ISSUE THREAD

**Issue by rdfriedl** [nozzle/react-static#80]
just thought id give you guys a head up that the `styled-components` example dose not work with `react-static@2.x.x`

do you guys know of any changes that might have broken it?
Im not super knowledgeable about `styled-components` although id be willing to look into fixing this issue if you could point me in the right direction

**Comment by tannerlinsley** [comment]
This is a known bug. Fix will be out by morning.

**Comment by tannerlinsley** [comment]
Please upgrade to the next major version 3.0.0.
Refer to the changelog for migration :)
https://github.com/nozzle/react-static/blob/master/CHANGELOG.md
