### ISSUE TITLE
Manage nested routes as children in sub-components ?

### ISSUE THREAD

**Issue by ostrebler** [nozzle/react-static#800]
Hey,

I just got started with react-static and it's awesome.

So I'm building a multi-language blog and I have some issues when it comes to nested routing. I don't actually know if that's a help or a feature request. Here is what I wanna do on the static.config.js side :

```
getRoutes: async () => {
    const graph = await dataToGraph(['author', 'language', 'post'])
    return [
      {
        path: '/',
        redirect: '/fr'
      },
      ...graph.language.map(language => {
        const posts = filter(graph.post, { language: language.title })
        return {
          path: `/${language.code}`, // like "en" or "fr"
          component: 'src/containers/Home',
          getData: () => ({ language }),
          children: [
            {
              path: '/about',
              component: 'src/containers/About',
              getData: () => ({ language })
            },
            {
              path: '/blog',
              component: 'src/containers/Blog',
              getData: () => ({ posts, language }),
              children: posts.map(post => ({
                path: `/${post.slug}`,
                component: 'src/containers/Post',
                getData: () => ({ post, language })
              }))
            }
          ]
        }
      }),
      {
        is404: true,
        component: 'src/containers/404'
      }
    ]
  }
```

So this generates routes like : 
```
/fr
/en/about
/fr/blog/my-post-slug
...
```

I'm stuck with the react part. Is it possible to manage a generic layout in my Home component ?

In the netlify-cms model, the layout and all the routing is done in App.js. I would like to show an internationalized nav bar, so it has to be rendered in the Home component because otherwise it doesn't know about the language. In other words, is it possible to render Home's children somewhere in the Home component ?

In dynamic React, I would do that by adding adding a Switch in App.js for the /fr and /en routing, and another Switch in the Home component just after the nav bar.

Thank you.

**Comment by tannerlinsley** [comment]
Even in a non-route file like App.js or Nav.js, you can use `RouteData` to get at the `language` prop. Doing that allows you to do internationalization at the component level (as long as every route in your app is guaranteed to have a `language` prop sent to it in the route data.

Does that help?

**Comment by tannerlinsley** [comment]
Also, for the sake of triaging, I would suggest closing this issue (I would classify it as an implementation question that has been solved by others already) and searching/reasking it on the support forum: spectrum.chat/react-static

**Comment by ostrebler** [comment]
That may help, thank you ! I'll close.
