### ISSUE TITLE
Styled Components Plugin FOUC

### ISSUE THREAD

**Issue by DanWebb** [nozzle/react-static#810]
**Describe the bug**
Since upgrading to use the styled-components plugin I'm experiencing Flash Of Unstyled Content in production

**To Reproduce**
Steps to reproduce the behavior use react v6 beta with the [styled-components plugin](https://github.com/nozzle/react-static/blob/v6/packages/react-static-plugin-styled-components)

**Expected behavior**
For the page to load without waiting for JS to load before styles.

**Browsers, Devices & Versions:**
Desktop: Tested on Mac latest Chrome & Safari
Mobile: Tested on Safari IOS
React static: Tested versions v6.0.0-beta.26 (with [new plugin](https://github.com/nozzle/react-static/blob/v6/packages/react-static-plugin-styled-components)) and v6.0.0-beta.22 (with [old plugin](https://github.com/nozzle/react-static-plugin-styled-components))
Styled components: v3.4

**Additional context**
I never experience the error previously without the plugin like in the [styled-components example](https://github.com/nozzle/react-static/tree/master/examples/styled-components) but I get an "Invariant Violation" stemming from the `renderToHtml` method when using this example with latest versions of react static + I'd rather make the effort to get the plugin working.

I'm wondering if the way the `Head` hook in the plugin API works similar to react helmet? If so it may be related to https://github.com/nfl/react-helmet/issues/291, any thoughts?

**Comment by tannerlinsley** [comment]
This was actually a problem with the rendering and extraction happening within different require contexts (bundled vs node). This will be fixed in the next beta.
