### ISSUE TITLE
Run Babel in node_modules 

### ISSUE THREAD

**Issue by philipp-spiess** [nozzle/react-static#816]
**Describe the bug**

react-static can not minify the main entry-point because it pulls in a dependency that uses newer JavaScript features than UglifyJS can handle.

```
ERROR in main.51c74111.js from UglifyJs
Unexpected character '`' [/Users/redacted/dev/this-week-in-react/node_modules/performance-now/index.js:21,0][main.51c74111.js:12593,20]
```

**To Reproduce**

1. Check out the repo at https://github.com/philipp-spiess/this-week-in-react/pull/10
2. Run `yarn && yarn build`

The package that is causing issues, `performance-now`, seems to be pulled in via `raf` which is a dependency of `react-static`:

```
β this-week-in-react (react_static) yarn why performance-now
yarn why v1.12.0
[1/4] 🤔  Why do we have the module "performance-now"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "performance-now@2.1.0"
info Reasons this module exists
   - "react-static#raf" depends on it
   - Hoisted from "react-static#raf#performance-now"
   - Hoisted from "open-graph-scraper#request#performance-now"
   - Hoisted from "react-static#download-git-repo#download#decompress#performance-now"
info Disk size without dependencies: "16MB"
info Disk size with unique dependencies: "36MB"
info Disk size with transitive dependencies: "36MB"
info Number of shared dependencies: 1
✨  Done in 0.71s.
```

**Expected behavior**

The build script displays no errors, the main.js artifact ends up being is compressed. 

**Desktop (please complete the following information):**
 - OS: macOS 10.13.5
 - Node.js: v9.7.1
 - Yarn: 1.12.0

**Comment by 0x6431346e** [comment]
Same error here...

to reproduce:
1. `react-static create`
2. `yarn add is-ipfs`
3. add `import 'is-ipfs'` somewhere
4. `yarn build`

gives:
> ERROR in main.1efbb910.js from UglifyJs
Unexpected token: name (encoded)

Stacktrace: https://github.com/multiformats/js-multihash/blob/master/src/index.js#L63

**Comment by stefanprobst** [comment]
@philipp-spiess Are you sure this is an issue with `react-static`? I checked out the repo in the issue you linked to and there's something weird going on:
```bash
$ cat node_modules/performance-now/package.json | grep name
"name": "strip-dirs",
```
After manually removing `yarn.lock` and reinstalling, the build went through without problems.

**Comment by philipp-spiess** [comment]
Oh wow 😱. I wonder how that is even possible. You're totally right this seems to be a yarn screw-up. Thanks for digging in! 

I'll leave it to you to close this ticket or keep it for the comment of @0x6431346e.

**Comment by 0x6431346e** [comment]
This is still a problem, one thing to note though, it errors only when building, using the package in development works.

Repo:
https://github.com/0x6431346e/build-error-repro/

I don't think this is a problem with the `multihashes` package, it looks fine, but I guess it could be...

**Comment by stefanprobst** [comment]
> I don't think this is a problem with the `multihashes` package, it looks fine, but I guess it could be...

Could you double-check? Building `multihashes` throws a `TypeError` for me.

**Comment by koalalorenzo** [comment]
@stefanprobst what is the complete error?

**Comment by tannerlinsley** [comment]
Node modules should always be compiled

**Comment by stefanprobst** [comment]
> Node modules should always be compiled

Sorry for being unclear: the question is whose responsibility it is: the library's or the app that uses the library. Even though `create-react-app` v2 [apparently now compiles dependencies in `ǹode_modules`](https://github.com/facebook/create-react-app/pull/3776) I think it's still expected that `main` in package.json points to ES5 code.

**Comment by tannerlinsley** [comment]
Yep. CRA is only compiling node modules for es6 import and interopability I
think. Same as us.

**Comment by digitalkaoz** [comment]
@tannerlinsley another issue which would be solved by #845

**Comment by ScriptedAlchemy** [comment]
Can those experienceing issues try turning off uglification? I’ve seen it cause problems like this before. Let me know if you remove uglifyjs. Do you still have the same problems?

**Comment by tannerlinsley** [comment]
With #845, I think we can close this. We are following CRA's external babel loader example exactly, and there is the escape hatch with `config.babelExcludes`.

**Comment by ScriptedAlchemy** [comment]
that's an acceptable solution in my opinion.

try Tanners solution and let us know if it resolves the problem
