### ISSUE TITLE
Eject webpack config

### ISSUE THREAD

**Issue by PeterKottas** [nozzle/react-static#817]
**Is your feature request related to a problem? Please describe.**
I am playing with react-static for the last day or 2. I have to modify the webpack config quite a lot (as I use typescript scss and some other stuff), which got me thinking. Wouldn't it make sense to add ability to eject webpack.config? Webpack config in react.static.config could then point to a file on disk. The thing is, I find it quite hard to understand what's included and what's not and how to make the most of existing defaults. I know that the motivation is 0-config that fits most people, but in reality, I am afraid every major website will need to modify this quite a lot. Also I've seen the react-static package.json and all of the build loaders/pugins are in there as opposed to client app. While I see the point of having this "under control" from react-static package, I just want to point out this also makes it harder to know what is installed already. I for example end up installing all css/style-loaders again in my app as I need to override some stuff. While this works, I am just a little bit afraid of some possible version clashes. Although at the same time, I am not exactly sure if this can be fixed. Maybe just documented better (have a list of plugins/loaders etc that you can use out of the box)

**Describe the solution you'd like**
Ability to eject webpack config (probably command line api)

**Describe alternatives you've considered**
Maybe at least log the final webpack config so that I can see what ends up in there

**Additional context**

**Comment by Pixelatex** [comment]
We could make a more documented 'how-to-extend-webpack' or extend the api for it more but the option to eject doesn't seem like it's gonna be worth it to me tbh.

**Comment by tannerlinsley** [comment]
Yeah, ejecting is not going to be an option. RS integrates with so many points of the config, which is why extension/modification is much better in this case. The minute you eject, you would cease to get updates and bug fixes to a very complex and streamlined webpack process.

I think the solution is to 
- Better document the default webpack config/loaders/plugins, 
- Educate on what parts of the webpack should not be modified (lest you break RS).
- Improve our examples on how to modify the webpack config.
- Move most of the webpack configuration use-cases to plugins.

**Comment by Pixelatex** [comment]
Moving the use-cases to plugins is probably the most important approach here as it removes the need to tinker with webpack and makes the whole thing more user-friendly.

**Comment by tannerlinsley** [comment]
I agree. For example, this issue is mostly about typescript and scss. Both of which are plugins that we can isolate and perfect in their own right. Once we do that, the work is done and installable with ease :)

**Comment by PeterKottas** [comment]
All above sounds good to me! The fear of breaking rs is making working with it rly uncomfortable at the moment. Looked at the early docs on plugins and I must say it sounds very promising. I have one pointer there though. 
If I understand it correctly, right now you provide a plugin name, and it either looks in plugins folder in root, or for an installed npm package. Would it also make sense to allow import/require from some other location? Similarly, in webpack you can do require('ts-loader') or just 'ts-loader'.
That being said, I am new and only getting up to speed with your v6 efforts. So this might have already been done or changed :)

**Comment by tannerlinsley** [comment]
You can achieve a similar implementation in v6 by doing
```javascript
plugins: [require.resolve('path/to/my/plugin/directory')]
```

The reason for this is that plugins are not single files. They are a collection of `node.api.js` and `browser.api.js`.

**Comment by PeterKottas** [comment]
Ah I see. That makes perfect sense then. Thanks!

**Comment by PeterKottas** [comment]
I assume I can close this now as after reading
- Better document the default webpack config/loaders/plugins,
- Educate on what parts of the webpack should not be modified (lest you break RS).
- Improve our examples on how to modify the webpack config.
- Move most of the webpack configuration use-cases to plugins.
It's clear you are aware of the "problem" and hopefully it will improve with v6.
Actually, if you don't mind me asking, is there any release date available for v6? I tried asking on spectrum chat but no reply so far. Definitely not interested in hearing actual dd/mm, just would love to know if it's days/weeks/months away. I am considering rewrite of our marketing page, but it can wait a bit if I could save some time rewriting v5 to v6 then.

**Comment by tannerlinsley** [comment]
I would like to have v6 out in a month, which seems definitely doable with our changes and momentum. There's always the possibility of a terrible bug hunt or change of scope, but I don't foresee that happening.

**Comment by PeterKottas** [comment]
Great that works perfect for me. I'll just prepare everything for the move and do the actual work when v6 lands. Thanks for the info!
