### ISSUE TITLE
material-ui template is using react-jss, but not included in the package.json

### ISSUE THREAD

**Issue by Rantelo** [nozzle/react-static#818]
**Describe the bug**
when running `yarn start` after creating a site with `material-ui` template, it throws an error saying `Cannot find module 'react-jss/lib/jss`

**To Reproduce**
1. Create a new project with `react-static create`
2. Select `material-ui` template
3. Run dev-server with `yarn start`
```
$ react-static start
  Error: Cannot find module 'react-jss/lib/jss'
  
  - module.js:542 Function.Module._resolveFilename
    module.js:542:15
  
  - module.js:472 Function.Module._load
    module.js:472:25
  
  - module.js:585 Module.require
    module.js:585:17
  
  - module.js:11 require
    internal/module.js:11:18
  
  - static.config.js:3 Object.<anonymous>
    /home/imuser/Documents/site/personalblog/static.config.js:3:1
  
  - module.js:641 Module._compile
    module.js:641:30
  
  - node.js:144 loader
    [personalblog]/[babel-register]/lib/node.js:144:5
  
  - node.js:154 Object.require.extensions.(anonymous function) [as .js]
    [personalblog]/[babel-register]/lib/node.js:154:7
  
  - module.js:560 Module.load
    module.js:560:32
  
  - module.js:503 tryModuleLoad
    module.js:503:12

```

**Expected behavior**
It should start dev-server using the template

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 LTS
 - Browser Chrome Version 68.0.3440.84 (Official Build) (64-bit)

**Additional context**
I don't think this issue is related to react-static by itself, because I tried other templates and they worked just fine.
I believe the issue is related with the template

**Comment by Herohtar** [comment]
This can be resolved with a simple `yarn add react-jss` or `npm i react-jss`. Material UI removed their `react-jss` dependency in version `3.2.0` so it no longer gets pulled in automatically.

**Comment by Rantelo** [comment]
> This can be resolved with a simple `yarn add react-jss` or `npm i react-jss`. Material UI removed their `react-jss` dependency in version `3.2.0` so it no longer gets pulled in automatically.

Great! It worked
Any reason to delete `react-jss` from the package.json?
If there is not, I can file a PR addition of the missing library
