### ISSUE TITLE
[v6] Preloader is a bit aggressive - non-local, protocol (tel/mailto), and others not getting cleaned out

### ISSUE THREAD

**Issue by tannerlinsley** [nozzle/react-static#822]
The preloader is currently attempting to fetch `routeInfo` for pages that are clearly not able to be react-static pages. These include non-local pages and non-http(s) protocols.

**To Reproduce**
- Place a link to https://google.com in a v6 site.
- Start the dev/build process and serve the site.
- Navigate to the page with the google link and watch the network tab.

**Expected behavior**
https://google.com should not make an attempt to load, since it is an external link that does not start with the siteRoot

**Comment by dicarlo2** [comment]
FWIW - using `onMutation` heavily assumes that the website is relatively static. We use react-static to deploy our entire website, including pages that are extremely dynamic - to be specific, they mutate the dom on every key press.

AFAICT - another issue is that it adds all links on the page on //every// mutation, rather than just the newly added links.

**Comment by tannerlinsley** [comment]
Yeah, I've tested the preloader with keyboard-level events like that on pages with hundreds of visible links and it seems to to really well, even with cpu throttling to simulate mobile devices. My guess is that it should work okay for now, and as we discover bottle necks we can make the watcher more performant.

One optimization we could do immediately, like you said, is to make the selector only function on descendants of the added/mutated nodes, instead of the whole document.

**Comment by digitalkaoz** [comment]
this hit me aswell...maybe a simple protocol/domain compare can fix this?

**Comment by tj** [comment]
Could the preloading be done on hover / proximity instead? I remember playing with some click latency thing, and there's around 300m-500ms between most people's clicks after they hover a link, plenty of time to fetch a page

**Comment by tannerlinsley** [comment]
This is a great idea. I'm actually slowly working out the details to allow plugins to control the nature of the preloader. This way you could technically import a community shared preloader, or write/configure any preloader to your liking.

**Comment by tj** [comment]
I suppose you could also just crank up the proximity threshold to enable the current behaviour (more or less) as well

**Comment by tannerlinsley** [comment]
Fixed with #855

**Comment by buzinas** [comment]
#855 is an issue… what's exactly the underlying PR?
