### ISSUE TITLE
Getting "TypeError: Object(...) is not a function" in the console, in the build package

### ISSUE THREAD

**Issue by maduraPradeep** [nozzle/react-static#823]
**Describe the bug**
Getting "Uncaught TypeError: Object(...) is not a function" issue in the build package. Seems it is generating from preact library. This issue has in preact examples of both v5 and v6. This is only occurring in the build and stage packages.

**To Reproduce**
1. Create preact example with `npx react-static create`
2. Build the package `yarn build`
3. Serve build package `yarn serve`
4. Go to the serve url
5. Open the browser console and you will see the error

**Expected behavior**
There shouldn't be any errors in build package

**Screenshots**
![screenshot from 2018-10-18 10-41-00](https://user-images.githubusercontent.com/2541823/47132610-74363c80-d2c2-11e8-9aa2-59b97251948f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Desktop 18.04
 - Browser Chrome
 - Version 69.0.3497.92

**Additional context**
The issue is not a browser specific issue. Checked on Brave browser as well.

**Comment by LauraBeatris** [comment]
I'm having the same issue @maduraPradeep Did you discover what it was?
