### ISSUE TITLE
react-static build not bundling React for production properly

### ISSUE THREAD

**Issue by jamesplease** [nozzle/react-static#825]
:wave: hi react-static team!

**Describe the bug**

I would expect that running `react-static build` would build a production version of my app, based on the react-static [docs](https://github.com/nozzle/react-static#quick-start).

![image](https://user-images.githubusercontent.com/2322305/47187222-2af8e380-d2e8-11e8-8936-6bdf3ecd9338.png)

And, I believe that this had been working for me. However, recently, builds have been showing me:

![image](https://user-images.githubusercontent.com/2322305/47187245-38ae6900-d2e8-11e8-97dc-626694e5aea1.png)

My build script is as follows:

```
"build": "npm run copy-css-files && react-static build",
```

**To Reproduce**

Follow the instructions [here](https://github.com/jamesplease/materialish/blob/master/CONTRIBUTING.md#contributing-to-the-docs) to run the docs of the project Materialish.

Or, you can navigate to [materialish.js.org](materialish.js.org) to see the end result of the build step.

**Expected behavior**

I would expect the build step that I have configured to build React properly (check the console for the warning).

I'm pretty sure this wasn't happening before, so I'm not sure what's up.

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version:  69.0.3497.100

**Comment by lifez** [comment]
Anyone facing this ?
