### ISSUE TITLE
is there any internationalization solution here

### ISSUE THREAD

**Issue by pomelo-nwu** [nozzle/react-static#827]
Hello, is there any internationalization solution here, such as `home.en-US.md `and `home.zh-CN.md` as data sources?

**Comment by pomelo-nwu** [comment]
> Hi, you can search on the spectrum.chat channel you'll find discussion like this one: https://spectrum.chat/react-static?thread=389ecf11-6c0d-4c86-a059-a69dbd8e3a8d
okay，thanks

**Comment by Pixelatex** [comment]
Closing the ticket as it's not a bug and/or really react-static specific enough.
