### ISSUE TITLE
[v6] 404.html is not generated

### ISSUE THREAD

**Issue by dicarlo2** [nozzle/react-static#832]
**Describe the bug**
404 page is output to a subdirectory rather than in the root.

**To Reproduce**
Build anything - notice that it outputs a 404 page to 404/index.html

**Expected behavior**
Outputs to 404.html

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
Bug is here: https://github.com/nozzle/react-static/blob/v6/packages/react-static/src/static/exportRoute.js#L243

Should be `route.path === '404'` (no leading slash), or even better, `route.path === getRoutePath('/404')` in case you change the format of a normalized route path.

**Comment by Herohtar** [comment]
@tannerlinsley This issue got closed by stale-bot, but I am encountering this issue in `v6.0.14`.

**Comment by tannerlinsley** [comment]
Can you post a link to your repo?

**Comment by Herohtar** [comment]
Sure, it's here: https://github.com/Herohtar/thalion-herohtar

**Comment by Herohtar** [comment]
@tannerlinsley Still seems to be not generating on my site even with the 404-related changes in `v6.0.15`. Am I doing something wrong?

**Comment by Herohtar** [comment]
Looks good now!

**Comment by tannerlinsley** [comment]
Awesome. Thanks for the help!
