### ISSUE TITLE
Not successfully generating build, but working locally?

### ISSUE THREAD

**Issue by andrewmartin** [nozzle/react-static#843]
First off, thanks for building this project; it's made developing a static site a breeze...

However, I'm running into a very bizarre and confusing issue, and am hoping someone can help. I have built and am running successfully locally.

Here's my `static.config.js`. From what I can tell, everything should be setup correctly, but I'm hitting a really weird issue where only the root path (`src/containers/Home`) shows up.

I'm using a simple aws script to sync up to an S3 bucket.

This page, which is fully developed locally (if you view the source, it actually is loading fine), isn't resolving completely. 
https://s3-us-west-1.amazonaws.com/dynastyweb/case-studies/roco/index.html

```js
export default {
  siteRoot: 'https://s3-us-west-1.amazonaws.com/',
  basePath: 'dynastyweb',
  getSiteData: () => ({
    title: 'React Static'
  }),
  getRoutes: async () => {
    return [
      {
        path: '/',
        component: 'src/containers/Home'
      },
      {
        path: '/about',
        component: 'src/containers/About'
      },
      {
        path: '/case-studies',
        component: 'src/containers/CaseStudies',
        getData: () => ({
          items: caseStudies
        }),
        children: caseStudies.map(study => {
          const slug = slugify(study.title.toLowerCase());
          return {
            path: `/${slug}`,
            component: 'src/containers/CaseStudy',
            getData: () => ({
              items: caseStudies,
              data: { ...study }
            })
          };
        })
      },
      {
        is404: true,
        component: 'src/containers/404'
      }
    ];
  },
  webpack: (config, { defaultLoaders, stage }) => {
    let loaders = [];

    if (stage === 'dev') {
      loaders = [{ loader: 'style-loader' }, { loader: 'css-loader' }, { loader: 'sass-loader' }];
    } else {
      loaders = [
        {
          loader: 'css-loader',
          options: {
            importLoaders: 1,
            minimize: stage === 'prod',
            sourceMap: false
          }
        },
        {
          loader: 'sass-loader',
          options: { includePaths: ['src/'] }
        }
      ];

      // Don't extract css to file during node build process
      if (stage !== 'node') {
        loaders = ExtractTextPlugin.extract({
          fallback: {
            loader: 'style-loader',
            options: {
              sourceMap: false,
              hmr: false
            }
          },
          use: loaders
        });
      }
    }

    config.module.rules = [
      {
        oneOf: [
          {
            test: /\.s(a|c)ss$/,
            use: loaders
          },
          defaultLoaders.cssLoader,
          defaultLoaders.jsLoader,
          defaultLoaders.fileLoader
        ]
      }
    ];
    return config;
  }
};
```

Can someone let me know where to even begin looking here? I'm really confused what could be happening, as the files and build are completely generating.

**Comment by andrewmartin** [comment]
I should mention that this is working perfectly swimmingly locally, no issues at all when I navigate to `/case-studies/roco` locally.

Is there something funky I'm doing when I'm generating the dynamic paths?

**Comment by andrewmartin** [comment]
Also, finally, should mention that locally, if I serve the `./dist` directory, the pages work too. Wondering if this is something weird with my S3 deploy?

**Comment by andrewmartin** [comment]
Whoops!

http://dynastyweb.s3-website-us-west-1.amazonaws.com/case-studies/roco/

This loads just fine. Sorry! Shouldn't have included the extension...

**Comment by digitalkaoz** [comment]
so it can be closed?

**Comment by andrewmartin** [comment]
Yes, please feel free to close. Apologies!
