### ISSUE TITLE
Styled Component not working on page refresh

### ISSUE THREAD

**Issue by jablonnc** [nozzle/react-static#85]
The following issue only occurs if I refresh on a route other than the main entry route (i.e. the splash screen).

**Issue Exists**
In this example, I have defined a simple link component that gets exported in the following manner.
<img width="354" alt="return-functional-component" src="https://user-images.githubusercontent.com/1964654/31944369-d4e5fc08-b899-11e7-8d86-6edadab04649.png">

When I refresh the page (assuming I'm not refreshing on the main entry screen), you can see the styled-component fails to inject the css into the page (class has no corresponding styles):
<img width="986" alt="link-on-refresh" src="https://user-images.githubusercontent.com/1964654/31944392-e8e257ce-b899-11e7-99a4-6d0f86664e8b.png">

**Issue Goes Away**
If I update this component to return itself in the following manner: 
<img width="330" alt="return-styled-link" src="https://user-images.githubusercontent.com/1964654/31944469-363b91ca-b89a-11e7-8f5d-891f70792332.png">

You can now see the styles are in fact applied on refresh:
<img width="921" alt="link-on-router-nav" src="https://user-images.githubusercontent.com/1964654/31944460-2de725d4-b89a-11e7-8ef9-5fb3df11d200.png">

I should note, I tried updating to 3.0.0 and that has not resolved the issue.  Any thoughts?

You can see the issue in the following project: https://github.com/jablonnc/react-static-styled-component-issue

**Comment by tannerlinsley** [comment]
Have you tried not naming both items `Link`?

**Comment by jablonnc** [comment]
This issue has been fixed as of react-static version 3.0.1+.  However naming both items link like we did above was probably not a great convention, so we've since reworked the structure of a component as well.
