### ISSUE TITLE
[v6.beta.30 bug] Then I navigate back via window.history.goback() on dynamic routes, I got this error:

### ISSUE THREAD

**Issue by JustFly1984** [nozzle/react-static#851]
**Describe the bug**
If I navigate back (there is no other way no go back with @reach/router), I got this error:
```
index.js:1455 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Routes (at StaticInfo.js:12)
    in Component (at app.js:319)
```

**Expected behavior**
Error is self describing

**Screenshots**
<img width="809" alt="screenshot 2018-11-08 20 55 06" src="https://user-images.githubusercontent.com/2255993/48238352-bf5edf00-e398-11e8-8eee-2a7a429ba940.png">

**Comment by tannerlinsley** [comment]
Fixed in latest beta
