### ISSUE TITLE
React-Static Router autoScrollToHash prop  not working

### ISSUE THREAD

**Issue by sallynorthmore** [nozzle/react-static#852]
**Describe the bug**
I want to remove the `autoScrollToHash` feature that comes with react-static's `^5.9.12`.  

Following the instructions in the Router docs has no effect: https://react-static.js.org/docs/components#router

**To Reproduce**
1. `react-static create`
2. Select `sass` 
3. cd into project, `npm i`
4. Edit `App.js` so that Router contains prop: `<Router autoScrollToHash={false}>`
5. `npm start`
6. Observe clicking on an anchor link still scrolls to hash anchor instead of jumping

**Expected behavior**
No scrollToHash behavior once I set the prop to false, per your documentation

```
app.js

import React from 'react'
import { Router, Link } from 'react-static'
import { hot } from 'react-hot-loader'
//
import Routes from 'react-static-routes'

import './styles/css/global.css'

const App = () => (
  <Router autoScrollToHash={false}>
    <div className="App">
      <div className="App-content">
        <Routes  />
      </div>
    </div>
  </Router>
)

export default hot(module)(App)

```

**Comment by Jojocaster** [comment]
I'm also running into this issue, is there any way to fix it ?

**Comment by tannerlinsley** [comment]
If you are referencing the animated scroll to hash, then you'll be glad to know it's been fixed in v6!

**Comment by Jojocaster** [comment]
Cheers ! 🎉
