### ISSUE TITLE
[5.9.12] Large bundle size (no tree shaking)

### ISSUE THREAD

**Issue by dontmakemethink** [nozzle/react-static#856]
**Describe the bug**
I use rxjs@6 in my app **(react-static 5.9.12**). After the build process every operator is in the bundle what makes it quite large.

I think it's related to: [https://github.com/ReactiveX/rxjs/issues/3765](https://github.com/ReactiveX/rxjs/issues/3765)
As far as I understood, there is `babel-preset-env` package which transforms es6 module syntax to commonjs and it makes tree-shaking impossible. I've tried set babel-preset-env `modules` option to false but instead I got the following error on build: 
```
  Error: /projects/repro/static.config.js:1
  (function (exports, require, module, __filename, __dirname) { import _regeneratorRuntime from 'babel-runtime/regenerator';
```

**To Reproduce**
1. `react-static create` & select basic template
2. `yarn add rxjs`
3. add some rxjs code to the app, eg.:
```
import { interval } from 'rxjs';
import { sample } from 'rxjs/operators';

const source = interval(1000);
const example = source.pipe(sample(interval(2000)));
const subscribe = example.subscribe(val => console.log(val));
```

4. `yarn build`
5. run `webpack-bundle-analzyer dist/client-stats.json dist` (must have webpack-bundle-analzyer installed globally)

**Expected behavior**
Bundle should contain only used rxjs operators.

**Screenshots**
<img width="1278" alt="screen shot 2018-11-19 at 22 18 54" src="https://user-images.githubusercontent.com/22578496/48736257-15f6d380-ec4b-11e8-98dd-2c934e717b66.png">

How to deal with this? Please help 😢
Thanks

**Comment by Pixelatex** [comment]
Hmm to be fair, not sure this is an RS-specific issue, more of a babel issue. There are quite a few modules that don't play well with tree shaking as I've noticed.

**Comment by ScriptedAlchemy** [comment]
This is caused by a few things. 

Some architectural challenges of RS5, the limitations of older Webpack, some limitations of my own software at the time. 

Unfortunately the old aggressive code splitting plugin available in Webpack 2,3 is not compatible with the versions of m software that support Webpack 2,3

RS6 does a better job, and some of its underlying codebase which I own, now supports more aggressive and advanced code splitting
