### ISSUE TITLE
[v5] cannot do truly dynamic import: Property value expected type of string but got null

### ISSUE THREAD

**Issue by sw-yx** [nozzle/react-static#858]
**Describe the bug**

This works:

```js
    componentDidMount = () => {
      import('../Test.mdx').then(Thing =>
        this.setState({ Thing: Thing.default })
      );
    };
```

but this doesnt work

```js
    componentDidMount = () => {
      const path = '../Test.mdx';
      import(path).then(Thing =>
        this.setState({ Thing: Thing.default })
      );
    };
```

It generates this opaque compile error:

```bash
Failed to build! Fix any errors and try again!
./src/containers/Home.js
Module build failed: TypeError: /Users/swyx/Work/react-static-mdx/src/containers/Home.js: Property value expected type of string but got null
```

I assume it has something to do with this babel plugin: https://github.com/airbnb/babel-plugin-dynamic-import-node/issues/15

Is this "truly dynamic" kind of import supported? or am I doing something wrong?

**Desktop (please complete the following information):**
 - OS: ios
 - Browser: chrome
 - Version: v5.9.12

**Additional context**
just trying to make dynamically importing components based on route data

**Comment by montezume** [comment]
@sw-yx if this helps, this seems to work.

```js

const path = "components/MyComponent";

const MyComponent = universal(import(`../${path}`), {
  loading: Loading,
  error: Failed
});
```

**Comment by ScriptedAlchemy** [comment]
Hey all. Let me know if there’s unanswered questions. I’m on my mobile but will re-read the issue. Universal needs then on the end to actually kick things off under the hood. 

It looks like a promise, but “then” is a custom function that must be envoked to make it work. 

If you use Babel-plugin-Universal-import. Then don’t use other “import” Babel plugins other than the syntax one as they conflict.  

Feel free to tag me in any code splitting issues directly. For obvious reasons, I should be able to help!

**Comment by ScriptedAlchemy** [comment]
Remember, import is actually transformed into a specification that  James and myself maintain. More can be read on react universal components repo. 

Good news: RUC showed up as a dependent for React, so the universal to suspense api should hopefully be an easy port

**Comment by sw-yx** [comment]
i didnt manage to get around to this in the end. was trying to build a framework on top of react-static that dynamically imports mdx files. too much context switching right now for me to get back to this but i will probably come back for it sometime in future. will close for now until i have time ot get back to this. thank you Zack and Malcolm!

**Comment by ScriptedAlchemy** [comment]
Alrighty! Good luck! I know context switching can get to us when the quantity starts increasing. 

Here if you need me!
