### ISSUE TITLE
React-Static NPM Vulnerable Package: webpack-dev-server <3.1.6

### ISSUE THREAD

**Issue by zach-snell** [nozzle/react-static#863]
**Describe the bug**
When installing related packages, react-static is attempting to install vulnerable package: 

                       === npm audit security report ===
                                 Manual Review
             Some vulnerabilities require your attention to resolve
          Visit https://go.npm.me/audit-guide for additional guidance

            High            Missing Origin Validation
            Package         webpack-dev-server
            Patched in      >=3.1.6
            Dependency of   react-static
            Path            react-static > webpack-dev-server
            More info       https://nodesecurity.io/advisories/725

**To Reproduce**
1. node-static create
2. Name it
3. Choose Template (I chose Material Design)
4. Installation seems to freeze, likely a suppressed error. Did not dig here.
5. terminal/cmd to created directory
6. npm install or yarn install
7. Note vulnerability alert

**Expected behavior**
node-static create should run and install with all packages without error or vulnerability.

**Screenshots**
![image](https://user-images.githubusercontent.com/10632545/49323948-af46a500-f4e9-11e8-81ca-d363f10ce461.png)

**Desktop (please complete the following information):**
 - OS: Win10x64
 - Browser N/A
 - Version N/A

**Additional context**
Clean install.

**Comment by ScriptedAlchemy** [comment]
If you upgrade Webpack dev server, does the venerability go away?

Sometimes it’s super hard to resolve dev only venrubilities, as nobody’s hacking localhost.

**Comment by tannerlinsley** [comment]
This is no longer an issue in v6 and as stated, it is a dev dependency.
