### ISSUE TITLE
The problem of using CSS module in react-static

### ISSUE THREAD

**Issue by lz-allen** [nozzle/react-static#864]
The Html page packaged in the development environment contains the class name, which will be lost in the production environment.The problem of using CSS module in react-static.

eg:
```
import React from 'react'
import {Link} from 'react-static'
import styles from './panel.less'

const Panel = (props) => {
    return (
        <div className={styles.panel}>
            <h3 className={styles.panelTitle}><span className={styles.text}>{props.title}</span>
                {
                    props.link && <Link className={styles.more} to={props.link}>{props.moreText}</Link>
                }
            </h3>
            {props.children}
        </div>
    )
}
export default Panel
```
## static.config.js
```
webpack: (config, { defaultLoaders, stage }) => {
      let loaders = []

      if (stage === 'dev') {
        loaders = [
          { loader: 'style-loader' },
          {
            loader: 'css-loader',
            options:{
              minimize: stage === 'prod',
              modules: true,
              sourceMap: true,
            }
          },
          { loader: 'less-loader' }]
      } else {
        loaders = [
          {
            loader: 'css-loader',
            options: {
              importLoaders: 1,
              minimize: stage === 'prod',
              modules: true,
              sourceMap: false,
            },
          },
          {
            loader: 'less-loader',
          },
        ]

        // Don't extract css to file during node build process
        if (stage !== 'node') {
          loaders = ExtractTextPlugin.extract({
            fallback: {
              loader: 'style-loader',
              options: {
                sourceMap: false,
                hmr: false,
              },
            },
            use: loaders,
          })
        }
      }

      config.module.rules = [
        {
          oneOf: [
            {
              test: /\.less$/,
              use: loaders,
            },
            {
              test: /\.css$/,
              use: loaders.slice(0, loaders.length - 1).map(item => {
                if(item.loader === 'css-loader'){
                  item ={
                    loader: 'css-loader',
                    options: {
                      importLoaders: 1,
                      minimize: stage !== 'dev',
                      sourceMap: true,
                    },
                  }
                }
                return item
              })
            },
            defaultLoaders.cssLoader,
            defaultLoaders.jsLoader,
            defaultLoaders.fileLoader,
          ],
        },
      ]
      return config
    }
```

**Comment by nikaspran** [comment]
This is a known issue, see https://github.com/nozzle/react-static/issues/601#issuecomment-429574588 for workaround.

**Comment by lz-allen** [comment]
@nikaspran 
is the  import ExtractCssChunks from 'extract-css-chunks-webpack-plugin' ?
But it was still wrong.
 ```
 import ExtractCssChunks from 'extract-css-chunks-webpack-plugin'

    webpack: (config, { defaultLoaders, stage }) => {
      let loaders = [
        {
          loader: 'css-loader',
          options:{
            minimize: stage === 'prod',
            modules: true,
            sourceMap: true,
          }
        },
        { loader: 'less-loader' }
      ]
      if (stage === 'dev') {
        loaders= [ { loader: 'style-loader' }].concat(loaders)
      } else {
        // Don't extract css to file during node build process
        if (stage !== 'node') {
          loaders = [ExtractCssChunks.loader, ...loaders]
        }else{
          loaders = [ExtractCssChunks.loader, ...loaders]
          config.plugins.push(new ExtractCssChunks({
              filename: '[name].[chunkHash:8].css',
              chunkFilename: '[id].[chunkHash:8].css',
          }));
        }
      }

      config.module.rules = [
        {
          oneOf: [
            {
              test: /\.less$/,
              use: loaders,
            },
            {
              test: /\.css$/,
              use: loaders.slice(0, loaders.length - 1).map(item => {
                if(item.loader === 'css-loader'){
                  item ={
                    loader: 'css-loader',
                    options: {
                      importLoaders: 1,
                      minimize: stage !== 'dev',
                      sourceMap: true,
                    },
                  }
                }
                return item
              })
            },
            defaultLoaders.cssLoader,
            defaultLoaders.jsLoader,
            defaultLoaders.fileLoader,
          ],
        },
      ]
      return config
    },
```

**Comment by ScriptedAlchemy** [comment]
This fixes it

Inside node.api.js

‘’’
import eslintFormatter from 'react-dev-utils/eslintFormatter'
import ExtractCssChunks from 'extract-css-chunks-webpack-plugin'
import path from 'path'
import fs from 'fs'

const appDirectory = fs.realpathSync(process.cwd())
const resolveApp = relativePath => path.resolve(appDirectory, relativePath)

export const eslintLoader = {
  test: /\.js$/,
  enforce: 'pre',
  use: [
    {
      options: {
        formatter: eslintFormatter,
        eslintPath: require.resolve('eslint')
      },
      loader: require.resolve('eslint-loader')
    }
  ],
  include: resolveApp('src')
}

export default options => ({
  webpack: (config, { stage, defaultLoaders }) => {
    console.log('stage:', stage)

    config.module.rules = [
      eslintLoader,
      {
        oneOf: [
          defaultLoaders.jsLoader,
          defaultLoaders.jsLoaderExt,
          defaultLoaders.cssLoader,
          defaultLoaders.fileLoader
        ]
      }
    ]

    const lastRule = config.module.rules[config.module.rules.length - 1]

    const cssLoader = lastRule.oneOf[2]

    if (stage === 'dev') {
      Object.assign(cssLoader.loader[1].options, {
        modules: true,
        orderWarning: false,
        localIdentName: '[name]__[local]' // '[hash:base64:5]'
      })
    }

    if (stage === 'prod') {
      // Replace first loader
      cssLoader.loader[0] = ExtractCssChunks.loader

      Object.assign(cssLoader.loader[1].options, {
        modules: true,
        localIdentName: '[hash:base64:5]'
      })
    }

    if (stage === 'node') {
      // Insert to begin
      cssLoader.loader.unshift(
        ExtractCssChunks.loader
      )

      Object.assign(cssLoader.loader[1].options, {
        localIdentName: '[hash:base64:5]',
        modules: true
      })

      // Insert to second position
      config.plugins.splice(1, 0,
        new ExtractCssChunks({
          filename: '[name].[chunkHash:8].css',
          chunkFilename: '[id].[chunkHash:8].css',
          hot: process.NODE_ENV === 'development', // if you want HMR - we try to automatically inject hot reloading but if it's not working, add it to the config
          orderWarning: true, // Disable to remove warnings about conflicting order between imports
          reloadAll: true, // when desperation kicks in - this is a brute force HMR flag
          cssModules: true
        })
      )
    }

    return config
  }
})
‘’’

**Comment by ScriptedAlchemy** [comment]
@lz-allen @nikaspran @i8ramin @kylemac @deden

**Comment by lz-allen** [comment]
All I need to do is use this “extract-css-chunks-webpack-plugin” and I will build an error. 
my webpack is ^4.0

**Comment by ScriptedAlchemy** [comment]
What’s the arrow that you are getting?

**Comment by ScriptedAlchemy** [comment]
My solution only works for RS 6

**Comment by tannerlinsley** [comment]
This is being tracked in #601
