### ISSUE TITLE
Bug: TypeError: Cannot read property 'from' of undefined

### ISSUE THREAD

**Issue by karland** [nozzle/react-static#869]
### Are you reporting a bug?

Yes.

1. Fresh install of `react-static` with `npm install -g react-static`
2. Calling `react-static create` fails. See below.

### Environment

1.  `react-static -V`:
6.0.0
2.  `node -v`:
v8.11.4
v10.14.2 (same error)

3.  `npm -v`:
5.6.0

4.  Operating system:
Windows 10

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

```sh
d:\myTemp>react-static create
C:\Users\karland\AppData\Roaming\npm\node_modules\react-static\node_modules\convert-source-map\index.js:61
  return SafeBuffer.Buffer.from(json, 'utf8').toString('base64');
                           ^

TypeError: Cannot read property 'from' of undefined
...
```

**Comment by Omashu** [comment]
works for me:
install as dependency, call 
`node ./node_modules/react-static/bin/react-static-create`
but the error with time reappears and helps reinstalling

1. `node -v`
v10.14.2

2. `npm -v`
6.4.1

3. Operating system:
Windows 10

**Comment by tannerlinsley** [comment]
I just released a fix for the create command. Can you please try again?

**Comment by karland** [comment]
I tried to install, but after the install of 

```sh
npm install -g react-static
```
I get

```sh
react-static -v
4.3.2
```

I checked. 6.0.2 is already on npm.

Thereafter some errors occur, but I suppose they are irrelvant since the versions got mixed up?

**Comment by tannerlinsley** [comment]
It appears this has been resolved. Reopen if more information becomes available. Thanks!
