### ISSUE TITLE
In development while changing static.config.js: TypeError: global.reloadAll is not a function

### ISSUE THREAD

**Issue by bkniffler** [nozzle/react-static#873]
I found this line here:

https://github.com/nozzle/react-static/blob/57ecc92a63182aab91112be5c3e787c338308b09/packages/react-static/src/browser/components/RouteData.js#L19

This should be uncommented I guess. It is being called here:
https://github.com/nozzle/react-static/blob/57ecc92a63182aab91112be5c3e787c338308b09/packages/react-static/src/browser/index.js

**Comment by tannerlinsley** [comment]
I'll get that taken care of.
