### ISSUE TITLE
react-static-plugin-sass doesn't work

### ISSUE THREAD

**Issue by paavohuhtala** [nozzle/react-static#881]
### Are you reporting a bug?

Yes.

`react-static-plugin-sass` doesn't work, at least not in dev mode. Trying to build a project with the plugin enabled crashes the build process, with the following error message:

```
PS C:\koodia\react-static-repro\repro> yarn start
yarn run v1.12.3
$ react-static start
=> Building Routes...
=> [✓] Routes Built (0.1s)
=> Building Templates
=> [✓] Templates Built
=> Building App Bundle...
Failed to build! Fix any errors and try again!
C:/koodia/react-static-repro/repro/src/app.scss (C:/koodia/react-static-repro/repro/node_modules/css-loader/dist/cjs.js??ref--4-oneOf-0-1!C:/koodia/react-static-repro/repro/node_modules/sass-loader/lib/loader.js??ref--4-oneOf-0-2!C:/koodia/react-static-repro/repro/src/app.scss)
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties
 @ C:/koodia/react-static-repro/repro/src/app.scss 2:14-154 21:1-42:3 22:19-159
 @ C:/koodia/react-static-repro/repro/src/App.js
 @ C:/koodia/react-static-repro/repro/src/index.js
 @ multi C:/koodia/react-static-repro/repro/node_modules/react-dev-utils/webpackHotDevClient.js (webpack)/hot/only-dev-server.js ../lib/bootstrapTemplates.js C:/koodia/react-static-repro/repro/src/index.js
```

### Environment

1.  `react-static -V`: `6.0.4`
2.  `node -v`: `v11.4.0`
3.  `npm -v`: `6.4.1`
4.  Operating system: Windows 10 Education x64

### Steps to Reproduce the problem

1.  `react-static create`, choose `sass` template
2.  `yarn start`

**Comment by tannerlinsley** [comment]
@ScriptedAlchemy Do you know why this would be failing? We might need to rework this plugin a bit.

**Comment by ScriptedAlchemy** [comment]
Yeah hmm 🤔 

Tannner, can you sanity check the code once more? It tried to keep it similar. 

I’ll check it out tomorrow and see what’s going on in there

**Comment by ScriptedAlchemy** [comment]
I think I have a clue as to what it is. Sorry everyone! I tried to give it time to air. 

Can you paste in your webpack config just so I can see it

**Comment by tannerlinsley** [comment]
@paavohuhtala Can you please paste a link to your code so we can better diagnose the issue?

**Comment by paavohuhtala** [comment]
Seems to work in latest version. Thanks! This was in `6.0.4` with the now-deprecated SASS template, as stated in the original post.

**Comment by ScriptedAlchemy** [comment]
@paavohuhtala theres a pr open here, let me know if it solves the issue?
https://github.com/nozzle/react-static/pull/899/

**Comment by ScriptedAlchemy** [comment]
Yeah it looks like v2 changed the api on us recently. Ughhh there’s a PR I just merged in and should deploy up. Please tag me in css stuff. I own most of the css related plugins used on Webpack 4

**Comment by digitalkaoz** [comment]
https://github.com/nozzle/react-static/pull/884 this should fix this issue
