### ISSUE TITLE
Webpack hook not called in v6

### ISSUE THREAD

**Issue by nathanielw** [nozzle/react-static#886]
### Are you reporting a bug?

Yes

### Environment

1.  `react-static -V`: 6.0.4
2.  `node -v`: v11.0.0
3.  `npm -v`: 6.4.1
4.  Operating system: MacOS 10.13.6

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  Create a new react-static project based on the "basic" template (although this affects all templates)
2.  Update the `static.config.js` file to have a `webpack` hook, [as documented](https://github.com/nozzle/react-static/blob/master/docs/config.md#webpack). Put a console log in it, or make it do something noticeable.
3.  Run: `yarn start`
4. Notice that the webpack hook doesn't seem to be called

### Expected Behavior
 The webpack hook should be called, or the documentation should be updated to specific the new/working way to modify the Webpack config.

**Comment by tannerlinsley** [comment]
Whoops. Looks like we need to update the documentation on this. The proper way of using the webpack hook now is through the plugin api. I'll get on this.

**Comment by tannerlinsley** [comment]
Updated :) https://github.com/nozzle/react-static/blob/master/docs/config.md#webpack
