### ISSUE TITLE
react-static v6.0.5  - yarn start doesn't start - Throws error on styled-components

### ISSUE THREAD

**Issue by mariovde** [nozzle/react-static#888]
### Are you reporting a bug?

Yes

### Environment

1.  `react-static -V`: 6.0.5
2.  `node -v`: v8.11.3
3.  `npm -v`: 6.4.1
4.  Operating system: Mac OSX Sierra 10.12.6 (16G1618)
5.  Browser and version (if relevant): Chrome Version 71.0.3578.98 (Official Build) (64-bit)

Package.json:

{
  "name": "react-static-example-styled-components",
  "version": "6.0.0-beta.30",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "start": "react-static start",
    "stage": "react-static build --staging",
    "build": "react-static build",
    "serve": "serve dist -p 3000"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "react-hot-loader": "^4.3.12",
    **"react-static": "^6.0.0-beta.30",**
    "react-static-plugin-styled-components": "^6.0.0-beta.28",
    "styled-components": "^4.1.1"
  },
  "devDependencies": {
    "babel-plugin-styled-components": "^1.3.0",
    "eslint-config-react-tools": "1.x.x",
    "serve": "^10.1.1"
  },
  "gitHead": "350700130b7501622eac16aa139107c684b62b01"

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  react-static create
2.  fill in a project name
3.  chose for styled-component
4.  project is created succesfully
5.  cd into folder, named from step 2
6.  yarn start (console shows yarn start v0.24.6, in my case)

Error:

Failed to build! Fix any errors and try again!
...src/App.js
Attempted import error: 'injectGlobal' is not exported from 'styled-components'.
 @ /src/index.js
 @ multi node_modules/react-dev-utils/webpackHotDevClient.js (webpack)/hot/only-dev-server.js ../lib/bootstrapTemplates.js 
src/index.js

=> File changed: /tmp/dev-server/react-static-templates.js
=> Updating build...
Failed to build! Fix any errors and try again!
src/App.js
Attempted import error: 'injectGlobal' is not exported from 'styled-components'.
 @ /src/index.js
 @ multi node_modules/react-dev-utils/webpackHotDevClient.js (webpack)/hot/only-dev-server.js ../lib/bootstrapTemplates.js src/index.js

### Expected Behavior

The site should spawn up, without errors.

**Comment by tannerlinsley** [comment]
Tracking in #876

**Comment by mariovde** [comment]
When updating App.js to this:

`import React from 'react'
import { Root, Routes, Link } from 'react-static'
import styled, { createGlobalStyle } from 'styled-components'

//

const GlobalStyle = createGlobalStyle`
  body {
    font-family: 'HelveticaNeue-Light', 'Helvetica Neue Light', 'Helvetica Neue', Helvetica, Arial,
      'Lucida Grande', sans-serif;
    font-weight: 300;
    font-size: 16px;
    margin: 0;
    padding: 0;
  }
`

const AppStyles = styled.div`
  a {
    text-decoration: none;
    color: #108db8;
    font-weight: bold;
  }

  nav {
    width: 100%;
    background: #108db8;

    a {
      color: white;
      padding: 1rem;
      display: inline-block;
    }
  }

  .content {
    padding: 1rem;
  }

  img {
    max-width: 100%;
  }
`

const App = () => (
  <Root>
    <AppStyles>
      <GlobalStyle />
      <nav>
        <Link exact to="/">
          Home
        </Link>
        <Link to="/about">About</Link>
        <Link to="/blog">Blog</Link>
      </nav>
      <div className="content">
        <Routes />
      </div>
    </AppStyles>
  </Root>
)

export default App
`

and 

`yarn start`


returns this error in the browser:

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
Check the render method of `App`.
