### ISSUE TITLE
update via npm -g doesn't update repository, error message: Error: route.is404 has been deprecated. Use `path: '/404'` instead! Route: {"is404":true,"component":"src/containers/404"}

### ISSUE THREAD

**Issue by tgrrr** [nozzle/react-static#890]
### Are you reporting a bug?

Yes

### Environment

1.  `react-static -V`: 6.0.6
2.  `node -v`: v8.11.4
3.  `npm -v`: 6.4.1
4.  Operating system: macOS Mojave 10.14

### Steps to Reproduce the problem

- Updated to react-static 6.0.6 via `npm i react-static`
- Installed app via `react-static create` > basic
- Also tested with algolia and netlify-cms
- run app with `yarn start`

### Expected Behavior

app starts with `yarn start`

This was fixed by uninstalling react-static globally and reinstallling globally

Is there something wrong with how react-static is updated with `npm i react-static -g`?

**Comment by tannerlinsley** [comment]
Version 6 has breaking changes and requires upgrades to your app. Have you
looked at the changelog?

**Comment by tannerlinsley** [comment]
For now the [changelog](https://github.com/nozzle/react-static/tree/master/CHANGELOG.md) is the best place to upgrade your old sites to v6. There is no plan to include or build an automatic updater (this would be close to impossible)

**Comment by tgrrr** [comment]
@tannerlinsley Thanks for the head's-up, but the breaking changes don't affect me.

An automatic update would be ridiculous. I reported it because there was a terminal message to update to the latest when I ran the cli.

It sounds like it's an edge case, happy to close it.

**Comment by tannerlinsley** [comment]
Oh awesome. I misunderstood then.
