### ISSUE TITLE
Request for router docs/examples

### ISSUE THREAD

**Issue by mikestopcontinues** [nozzle/react-static#893]
### Is this a feature request?

I'm currently trying to upgrade to v6, and I've hit some snags with the router. The docs say v6 still uses `react-router` under the hood, and that I can require my own version to override the default. However, it looks like v6 is actually using a smidge of `@reach/router`, which has a noticeably different API.

I think it would be really useful to see a few things:

1. Some description of the router-lite approach you took for v6 and why you're recommending `@reach/router` going forward.
2. An example using `@reach/router`, showing how to get `react-router` features in the new context. For example, `withRouter`.
3. And another example that demos how to continue using `react-router`.

I'm going to plow ahead on this, but I suspect this sort of documentation would be helpful all around.

Thanks!

**Comment by tannerlinsley** [comment]
Yes absolutely

**Comment by tannerlinsley** [comment]
I'll start working up some more docs on what ships with React Static and how to use your own router for dynamic routes. Some quick notes:
- React Static ships with a reach/router `Router` instance in the `Root` component. This is mostly to make it easier for reach/router's `Link` component to work out of the box without having to inject your own router again. 
- Technically, you don't have to use reach/router's `Link`. You could use any component that updates the window pathname via the html5 push/pop state changes.
- Dynamic routes are still a bit hazy with v6. They're definitely possible, but literature and examples of it are almost non-existent. This needs to change.
- I would like to see a [Guide](/docs/guides) written about how to do this. If you (the person reading this) have this use case in your app, then you're probably the best person to write that guide. Go for it!

**Comment by farskid** [comment]
I just upgraded my personal website's codebase which was using react-static v5 to v6 and had to do a handful of refactors for router to work the same. Probably I can help with the migration of routing and specially nested dynamic routes from v5 to v6.

**Comment by mikestopcontinues** [comment]
@farskid, I'd really like to see how you did your work, and I'd also be happy to contribute to the docs as well, once I get things running.

**Comment by tannerlinsley** [comment]
I'v upgraded a large portion of the docs to reflect some important changes:
- Removed old CSS-in-JS explanation from concepts and reference the use of plugins and the plugin API now.
- Removed templates from the concepts
- Updated 404 handling in concepts to reflect the removal of react-router
- Added a `dynamic-routes-reach-router` guide that gives a quick and simple example of how to do dynamic routes with reach-router.
- Added a `pagination` guide.

**Comment by tannerlinsley** [comment]
I think with the guides we have now and the updated docs, this can be closed.
