### ISSUE TITLE
Move away from hard-coded examples towards guides

### ISSUE THREAD

**Issue by tannerlinsley** [nozzle/react-static#895]
Right now, examples are extremely difficult to maintain because:
- There are a lot of them
- They all differ slightly from one another in seemingly random ways
- They have a TON of similar code, but currently can't share that code
- Breaking changes must be made manually either via search and replace, codemods (we don't have them yet), or line by line.

### Guides
As a maintainer, I would 100% rather not maintain lists of examples at all, and instead just maintain code snippets of how to do certain things. I agree that this feels like a hard thing for people getting started with React Static, but personally I feel like boilerplates and starters are somewhat flawed from the beginning. They teach the user nothing about setting up the technologies inside of it, and usually end up with the user either breaking the setup, or misunderstanding it to the point of hardship. This is why create-react-app is so popular!

Consider this:
- Convert all example libraries into guides on how to implement/use said technology in React Static.
- Most examples would probably become plugins, which are extremely easy to maintain, use and educate with.
- Still maintain and ship 2 templates for users to get started
	- Blank (resembling create-react-app)
	- Basic
	- Stress Test (for testing large builds)
- Still allow the user to use a custom template from github or their filesystem

I believe this change would allow React Static to move faster and become more teachable, instead of just becoming a massive collection of boilerplates.

## Claim your work!
If you plan on converting an example into a guide, please check the box next to it. If you stop work on it, please uncheck it so someone else can work on it. When the guide is PR'd and merged, I will remove it from this list! Thanks.

- [ ] apollo
- [ ] apollo-redux
- [ ] basic-prismic
- [ ] contentful
- [ ] custom-routing
- [ ] documentation
- [ ] dynamic-imports
- [x] emotion
- [ ] firebase-auth
- [ ] gentics-mesh
- [ ] graphql-request
- [ ] less-antdesign
- [ ] markdown
- [ ] material-ui
- [ ] netlifycms
- [ ] non-static-routing
- [ ] on-the-fly-routing
- [ ] pagination
- [ ] preact
- [ ] previous-next-navigation
- [ ] redux
- [ ] sass
- [x] styled-components
- [ ] styled-jsx
- [ ] tailwindcss
- [ ] typescript

**Comment by Herohtar** [comment]
I like this idea. The most frustrating thing for me with `react-static` has been out-of-date examples or ones that just don't work at all. That's not helpful when you're trying to learn how to use something new. Even with a working example, you're left to pick it apart on your own and try to figure out which specific parts (across multiple files) are actually part of the feature you are wanting to use and even then may not be sure why. I would much rather see a guide or how-to that details what steps need to be taken to achieve a certain thing and some explanation of why those steps are required.

**Comment by tannerlinsley** [comment]
My guess is this issue isn't going to get used, so we can just move forward naturally as people ask for examples or plugins, we can add guides.
