### ISSUE TITLE
Production links not working (work fine in development)

### ISSUE THREAD

**Issue by quiringk** [nozzle/react-static#897]
### Are you reporting a bug?

Yes

### Environment

1.  `react-static -V`: ^6.0.6
2.  `node -v`: 10.11.0
3.  `npm -v`: 6.4.1
4.  Operating system: Mac

### Steps to Reproduce the problem

Everything works fine in development mode (npm run start). When I go to production (npm run build), I get an error for each link on my home page (similar to each blog post in the demo.) I have 10 links and I get 10 errors. 

![image](https://user-images.githubusercontent.com/6529857/50182963-9994f600-02c5-11e9-9636-b1b71f3bacee.png)

When I click on a link the url changes correctly but I get the same error and the loading spinning wheel.

### Expected Behavior

Works like normal like in the development environment.

### Reproducible Demo

https://foo.brandlive.live/

**Comment by tannerlinsley** [comment]
It looks like your server isn't serving up the `routeInfo.json` files correctly. Without more info on how your server is set up, I'm not sure how to help other than say make sure your server can serve up those files correctly.

<img width="950" alt="screen shot 2018-12-18 at 2 16 10 pm" src="https://user-images.githubusercontent.com/5580297/50183550-b1717780-02cf-11e9-93b3-c47f5b6701e8.png">

**Comment by quiringk** [comment]
OK interesting. Thanks for the quick response! We did do some nginx server configuration so I will check. But FYI, I ran "react-static create" and "npm run build" for the sample with blog posts and it works fine.

**Comment by quiringk** [comment]
When I type the URL of the link I was clicking on (ex: https://foo.brandlive.live/c/14677/) in the browser and load it it works fine. Do you still think this is a server issue? (I only get the above error when clicking the link to go to the page, not typing the URL and hitting enter)

**Comment by tannerlinsley** [comment]
Yes. That pages renders because the routeInfo needed to render it is embedded in the html and used when the app hydrates. Subsequent navigation on your site is broken though because your server is not serving xhr requests to `your/page/routeInfo.json` correctly. Without that routeInfo, the app doesn't know what data to fetch or which template to load for a given page.

**Comment by tannerlinsley** [comment]
Closing this for now. If you are able to fix the JSON ajax issue and still have problems, feel free to reopen this issue.

**Comment by quiringk** [comment]
@tannerlinsley You were correct. 

FYI: On our nginx server droplet we were messing around with CORS configuration for a separate issue which must have affected the loading of the json files. Once I removed the CORS configuration we added things worked like they should.

**Comment by ScriptedAlchemy** [comment]
Yeah usually it’s an OPTIONS request which needs to return 200. It’s a preflight check browsers do to see if they are allowed to even make the call. Proxy via node or making options calls return 200 status fixes this
