### ISSUE TITLE
Add example showing folder based data (like Jekyll)

### ISSUE THREAD

**Issue by derekperkins** [nozzle/react-static#9]

**Comment by tannerlinsley** [comment]
👍

**Comment by derekperkins** [comment]
Per request on the launch Reddit thread https://www.reddit.com/r/reactjs/comments/74j2ru/introducing_reactstatic_a_progressive_staticsite/dnz2x3s/

**Comment by zebapy** [comment]
I would love to see example or support for YAML data files. We use these a ton for manage data for our static sites.

**Comment by tannerlinsley** [comment]
Could you post an example of your files and where they are located and
managed?

**Comment by zebapy** [comment]
It's really just jekyll's convention because we use jekyll currently (I'm hoping to adopt a react static site generator soon). `src/data/somedata.yml` (multiple files here sometimes)

Currently, Gatsby only supports yaml files that are arrays, so it'd be a win if normal yaml file support was in this.

**Comment by malonehedges** [comment]
Interested in using `react-static` for a photography portfolio and would love to store the images in the repo with the code. This would be perfect if there was a filesystem example

**Comment by mdxprograms** [comment]
+1 for this. Is there a way to use https://github.com/jonschlinkert/remarkable or something similar?

**Comment by mdxprograms** [comment]
+1

**Comment by malonehedges** [comment]
@derekperkins Can we get a `pinned` tag or something to avoid the stale bot closing this if it is still planned?

**Comment by tannerlinsley** [comment]
I'll look into it
