### ISSUE TITLE
TypeScript typings do not export <Root>

### ISSUE THREAD

**Issue by Vinnl** [nozzle/react-static#900]
### Are you reporting a bug?

Yes.

I'm trying to upgrade a project to v6, and one of the first things I'm running into is that I want to `import { Root} from 'react-static'`, but TypeScript tells me

> Module '"react-static"' has no exported member 'Root'. (2305)

Which is correct: I don't see Root being exported from `index.d.ts`.

### Environment

1.  `react-static -V`:
6.0.9
2.  `node -v`:
v10.14.1
3.  `npm -v`:
6.4.1
4. `yarn -v` (I use Yarn):
1.12.3
5.  Operating system:
Ubuntu 18.04.1 LTS

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

I can't really provide the steps from a basic template yet as I have yet to write a plugin for TypeScript, but basically, the line `import { Root, Routes } from 'react-static'` that is in the freshly-installed template will not work if TypeScript were to be enabled.

### Expected Behavior

The TypeScript typings to be up-to-date with v6.

**Comment by tannerlinsley** [comment]
Feel free to submit a PR with the necessary changes

**Comment by tannerlinsley** [comment]
Closing for now, since typescript is not technically or officially supported by React Static (but is absolutely possible and used by some today).

Would love to see a PR to fix this.

**Comment by Vinnl** [comment]
Yes, I hope to look at it over the holidays. I take it the typings as a whole then are not updated for v6?

Btw, if it's not officially supported, it might be worthwhile to consider moving the typings to DefinitelyTyped? That's usually a sign that they're more likely to be lagging behind the official project compared to when the project itself hosts them. But for now I'll submit them here if I get around to it :)

**Comment by bernatfortet** [comment]
That would be aswesome. 
For now I just added:
`export class Root extends React.Component {}`
