### ISSUE TITLE
React-static not work with babel-plugin-import

### ISSUE THREAD

**Issue by leekad** [nozzle/react-static#902]
### Are you reporting a bug?
yes

### Environment

1.  `react-static -V`: `6.0.9`
2.  `node -v`: `v11.4.0`
3.  `npm -v`: `6.4.1`
4.  Operating system: MacOS Mojave
5.  Browser and version (if relevant): Chrome

### Steps to Reproduce the problem, repo here [https://github.com/leekad/react-static-antd-error](https://github.com/leekad/react-static-antd-error)

**Base your steps off of any freshly installed react-static template!**

1.  react-static create
2.  select blank
3.  install `antd`, install `babel-plugin-import`
4.  config .babelrc

```
{
  "presets": ["react-static/babelPreset.js"],
  "plugins": [
    [
      "import",
      {
        "libraryName": "antd",
        "style": true
      }
    ]
  ]
}
```

### Expected Behavior

Antd components should be import in chunks and app render correctly

### got Error
![image](https://user-images.githubusercontent.com/14184017/50222172-05f91d80-03ca-11e9-8ed6-cd29b3a428fd.png)

**Comment by tannerlinsley** [comment]
I'm not sure how to fix or diagnose this issue. Does anyone have any experience with this babel plugin?

**Comment by justinkuntz** [comment]
Probably related, I just updated and used 'react-static create' utilizing the stress test template and received the following error when doing 'yarn start':
'''Error: Cannot find module 'react-static/babel-preset.js' from '/Users/groot/Projects/ddtsi-static'''

**Comment by ScriptedAlchemy** [comment]
it wont, you must use babel-plugin-universal-import only. 
its part of universal. 

PR features to babel-plugin-universal-import if you need them, but this projects code splitting is based on react-universal-component. 

This isn't a bug, this is our architecture
