### ISSUE TITLE
[v6] Plugin options bug

### ISSUE THREAD

**Issue by leekad** [nozzle/react-static#903]
### Are you reporting a bug?
yes

### Environment

1.  `react-static -V`: `6.0.9`
2.  `node -v`: `v11.4.0`
3.  `npm -v`: `6.4.1`
4.  Operating system: MacOS Mojave
5.  Browser and version (if relevant): Chrome

### Steps to Reproduce the problem, repo here [https://github.com/leekad/react-static-antd-error](https://github.com/leekad/react-static-antd-error)

1. I create `react-static-plugin-less`
2. Add options to it
3. Expect it works, but it didn't.

### Expected Behavior

Plugin options should work.

**Comment by ScriptedAlchemy** [comment]
Details as to what we are looking for? What’s the bug you are having?

**Comment by tannerlinsley** [comment]
We just pushed a fix for a bug that was causing this. It had to do with plugin resolution. Please upgrade, try again, and reopen this issue if the problem persists.
