### ISSUE TITLE
"Error: This page template could not be found and a 404 template could not be found to fall back on. This means something is terribly wrong and you should probably file an issue!"

### ISSUE THREAD

**Issue by Vinnl** [nozzle/react-static#907]
### Are you reporting a bug?

Yes; I got the following error:

> Error: This page template could not be found and a 404 template could not be found to fall back on. This means something is terribly wrong and you should probably file an issue!

Obedient as I am, here I'm filing the issue. Unfortunately, I'm not quite sure what data is relevant.

### Environment

1.  `react-static -V`:
2.  `node -v`:
3.  `npm -v`:
4.  Operating system:
5.  Browser and version (if relevant):

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

Unfortunately, I haven't been able to reproduce this in a freshly installed template. Rather, I encountered this while trying to convert an existing React-Static project. I tried both setting up my 404 page for the path `'404'`, as well as moving it into the `/pages` dir (which does not yet contain any other pages). Neither fixed it.

### Expected Behavior

...not to get this error? If there's any more relevant information for me to provide, let me know.

**Comment by tannerlinsley** [comment]
This could mean a few things. The most likely is that your templates and
data are unfortunately not being fetched. If you could post a link to your
repo and or your site we can then diagnose from there.

**Comment by Vinnl** [comment]
Luckily it's open source, so I can: https://gitlab.com/Flockademic/plaudit/tree/82-migrate-to-react-static-v6/website

(Note that that's a specific folder in a specific branch.)

**Comment by tannerlinsley** [comment]
Just released a patch that fixes some major issues we found with routeInfo.json files. Will you please upgrade to the latest and try again?

**Comment by kirklikecaptain** [comment]
I just upgraded to 6.0.14, still seeing the same error when hitting an unknown path.

The error happens in both cases:
- 404.js component in scr/pages
- Manually defining 404 path/component in static.config

This issue persists when built/served.

**Comment by tannerlinsley** [comment]
Yeah, we're seeing it too (now being caused by a different bug). We're working on a fix. Thanks for your patience!

**Comment by tannerlinsley** [comment]
Alright, just did a patch release to handle an unhandled edge case where 404 templates were sometimes not loaded correctly. Can you upgrade and test again?

**Comment by kirklikecaptain** [comment]
Looks like it's working again in 6.0.15 for both cases:

- 404.js component in scr/pages
- Manually defining 404 path/component in static.config

The fallback 404 worked when neither were specified. Thanks for the quick fix!

**Comment by tannerlinsley** [comment]
Awesome! You bet. Spread the good word!

**Comment by ScriptedAlchemy** [comment]
Was this touting or chunk flushing related? Quick summary so I can help more

**Comment by tannerlinsley** [comment]
Nope. This was a route info issue.

**Comment by Vinnl** [comment]
Tested the fix here as well; works like a charm. Thanks!
