### ISSUE TITLE
dev run shows different styling than production build

### ISSUE THREAD

**Issue by paramr** [nozzle/react-static#910]
### Are you reporting a bug?
I am trying to build static site using material-ui.  Sample is at:  https://github.com/paramr/react-static-issue/tree/master .  when I run in dev i see styling of UI which disappears when I run in prod.
Dev:
<img width="663" alt="screen shot 2018-12-20 at 5 14 38 pm" src="https://user-images.githubusercontent.com/691499/50319185-d35b2d80-047a-11e9-9364-c37e5148eb19.png">

Prod:
<img width="624" alt="screen shot 2018-12-20 at 5 14 08 pm" src="https://user-images.githubusercontent.com/691499/50319184-d0f8d380-047a-11e9-9856-31f37eb94192.png">

### Environment

1.  `react-static -V`:  6.0.11
2.  `node -v`:  v10.14.2
3.  `npm -v`:  6.4.1
4.  Operating system:  mac OS - 10.14.2
5.  Browser and version (if relevant): Repros on safari and chrome

### Steps to Reproduce the problem

I started from archives/old-examples/material-ui and fixed issues that arose to get it working for dev.  Repro steps are:
1.  $ git clone https://github.com/paramr/react-static-issue.git
2.  $ cd react-static-issue
3.  $ npm install
4.  $ npm run start
5.  open http://localhost:3000 on browser.
6.  $ non run build-dbg
7.  $ cd dist
8.  $ python3 -m http.server 8080
9. open http://localhost:8080 on browser

### Expected Behavior

Both sites should look the same.

**Comment by Herohtar** [comment]
Something changed with `renderToHtml` and they added `renderToComponent`, but I never saw what exactly the changes were and the docs are kind of vague about how they work.

As best I can tell, you now have to do something like this, but I'm still trying to resolve other build issues with v6, so I can't confirm that it actually works:
```
  renderToElement: App => (
    <JssProvider registry={new SheetsRegistry()} generateClassName={createGenerateClassName()}>
      <MuiThemeProvider theme={createMuiTheme(theme)} sheetsManager={new Map()}>
        <App />
      </MuiThemeProvider>
    </JssProvider>
  ),
  renderToHtml: (render, app, { meta }) => {
    const html = render(app)

    meta.jssStyles = app.props.registry.toString()

    return html
  }
```

**Comment by paramr** [comment]
Thanks for more pointers.  I will try to play with this more.

But my bigger concern is to understand why deployment and dev builds diverge.  Isn't it a bit scary? :)

**Comment by tannerlinsley** [comment]
Sounds like we should have removed the renderToHtml and component methods
entirely and only offer the node.api.js plugin hooks. I'll post how to get
material UI working asap.

**Comment by paramr** [comment]
ok got it working.

```
  renderToElement: async (App, { meta, clientStats }) => {
    // Create a sheetsRegistry instance.
    const sheetsRegistry = new SheetsRegistry()

    // Create a MUI theme instance.
    const muiTheme = createMuiTheme(theme)

    const generateClassName = createGenerateClassName()
    return
      <JssProvider registry={sheetsRegistry} generateClassName={generateClassName}>
        <MuiThemeProvider theme={muiTheme} sheetsManager={new Map()}>
          {comp}
        </MuiThemeProvider>
      </JssProvider>
  },
```

and removed renderToHtml.

Not back to my original question on why there is difference between dev and build version?  Doesn't renderToElement/renderToHtml get called for dev version?  If not how do I make sure both paths give essentially same results.

**Comment by ScriptedAlchemy** [comment]
This solved? Or must I step in here?

**Comment by paramr** [comment]
Thanks for response ScriptedAlchemy.  It seems to work with changing renderToElement.  However question is still valid on why dev and prod version diverge without renderToElement (expectation in that case would be both are rendered with same styling).  So would love to understand the reason behind the divergence.  At the minimum there is a gotcha that needs to be documented (or may be it already is documented somewhere?)

**Comment by tannerlinsley** [comment]
The process of static generation doesn't happen at dev time, as this would be too costly and slow and just doesn't make sense for developer experience.

Both `renderToElement` and `renderToHtml` are methods that are used only to produce the static HTML for the static site. That HTML is then used as the starting point for the app to rehydrate.

Just as with any static site generation in React, there are side effects of rendering that must be extracted and pushed into the resulting HTML so as to ensure that the HTML markup looks exactly the same as the post-mounted react markup.

These methods provide a place to do that (but I can see how they are a bit confusing), and to be honest, most of this should be happening in plugins that we haven't built yet.

You can still achieve what you are wanting without a plugin for now though. 

This repo has a working static export configuration for matierial UI: https://github.com/cbroberg/react-static-mui

In fact, let's track this issue there (#896) from here on out.

**Comment by paramr** [comment]
Thanks for explanation.
