### ISSUE TITLE
Document error on v6

### ISSUE THREAD

**Issue by kations** [nozzle/react-static#911]
If I use this in basic v6 template:

// static.config.js
export default {
  Document: ({ Html, Head, Body, children, siteData, renderMeta }) => (
    <Html lang="en-US">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Body>{children}</Body>
    </Html>
  ),
}

I get the error that react is not defined.

**Comment by tannerlinsley** [comment]
You must import react wherever you use jsx

**Comment by kations** [comment]
yes but in 6.0.2 it failed with another error after importing react. In 6.0.11 it seems to work now 👍 

one short question: how could I get the routeData there for title and some meta tags?
Thanks
