### ISSUE TITLE
Bring back building with a config object v6

### ISSUE THREAD

**Issue by madroneropaulo** [nozzle/react-static#919]
### Is this a feature request?
I have a use case where I have multiple projects under the same repo, this way I can easily share components and configurations for all of them. Using the node api I want to be able to dynamically set the dist location and the entry point that will change from project to project. I was able to do this on v5 by just passing the static.config object to the build method, but that's no longer supported on v6.
 My feature request is to bring back allowing a config object to be used with the node api.

### Environment

1.  `react-static -V`: 6

**Comment by tannerlinsley** [comment]
There are a few reasons for this:
- Historically, both plugins and configs could use *some* of the same hooks, but did not share the same API. This made the documentation confusing, given that there were 2 ways to accomplish the same thing.
- Plugins are sharable, composable, etc. This makes them a more versatile API location than a config file.
- The effort required to use the new plugin system can be as simple as a relocation of code from the config file to a `node.api.js` file in your project root (No plugins folder needed). This is a very simple change that standardizes the API across React Static for customizing the build system (which is a big win for the docs and knowledgebase).
- If configurations in local `node.api.js` files become common, they can easily be extracted into the local `plugins` directory, or even shared and installed via NPM.

Of course, there are certain options that must remain in the `static.config.js` file that are specific to the project and not an extension or integration. From the config file, you have 100% control over what plugins you want to load or not load.

I agree that this is an abrasive change for some who really loved the all-inclusive config, but the reasons I outlined above hopefully help illustrate why this change will ultimately help React static be easier to learn, maintain, document, customize, and automate.

As time permits, we're working on a migration guide, but if you still have questions on how to migrate to v6, feel free to ask.
