### ISSUE TITLE
Plugin documentation page is 404

### ISSUE THREAD

**Issue by cmontgomerymt** [nozzle/react-static#920]
I was looking for documentation for using webpack in v6.

1) https://github.com/nozzle/react-static/blob/master/docs/config.md#webpack --> Points to config docs.

2) https://github.com/nozzle/react-static/blob/master/docs/config.md#webpack --> Points to plugin API section

3) https://github.com/nozzle/react-static/blob/master/docs/config.md#plugin-api --> Points to API documentation link

4) https://github.com/nozzle/react-static/blob/master/docs/plugins.md - 404

Was the documentation moved? I'm trying to migrate a current project to v6.

**Comment by tannerlinsley** [comment]
Or was converted into a directory. It should be
https://github.com/nozzle/react-static/blob/master/docs/plugins/ or
https://github.com/nozzle/react-static/blob/master/docs/plugins/README.md

**Comment by tannerlinsley** [comment]
Please PR any updates to documentation you find! 👍

**Comment by cmontgomerymt** [comment]
Thanks.
