### ISSUE TITLE
Missing static.config.js

### ISSUE THREAD

**Issue by hellojere** [nozzle/react-static#921]
### Are you reporting a bug?

Yes. Any of the examples created do not include the `static.config.js` file at all. 

### Environment

1.  `react-static -V`: 6.0.18
2.  `node -v`: v11.5.0
3.  `yarn -v`: 1.9.4
4.  Operating system: macOS Mojave 10.14.3 Beta (18D32a)

### Steps to Reproduce the problem

1.  Create a new project with `react-static create`

### Expected Behavior

Project to include the `static.config.js` file.

**Comment by tannerlinsley** [comment]
I can confirm that both the `basic` and `stress-test` examples have the necessary static.config.js files after using `react-static create` as expected.

It is important to note that the `blank` example doesn't require any static configuration, thus a `static.config.js` file is not necessary. Of course, you can add one if you'd like.

**Comment by tannerlinsley** [comment]
If you still think this is an error (eg. the files are still not showing up for you, or you think there is good reason to include a config for the `blank` template), feel free to reopen with more details on how to replicate the issues.

**Comment by maxjowett** [comment]
Without the `static.config.js` file how does one require plugins they've installed?

e.g. I've installed support for SASS using `react-static-plugin-sass` -- how do I add this plugin if I'm using the blank template?

**Comment by tannerlinsley** [comment]
You can add the file and place the plugin in the plugins array it exports.
