### ISSUE TITLE
Add prettier to keep contributions from changing formatting

### ISSUE THREAD

**Issue by D1no** [nozzle/react-static#93]
To prevent IDE specific re-formats, its probably a good idea to add a prettier hock so nobody needs to worry about that anymore:
https://github.com/prettier/prettier

**Comment by gagan0723** [comment]
#### Then let's add a ```.editorconfig``` as well.

**Comment by crubier** [comment]
Yup @D1no this is a great Idea, my `prettier-atom` keeps interfering with the custom eslint formatting of this project... I would love to just use plain prettier and be done with formatting issues already :-)

**Comment by D1no** [comment]
Just until this is done, just do your magic and run 
`yarn test --fix`
To have eslint format all the documents

**Comment by D1no** [comment]
Implementation Reference how it prettier could be done for react-static:
https://github.com/shoplinksys/gitmoji/blob/master/package.json#L41

**Comment by cgmx** [comment]
As a suggestion... `eslint --fix` should be run by default as a `yarn precommit` step.
This would help keep consistent formatting **before** commits are made.

This can be refactored by changing the following line the `package.json:#L15`

```
"test": "eslint src examples",
```
to
```
"test": "eslint src examples | eslint --fix",
```
Then we can add a precommit step to the `package.json`:
```
"precommit": "git add -A | yarn test"
```

**Comment by marbemac** [comment]
Stale bot strikes again... this should not be closed.
