### ISSUE TITLE
Error when starting dev server with global react-static CLI

### ISSUE THREAD

**Issue by sbaumeister** [nozzle/react-static#930]
After running `react-static start` in a newly created project and visiting http://localhost:3000 I get the following message: `Oh-no! Something’s gone wrong!`
Detailed error output from Chrome: [localhost-1546195846717.log](https://github.com/nozzle/react-static/files/2717426/localhost-1546195846717.log)

Using `npm run start` or `npx react-static start` works just fine.

### Environment
1.  `react-static -V`: 6.0.18
2.  `node -v`: v10.14.2
3.  `npm -v`: 6.4.1
4.  Operating system: macOS 10.14.2

### Steps to Reproduce the problem
1.  Install react-static `npm install -g react-static`
2.  Run `react-static create`. Create `new-project` and select `basic` template.
3.  `cd new-project && react-static start`
4. Open browser at http://localhost:3000

**Comment by nozzle** [comment]
This should be fixed in the latest version and is likely related to #929
