### ISSUE TITLE
CSS Imports are Broken

### ISSUE THREAD

**Issue by knpwrs** [nozzle/react-static#932]
# Issue

It seems like all CSS imports are now broken, even in the starter projects.

# Reproduction

```sh
npx react-static create
# accept all defaults, including basic template
cd my-static-site
yarn start
```

After running those commands you will see the following output (your paths may vary):

```
❯ yarn start
yarn run v1.12.3
$ react-static start
=> Building Routes...
=> [✓] Routes Built (0.2s)
=> Building Templates
=> [✓] Templates Built
=> Building App Bundle...
Failed to build! Fix any errors and try again!
/Users/knpwrs/Downloads/my-static-site/src/app.css
TypeError: Class constructor Dependency cannot be invoked without 'new'
 @ /Users/knpwrs/Downloads/my-static-site/src/App.js 12:0-19
 @ /Users/knpwrs/Downloads/my-static-site/src/index.js
 @ multi /Users/knpwrs/Downloads/my-static-site/node_modules/react-dev-utils/webpackHotDevClient.js (webpack)/hot/only-dev-server.js ../lib/bootstrapTemplates.js /Users/knpwrs/Downloads/my-static-site/src/index.js

=> File changed: /tmp/dev-server/index.html
=> Updating build...
Failed to build! Fix any errors and try again!
/Users/knpwrs/Downloads/my-static-site/src/app.css
TypeError: Class constructor Dependency cannot be invoked without 'new'
 @ /Users/knpwrs/Downloads/my-static-site/src/App.js 12:0-19
 @ /Users/knpwrs/Downloads/my-static-site/src/index.js
 @ multi /Users/knpwrs/Downloads/my-static-site/node_modules/react-dev-utils/webpackHotDevClient.js (webpack)/hot/only-dev-server.js ../lib/bootstrapTemplates.js /Users/knpwrs/Downloads/my-static-site/src/index.js
```

I even tried cloning this repo, running `yarn` and `yarn build`, and using the resulting local build of `react-static`. Same problem. **If you remove all CSS imports then the build works as expected.**

# Context

I'm attempting to upgrade from V5 to V6 and I cannot get my `sanitize.css` and `typeface-lato` dependencies to import properly. I was very frustrated with this so I started up a new project and found the build errors with default settings. I didn't even get to the point of installing my external CSS dependencies.

# Environment

1.  `react-static -V`: 6.0.19
2.  `node -v`: v11.4.0
3.  `npm -v`: 6.4.1
4.  Operating system: macOS 10.14.2
5.  Browser and version (if relevant): n/a

**Comment by grmmph** [comment]
any updates on this?

**Comment by ScriptedAlchemy** [comment]
No repo, no ability to reproduce
