### ISSUE TITLE
Intentionally unused import in Package Guides (?)

### ISSUE THREAD

**Issue by NavyAdmiral** [nozzle/react-static#936]
[In Material UI guide there is an unused import at line #12 ](https://github.com/nozzle/react-static/blame/master/docs/guides/material-ui.md#L12)

Is `createMuiTheme` intentionally imported and left unused for awareness about custom themes? If so, wouldn't it be better to document its usage too? If not, why import it at all?

**Comment by tannerlinsley** [comment]
It's an unused variable by accident. Good find! I've removed it from the guide :)

**Comment by NavyAdmiral** [comment]
Nice! That still leaves a question for me, how do we go on about using custom MUI themes? 😄

**Comment by tannerlinsley** [comment]
You should be able to use the theme as you normally would in your App.js or any other top level components. Just use the MUI theme provider and pass in your theme as far as I understand.

https://material-ui.com/customization/themes/#muithemeprovider
