### ISSUE TITLE
react-router-dom with v6

### ISSUE THREAD

**Issue by NavyAdmiral** [nozzle/react-static#937]
I read that @reach/router was a recommended router for v6, but I'd like to make it work with react-router-dom. I've reported the issues I faced [here](https://spectrum.chat/react-static?thread=ce379fed-c233-4e00-8a03-8074b27316dd) with reproducible steps and the changes I made from v5 to v6. Build fails in production and nothing I've tried to resolve it worked. Is there a guide for react-router-dom that I missed? Sorry to be reporting a question-like issue here, but perhaps this is a bug.

**Comment by tannerlinsley** [comment]
I'm currently working on a Guide for this. There might also be a plugin! Stay tuned.

**Comment by tannerlinsley** [comment]
https://github.com/nozzle/react-static/tree/master/docs/guides/dynamic-routes-react-router

**Comment by dlopuch** [comment]
@tannerlinsley That react-router guide you wrote (now at https://github.com/react-static/react-static/blob/master/docs/guides/dynamic-routes-react-router.md ) is missing the BrowserRouter / StaticRouter substitution described above. Technically that guide is missing any react-router `<Router>` component. Could use an update.

**Comment by SleeplessByte** [comment]
It's not missing anything, because the plugin injects a `Router` at `Root`.
