### ISSUE TITLE
react-static-plugin-less does not have suffiecient NPM permission for publishing

### ISSUE THREAD

**Issue by tannerlinsley** [nozzle/react-static#938]
@leekad, for now, you'll need to add me (`tannerlinsley`) as an admin via NPM to the `react-static-plugin-less` package

Until we get publishing to an automatic state, I do all of the released from my user and currently can't publish any new releases for this package.

**Comment by ScriptedAlchemy** [comment]
I can do this in a few hours or less

**Comment by ScriptedAlchemy** [comment]
Can you do a call around 5 or 6 my time, I’m in Redmond, WA

Ive done this to all my work and here at Starbucks

**Comment by ScriptedAlchemy** [comment]
You need to follow git commit message conventions though.
This for releasing: 
https://github.com/semantic-release/semantic-release

This for CLI like, easy commit message generation: 
https://github.com/commitizen/cz-cl


This is super easy to make, I’m working with webpack on commit message validation which ill roll here ASAP. (I got an invite from Tobias to join webpack core)i

**Comment by tannerlinsley** [comment]
Yeah, just ping me in slack and we can chat whenever you can.

**Comment by ScriptedAlchemy** [comment]
Cool, I'll be driving but read the links over ahead of time and we will have about an hour

**Comment by tannerlinsley** [comment]
We might as well add the all-contributors spec while we're at it too. People need to be recognized for their help!

**Comment by leekad** [comment]
@tannerlinsley 	do you still need admin for this?

**Comment by leekad** [comment]
@tannerlinsley 	someone publish the same package to npmjs. I cannot publish my package too :)

**Comment by leekad** [comment]
Hi @xwl7001 are you there?

**Comment by ScriptedAlchemy** [comment]
@tannerlinsley i dont know how to add the all contributors thing, but ill start working on semantic release next week / when my wife falls asleep tonight

**Comment by tannerlinsley** [comment]
Sounds good. I'll do the all contributors spec

**Comment by leekad** [comment]
@tannerlinsley 	i've added you as `maintainer` for `react-static-plugin-less`. Now you can move it from packagesQueue to packages

**Comment by tannerlinsley** [comment]
Awesome. I'll do this on the next release.
