### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by D1no** [nozzle/react-static#94]
As soon the implementations have settled:
- an E2E style test by simply comparing snapshot of the output html
- unit tests for the few costume functions instrumenting `static.config.js` variations

Since react-static is very thin, building on well tested libraries such as React 16 and React-Router, the effort is probably minimal.

**Comment by cgmx** [comment]
As I'm working on the hotfix for #124 I could get some test units in for that hotfix.. 
Only question would be is what test framework? Mocha, Ava, etc?

Let me know I can implement it alongside the hotfix.

**Comment by cgmx** [comment]
Per my conversation with @tannerlinsley, conclusion is to integrate [Jest](https://facebook.github.io/jest/).

Tanner also recommended Kent C. Dodds style Integration Tests over E2E or unit tests, hence Integration tests will be implemented.

**Comment by poorpaddy** [comment]
Locally I've already implemented Mocha, Karma, Chai with Istanbul instrumentation and code coverage reporting for unit tests. Along with webdriver.io for functional tests. Just mentioning because organizations may already have set frameworks designated.

**Comment by EmilTholin** [comment]
@poorpaddy Sounds great! Open up a PR with tests?

**Comment by poorpaddy** [comment]
@EmilTholin I'll see if I have time this holiday weekend. At minimum I can do a PR for the implementation with an example or two. I'm afraid the code coverage on my current project is embarrassing.

Coverage for statements (50%)
Coverage for lines (48.99%)
Coverage for branches (31.48%)
Coverage for functions (42.5%)

**Comment by tconn89** [comment]
I'm having an issue with jest not able to read JSX.  What should my .babelrc look like since it extends react-static/.babelrc?  I'm not sure that jest can find React-Static .babelrc in node_modules
