### ISSUE TITLE
react-static-plugin-jss configured for MaterialUI doesn't always insert correct CSS

### ISSUE THREAD

**Issue by Herohtar** [nozzle/react-static#940]
When using `react-static-plugin-jss` configured to use MaterialUI as shown in the guide, some routes are rendered with the correct CSS, but others are not. In the cases where it is missing, the `<style id="jss-server-side">` tag with some minimal CSS is still inserted, but it is not the correct CSS that should be getting rendered.

### Environment

1.  `react-static -V`: 6.1.4
2.  `node -v`: 11.4.0
3.  `npm -v`: 6.4.1
4.  Operating system: Windows 10 x64
5.  Browser and version (if relevant): N/A

### Reproducible Demo

Here is the branch in my repository with the plugin setup: https://github.com/Herohtar/thalion-herohtar/tree/jss-plugin

After running `build` the root `index.html` does not contain the correct MaterialUI CSS, but  `404.html` does. Looking into the routes, `blog/2018/index.html` does not contain the correct CSS, but `blog/2017/index.html` does. There are some other pages that are missing the MaterialUI CSS as well.

For comparison, here is the main branch that is just using a dropped-in `node.api.js` configured for MaterialUI and the CSS is rendered correctly on all pages: https://github.com/Herohtar/thalion-herohtar/tree/master

**Comment by tannerlinsley** [comment]
The only difference there is that your `node.api.js` file has the theme extracted to the export level. This might be the key to your styles showing up correctly. Try using your `node.api.js` instead of the plugin and see if that fixes it. If it does, then it's likely we need to make a `react-static-plugin-material-ui` plugin that handles this edge case (hopefully it could just use the `jss` plugin we've already created and add the extra stuff)

**Comment by Herohtar** [comment]
Using my dropped-in `node.api.js` works, as can be seen in the main branch, unless you were wanting me to test it in a different way somehow?

It seems that if I move the `MuiThemeProvider` out like it is for the `jss` plugin branch then the behavior is the same, with the CSS only being inserted on some routes.

**Comment by tannerlinsley** [comment]
Looks like that's a requirement for Material UI then. We'll need to sort
this out.

**Comment by Herohtar** [comment]
So looking at it some more, the docs seem to imply that you have to give it a `MuiThemeProvider` to use SSR at all for MaterialUI, and state that you need to create a new instance of the sheets manager, sheets registry, and class name generator for each request. I'm not sure of the exact details of how those work together, but it seems separating them out like that causes them to not function correctly.

Even without trying to insert `MuiThemeProvider` somewhere, there is still the inconsistent CSS when trying to use MaterialUI with the `jss` plugin as currently described by the guide. I think it is more than just an edge case and will require it's own plugin... I'm not sure how you could write it to use the `jss` plugin since `MuiThemeProvider` needs to be inserted below `JssProvider`....

**Comment by bentranmyriota** [comment]
Just wonder whether there is a solution to the above issue. I am having the same issue

**Comment by tannerlinsley** [comment]
Yeah, let's hear it!

**Comment by bentranmyriota** [comment]
I modified to your react-static-plugin-react-jss to:
```javascript
 beforeRenderToElement: (App, { meta }) => props => {
        const generateClassName = createGenerateClassName();
        // Create a sheetsRegistry instance.
        meta.jssSheetsRegistry = new SheetsRegistry();
        // fresh sheet manager
        props.sheetsManager = new Map();
        props.theme = createMuiTheme(providerProps.muiTheme);
        return (
            <JssProvider generateClassName={ generateClassName } registry={ meta.jssSheetsRegistry }>
                <App { ...props } />
            </JssProvider>
        );
    },
    Head: ({ meta }) => {
        return <React.Fragment>
            <style id="jss-server-side" dangerouslySetInnerHTML={{ __html: meta.jssSheetsRegistry.toString() }}/>
        </React.Fragment>
    },
```

Then in App.js
```javascript
export default function App(props?: any) {
    const theme = createMuiTheme(props.muiTheme ? props.muiTheme : MATERIAL_UI_THEME);
    return (
        <Root>
            <MuiThemeProvider theme={ theme } sheetsManager={ props.sheetsManager }>
                <Main/>
            </MuiThemeProvider>
        </Root>
    );
}
```
