### ISSUE TITLE
Wrong location from reach-router's Location during static render

### ISSUE THREAD

**Issue by Herohtar** [nozzle/react-static#945]
I'm rendering some navigation tabs that are present on all routes, so they are in the main `App.js` component and I'm using the `<Location>` provider from `reach-router` in order to use the location to highlight the tab corresponding to the current page. The relevant component looks like this:
```
<Location>
  {({ location }) => (
    <Tabs value={location.pathname} centered component="nav">
      <Tab component={Link} value={routes.HOME} to={routes.HOME} label="Home" />
      <Tab component={Link} value={routes.PRODUCTS} to={routes.PRODUCTS} label="Products" />
      <Tab component={Link} value={routes.ORDER} to={routes.ORDER} label="Order Form" />
    </Tabs>
  )}
</Location>
```

This works fine when the page is operating live via React; however, the statically rendered version is incorrect and causes issues if the user navigates directly to a page URL. I did some digging and it seems that the value of `location.pathname` is always `/` during the static render phase instead of the actual path of the route.

### Environment

1.  `react-static -V`: 6.1.4
2.  `node -v`: 11.4.0
3.  `npm -v`: 6.4.1
4.  Operating system: Windows 10 x64
5.  Browser and version (if relevant): N/A

**Comment by tannerlinsley** [comment]
Looks like we need to update the default router in Root.js to use the Reach Router static renderer during static export.

**Comment by tannerlinsley** [comment]
@herohtar would you like to head that up?

**Comment by Herohtar** [comment]
I can try to take a look at it.

**Comment by Herohtar** [comment]
@tannerlinsley I can't seem to get v6 to build, or do anything really...

I've pulled the code from `master` and have followed the updated steps in the contributing guide, but it doesn't appear to actually build with `yarn build`:
```
yarn run v1.12.3
$ lerna run 'build' --ignore react-static-example-*
lerna notice cli v3.6.0
lerna info filter [ '!react-static-example-*' ]
lerna success run No packages found with the lifecycle script ''build''
Done in 5.30s.
```

`yarn test` throws errors:
```
yarn run v1.12.3
$ yarn format && lerna run test
$ prettier docs/** --write && lerna run format
docs\browser.md 150ms
docs\cli.md 55ms
docs\components.md 200ms
docs\concepts.md 175ms
docs\config.md 228ms
docs\guides\algolia.md 32ms
docs\guides\animated-routes.md 25ms
docs\guides\apollo.md 76ms
docs\guides\aws-lambda.md 20ms
docs\guides\dynamic-routes-reach-router.md 30ms
docs\guides\dynamic-routes-react-router.md 44ms
docs\guides\emotion.md 21ms
docs\guides\jss.md 9ms
docs\guides\material-ui.md 15ms
docs\guides\pagination.md 34ms
docs\guides\README.md 22ms
docs\node-api.md 92ms
docs\plugins\browser-api.md 18ms
docs\plugins\node-api.md 117ms
docs\plugins\README.md 60ms
docs\README.md 11ms
lerna notice cli v3.6.0
lerna info Executing command in 8 packages: "yarn run format"
lerna ERR! yarn run format exited 1 in 'react-static-plugin-css-modules'
lerna ERR! yarn run format stdout:
$ prettier 'src/**/*.js' --write
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run format stderr:
[error] No matching files. Patterns tried: 'src/**/*.js' !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
error Command failed with exit code 2.

lerna ERR! yarn run format exited 1 in 'react-static-plugin-css-modules'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by tannerlinsley** [comment]
Hmm. There are definitely packages with the build command. And the
contributing docs might need some updating.

In the fresh repo:
yarn
Yarn build/start

That doesn't work?

Make sure yarn is up to date too.

**Comment by Herohtar** [comment]
I'm using yarn v1.12.3. Entirely deleted the repo and cloned it fresh, ran `yarn` which completed with no errors, but `build/start` don't work:

```
PS C:\Users\Me\Desktop\HTML\react-static> yarn build
yarn run v1.12.3
$ lerna run 'build' --ignore react-static-example-*
lerna notice cli v3.6.0
lerna info filter [ '!react-static-example-*' ]
lerna success run No packages found with the lifecycle script ''build''
Done in 6.17s.
PS C:\Users\Me\Desktop\HTML\react-static> yarn start
yarn run v1.12.3
$ yarn watch
$ lerna run 'watch' --ignore react-static-example-* --parallel
lerna notice cli v3.6.0
lerna info filter [ '!react-static-example-*' ]
lerna success run No packages found with the lifecycle script ''watch''
Done in 1.71s.
```

**Comment by tannerlinsley** [comment]
So weird. Is Lerna up to date?

**Comment by Herohtar** [comment]
Lerna is v3.6.0 which is what's specified in the package. I updated it to the latest 3.9.0 with the same results.

**Comment by tannerlinsley** [comment]
If you go into the packages/React-redux directory, are you able to yarn
build?

**Comment by tannerlinsley** [comment]
Sorry, autocorrected to react-redux. I meant `packages/react-static`

**Comment by Herohtar** [comment]
Hm, yes, `yarn build` and `yarn start` work in `packages/react-static`

**Comment by tannerlinsley** [comment]
Hmmm. That should work for you for now, but it seems like Lerna is choking in your env. Not sure why either.
