### ISSUE TITLE
It's possible to produce a "successful" build that yields no JS bundle or HTML

### ISSUE THREAD

**Issue by benedfit** [nozzle/react-static#946]
### Are you reporting a bug?

Yes. It's possible to produce a "successful" build that yields no JS bundle or HTML. I stumbled across this issue when one of my data API end-point was unavailable.

### Environment

1.  `react-static -V`: 6.1.4
2.  `node -v`: 8.9.0
3.  `npm -v`: 5.5.1
4.  Operating system: Mac OS
5.  Browser and version (if relevant): N/A

### Steps to Reproduce the problem

1.  Run `react-static create` and select the `basic` template
2.  Edit `static.config` to return an empty array from `getRoutes`
3. Delete `src/pages`
4. Run `yarn build`
5. Observe that, despite a console warning of no "index" page, build is successful, and that `dist` contains just `react-static-browser-plugins.js`
6. Edit `static.confg` and throw an error from `getRoutes`
7. Run `yarn build`
8. Observe that build is successful, and that `dist` contains just `react-static-browser-plugins.js`

### Expected Behavior

Because there are no "page" routes or routes returned by `getRoutes`, `yarn build` should fail with exit code 1 in both cases. Previous in v5, when I threw an error caused by an unavailable end-point the build would fail. The current v6 behaviour can result in a CI tool such as Netlify deploying the minimal `dist` directory

**Comment by tannerlinsley** [comment]
Yeah, this means an error is likely getting swallowed somewhere during the internal `getRoutes()` call.

**Comment by tannerlinsley** [comment]
@benedfit Do you feel up to digging into the code for this?

**Comment by tannerlinsley** [comment]
I was successfully able to throw an error in my `getRoutes` function and it stopped the build, then exited with an non-zero error code, which is expected.

I haven't tried to return an empty array of routes.

**Comment by benedfit** [comment]
Tested on `v6.1.5` and I still get what looks like a successful "Done" message in the console from

```
getRoutes: async ({ dev }) => {
    throw new Error('blah')
}
```

Output:
```
$ react-static build

=> Cleaning dist...
=> [✓] Dist cleaned
=> Building Routes...
  Error: test

  - static.config.js:40 Object._callee$
    /private/var/application/newhighsco/destiny-clan-warfare/static    .config.js:40:11

  - runtime.js:62 tryCatch
    [destiny-clan-warfare]/[regenerator-runtime]/runtime.js:62:40

  - runtime.js:288 Generator.invoke [as _invoke]
    [destiny-clan-warfare]/[regenerator-runtime]/runtime.js:288:22

  - runtime.js:114 Generator.prototype.(anonymous function) [as nex    t]
    [destiny-clan-warfare]/[regenerator-runtime]/runtime.js:114:21

  - static.config.js:20 asyncGeneratorStep
    /private/var/application/newhighsco/destiny-clan-warfare/static    .config.js:20:103

  - static.config.js:22 _next
    /private/var/application/newhighsco/destiny-clan-warfare/static    .config.js:22:194

  - static.config.js:22
    /private/var/application/newhighsco/destiny-clan-warfare/static    .config.js:22:364

  - new Promise

  - static.config.js:22 Object.<anonymous>
    /private/var/application/newhighsco/destiny-clan-warfare/static    .config.js:22:97

  - static.config.js:39 Object.getRoutes
    /private/var/application/newhighsco/destiny-clan-warfare/static    .config.js:39:12

  - index.js:10 getRoutes
    [destiny-clan-warfare]/[react-static]/src/static/getRoutes/inde    x.js:10:31

  - runtime.js:62 tryCatch
    [destiny-clan-warfare]/[regenerator-runtime]/runtime.js:62:40

  - runtime.js:288 Generator.invoke [as _invoke]
    [destiny-clan-warfare]/[regenerator-runtime]/runtime.js:288:22

  - runtime.js:114 Generator.prototype.(anonymous function) [as nex    t]
    [destiny-clan-warfare]/[regenerator-runtime]/runtime.js:114:21

  - index.js:34 asyncGeneratorStep
    [destiny-clan-warfare]/[react-static]/lib/static/getRoutes/inde    x.js:34:103

  - index.js:36 _next
    [destiny-clan-warfare]/[react-static]/lib/static/getRoutes/inde    x.js:36:194

  - index.js:36
    [destiny-clan-warfare]/[react-static]/lib/static/getRoutes/inde    x.js:36:364

  - new Promise

  - index.js:36
    [destiny-clan-warfare]/[react-static]/lib/static/getRoutes/inde    x.js:36:97

  - index.js:9
    [destiny-clan-warfare]/[react-static]/src/static/getRoutes/inde    x.js:9:10

  - getRoutesFromPages.js:75 subscription
    [destiny-clan-warfare]/[react-static]/src/static/getRoutes/getR    outesFromPages.js:75:10

  - runtime.js:62 tryCatch
    [destiny-clan-warfare]/[regenerator-runtime]/runtime.js:62:40

  - runtime.js:288 Generator.invoke [as _invoke]
    [destiny-clan-warfare]/[regenerator-runtime]/runtime.js:288:22

  - runtime.js:114 Generator.prototype.(anonymous function) [as nex    t]
    [destiny-clan-warfare]/[regenerator-runtime]/runtime.js:114:21

  - getRoutesFromPages.js:24 asyncGeneratorStep
    [destiny-clan-warfare]/[react-static]/lib/static/getRoutes/getR    outesFromPages.js:24:103

  - getRoutesFromPages.js:26 _next
    [destiny-clan-warfare]/[react-static]/lib/static/getRoutes/getR    outesFromPages.js:26:194



✨  Done in 6.90s.
```

**Comment by tannerlinsley** [comment]
Hmmm. This is making me want to refactor the code behind this pipeline...

**Comment by sw-yx** [comment]
bump

**Comment by tannerlinsley** [comment]
After a passthrough of this logical tree and some debugging, I couldn't find where the error's are getting swallowed. I'm going to do another run-through later this week.

**Comment by tannerlinsley** [comment]
v7 uses a whole new flow for CLI commands and should no longer swallow errors. If you still run into this error in the new version, please reopen this issue!

Thanks for your feedback on this as always.
