### ISSUE TITLE
Running "build" on Windows partially completes with errors

### ISSUE THREAD

**Issue by gpoole** [nozzle/react-static#948]
### Environment

1.  `react-static -V`: 6.1.5
2.  `node -v`: 10.9.0
3.  `npm -v`: 6.2.0
4.  Operating system: Windows 10 Home 1803
5.  Browser and version (if relevant): N/A

### Steps to Reproduce the problem

On Windows, generate a site with the basic template. Then, run:

```
npm run build
```

The build seems to partially succeed, but after "=> Exporting HTML across 16 threads..." several errors are output to the console saying:

> react-static update check failed.

Internally, it looks like the error is being thrown by `update-notifier` and the message is:

> Error: EPERM: operation not permitted, rename 'C:\Users\Greg\.config\configstore\update-notifier-react-static.json.3330641592' -> 'C:\Users\Greg\.config\configstore\update-notifier-react-static.json'

I think it's a race condition where multiple `update-notifier` processes are trying to change the same file at the same time. I think this is because [update-notifier is run in a common import](https://github.com/nozzle/react-static/blob/c921bec343430bf3a759f0d3330986a369f2f194/packages/react-static/src/utils/binHelper.js#L27), so it's also being called in all the processes started to export HTML.

### Expected Behavior

The site should build without errors.

**Comment by tannerlinsley** [comment]
We'll be removing the notifier in the next patch. It's been very unreliable and presented more problems than needed.

**Comment by gpoole** [comment]
Cool, sounds good 👍

**Comment by tannerlinsley** [comment]
Should be removed in latest.
