### ISSUE TITLE
Running "start" during a fresh creation of a project with the basic template that resides in a location that contains \u in the path causes an error

### ISSUE THREAD

**Issue by smasinde** [nozzle/react-static#949]
### Environment

1.  `react-static -V`: 6.1.5
2.  `node -v`: 8.12.0
3.  `npm -v`: 6.4.1
4.  Operating system: Windows Enterprise 1803
5.  Browser and version (if relevant): 

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  react-static create
2.  What should we name this project? * anything that begins with a letter 'u' *
3.  Select a template.... *basic*
4.  cd "user-site"
5.  yarn start

### Expected Behavior

The expected result is that the site should deploy and be viewable on localhost. 

### Error Message

SyntaxError: C:\path\to\project\tmp\dev-server\react-static-browser-plugins.js: Bad character escape sequence (6:39)

so I am assuming it is because the generated file does not escape the \u. A work around would be to not use naming starting with u, but that is a tad inconvenient.

**Comment by LukasV** [comment]
Hello there. I got the same error running "yarn start" when my project is at c:\xam\react-static. When I move it to c:\temp\react-static. Everything works just fine.

**Comment by smasinde** [comment]
maybe it is the \x that is disturbing you. I think that needs to be escaped.. and adding it to the js file creates an error.
