### ISSUE TITLE
What you think about universal-webpack?

### ISSUE THREAD

**Issue by BjornMelgaard** [nozzle/react-static#95]
https://github.com/catamphetamine/universal-webpack
[discussion on next.js](https://github.com/zeit/next.js/issues/1245) 
[best boilerplate I've seen using it](https://github.com/thomhos/react-typescript)

sturdy codebase to extract common logic, plethora of examples, possibility to write server on whatever you want, why not?

**Comment by D1no** [comment]
Sadly, Webpack Universal only supports Webpack 2 😕

**Comment by BjornMelgaard** [comment]
@D1no not sure https://github.com/catamphetamine/universal-webpack/issues/78

**Comment by D1no** [comment]
Sorry, but the maintainer seems to be an idiot on the same stroke. I‘d rather not have a dependency to that guy in my commercial stack.

**Comment by BjornMelgaard** [comment]
@D1no I understand )
