### ISSUE TITLE
Is React-Static right for my dynamic use-case?

### ISSUE THREAD

**Issue by mehdi-cit** [nozzle/react-static#950]
Hello and thank you for this interesting project.
I'm struggling with Next.js (probably too heavy for our our use case) and I am very enthusiastic about react-static.
However, I have a few questions. I am not sure the title I gave this post is very relevant. I first wanted to title it something along the line of "Is react-static a good fit for my use case?" ... but wanted to use a more descriptive title for future "readers". So, I guess I'm saying, feel free to update the title as you see fit!
Back to my "use case".
I have a back-end that has tens of thousands of "pages". I have a dozen page types (Component, templates whatever you want to call them).
The thing is that apart from the home page found at the root '\'. Other pages can have any route. For instance page found at route "abc/123" can be of type "Article", but it could also be of type "FAQ". We cannot assume anything at development time. Worse, things can change at run time! So, it can be an Aricle but few minutes later it might become a Contact-us page! 
Obviously, when we get the data for "abc/123" we get with it meta data from which to know what type of page it should be "displayed with"!
I really like react-static "simplicity" but one thing is "worrying me". In the documentation it says:

> All of the data your site needs to render is gathered up-front in your static.config.js 

So, is it possible to have getRoutes return different "path/data" at runtime? 
Also, note that the different route are discoverable at runtime as well. So for instance the page at route xyz/alpha/romeo can only be found by the user/system after the user visits "abc/456". So our static.config.js would need to return yet a different "array" on almost all new visited routes.
Last but not least, some pages/routes can be deleted or added, other pages may get updated (change content and even type). And all, at runtime! :)

If the above scenario is not supported by react-static. Did anyone try to have a separate process that listens to "a backend" and causes the static.config.js to be rerun whenever the backend undegoes changes (page creation, deletion or updates). In my case, changes have to become live within minutes... or even seconds if possible!

Cheers~

**Comment by mehdi-cit** [comment]
Thank you much for the prompt and elaborated reply!
Just quick question about your last bullet point if you will. Does the upcoming re-export feature properly take care of deleted pages/routes as well? The pages are not updated but can be deleted and newly created

**Comment by tannerlinsley** [comment]
I does not take care of deleted pages, though you are more than welcome to simply delete the `dist/path/to/your/route` directory for any routes that need to be removed.
