### ISSUE TITLE
React and React-Dom versions

### ISSUE THREAD

**Issue by NavyAdmiral** [nozzle/react-static#958]
Hi. Why is React @alpha and React-Dom 16.7? Referring to [react-dom here](https://github.com/nozzle/react-static/blob/master/packages/react-static/package.json#L81) and [react here](https://github.com/nozzle/react-static/blob/master/packages/react-static/package.json#L79). 
Is it possible to override the versions set by react-static?
I would like to use hooks, but as far as I'm aware both react and react-dom need to be 16.7@next

**Comment by tannerlinsley** [comment]
The latest hooks are now actually available in v16.8.0-alpha.0. We should get this updated.

As far as overriding the version, you could install your own version in your project, and it might work fine. Give it a shot and give us any feedback you have.

**Comment by NavyAdmiral** [comment]
Hmmm @tannerlinsley, that's how I thought it worked too, but updating react/react-dom in the project has no influence whatsoever. Could this have something to do with React being in `gui/` child folder while `package.json` is in a parent folder? I'm referring to the following project: https://github.com/smartcontractkit/chainlink

There's a lot in that repo, but all it takes to see that react-static isn't serving project-wide React is doing `yarn add react@next react-dom@next` and `yarn start`

**Comment by NavyAdmiral** [comment]
@tannerlinsley I confirmed the issue is with the project structure. React-static recognizes change in React version only if node_modules is where `react-static start/build/...` is exec'ed

**Comment by numso** [comment]
I have also been really excited to try out hooks and was able to get them working in react-static by using [yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/). When I installed `react@16.8.0-alpha.0` and `react-dom@16.8.0-alpha.0` in my project, I got two versions of each. Adding the following to the end of my package.json cleared that up:
```
  "resolutions": {
    "react": "16.8.0-alpha.0",
    "react-dom": "16.8.0-alpha.0"
  }
```

**Comment by sw-yx** [comment]
very helpful @numso thank you

**Comment by pie6k** [comment]
Using @numso solution with forced `resolutions` worked like a charm. I don't feel 100% 'comfortable' with it, but it works.
