### ISSUE TITLE
react-static-plugin-react-router StaticRouter context is undefined

### ISSUE THREAD

**Issue by craighillwood** [nozzle/react-static#961]
### Are you reporting a bug?

Yes. I don't know how the error (explained below, that appears on the terminal) affects the `build`, but I can just assume that it could lead to some issues.

### Environment

1.  `react-static -V`: `6.2.0`
2.  `node -v`: `10.15.0`
3.  `npm -v`: `6.5.0`
4.  Operating system: macOS Mojave `10.14.2`
5.  Browser and version (if relevant): Not relevant

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1. `react-static create`
2.  Choose `basic` template.
3.  `cd my-static-site`
4. `npm uninstall react-static` (cause it's version is `6.0.18` which still doesn't have support for `react-router-dom` [ref](https://github.com/nozzle/react-static/blob/master/CHANGELOG.md#610)).
5. `npm i react-static react-static-plugin-react-router react-router-dom`
6. Now our `packages.json` looks like:
```
// package.json
{
  ...,
  "dependencies": {
    ...
    "react-router-dom": "^4.3.1",
    "react-static": "^6.2.0",
    "react-static-plugin-react-router": "^6.1.1"
  }
}
```
7. Add `react-static-plugin-react-router` plugin to `static.config.js` so it looks like:
```
// static.config.js
export default {
  ...,
  plugins: ['react-static-plugin-react-router']
};
```
8. Delete from `pages` directory the following files so we don't have any reference to `@reach/router`.
- `blog.js`
- `about.js`

9. Comment (or delete 🤷‍♂️) the `getRoutes` property in `static.config.js`, so again, we don't import any files that reference `@reach/router`.
10. Add `--debug` flag to npm script `stage` in `package.json` (otherwise the error won't show), so it looks like:
```
// package.json
{
  ...,
  "scripts": {
    ...,
    "stage": "react-static build --staging --debug",
  }
}
```
11. `npm run stage`, your should get the following **Error** 2 times (one per route):
```
Error: Warning: Failed prop type: The prop `context` is marked as required in `StaticRouter`, but its value is `undefined`.
      in StaticRouter
      in Unknown (at Root.js:90)
      in RouterScroller (at Root.js:83)
      in Wrapper (at Root.js:89)
      in ErrorBoundary (at Root.js:88)
      in Root (at StaticInfo.js:17)
      in Context.Consumer (at StaticInfo.js:12)
      in StaticInfo (at StaticInfo.js:16)
      in Unknown
      in App (at bootstrapApp.js:9)
      in Context.Provider (at bootstrapApp.js:8)
      in Unknown (at exportRoute.js:120)
      in ReportChunks (at exportRoute.js:107)
      in FinalComp (at exportRoute.js:171)
```

I think it has to do with the `react-static-plugin-react-router` plugin not passing the `context` prop to `StaticRouter` (as explained on the error message) https://github.com/nozzle/react-static/blob/master/packages/react-static-plugin-react-router/src/browser.api.js

### Expected Behavior

Not have this error show on the terminal. Which could be fixed (I think) by passing the `context` prop to the `StaticRouter`, as it's a required prop.

### Reproducible Demo

No.

**Comment by tannerlinsley** [comment]
We can just do this `context={{}}` for now. Would you like to PR that change?
