### ISSUE TITLE
prefetch={false} doesn't work with <Link> component anymore

### ISSUE THREAD

**Issue by krzysztof-pyrzyk-ah** [nozzle/react-static#970]
I've noticed that since React-Static v6 it's impossible to disable prefetching on `<Link>` component.
Seems like `<Link>` from `@reach/router` doesn't support it.

### Environment

1.  `react-static -V`: 6.2.0
2. `node -v`: 11.5.0
3. `yarn -v`: 1.12.3
4.  Operating system: OSX 10.14.2

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  Add <Link to='/whatever' prefetch={false}>
2.  Visit the site and scroll down until the link is visible
3.  Check network tab to see if any prefetch requests were made

### Expected Behavior

Expected behavior is the one described in the [documentation](https://github.com/nozzle/react-static/blob/master/docs/components.md#link)

**Comment by tannerlinsley** [comment]
v6 doesn't include its own router anymore, so the Link documentation should have been removed.
