### ISSUE TITLE
ERROR: No outputPath was provided as an option to flushChunks

### ISSUE THREAD

**Issue by JamesMessinger** [nozzle/react-static#971]
### Are you reporting a bug?
Yes

I originally posted this in Issue #656, but figured it makes more sense to open a new issue, since 656 is already closed.

I'm getting the following error:

```
 Error: No `outputPath` was provided as an option to `flushChunks`.
        Please provide one so stylesheets can be read from the
        file system since you're embedding the css as a string.

  - createApiWithCss.js:151 stylesAsString
    [test-project]/[webpack-flush-chunks]/dist/createApiWithCss.js:151:11

  - createApiWithCss.js:98 Object.toString
    [test-project]/[webpack-flush-chunks]/dist/createApiWithCss.js:98:53

  - HeadWithMeta.js:14 toString
    [test-project]/[react-static]/src/static/components/HeadWithMeta.js:14:25
  ```

I believe the problem is that the [`outputPath` option](https://github.com/faceyspacey/webpack-flush-chunks#options-api) is not passed to `webpack-flush-chunks` on this line:

https://github.com/nozzle/react-static/blob/21bb89a15092e93798e573fbe2f75c4e433e52fe/packages/react-static/src/static/exportRoute.js#L128-L130
 

### Environment
1.  `react-static -V`: 6.2.0
2.  `node -v`: v10.11.0
3.  `npm -v`: 6.4.1
4.  Operating system: Windows 10
5.  Browser and version (if relevant):  Chrome 71

### Steps to Reproduce the problem
1. Create a new project using the "blank" template.
2. Add a `static.config.js` file with the following contents:

```javascript
export default {
  extractCssChunks: true,
  inlineCss: true,
}
```

3. Run `react-static build` to get the error

### Expected Behavior
No error 😄

### Say Something Nice
I just discovered this project yesterday, and I'm **really** excited about it.  It seems like _exactly_ what I've been looking for and addresses many of the pain-points that I experienced with Gatsby.   **Thank you so much** for creating this! 🏆💯

**Comment by tannerlinsley** [comment]
@ScriptedAlchemy Any ideas here?

**Comment by arlair** [comment]
It seems `inlineCss` being true triggers this error in my project.
