### ISSUE TITLE
devBasePath doesn't work as expected

### ISSUE THREAD

**Issue by JamesMessinger** [nozzle/react-static#972]
### Are you reporting a bug?
Yes.

The `devBasePath` option is useful for making sure your site will work as expected when it's not at the root of the domain.  Super handy 👍 

But the dev server (`react-static start`) **also** serves the site at the root path, and components like `<Link>` produce URLs that point to the root path, **not** the `devBasePath`.

### Environment
1.  `react-static -V`: 6.2.0
2.  `node -v`: v10.11.0
3.  `npm -v`: 6.4.1
4.  Operating system: Windows 10
5.  Browser and version (if relevant):  Chrome 71

### Steps to Reproduce the problem
1.  Create a new project using the "basic" template
2.  Set the `devBasePath` in `static.config.js` to something like `my-site`
3.  Run the dev server (`react-static start`)
4. Browse to `http://localhost:3000/my-site`.  It works as expected
5. Click the "About" link in the nav bar.  
  - It takes you to `/about` instead of `/my-site/about`
  - The page still renders correctly, even though the route is wrong

This defeats the purpose (as I understand it) of the `devBasePath` option, since my site will still work, even if I have links or images that mistakenly don't include the base path.   I wont' discover that my URLs are broken until I deploy the site to production, where they won't work.

### Expected Behavior
1. When the `devBasePath` is set, the dev server should only serve content under that path.  Anything above that path should show the 404 page.

2. `<Link to="/about">` should render as `<a href="/my-site/about">` instead of `<a href="/about">`

**Comment by tannerlinsley** [comment]
Yeah, this looks like a bug. @JamesMessinger would you like to give a PR a try to fix this?

**Comment by JamesMessinger** [comment]
I tried changing the `publicPath` option as mentioned above, but no luck.  In fact, it made things worse.  Nothing would render, regardless of whether the URL was correct or not.  Every URL returns a blank page (a 200 response, not a 404)

**Comment by tannerlinsley** [comment]
Something about devBasePath is funky to me still. I know we put it in because theoretically it makes sense. However, from a local development perspective, it's very strange. 

What would be the downsides of just not supporting a devBasePath? Wouldn't the site behave as it normally would when deployed with a `basePath`?

**Comment by JamesMessinger** [comment]
I'd be fine with `devBasePath` going away, but then I'd expect the local dev server to use `basePath` instead.  

I'm sure you'll agree that it's always best for your development environment to match the production environment as closely as possible.  Fewer bugs make their way into production that way.  For example, it's far too easy in a React site to accidentally use `<a>` instead of `<Link>` or to use a hard-coded `<img>` path, or any number of other things.  As developers, we tend to think of paths as relative to the root of the project that we're working in (e.g. `/assets/logo.png`, forgetting that it will _actually_ be served from `example.com/my/site/assets/logo.png`), so it's easy to absentmindedly hard-code a project-relative path somewhere.  And if the local dev server is serving stuff from root, then this type of easy mistake will go unnoticed.
