### ISSUE TITLE
Tree remount on history.replaceState()

### ISSUE THREAD

**Issue by layershifter** [nozzle/react-static#974]
## Story

1. `history.replaceState()` is overridden by [Location.js#L26](https://github.com/nozzle/react-static/blob/v6.3.0/packages/react-static/src/browser/utils/Location.js#L26), this allows React Static to add own subscribers
2. Subscriber is added there, [Routes.js#L30](https://github.com/nozzle/react-static/blob/v6.3.0/packages/react-static/src/browser/components/Routes.js#L30), it will call `forceUpdate()`
3. `getComponentForPath()` will always return a new component, [Routes.js#L83](https://github.com/nozzle/react-static/blob/v6.3.0/packages/react-static/src/browser/components/Routes.js#L83):

```jsx
<Routes>
  {({ getComponentForPath, routePath }) => {
    const Component = getComponentForPath(routePath);
    console.log("Component", C === Component);
    console.log("Root", P === Root);
    C = Component;
    P = Root;
    return <Component key={routePath} />;
  }}
</Routes>
```

```jsx
// First render
Component false
Root false
// Fetch info about missing route
Component false
Root true
// After history.replaceState()
Component false
Root true
```

## Issue

The behavior described above works fine for a navigation between pages, but when I'm doing `history.replaceState(undefined, undefined, '#anchor')` it causes an update and remount of a whole tree. In my case it does a strange page jump.

```
componentDidMount()
// CLICK
history.replaceState()
componentDidMount()
```

![static](https://user-images.githubusercontent.com/14183168/51285846-ae61c800-19f0-11e9-8783-1f2bbeb0f991.gif)

### Environment

1.  `react-static -V`: 6.3.0

### Monkey resolution

```diff
-        return (newProps = {}) =>
-          Comp ? (
-            <Comp {...newProps} {...(is404 ? { is404: true } : {})} />
-          ) : null
+ return <Comp {...(is404 ? { is404: true } : {})} />
```

This works fine to me, it's too late there to find a better solution 🌃

**Comment by ostrebler** [comment]
Same kind of issue here, except it happens on global store updates.
And when using react-static's Root and Routes with @reach/router's navigate function, history states are not forwarded to the new route.

**Comment by tannerlinsley** [comment]
Yeah I am getting this too. Need to look into this
