### ISSUE TITLE
Shared data is not available when using the `withRouteData` 

### ISSUE THREAD

**Issue by bram-l** [nozzle/react-static#981]
### Are you reporting a bug?
Yes. Shared data is not available in the props when using the `withRouteData` HOC in the build. While running in dev mode it does work as expected.

### Environment

1.  `react-static -V`: 6.3.2
2.  `node -v`: v10.11.0
3.  `npm -v`: 6.4.1
4.  Operating system: macOS

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  Add to one of the routes, eg. `blog` in the basic template:
```js
sharedData: {
  foo: createSharedData({ bar: 'foobar' }) 
},
```
2. Check the result using:
```jsx
export default withRouteData(({ posts, foo }) => (
  <div>
    <h1>It's { foo.bar }.</h1>
    [...]
```
3. `yarn build`
which results in:
```
TypeError: Failed exporting HTML for URL blog (src/pages/blog.js):Cannot read property 'bar' of undefined
```

### Expected Behavior
Successful build with `<h1>It's foobar.</h1>` on the blog page

**Comment by krzysztof-pyrzyk-ah** [comment]
`createSharedData` function doesn't return just the data itself, it returns an object ```{
    hash: shorthash.unique(JSON.stringify(data)),
    data,
  }```
To access shared data from your example I believe you should write it as follows:
` <h1>It's { foo.data.bar }.</h1>`

**Comment by krzysztof-pyrzyk-ah** [comment]
@tannerlinsley I've been trying to fix this, but with no success. Any ideas where should I look for the root cause? Export command is quite complex and hard to debug.

**Comment by tannerlinsley** [comment]
I'll try to dig up some good places to look for you.

**Comment by bram-l** [comment]
@tannerlinsley after some deep digging I think I found a solution myself! Please let me know if this makes any sense to you. Also, I took the liberty to remove the return value of the prefetch methods as it turned out to be unused and slightly confused as it was before. Another option would be to actually return the merged data form the prefetch method instead of mutating the routeInfo, but I'm afraid that would mean refactoring in quite a few places and way more complicate to make sure it won't break anything...
