### ISSUE TITLE
Redirect from getRoutes does not redirect

### ISSUE THREAD

**Issue by obaydmir** [nozzle/react-static#990]
### Are you reporting a bug?

Yes, after setting `redirect` on a route, it will not redirect to specified `path`.

### Environment

1.  `react-static - 6.3.3`:
2.  `node - 10.15.0`:
3.  `npm - 6.4.1`:
4.  `ubuntu:trusty`:
5.  `yarn - 1.12.3`:

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1. Add a redirect route to list of routes. The route to redirect works, because if I go to it works.

```javascript
getRoutes: [
  { path: 'test', component: 'src/pages/test' },
  { path: 'redirect', redirect: 'test' },
]
```

2. Navigate to `/test`, I will see the page as expected. Navigate to `/redirect`, get a 404 page.

### Expected Behavior

Redirect to the route.

**Comment by heymaddieh** [comment]
Is there a status update on this bug? We are having the same issue.

**Comment by tannerlinsley** [comment]
We're looking into it still. Stay tuned!

**Comment by boennemann** [comment]
As per https://github.com/nozzle/react-static/issues/1066#issuecomment-475052393

Try removing the `-s` flag from `serve`.

**Comment by tannerlinsley** [comment]
v7 production builds should function properly for redirects now. If you are still having issues, make sure you are indeed not using the `-s` option on the `serve` command.
