### ISSUE TITLE
Basic template fails on build, without alterations

### ISSUE THREAD

**Issue by jeffhee** [nozzle/react-static#991]
### Are you reporting a bug?

From a fresh installation of react-static, npm run build fails.

### Environment

1.  `react-static -V`: 6.3.3
2.  `node -v`: 8.5.0
3.  `npm -v`: 6.4.1
4.  Operating system: MacOS

### Steps to Reproduce the problem

From console:
`mkdir react-static-test`
`cd react-static-test`
 `npm install -g react-static`
`react-static create `
named project 'react-static-test'
chose 'basic' as the template

`cd react-static-test`
`npm run start`

Site loads in browser successfully, however:

`npm run build`

> ERROR in /[***SNIPPED***]/react-static-test/react-static-test/dist/react-static-templates.js 1:1051
Module parse failed: Unexpected token (1:1051)
You may need an appropriate loader to handle this file type.
> import _path5 from"path";import _universalImport5 from"babel-plugin-universal-import/universalImport";import _path4 from"path";import _universalImport4 from"babel-plugin-universal-import/universalImport";import _path3 from"path";import _universalImport3 from"babel-plugin-universal-import/universalImport";import _path2 from"path";import _universalImport2 from"babel-plugin-universal-import/universalImport";import _path from"path";import _universalImport from"babel-plugin-universal-import/universalImport";import universal,{setHasBabelPlugin}from'/Users/jeffhee/Documents/Projects/react-static-test/react-static-test/node_modules/react-universal-component/dist/index.js';setHasBabelPlugin();var universalOptions={loading:function loading(){return null;},error:function error(props){console.error(props.error);return React.createElement("div",null,"An error occurred loading this page's template. More information is available in the console.");}};var t_0=universal(_universalImport({id:"../src/pages/404.js",load:function load(){return Promise.all([import(/* webpackChunkName: 'src-pages-404' */'../src/pages/404.js')]).then(function(proms){return proms[0];});},path:function path(){return _path.join(__dirname,'../src/pages/404.js');},resolve:function resolve(){return require.resolveWeak('../src/pages/404.js');},chunkName:function chunkName(){return"src-pages-404";}}),universalOptions);var t_1=universal(_universalImport2({id:"../src/pages/about.js",load:function load(){return Promise.all([import(/* webpackChunkName: 'src-pages-about' */'../src/pages/about.js')]).then(function(proms){return proms[0];});},path:function path(){return _path2.join(__dirname,'../src/pages/about.js');},resolve:function resolve(){return require.resolveWeak('../src/pages/about.js');},chunkName:function chunkName(){return"src-pages-about";}}),universalOptions);var t_2=universal(_universalImport3({id:"../src/pages/blog.js",load:function load(){return Promise.all([import(/* webpackChunkName: 'src-pages-blog' */'../src/pages/blog.js')]).then(function(proms){return proms[0];});},path:function path(){return _path3.join(__dirname,'../src/pages/blog.js');},resolve:function resolve(){return require.resolveWeak('../src/pages/blog.js');},chunkName:function chunkName(){return"src-pages-blog";}}),universalOptions);var t_3=universal(_universalImport4({id:"../src/containers/Post",load:function load(){return Promise.all([import(/* webpackChunkName: 'src-containers-Post' */'../src/containers/Post')]).then(function(proms){return proms[0];});},path:function path(){return _path4.join(__dirname,'../src/containers/Post');},resolve:function resolve(){return require.resolveWeak('../src/containers/Post');},chunkName:function chunkName(){return"src-containers-Post";}}),universalOptions);var t_4=universal(_universalImport5({id:"../src/pages/index.js",load:function load(){return Promise.all([import(/* webpackChunkName: 'src-pages-index' */'../src/pages/index.js')]).then(function(proms){return proms[0];});},path:function path(){return _path5.join(__dirname,'../src/pages/index.js');},resolve:function resolve(){return require.resolveWeak('../src/pages/index.js');},chunkName:function chunkName(){return"src-pages-index";}}),universalOptions);// Template Map
| export default{'../src/pages/404.js':t_0,'../src/pages/about.js':t_1,'../src/pages/blog.js':t_2,'../src/containers/Post':t_3,'../src/pages/index.js':t_4};export var notFoundTemplate="../src/pages/404.js";
 @ ../lib/bootstrapTemplates.js 4:15-63 15:20-68
 @ multi ../lib/bootstrapPlugins.js ../lib/bootstrapTemplates.js ../lib/bootstrapApp.js

                => There were ERRORS during the node build stage! :(
                => Fix them and try again!

### Expected Behavior

Basic site is compiled and outputted in /dist folder

**_THANK YOU!_**

**Comment by Ziinc** [comment]
The version used in the global version is probably different from the version pinned in the basic template.

Try without a global installation:
```
npx react-static create
cd to/my/folder
npm install react-static
npm start
```

**Comment by nathanpower** [comment]
Looks like you have the same problem as me. It seems that the build chokes on the webpack dynamic import, i.e. the first occurrence of `[import(/* webpackChunkName: 'filename.js')]`

**Comment by nathanpower** [comment]
Looks like this is this issue: https://github.com/webpack/webpack/issues/8656

**Comment by jeffhee** [comment]
@nathanpower Thanks!
