### ISSUE TITLE
[discussion] react-static-plugin-podcast

### ISSUE THREAD

**Issue by sw-yx** [nozzle/react-static#997]
### Is this a feature request?

Yes, but more of a discussion 

### Environment

Run and copy the result of:

`npx envinfo --system --npmPackages react* --binaries --npmGlobalPackages react* --browsers` 

here:

```
  System:
    OS: macOS High Sierra 10.13.4
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 2.77 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Safari: 11.1
  npmGlobalPackages:
    react-static: 6.3.2
```

of course include any other package versions here if relevant. 

### Reproducible Demo

https://github.com/sw-yx/react-static-podcast-hosting

### Context

I have written a tech agnostic podcast RSS feed generator that I am using together with the above demo:

https://github.com/sw-yx/podcats

Obviously, a possible next step is to turn this into a plugin for R-S that would make it even more plug and play. however i'm a little lacking in imagination because i am doing everything within `static.config.js`. So i'm open to ideas, and am happy to break up the "monolith" of `podcats` accordingly if needed.

**Comment by tannerlinsley** [comment]
The plugin system has been revamped in v7 and we can easily add more plugin points now without breaking anything at all. Let me know what areas of the build pipeline you need additional control over to make this a reality and we'll do it!

**Comment by tannerlinsley** [comment]
Adding this to the icebox. Still a great idea for sure.
